### ISSUE TITLE
[USABILITY] Suggested changes to "Connect to Illinois" dialog

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1007]
The "Connect to Illinois" dialog box in the Building Access section on the home page has two problems. (As I see it.)

1. The prompt to connect your NetID mentions "student or faculty members", but leaves out non-faculty employees.

**Current:** "Are you a student or faculty member? Sign in with your NetID."

**Change to:** "Are you a university student or employee? Sign in with your NetID."

2.  We also prompt users to "Connect to Illinois" with a phone number. But a phone number will not provide them access to their Building Access status.

**Change:** Delete the phone number section from this dialog box.

![connect netid phone mark](https://user-images.githubusercontent.com/66988329/142935863-728aefa5-1dda-48f1-85d4-0e9f7e495687.jpeg)

**Comment by mihail-varbanov** [comment]
Point 1 is fixed in 3.0.56. @pmarkhennessy requested to preserve the phone/email login section (point 2).
