### ISSUE TITLE
[BUG] creationDate time format inconsistent (sometimes wrong) in profile data

### ISSUE THREAD

**Issue by wryanthomas** [rokwire/illinois-app#102]
**Describe the bug**
The creationDate time values in profile logs, when ep_name = Profile, are using the wrong time format. (Time format is correct when ep_name = PII.) The result is inconsistent creationDate time values. Here is a sample of a uuid with two creationDate timestamps in profile data:

Profile | 2020/08/18T16:23:52
PII | 2020-08-18T16:24:46.407Z

The preferred format is the ISO 8601-compatible version, the one being used where ep_name = PII:
2020-08-18T16:24:46.407Z

**To Reproduce**
I'm not sure what produces the error, I can only see the evidence of it in the logs.

To see the issue...
Search logs, aggregate by uuid (user_uuid) and list creationDate.

In Splunk, use the following command from Rokwire Team app. (Has dependency of user_uuid field extraction/eval available in the app.)  If you use 'verbose' mode, you can then view the events individually.

```
index=apps-rokwire_illinois sourcetype="illinois:rokwire:profile"
| stats list(ep_name) AS ep_name list(creationDate) AS creationDate by user_uuid
| eval ep_name = mvdedup(ep_name)
| eval creationDate = mvdedup(creationDate)
```

**Expected behavior**
timestamps should always be written with the same time format in the profile logs (preferably in ISO 8601-compliant time format).

**Comment by sandeep-ps** [comment]
Hi @wryanthomas, I think this would be an issue in the profile building block code. Could you please move this to https://github.com/rokwire/rokwire-building-blocks-api? Thanks.
