### ISSUE TITLE
[BUG] Version 3.0.55 testing (login)

### ISSUE THREAD

**Issue by balicea** [rokwire/illinois-app#1044]
**Describe the bug**
Dev version of 3.0.55 does not always log in smoothly when using phone #/e-mail.

**To Reproduce**
1. Uninstall prior version of Illinois App on device.
2. Install 3.0.55 dev version.
3. log in using phone/e-mail option (I used both resulting in the same behavior).
4. could not log in the first time (worked for subsequent tries).

**Expected behavior**
Expect to be able to log in using this option smoothly (no errors or hangs).

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Android dev version
 - Version 3.0.55

**Smartphone (please complete the following information):**
 - Device: Android phone
 - Version: Android 9

**Comment by pmarkhennessy** [comment]
This was a backend issue. Please close if it is fixed @balicea
