### ISSUE TITLE
[BUG] Bus Pass unable to load in 3.0.56

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1056]
I'm not sure if this is a wide-spread problem or not. But, I get "Unable to load bus pass" when I tap on "Use bus pass" in the wallet.  My Illini ID loads fine.

**Comment by dobromirdobrev** [comment]
Hi @kpecknold ,
We are unable to reproduce this issue. Could you please share with us more details like user scenario, how you signed in (NetId, email, phone), device OS, app version etc? 
Any details would be very helpful.
cc @pmarkhennessy

**Comment by dobromirdobrev** [comment]
Hi @kpecknold , do you have any update on this?

**Comment by kpecknold** [comment]
@dobromirdobrev  - seems to be resolved. Thank you!
