### ISSUE TITLE
[BUG] Increase Favorites (star) button click area 

### ISSUE THREAD

**Issue by TodorBachvarov** [rokwire/illinois-app#1062]
JP is still unable to save (star) any items from anywhere (widgets, panels etc). Can we increase touch areas? It does work for me. Interesting point is that the + for adding an event in Groups takes me 3 attempts to make it work and for JP it is not an issue.

**Comment by kpecknold** [comment]
I have this same problem, it takes me several time to tap the "+". Also, on a groups event card. White space doesn't trigger, so if the title is short, it's hard to get to the detail card.
