### ISSUE TITLE
[BUG] Capitalization of Sections on Home Page

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1073]
I believe we should capitalize Features in "Highlighted features" and For You in "Events for you" - to be consistent with the other sections

**Comment by joegrohens** [comment]
@pmarkhennessy @kpecknold @TodorBachvarov @Priyaravi8 @ToddNelson 

I appreciate attention to consistency in screen typography. (Sometimes it's hard to find anyone who cares.)

However, I recommend that we make a more systematic review of section headings and screen titles before making one-off changes.

We are arranging to audit the capitalization in all Illinois app screens once Priya has captured the 3.0 screens (by Dec 10).

The style we have for Rokwire apps is "title case" (https://en.wikipedia.org/wiki/Title_case). That means that important words are capitalized and "less important" words -- i.e., articles, prepositions and conjunctions are not.

In "Events For You", for example, the word "for" is a preposition, and therefore would be lower case: **Events for You**.

This style can be somewhat debatable, so I expect to seek buy-in from anyone who cares before submitting our change requests. 

Todor and Kathryn - I would prefer that for this commit we change "Events For You" to "Events for You".

Please let me know if you disagree.

- Joe
