### ISSUE TITLE
[BUG] Updating group event not working

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#1081]
**Describe the bug**

**To Reproduce**
1. Create a new group (visibility can be private or public)
2. Create an event (visibility can be private or public) in the group.
3. Update group event (e.g. change description or visibility.)
4. See that the event is not updated on the Events talent home screen.

**Expected behavior**
Group events should get updated properly.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Android
 - Version: 2.8.2 TEST instance.

**Additional context**

**Comment by mihail-varbanov** [comment]
I was unable to recreate this exactly because the "Events talent home screen" displays some random event selection. However I noticed that we do not update this its content on event creation or update, as well as when the app resides in background for long time. This is fixed in 3.0.62.

**Comment by sandeep-ps** [comment]
Thanks. Retested and this is resolved.
