### ISSUE TITLE
[FEATURE] Show debug initialization status on startup

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#1087]
**Re: University Monday 2021/12/06** / 2021-12-07

6 We are seeing issues with startup in UIUC 3.x also. One user showed JP that it takes over 40 seconds for the splash to finish so he can continue. In settings/debug can we add an option for "Output startup loading" and default it to true. When true, show at the bottom of the splash (or toast on Android if needed) what we are about to load (maybe Loading xxx and Loading xxx completed) so we can work out what is causing the delay.

**Comment by dobromirdobrev** [comment]
Done in iOS only for version 3.0.62. TBD in Android

P.S. I reopen this issue because github closes it automatically.

**Comment by dobromirdobrev** [comment]
Done in Android for version 3.0.63
