### ISSUE TITLE
[BUG] Groups request - Failed to send request

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1098]
**Describe the bug**
The user receives "Failed to send request" when he tap on the Request to Join button.

**To Reproduce**
1. Install Illinois app version 3.0.63
2. Navigate to Browse screen and tap on Groups tile
3. Tap on the "Study Ancient History" group and send "Request to Join"

**Actual Result**
Failed to send request message is received.

**Expected behavior**
The request has to send to the group admin without a failure notice.

**Screenshots**
![group failed](https://user-images.githubusercontent.com/26231179/145290208-c18f7c7a-4016-4ba7-9ded-10615353b8c9.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.0.63]

**Comment by pmarkhennessy** [comment]
Please retest on Monday 13th (Dec 2021) after latest Groups BB has been deployed.
