### ISSUE TITLE
[BUG] Group notification is not received

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1109]
**Describe the bug**
Group notification is not received in the device when a group post, invites and updates are added.

**To Reproduce**
1. Install an Illinois app
2. Navigate to browse and tap on Groups
3. Create a public group. A user sends a request to join the created group

**Actual Result**
Notification is not received on the device. **Note** - Notification is enabled in the device for the Illinois app and Group notifications are enabled.

**Expected behavior**
Notification should pop up on the device when a group posts, invites, and updates are added.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.0.63]

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,
This was fixed some time ago on the backend. Please retest with the latest app version you have.
