### ISSUE TITLE
[ACCESSIBILITY] MyIllini login gets stuck in a loop

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1110]
Describe the accessibility issue
Attempting to log in to MyIllini through Illinois app produces a 2FA loop. After you go to Shibboleth and login in, you get the 2FA challenge. After responding to a push request in Duo, you need to go back to Illinois app. But the back button takes you to the login screen again.

This seems similar to the MyMcKinley login problem.

To Reproduce

1. In Illinois app, touch myIllini. 
2. Scroll to "Current Students"
3. Touch Log in
4. Enter Shiboleth credentials
5. Answer Duo 2FA challenge
6. Go back to Illinois app 

This should take you to My Illini content, but instead it takes you back to the My Illini login panel.

Iphone 11 - current ios.

**Comment by mihail-varbanov** [comment]
@pmarkhennessy / **University Monday 2021/12/13** / 2021-12-13

2.5 "My Illini", please make this use an external browser. (GIT issue #1110). (I believe this appears if you are a student on the Home panel and in the Browse panel)

**Comment by mihail-varbanov** [comment]
Fixed in 3.0.66

**Comment by joegrohens** [comment]
confirmed fixed
