### ISSUE TITLE
[BUG] Group admin name is not displayed

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1111]
**Describe the bug**
When a user creates a group, the Group admin name is not displayed on the group. 

**To Reproduce**

1. Install an Illinois app
2. Navigate to browse and tap on Groups
3. Create a public group.

**Actual Result**
 Once a group has been created the admin of the group name is not displayed on the main group screen and "Manage member's" screen of the group.

**Expected behavior**
 Once a group has been created the admin of the group name should display on the main group screen and "Manage member's" screen of the group.

**Screenshots**
![admin name](https://user-images.githubusercontent.com/26231179/145476222-4476aef7-6261-4e5b-8251-bc7f8a1e7ee1.png)
![admin name 1](https://user-images.githubusercontent.com/26231179/145476230-9c7d086b-3eb1-4ec2-b888-1e853abdca34.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.0.63]

**Additional context**

**Comment by pmarkhennessy** [comment]
Cannot recreate
