### ISSUE TITLE
[BUG] Inbox title is "Illinois" to all message

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1112]
**Describe the bug**
All the message received in Inbox has the same subject title "Illinois"

**To Reproduce**

1. Install an Illinois app
2. Navigate to browse and tap on Groups
3. Create a public group. When users create a post in the group or when we receive a request to join a group or when an event is created in the group, a message is created in Inbox.

**Actual result**
All the message received in Inbox has the same subject title "Illinois"

**Expected behavior**
The subject title should display relevant to the message.

**Screenshots**
![Illinois title](https://user-images.githubusercontent.com/26231179/145477669-1d04a6e0-62d3-4011-a9fe-ecbc6f3cca2f.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.0.63]

**Additional context**

**Comment by pmarkhennessy** [comment]
@Priyaravi8 I changed this from Medium Bug to Low Enhancement for now so it remains on the radar...also added you to the assignees...
