### ISSUE TITLE
[USABILITY] 3.0.67 Problems with events saved to phone calendar (ios)

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1136]
I would like to point out a few ways that Events saved to the iphone's ical calendar are not as good as they could be.

1. Most events coming from webtools calendars are set to be all-day or multi-day events. 
An all-day event is added to the iphone calendar as an event that starts at 12:00 am and ends at 11:59 pm. 

This 24-hour range for the event results in a color block that fills the entire day column, and covers obscures other events listed for that day.  (See screenshot 1.)

![cal 1](https://user-images.githubusercontent.com/66988329/146106169-11744f35-6c65-4672-8d18-1e6f357a7fce.png)

It would be better if the event could be saved to the calendar with the "all-day" setting switched on. Then the event will display in a single row at the top of the day column. (See screenshot 2.)

![cal 2](https://user-images.githubusercontent.com/66988329/146106519-d5a08e06-d231-4b15-9228-4b7cf43b7d32.png)

2. Also, the resource URL (assets.rokwire.illinois.edu/etc./etc.) cannot be followed by a user of the calendar. I don't know why you include it, but if there is no good use for it, I think you should remove it. Users will click the link and expect it to go somewhere, and then they will think something is broken when they get 404: Not Found.

----
Illinois App v 3.0.67
iphone ios 15.2

**Comment by TodorBachvarov** [comment]
Regarding URL (assets.rokwire.illinois.edu/etc./etc.): This is included so the user can open deeplink that will redirect to UIUC app and will open the saved Event. 
All day events in progress.
