### ISSUE TITLE
[Usability] v3.0.72 Web Content Blocked - no iphone setting to change it

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1168]
**Describe the accessibility issue**

When I try to open an external web page, I get "Web Content Blocked".
The message gives me a link to change my preferences. The link takes me to the iphone settings for Illinois app.
But I don't see any setting for cookies there. (see screenshots below)

**To Reproduce**
Examples of external web pages that provoke this message:

- Settings > Submit Feedback _(It's pretty unfortunate that this one is blocked)_
- Wellness > Wellness Reflection

![cookies blocked 1 ](https://user-images.githubusercontent.com/66988329/147803157-1d24cb5c-67f8-49d9-bf3c-901edfc3b19b.jpeg)
![cookies blocked 2](https://user-images.githubusercontent.com/66988329/147803159-6573428b-4280-471e-96de-298be2b45e87.PNG)

**Screenshots**

Smartphone (please complete the following information):

Device: iphone 11
OS: ios 15.0.2

On settings for Safari, I do have "Block Pop-ups" enabled. I don't know if this is relevant. I turned it off, and it didn't make a difference.

**Comment by joegrohens** [comment]
1. Misho told me to enable Settings > Illinois > Allow Tracking





2. Misho then told me to enable iphone: Settings > Privacy > Tracking.

> Regarding the reset, you should first go to Settings > Privacy > Tracking. There is a switch for overall control of tracking across all apps on the device - “Allow Apps to Request to Track”. It should be turned on. Then, to reset and start over, best of all would be first to uninstall the existing Illinois app and then to re-install 3.0.72 from starch. Then, after finishing the onboarding flow, try to open any Wellness page (e.g. Physical / Wellness Reflection). The operating system should prompt you whether you allow the Illinois app to track your activity.


After I enabled tracking on my iphone, I then followed a link to an external web page. The Illinois app asked me I wanted to allow tracking.
<img width="257" alt="Screen Shot 2022-01-02 at 11 50 18 AM" src="https://user-images.githubusercontent.com/66988329/147884670-828c185c-de50-4d0b-b494-b59a758e9141.png">

After I allowed tracking this time, the "Allow Tracking" option was added to 
iphone: Settings > Illinois

![settings illinois allowtracking copy](https://user-images.githubusercontent.com/66988329/147885106-da4085f4-44b4-41a2-8718-f747e9feb782.jpeg)


Also, my iphone Settings > Privacy > Tracking screen now includes Illinois app as an app that has asked for permissions to track my activity.

![settings privacy tracking copy](https://user-images.githubusercontent.com/66988329/147885176-582712ea-a3c3-4897-b06f-5229210548ce.jpeg)

But before I enabled Tracking on my iphone and tried to open an external web page in Illinois app, those tracking options for Illinois app were not available through iphone Settings.

==
**Problem and Possible Solution**

It seems to me that the iphone Settings > Privacy > Tracking setting is off by default.
This means that users might have web content blocked and not know how to allow cookies.

The user will need to do what I did:
1. Enable Tracking at iphone: Settings > Privacy > Tracking
2. Open an external web page (e.g., any of the Wellness tools). This should provoke the Allow Tracking dialog box. (screenshot 1 above in this comment post)
3. Choose "Allow".

That seems complicated, and a user will not know to do step 1.

Is it possible to redefine the link in the Web Content Blocked screen (below)?
Currently the link takes a user to iphone: Settings > Illinois
I think instead it should take the user to iphone: Settings > Privacy > Tracking. 

![webcontentblocked copy](https://user-images.githubusercontent.com/66988329/147885482-8a44cc90-e14b-46da-9e98-ca63f0b06c20.jpeg)

**Comment by mihail-varbanov** [comment]
@joegrohens,

1. I do not think that Settings > Privacy > Tracking is turned off by default, or at least it was initially turned on in my case. Did you previously (before upgrading to 14.5+) turn off sharing your Identifier for Advertisers (IDFA)? It seems that this setting affects the initial value of Allow Tracking.

2. It is not possible to redefine the link.

3. All we can do is to explain what the user should do in order to enable the overall tracking.

**Comment by mihail-varbanov** [comment]
@joegrohens, I am assigning this issue to you because I am expecting from you the resolution that we should implement.

**Comment by joegrohens** [comment]
@mihail-varbanov I will consult with some folks here about what is the best solution and come back.

**Comment by mihail-varbanov** [comment]
@pmarkhennessy: **Re: University Tuesday 2022/01/04** / 2021-01-07

Can we add at the end of the paragraph after the link, so it changes from: 

"here."

To:

"here. Your phone Settings may also need to have Privacy > Tracking enabled."

**Comment by mihail-varbanov** [comment]
Fixed in version 3.1.9 as described in the above comment.
