### ISSUE TITLE
[USABILITY] Building access - Scroll down to view the information on the screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1201]
Describe the usability issue
User has to scroll down to view their building access information on the screen.

To Reproduce

1. install the Illinois app
2. Complete the onboarding steps and login to the app with users credentials
3. Navigate to wallet screen and tap on "Use Id" in the Illini ID section

**Actual result** 
User has to scroll down to view their building access information on the screen.

**Expected Result**
Users should be able to see the building access information "Granted" or "Denied" without scrolling the screen.
Remove the extra space above the user's photo to avoid scrolling.

Smartphone (please complete the following information):

Device: [e.g. iPhone]
App version - 3.0.72

**Comment by TodorBachvarov** [comment]
Fixed in v 3.1.13+ and v3.2.4+

**Comment by Priyaravi8** [comment]
Fixed
