### ISSUE TITLE
[BUG] login loop on Android v 3.0.67

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1205]
**Describe the bug**
I am copying this bug report from a Slack message 
https://rokwire-workspace.slack.com/archives/CEQSU7PNY/p1641423660336600

These are the words of users on Slack#Feedback for Illinois app.

_User 1 Jan 4, 2022._ 

> The log in process is a loop of entering information, then being sent back to the app where you are still not logged in.

_User 2 Jan 5, 2022._

>When I try to log in from the Illinois app I'm taken to my phone browser where I log in with my Netid and password and am then returned to the app without being logged in. The app just insists that I log in and the process repeats itself over and over from app to browser to app to browser ad nauseum. It's as if following the app's instructions made no difference in logging in to the app because it leaves me no alternative other than to try to log in again using my Netid and password through the browser.

>I used to use a newer android version on a Motorola phone that I no longer use, but it didn't make any difference with the Illinois app. I still had the same problem. My current Moto G4 Android version is 7.0. I never had an issue with the Safer Illinois app even on this older android version. The Illinois app on my current phone is the current version, 3.0.67

**Comment by joegrohens** [comment]
User #2 resolved his problem by switching to another browser on his phone (to Chrome or Firefox). He thinks the browser he had been using was set to block pop-ups, possibly.

**Comment by pmarkhennessy** [comment]
This should be resolved in 3.1.12 and above

**Comment by joegrohens** [comment]
This appears to be fixed. Confirmed by Thomas Nelshoppen at Tech Services Help Desk.
