### ISSUE TITLE
[USABILITY] "Connect to Illinois" should say that login with NetID is required for Building Access

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1221]
**Describe the usability issue**
A significant number of users who report that they can't see the Building Access button are not logged in with NetID. They are either logged in by phone number, email address (e.g., hotmail) or not logged in at all. (Since Jan 1, > ten out of 100 people reporting on Feedback.) 

Their problem reports are usually something like "I can't find the building access pass - where is it?"

Could we add a sentence such as the following to the "Connect to Illinois" section on the home screen?

> “Important: Your NetID sign-in is REQUIRED to be able to use the Building Access feature.”

![Screenshot 2022-01-13 at 12 53 36 PM](https://user-images.githubusercontent.com/66988329/149542670-55d64f6c-4074-4d3a-ac7c-81ca5f452cf0.jpeg)

I would also suggest that we consider removing* the ability to sign in by email or phone number from this part of the app.  *Temporarily until campus people learn how to use the app for Building Access. Obviously this idea requires a lot of thought.

Joe

**Comment by joegrohens** [comment]
Another (possibly better) option could be to make the Building Access button visible, and prompt a user to login with NetID when they tap the button.

**Comment by dobromirdobrev** [comment]
This is implemented as follows:

> After "...your NetID." and before the button add a new sentence "(A NetID sign-in is REQUIRED to be able to use the Building Access feature)." so it now looks like "...your NetID. (A NetID sign-in is REQUIRED to be able to use the Building Access feature)."


Done in version 3.1.14
