### ISSUE TITLE
[USABILITY] Privacy Center settings is a black screen

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1229]
**Describe the usability issue**
Trying to open the privacy center settings takes you to a black screen.

**To Reproduce**
Go by any route:

- Home > Manage My Privacy (or)
- Browse > Privacy Center > Managed and Understand Your Privacy (or)
- Settings > Privacy Center

![privacy bug](https://user-images.githubusercontent.com/66988329/149876821-5392bb11-0e66-401a-b733-3444df66e06a.jpg)

**A clear and concise description of what you expected to happen.**
I see an app screen and I want it (not) painted black.
It's not easy facing up when your whole screen is black.
I want to see the privacy settings, in their summer clothes.
I have to file an issue, until my darkness goes.

**Comment by joegrohens** [comment]
v3.1.11 on both android and ios

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,
this was fixed in version 3.1.12. Please verify it. cc @pmarkhennessy

**Comment by joegrohens** [comment]
Verified fixed in 3.1.14
