### ISSUE TITLE
[BUG] Privacy level setting is not working

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1234]
**Describe the bug**
Users are not able to set the privacy level while onboarding and Manage and Understand your Privacy screen is blacked out

**To Reproduce**
1. Install the Illinois app version  3.1.11 
2. Proceed with onboarding steps
3. Select the user role as a University student and proceed to the Full access screen to set the Privacy level

**Actual Result**
The user is not able to change/adjust the Privacy level which is set on the slider. 

**Expected behavior**
User should be able to change/adjust the privacy level using the slider bar

****NOTE -**
**1.  The user continues to proceed further with the already set privacy level without changing.**
**2. Sign in as with user netid/pwd and proceed further.**
**3. Navigate to setting screen and tap on Privacy center**
**4. Tap on Manage and Understand your Privacy** 

**The app is displaying a black screen and is not able to go back or proceed further in the Illinois app.**
**Also, if the user's privacy setting is set to 2 and not able to change the level, Users are not able to see the Wallet menu in the App**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]

 - Version [e.g. 3.1.11 ]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 The slider is not meant to work in onboarding anymore as the questions control it. We are already looking at black screen issue.

**Comment by pmarkhennessy** [comment]
This should be fixed in 3.1.12 and above. N.B. We are doing the slider in onboarding.
