### ISSUE TITLE
[BUG] Groups - Add a new event - can not scroll list of other groups to select/deselect

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1238]
**Describe the bug**
I am now the admin of a lot of groups.  When I add a new event, I get the prompt to select/deselect the other groups I would like to copy the event to. My list is more then one screen long. I can't deselect the one that is partially off the bottom of the screen, and I believe there are others I can't see. Please add a scroll to that list. 

iOS version 3.1.11

**Comment by kpecknold** [comment]
Also, this may also be the reason I can't save an event to another group. After this is fixed, will need to test this.

**Comment by dobromirdobrev** [comment]
Fixed in version 3.1.13. Please verify.

**Comment by dobromirdobrev** [comment]
Fixed in version 3.1.13
