### ISSUE TITLE
[USABILITY] Font Styling for Campus Reminders

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1240]
Describe the usability issue
Campus Reminders needs style adjustment.

1. The font size of the reminder cards is too large. It should be the same size as an Event title.

2. Capitalization of the section title "Campus Reminders" is all caps. It should be initial caps, like the other section titles.

![campus reminders](https://user-images.githubusercontent.com/66988329/150042978-0ef3ceea-88c5-4fb8-a3c5-519a159b20fb.jpeg)

**Comment by dobromirdobrev** [comment]
Done in version 3.1.14.

**Comment by joegrohens** [comment]
Verified fixed in 3.1.14
