### ISSUE TITLE
[USABILITY] Groups - need a search/filter for members

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1252]
Describe the usability issue
Now that we have groups with hundreds of members, we need the ability to search/filter the list based on input in order to find a member without 50 scrolls. I'm may need to look for specific members to a) make them an admin b) remove them from the group c) confirm that they are in the group

**Comment by TodorBachvarov** [comment]
Fixed in v3.1.14

**Comment by kpecknold** [comment]
Tested in 3.1.14 - looks and works well!  Thank you!
