### ISSUE TITLE
Building Access view on older iPhone requires scrolling

### ISSUE THREAD

**Issue by RokBill** [rokwire/illinois-app#1254]
I have the following report from a user who is running V3.1.11 of Illinois.

"When I bring up the “Building Access” option on my iPhone 8+, the QR code and access status information is cut off at that the bottom of the screen.  Each time I show it I need to scroll down to display the information.  Could this page be reformatted so all the information is displayed without having to scroll down?  I remember this was an issue in the Safer Illinois app but was corrected."

**Comment by pmarkhennessy** [comment]
This should be fixed in 3.1.13

**Comment by pmarkhennessy** [comment]
@RokBill can you close this now?
