### ISSUE TITLE
[BUG] (Re)editing a group-created event produces black screen

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1262]
**Describe the bug**
 When I try to edit an event that has been created in an Illinois app Group, I get a black screen.

**To Reproduce**
After a group event is created do the following:

1. Open the Event within the Group.
2. Tap Edit
A black screen appears. (sometimes this hangs the app and I have to reinstall; usually I can back out of the black screen)

(or) 
1. Tap the three dots (...) in the Event card
2. Tap Edit
Black screen appears.

**Expected behavior**
Edit should open the Event Editing screen.

**Desktop (please complete the following information):**
Illinois 3.1.11; This bug is present in the APK for 3.1.13

iphone 11 ios 15
google pixel 3 android 12

**Comment by dobromirdobrev** [comment]
Fixed in version 3.1.15.

**Comment by joegrohens** [comment]
confirmed fixed.
