### ISSUE TITLE
[BUG] Polls in Groups - Voted and non voted options both are checked

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1264]
**Describe the bug*
Both the options (eg A and B) in the polls are checked though the user voted only for one option (option A )

**To Reproduce**
1. Install the app
2. Navigate to the group and create a poll in your own group.
3. Poll to choose OPtion A or Option B
3. Members of the group voted only for Option A in the poll and the poll is ended

**Actual result**
Both the options (eg A and B) in the polls are checked though the user voted only for one option (option A )

**Expected behavior**
App should display the result of the poll with the voted option checked but not both the option checked.

**Screenshots**
![poll in grp](https://user-images.githubusercontent.com/26231179/150434192-e7eff579-978d-4e37-ba03-b0f20d188964.png)

**Smartphone (please complete the following information):**
 - Version [e.g. 3.1.14]

**Additional context**

**Comment by dobromirdobrev** [comment]
Fixed like shown in the screenshot for version 3.1.15.

<img width="299" alt="Screenshot 2022-01-21 at 7 28 21" src="https://user-images.githubusercontent.com/5978121/150471292-84eec21b-b8f2-4861-84e7-9df2cb9e5b9f.png">

**Comment by Priyaravi8** [comment]
Fixed
