### ISSUE TITLE
[BUG] Leave the group text is cut off

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1265]
**Describe the bug**
The text of leave the group is cut off

**To Reproduce**
1. Install the app
2. Navigate to app and create a group
3. Go to the newly created group

**Actual Result**
Leave the group text is cut off

**Expected behavior**
The text should be clear to the user without cutting off. Also, it is not a button to match others in the row. It's an underlined text.

Screenshot
![leave](https://user-images.githubusercontent.com/26231179/150435165-ed890731-1b06-4453-a5fc-428b1bfd4260.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 3.1.14]

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,
Just FYI the button is not cut off but it is placed in a horizontal scroll. Either way, we placed "Leave" button below the other ones and right aligned.

As regards to the UI of the button, it intentionally looks like this as this is required is #388 .

This could be verified in version 3.1.15

**Comment by Priyaravi8** [comment]
Fixed.
