### ISSUE TITLE
[USABILITY] Groups and Notifications

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1272]
Please allow notification settings to be at the individual group level. When a person is a member of more than one group, they may want to have notifications on for some groups, but not for others.  

Current notifications are "all or nothing" and apply to all groups equally.

**Comment by pmarkhennessy** [comment]
This adds a lot of complexity. JP and I have discussed this and we should discuss this more. For now I am marking this as an enhancement and low priority and also adding you to the assignees.
