### ISSUE TITLE
[FEATURE] Groups - Restrict polls to admins only

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1280]
I don't know if this should be considered a bug, but it could become an urgent issue if not addressed.
Currently, group admins can delete posts and replies if something is inappropriate.
When polls were recently added, the same delete privilege was not added for polls.

Staff have expressed concern about the inability to delete something offensive or inappropriate. The other option would be to limit polls to group admins only.

**Comment by pmarkhennessy** [comment]
@kpecknold Will discuss with JP, just an oversight when the feature was added.

**Comment by kpecknold** [comment]
@pmarkhennessy   Res Life staff want to restrict polls to admins only

**Comment by pmarkhennessy** [comment]
@kpecknold OK got it

**Comment by TodorBachvarov** [comment]
Add post button is now available only for Group Admin.

**Comment by kpecknold** [comment]
@TodorBachvarov  Hi Todor, did you mean to say "poll" rather than "post"?

**Comment by TodorBachvarov** [comment]
@kpecknold, Yes, I've restricted add poll button. Sorry for the mistake in the comment.

**Comment by kpecknold** [comment]
This has been resolved by adding a group setting "only admins can create polls"
