### ISSUE TITLE
[BUG] Laundry should not have a dependency on audience self-identification 

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#130]
**Describe the bug**
My record is marked as a housing resident, but unless I self-identify as a student, laundry does not show up. The laundry feature should not be linked at all to how I self-identify, only to "HousingResidentStatus":true. 

**To Reproduce**
1. Contact me (courtney@illinois.edu) to be added to the system as a housing resident
2. Identify as an employee in the app
3. Login with NetID
4. See that Laundry tile does not show
5. In privacy center, personal information, change "who you are" to Student, see that it does show up

**Expected behavior**
Laundry should show up for everyone who is only to "HousingResidentStatus":true, regardless of "who you are"

**Comment by TodorBachvarov** [comment]
The role rule is removed for laundry from the talent chooser. Fixed on Dev.

**Comment by mdryankov** [comment]
@kpecknold, please retest and close if this issue is fixed? Thanks
