### ISSUE TITLE
[BUG] Privacy Level 3 cannot be set.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1305]
**Describe the bug**

1. Slide the Privacy slider to 3. 
2. Set Privacy. 
3. The Slider moves to 2.

**Expected behavior**
The setting should be 3.

**Screenshots**
![privacy settings 1](https://user-images.githubusercontent.com/66988329/152280194-dac12ab9-665f-47f4-a481-01907abcd0b8.jpeg)

![privacy settings 3](https://user-images.githubusercontent.com/66988329/152280231-c2134ef8-2a90-4882-be2c-55d6ebaeabe9.jpeg)

![privacy settings 2](https://user-images.githubusercontent.com/66988329/152280215-7d4adafe-f69d-41db-89b8-171c78db27f3.jpeg)

**Equipment:** 
ios 15, iphone 11, Illinois App v3.1.15

User Role:
University Student AND University Employee

**Comment by joegrohens** [comment]
This is still broken in 3.2.33

**Comment by pmarkhennessy** [comment]
@joegrohens we are doing privacy cleanup this month (March 2022) so we will address this during that time

**Comment by joegrohens** [comment]
This is fixed in v3.2.37
