### ISSUE TITLE
[BUG]  Events do not display after the start date and time has been reached

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#131]
**Describe the bug**
Events disappear after the start date and time have been reached.  They should not disappear until the end date and time have been reached.  This is particularly problematic for multi-day events and super events.

**To Reproduce**
1. Create an event
2. Wait until the event start time has passed, but the end date and time has not yet been reached.
3. Search for the event
4. See that it can't be found

**Expected behavior**
Events and Super Events should display until they have ended

**Comment by mdryankov** [comment]
@sandeep-ps I'm unable to create an event on dev env. Could you please help, because I'm blocked and I'm unable to debug this issue?

**Comment by sandeep-ps** [comment]
@mdryankov, I have added you to the AD group that will let you create events with a valid ID token. Please try creating event after some time.

**Comment by mdryankov** [comment]
@sandeep-ps @kpecknold  please retest with a new version. This ticket has been handled in #83
