### ISSUE TITLE
[BUG] Event Manager time conversion problem

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#132]
**Describe the bug**
Event times convert improperly (adds 5 hours) unless a valid event location is entered. This is still true even when the "virtual event" flag is checked. 

**To Reproduce**
1. Use the Event Manager to modify the "Time Conversion Example Event"
2. Change the start time to 1pm
3. Save the event
4. See the start time is displayed as 6pm

**Expected behavior**
When the "virtual event" flag has been checked, date and time should default to using CST.

**Comment by sandeep-ps** [comment]
Hi @kpecknold, this is fixed with a recent Events Manager feature https://github.com/rokwire/events-manager/issues/533. We will get the next version of Events Manager with this feature released soon.
