### ISSUE TITLE
[USABILITY] Change label in Personal Info: should be UIN

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1334]
Go to Settings > Personal Information > Personal Information 

The UIN at the top of the screen is labeled "NetID".

Please change the label to "UIN".

thx
![NetID sb UIN](https://user-images.githubusercontent.com/66988329/153305413-4f6da697-699a-43ac-be9e-5e46f58147c0.png)

**Comment by dobromirdobrev** [comment]
Fixed in version 3.2.34.

**Comment by joegrohens** [comment]
confirmed fixed in v3.2.34
