### ISSUE TITLE
[USABILITY] Changing from Browse to Home doesn't work sometimes.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1355]
**Describe the usability issue**

Occasionally the Illinois app will get locked on the Browse screen, and user is unable to change to Home screen or Wallet.

Here is a screenshot of Home screen button selected, but still on Browse screen.
![home screen shows Browse](https://user-images.githubusercontent.com/66988329/154294711-9d6e55cd-8dc4-43b2-a2b0-637efa9b296a.jpeg)

**To Reproduce**
1. Tap Browse to view Browse screen. 
2. Mess around. (Not sure exactly what we did to trigger. See paragraphs below.)*
3. Tap Home. The Home screen does not appear, and instead Browse is still shown.

*We have been able to reproduce this, but we aren't sure what we have done immediately prior to trigger this condition. It always comes as a surprise while we are doing other things.

But it probably involves playing around with Privacy Settings. 

You will notice that there is no Wallet visible in this screen shot. It means I was probably only privacy level 1 or 2. And possibly signed out.

Once the Browse screen is locked, the user has to quit the app and restart to enable Home screen again.

(Update: See also issue https://github.com/rokwire/illinois-app/issues/1357, CASE 5, Step 7, for a description of some things I did to trigger this "stuck on Browse screen" state.)

**Equipment**
iphone 11, ios 15
Illinois app v 3.1.15

**Comment by dobromirdobrev** [comment]
Fixed as part of #1357 . Please verify it in version 3.2.27 or greater.

**Comment by joegrohens** [comment]
Confirmed fixed in 3.2.33
