### ISSUE TITLE
[USABILITY] Privacy Center settings do not work as advertised

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1357]
**Describe the usability issue**

Privacy Level settings to do not produce the effects one would expect.

Rebecca and I did several experiments changing to different privacy levels. I will describe each case below.

**CASE 1**
1. Start with privacy level 5, signed in w NetID
2. In Privacy Center, change privacy level to 1. 
A confirmation screen appears. It warns of reduction in features, **including that you will be "logged off".**
![privacy settings warning 1 sm](https://user-images.githubusercontent.com/66988329/154124686-69018ef2-ba94-4595-8ece-a93361981470.jpeg)

3. Look at Home screen - Building Access is still there while user is at Privacy Level 1.

4. Look at Settings > Personal Information : personal info is still there; user is still logged in.
![Personal Info privacy 1](https://user-images.githubusercontent.com/66988329/154126895-b86a2c3f-7fbe-46c2-a7c6-3caca952ba33.jpeg)

5. Look at Settings 
_Disconnect your NetID_ is not there, even though user is still logged in.

**Conclusion:** 
Changing to level 1 should sign out the user, but it does not. Level 1 does hide the Wallet. We did not explore what other features were disabled or left enabled. 

**CASE 2**
1. Start with privacy level 5, signed in w NetID.
2. Set privacy level to 3.
3. Confirm and Save Setting.
![privacy settings 3](https://user-images.githubusercontent.com/66988329/154175420-0e3c7037-b958-445c-b64a-94987e44ee0d.jpeg)

4. Look at the Privacy Center setting. The privacy setting will be level 2.
5. Look at Settings > Personal Information. User is still signed in.

**Conclusions:** The privacy was set to a level one increment below the level selected. There is no way to set Level 3. Also, as with privacy level 1, the user is not signed out at level 2, but we think should be.

**CASE 3**
Similar to Case 2, try to set privacy level to 2, and you will find that the saved setting is actually level 1.

Conclusion: The slider misrepresents the setting that you actually get.

**CASE 4**
We wanted to see what privacy level would be created if a user signs out.

1. Start at level 5 and sign out.  (Settings > Personal Information > Sign Out)
2. Look at Personal Information. User information is absent.
![personal information signed out](https://user-images.githubusercontent.com/66988329/154178112-a2957683-4419-4b4e-8349-50206715a6b7.jpeg)

3. Look at Privacy Center > Manage and Understand Your Privacy. The privacy setting is still level 5. (I think it should have changed to 3.)
4. Go to Home screen. The _Connect Your NetID_ is shown. 
5. Tap it to sign in. The app signs you in without taking you to Shibboleth. Privacy Level is still at 5, where user left it before signing off.

**Conclusions:** Signing out should reduce your Privacy Level to at least 3, but it doesn't.

**CASE 5**
What will happen if you sign out, and then set Privacy Level to 1?

1. Start with Privacy Level 5.
2. Sign Out.
3. Open Privacy Center > Manage and Understand Your Privacy. (You will see that privacy is till at level 5.)
4. Slide the privacy level to 1. Tap "Set Privacy. 
The same confirmation panel is shown as in Case 1. It says that changing privacy level will "Log you off system", even though you are already logged off.
5. Tap "Yes" to confirm.
6. Go back to the Privacy Center > Manage and Understand Your Privacy. You will see that your privacy level is 1. 

![slider set my privacy](https://user-images.githubusercontent.com/66988329/154179680-75d65488-2497-4e45-8243-69ecfe06dbb2.jpeg)

...

7. At this point I tapped the "Set my Privacy" button because it was enabled, and I wanted to see what would happen. When I tapped it, I was unable to go to the Home screen and was stuck on the Browse screen. (Cf., https://github.com/rokwire/illinois-app/issues/1355.) In issue 1355 I was unable to describe what caused the Browse screen lockup. But I think tapping Set Privacy without changing the slider might be involved; at least it was this time.

...
8. I had to restart the app.  I then continued in the state of privacy level 1, signed out.
9. Go to Home screen. Tap _Connect your NetID_.  
10. I was logged in without being taken to Shibboleth. (I believe this is normal behavior.)

**Conclusions:**  
- Confirmation panel says "you will be logged off" when you are already logged off. It could be smarter than that. 
- Why do you have to go back to the _Privacy Center > Manage and Understand Your Privacy_? after confirming "Set My Privacy?" That's where you were before when you got the confirmation panel. The app should stay there so that users can see that they have the privacy level they wanted.

**Other notes:**
The confirmation panel of "Your New Privacy Level" lists data exchanges that don't really seem to happen in Illinois app. I think this screen needs to be reviewed and probably rewritten.

The confirmation panel in Case 1, Step 2 above, (changing to Privacy Level 1) warns that changing to level 1 will:
- Don't store your location. (Is location really stored in the system or on the phone? I don't see where location history is used.)
- Log you off system. (As has been shown, the user is never logged off. But I think this is a bug.)
- Turn off notifications. (This warning is accurate. It does turn off notifications.)
- Remove your credit card info. (Is credit card info really stored anywhere in the app or the system? The only use of credit card is Illini Cash, and this appears to be a pass-through use of bankcard credentials.)
- Don't share your data with other users. (Now that Converge is not used, I don't think we have any data exchange with other users. And even in the case of Converge, was data shared with "other users" or with another data processing system?)

**Comment by mihail-varbanov** [comment]
Many of the problems described here had been fixed by the above updates but overall check of privacy processing across the entire application is still needed.

**Comment by joegrohens** [comment]
I tested these changes in v3.2.33. 

- Case 1 is fixed. Changing from level 5 to level one logs out the user as advertised. 
- Case 2 is partly fixed. The user is logged out, as they should be. But changing from level 5 to level 3 results in a change to level 2 (bug). 
- Case 3 is partly fixed. The user is logged out, as they should be. But changing from level 5 to level 2 results in a change to level 1 (bug).  
- Case 4 is the same as before. I am not sure what the app should do here. It seems like there is no point to being at level 5 unless you are signed in. So I naively thought that signing out would lower your privacy level to 3 or lower.
- Case 5 seems fixed. After doing the procedure described above, I could not reproduce the freeze on the Browse screen.

**Comment by mihail-varbanov** [comment]
Thanks for this summary, @joegrohens! @pmarkhennessy, we should probably include the complete cleanup of privacy handling in the TODO list for 3.3?

**Comment by joegrohens** [comment]
**Update based on v3.2.37**

Cases 2 and 3 are now completely fixed. Changing settings to level 3 and level 2 no longer slips to a lower setting.

Case 4 is still something I wonder about. If you sign out, should it lower your privacy level to 3?
