### ISSUE TITLE
[FEATURE] Modify the Wellness Answer Center button (Home Screen)

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1364]
**Is your feature request related to a problem? Please describe.**

This request from Technology Services Help Desk is intended to solve a problem of overload, where they get COVID-related questions that are better directed to McKinley Health Center and other offices on campus. 

The Help Desk has asked for modifications to the contact information given in the Wellness Answer Center button, so as to head off people with issues that the Help Desk can't really handle, such as medical ones.

**Describe the solution you'd like**

Please make the following modifications to the "Wellness Answer Center" BUTTON on the Home page.

1. Change the title of the button to: "Answer Center". 
2. Change the sentence below the button's title to: "Get answers to your questions."

Also, please make the following modifications to the Wellness Answer Center PANEL that opens after tapping the button.

1. Change the title of the panel to "Answer Center".
2. Replace the text content of the panel with the content of these two buttons (which are links to pages in the Campus Guide). 

![Contacts for Covid Help](https://user-images.githubusercontent.com/66988329/154411039-794c6c87-fb28-4d36-85df-985a2be1d65f.jpg)

The first one links to _Campus Guide > Help > Contacts for COVID-19 Issues_

![faqs](https://user-images.githubusercontent.com/66988329/154412553-240c5be0-daa5-4ca7-800c-c22245737c03.jpeg)

The second one links to _Campus Guide > Help > Building Access FAQs_

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,

I have comment about the last portion of this task.

> 1. The first one links to Campus Guide > Help > Contacts for COVID-19 Issues

> 2. The second one links to Campus Guide > Help > Building Access FAQs

These two cannot be linked as desired. All the content in "Campus Guide" is built based on a json content retrieved from Content BB - section, categories etc. These items have nesting and we cannot just link to a specific Guide item from outside the "Campus Guide". 

What we can do is to create new panels with hardcoded data. Please, let me know if this works for you. cc @pmarkhennessy .

**Comment by joegrohens** [comment]
@dobromirdobrev @pmarkhennessy 

Hi Dobromir -

Can you see how the Campus Guide content is linked to _Wellness Widget > Health & Wellness > Physical Wellness > Wellness Pledge?_ 

When a user taps "Wellness Pledge", a panel opens that displays the content of _Campus Guide > Mental & Emotional Health > Wellness Pledge_. It somehow bypasses the nesting.

The content for this "Wellness Pledge" opened from the link in the Wellness Widget does not seem to be in a hardcoded panel. Because when I make a change to the text of the Wellness Pledge in the Campus Guide (by editing Content BB in the Admin app), the same change is then displayed in the panel that follows from the Wellness Widget. 

I would like you to use the same mechanism here that we used in the Wellness Widget. Is that possible?

If it is not possible, then yes, we could live with a hardcoded panel temporarily. But at some point in the near future the content will need to be updated, and I believe the best way to do that is through the  Content BB. 

Thank you.

Joe

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,

Thank you for the guidance! We defined ids of these two specific guide items in the app config. And when the user taps on one of them, the app opens the specified guide item. This is implemented in version 3.2.26. You can check it and let us know.

P.S. I reopen the issue because github closed it automatically.

**Comment by joegrohens** [comment]
@dobromirdobrev 

I have checked this in a dev version. Since the Content BB for dev doesn't have this content, I can't verify how the guide page will look. However, the buttons look good.

**Comment by joegrohens** [comment]
I will leave this issue open until I can verify it in prod.

**Comment by joegrohens** [comment]
I have verified this implementation in v3.2.33
