### ISSUE TITLE
[FEATURE] DateCat Tile

### ISSUE THREAD

**Issue by ToddNelson** [rokwire/illinois-app#1371]
**Is your feature request related to a problem? Please describe.**
A temporary solution until calendaring for campus LMSs are integrated into the Illinois App.

DateCat (or Due Date Catalog) is an application that merges all assignments and due dates from Moodle, Canvas, and Compass into one calendar. 

**Describe the solution you'd like**
Please add a "DateCat" tile to browse menu of Illinois App (please double-check with JP on integration specifics).

**Additional context**
The DateCat application is at:  apps.atlas.illinois.edu/datecat
The ATLAS AppDev team are available to help test, please let me know when we are ready to pass an APK to them for testing. (I understand their app log-in is similar to myIllini, using Shib)

**Comment by mihail-varbanov** [comment]
**Re: University Monday 2022/02/21** / 2022-02-23

4.1 Issue 1371: Use an "external" browser for the URL in the issue and in the Browse panel above State Farm Event Parking (see due_date_catalog.png) add "Due Date Catalog" to invoke the browser.

![due_date_catalog](https://user-images.githubusercontent.com/5631487/155323587-34db434c-f05d-4c5c-9827-7fc360595558.png)

**Comment by mihail-varbanov** [comment]
Added in version 3.2.25

**Comment by ToddNelson** [comment]
Thanks, we'll pass along to the testing group once the next APK is available for testing. Will reopen if needed.
