### ISSUE TITLE
[USABILITY] Capitalization changes in various screens

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1386]
We conducted a capitalization audit of screens in Illinois app 3.0

The changes requested conform to these style rules:

- Titles use title case.
- Section headings use title case.
- Sub-headings use title case.
- Buttons use title case.

The links to screen captures should be accessible. Some of the image files are in Google Drive. We shared the folder with @TodorBachvarov. If links don't work, or someone else needs access, please comment and I will fix it.

Also, if a different format for this report (e.g., spreadsheet, google doc) would be more convenient, please let me know and I will reformat.
Thank you,

Joe Grohens

....
[Capitalization Audit submitted.docx](https://github.com/rokwire/illinois-app/files/8128848/Capitalization.Audit.submitted.docx)

**Comment by joegrohens** [comment]
Mark asked me to put the screens in a zip folder. I am uploading three zip folders here that contain the screens.

The resubmitted .doc file says which ZIP file is used for each section.


[Screens 1.zip](https://github.com/rokwire/illinois-app/files/8137872/Screens.1.zip)
[Screens 2.zip](https://github.com/rokwire/illinois-app/files/8137875/Screens.2.zip)
[Screens 3.zip](https://github.com/rokwire/illinois-app/files/8137877/Screens.3.zip)
[Capitalization.Audit.resubmitted.docx](https://github.com/rokwire/illinois-app/files/8137878/Capitalization.Audit.resubmitted.docx)
.

**Comment by dobromirdobrev** [comment]
Done in version 3.2.27.

P.S. I reopen this issue because github closed it automatically.

**Comment by joegrohens** [comment]
All changes have been made. Thank you, Dobromir.
