### ISSUE TITLE
[USABILITY]_Campus Reminder font style

### ISSUE THREAD

**Issue by nataliehelregel** [rokwire/illinois-app#1401]
Hello!

Design Issue:
The font style for Campus Reminders within the Home screen is difficult to read. The reminders are written with enough characters that they should be treated a paragraph text as opposed to header text which is bolder and larger. 
I'd also suggest rearranging the text and date so the deadline date is above the actual text reminder. 
Current Design-
![image](https://user-images.githubusercontent.com/96087558/155751405-8858e2c3-b608-433b-a231-72df861527bb.png)

To Reproduce:
Change the text within the reminders to the same size and thickness as other body copy on the home page. Example font styles to mimic would be the Campus Guide Highlights at the bottom of the home screen. 
Mock Up Example-
![Campus Reminders Font Style Re-Design_01](https://user-images.githubusercontent.com/96087558/155751663-fc4422f1-b3bc-49a8-a293-b69f777f1634.png)

Thanks!

Natalie Helregel
UX Designer
Smart, Healthy Communities Initiative Office

**Comment by pmarkhennessy** [comment]
@nataliehelregel Thank you. I will bring this up during my Tuesday planning meeting.

**Comment by joegrohens** [comment]
I agree with Natalie's recommendation for font and also the position of the date. I initiated this issue with Natalie.

**Comment by mihail-varbanov** [comment]
Resolved in version 3.2.34.
