### ISSUE TITLE
[FEATURE] Alternate Login Changes

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#1407]
**Re: University Monday 2022/02/28** / 2022/03/01

3 Todor/Dobromir. We need to get this done tonight. It involves changes to Home panel "Connect" widgets, Settings panel and panels invoked from the Settings panel.

https://miro.com/app/board/o9J_khwejqw=/?moveToWidget=3458764519950627981&cot=14

https://app.zeplin.io/project/61df16e6e59b1b28c417589b/dashboard

This alternate login was implemented by Ryan, I believe, at Rockmetro. JP and I have reviewed it, hence the Miro changes. I attach screenshots circled in red for obvious changes.

N.B. In Settings - Updated.png The top section is being removed and replaced with the section at the bottom with the Sign out button. We would use the same method for Phone or Email, showing the correct number or email and the method "Phone" or "Email".

N.B. Settings - Add Email Address.png will also be used for Phone. It will need title bar, text, edit control text and button changed accordingly.

N.B. Settings -Updated Phone Number.png and Settings -Updated email.png are what happens if the alternate login type is already set.

![Settings - Updated](https://user-images.githubusercontent.com/5978121/156118070-6b3f5a07-3ee5-429d-844e-65d2007c99e0.png)

![Settings -Updated Phone Number](https://user-images.githubusercontent.com/5978121/156118075-d8c46c0e-44f3-4812-a689-95ef3c252ab6.png)

![home_connect](https://user-images.githubusercontent.com/5978121/156118078-2b67a8bb-89f0-466a-8fe3-f3e310784479.jpg)

![Settings - Updated Email](https://user-images.githubusercontent.com/5978121/156118086-c9ae6f34-dc18-4158-972d-e8a77d3c50dd.png)

![Settings - Add Email Address](https://user-images.githubusercontent.com/5978121/156118088-bf75f786-7af8-4b29-adfd-09841c4ea1b4.png)

**Comment by TodorBachvarov** [comment]
More changes: 
![error_text_email](https://user-images.githubusercontent.com/11226365/156426916-3a43a567-1559-4b82-9168-c4f1dcf47224.jpg)
![error_text_phone](https://user-images.githubusercontent.com/11226365/156426930-80d55b73-9f7c-40ef-9ce7-cce781e9bbf3.jpg)
![settings_look_phone](https://user-images.githubusercontent.com/11226365/156427013-f91ad027-87b5-460f-a7ea-b9ec74b9bc1a.jpg)
![settings_not_signed_in_3_changes](https://user-images.githubusercontent.com/11226365/156427039-0611bb30-7323-4bd9-a404-e3ac95690229.jpg)
![settings_typo](https://user-images.githubusercontent.com/11226365/156427074-8c90ed63-82ca-42c3-afdb-2089062769e5.jpg)
![title_bar_typo](https://user-images.githubusercontent.com/11226365/156427232-a041357c-31d0-4be1-8b7e-fcb19e0bf04f.jpg)
