### ISSUE TITLE
[BUG] Linking NetId account does not require removing

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#1420]
**Re: University Monday 2022/02/28** / 2022-03-04

2 We found only one problem now with Alternate Logins. If you are logged in with Email or Phone and you add netID as an alternate login we do not ask you to re-login with the currently signed in mechanism (email or phone). We only do this correctly if we are signed in with netID and add an email or phone. Please fix.

**Comment by Priyaravi8** [comment]
@mihail-varbanov - I logged in with my Phone number. Tap on Add a netID for "Alternate Sign Ins" - " Sign in Required" message is displayed
![Alternate add netid](https://user-images.githubusercontent.com/26231179/157286373-92dd6b98-c1c0-43c7-b95c-3bb300c1872b.png)

**Comment by mihail-varbanov** [comment]
Hi @Priyaravi8, yes, this is the correct behavior. Each time we attempt to add an alternate account the user has to re login first with its current account.

Here is the specification for this that we got from @pmarkhennessy:

**Re: University Monday 2022/02/28** / 2022-03-02

`1.6 To resolve the current 403 error you see and one step the old way did not have, is when you click the alternate account to do an "add" we need to make the user "re-login" with the method they are currently logged in as before showing the add panel. So if they are netID logged in and adding a phone then show the Shib login and after a successful login then show them 3NewPhoneAdd.png followed by 4NewPhoneAddStep2.jpg etc. If the user is logged in by phone then we would want them to re-login by phone before showing add email etc`

![3NewPhoneAdd](https://user-images.githubusercontent.com/5631487/157389411-c38dd5d1-f433-433e-b703-227d2981b2c4.png)

![4NewPhoneAddStep2](https://user-images.githubusercontent.com/5631487/157389451-42ea07e9-a32f-4012-90ea-e6467f407981.jpg)
