### ISSUE TITLE
[BUG]Groups -  Cancel button on Select image screen is not working

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1441]
**Describe the bug**
Tapping the Cancel button on the Select Image screen should cancel the image uploading function but its not doing its job.

**To Reproduce**

1. Install the Illinois app
2. Complete onboarding steps and login to the app with Netid
3. Navigate to Group and tap on "Create" to create a group
4. Tap on the "Add Cover" image on Create a Group screen and tap on "Choose from device option"
5. Tap on the "Gallery" option and select an image in the gallery and tap the tickmark to add the image

**Actual Result**
Tap on the Cancel button on the Select image screen.  The **Cancel** button is not working.

**Expected behavior**
Tapping the Cancel button on the Select Image screen should cancel the image uploading function.

**Screenshots**
![cancel image](https://user-images.githubusercontent.com/26231179/157551696-c7ab862c-5e4e-4ab0-822c-9a2fae437e3f.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.2.34]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 Fixed in 3.2.35, please confirm and close when it becomes available
