### ISSUE TITLE
[BUG] Many app users on Android are not able to get past the splash screen

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#146]
**Describe the bug**
Many app users on Android are not able to get past the splash screen. This is replicated by many users and is also reported in the app store reviews.

**To Reproduce**
1. Install the app in an Android device
2. Start the app
3. The app is stuck on the splash screen and the text "Your official companion for the University of Illinois" and "Get Started" button are missing in that screen (see screenshot below).

**Expected behavior**
App should load successfully for all Android users.

**Screenshots**
![image](https://user-images.githubusercontent.com/4306604/97764888-21610380-1ade-11eb-8316-15e723116f90.png)

**Smartphone (please complete the following information):**
 - Device: LG G5
 - OS: Android 8
 - Version 2.2.18

**Additional context**
The issue reported here is as discovered by one user, but some people have reported that the app stopped working in Android after some time. It is not clear whether it was due to the update. In the test Android devices that we use, the app is loading fine.

**Comment by dobromirdobrev** [comment]
Hi @sandeep-ps ,
We are unable to recreate this issue on our side. We handled two crashes (#139 & #144 ) that could be related to this problem but we have no proof that they have something in common with this behaviour. 
Could the one reported this issue supply any logs from his device? They will be very helpful for us.

**Comment by nelshopp** [comment]
Hi @sandeep-ps, 
I have another customer with a similar issue (Pixel 5).  Should I contact him and get some more data points regarding his issue?  
Also, is this issue limited to Android?  Another customer is having the same issue with iOS.  I have some details on that.  Let me know how you want to proceed with that one.  

-Tom

**Comment by sandeep-ps** [comment]
Hi, @nelshopp, yes, gathering more details including steps to reproduce will be helpful. If sensitive data is involved, please share it via email or Slack. When this issue was created, it was probably reported only in Android. Please feel free to create another issue specifically for iOS users. I guess the fix for that one might be different from Android.

**Comment by sandeep-ps** [comment]
@nelshopp, I suggest that we close this issue as it's very old and most likely this isn't a bug now. We can always open another bug report if this comes up in the future. What do you think?

**Comment by nelshopp** [comment]
That is fine with me, @sandeep-ps .  Feel free to close. 

Tom
