### ISSUE TITLE
[BUG] Users not able to login to Quick poll when Privacy level set to 3

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1477]
**Describe the bug**
Setting the Privacy level to 3 while onboarding, users are not able to login to Quick poll with their Netid and PWD. If Polls display only for the Privacy level 4 and up, Users need to be informed on the screen to set the privacy level 4 and up instead of displaying the Login button.

**To Reproduce**

1. Install the Illinois app
2. While onboarding, set the privacy level to 3
3. Proceed further and tap on the Browse menu
4. Tap on Quick poll and Login
5. Enter the user Credentials - Netid/Pwd

**Actual Result**
Users not able to login successfully and load the Polls

**Expected behavior**
Users should be able to log in and see the Polls.

**NOTE - If Polls display only for the Privacy level 4 and up, Users need to be informed on the screen to set the privacy level 4 and up instead of displaying the Login button.**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 3.2.37]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 We are working privacy and what happens around privacy this month for the next release

**Comment by knguyenjahiel** [comment]
Closing this ticket. In the current 4.3.61 prod version, Privacy Setting Level 3 does not require login. Subsequently, as currently designed, users cannot see Polls if their Privacy Setting Level is below 4.
