### ISSUE TITLE
[FEATURE] Make Groups FERPA compliant

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#1484]
**Re: University Monday 2022/03/21** / 2022/03/23

1.2.1.3 Groups to be FERPA compliant. 

1.2.1.3.1 In settings/privacy center at the bottom above Privacy Statement add a Checkbox default to false for "FERPA compliant". Store in Core BB user profile?

1.2.1.3.2 May need Mladen. In Groups only show a user's Name to Admins if this user has FERPA True. So for regular members anywhere they can see a member's name it must be hidden. For now just show "Suppressed" as the name.

**Update**: FIRMA replaced with FERPA

**Comment by kpecknold** [comment]
@dobromirdobrev   Good morning, I believe you mean FERPA (Family Educational Rights and Privacy Act)?

**Comment by dobromirdobrev** [comment]
Hi @kpecknold ,

This is taken from @pmarkhennessy 's request. 

Mark, could you please explain what you mean by FIRMA (or is it FERPA)?

**Comment by pmarkhennessy** [comment]
@dobromirdobrev FERPA is correct and thanks @kpecknold for correcting this.

**Comment by dobromirdobrev** [comment]
Update 1: **Re: University Monday 2022/03/21** / 2022/03/24

1.1 To make things clearer attached pics show Admin view of members and Member (not Admin) view of members. See member_only_group_members_view.png and admin_group_members_view.png

1.2 The attached images also show how to handle FERPA for Admins and Members. See member_only_group_members_view.png and admin_group_members_view.png. I think it is better to just replace a FERPA member's name with *s.

1.3 See member_only_group_home_panel.png for how we should let a member get to the member list panel. I think the member profile picture create/edit etc can go below the link in the image. "Groups profile picture". See also 1.4 below.


![member_only_group_home_panel](https://user-images.githubusercontent.com/5978121/159856797-2dba7115-6c6c-426b-847c-7dcebfda6b03.png)
![admin_group_members_view](https://user-images.githubusercontent.com/5978121/159856811-717996dc-28b2-437a-831b-06ba1cce8299.png)
![member_only_group_members_view](https://user-images.githubusercontent.com/5978121/159856815-57a81e56-cb17-4e49-850f-784dc541025e.png)
