### ISSUE TITLE
Add Healthy Illini Podcast to 'Interactive Activities' section of all Wellness Pages

### ISSUE THREAD

**Issue by dr-mel** [rokwire/illinois-app#1485]
**Describe the solution you'd like**
Please add an icon linked to the Health Illini Podcast page: https://anchor.fm/mckinley-health-center.

The icon should live under the "Interactive Activities" section of each Wellness Page.

A VERY rough mock-up is attached.

Email or slack me for more details:

mrfenner@illinois.edu
@Mel Fenner on Slack

![HealthyIlliniPodcast](https://user-images.githubusercontent.com/95657673/159739511-1a386fae-f649-4c8e-b37b-0ab2ea512828.PNG)

**Comment by mihail-varbanov** [comment]
Added in version 3.3.5.

NB: I created the podcast icon by myself trying to make it similar to the other wellness icons. If you do not find it appropriate please provide the icon to use there (222x222@72ppi).

**Comment by dr-mel** [comment]
> Added in version 3.3.5.
> 
> NB: I created the podcast icon by myself trying to make it similar to the other wellness icons. If you do not find it appropriate please provide the icon to use there (222x222@72ppi).

Where can I see the icon you created?

**Comment by mihail-varbanov** [comment]
@dr-mel, here is quick snapshot:

![Simulator Screen Shot - iPhone 13 - 2022-03-24 at 17 01 13](https://user-images.githubusercontent.com/5631487/159946065-9dff4192-4886-4903-9399-299898c826c5.png)

I asked @TodorBachvarov to post the links to the today build (3.3.5) here so you can try it in real.

**Comment by dr-mel** [comment]
This looks pretty good. I'm getting feedback from other stakeholders and will let you. 

To clarify, the icon should be under the Interactive Activities section of each area of wellness. So if you click on Physical, Mental, Environmental, Financial, Spiritual, Vocational, Emotional, or Social the podcast icon should be there. Hope that makes sense.

**Comment by mihail-varbanov** [comment]
@dr-mel,

Yes, it makes sense. The "Health Illini Podcast" button is added to all "Interactive Activities" sections across the wellness panels. BTW, the Financial panel does not contain "Interactive Activities" section so "Health Illini Podcast" does not persist there. This should get available in version 3.3.6.

**Comment by vburgett** [comment]
@mihail-varbanov add a "y" to "Health" since it should be "Healthy Illini Podcast" for all instances
 
In version 3.3.16 interactive activities is still not available for the financial section.

**Comment by mihail-varbanov** [comment]
@pmarkhennessy ^

**Comment by dr-mel** [comment]
Sorry, @mihail-varbanov @pmarkhennessy -- I misspelled the title of the button in my original request. 

It should be "Healthy Illini Podcast".

-Mel

**Comment by mihail-varbanov** [comment]
Fixed in main develop branch and v3.3 support branch. The fix should be available in Illinois app version 4.0.2 and in version 3.3.23 in case we do not release the current release candidate 3.3.22.

**Comment by mihail-varbanov** [comment]
Yes, @dr-mel. You should leave this issue opened until you verify the change after you get the next build/release.
