### ISSUE TITLE
[ACCESSIBILITY] Quick Polls - TalkBack user not given status messages

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#1496]
**Describe the accessibility issue**
Closing Poll - TalkBack user not given status message of completion. 
[WCAG 4.1.3 Status Messages (AA)](https://www.w3.org/TR/WCAG21/#status-messages)

**Steps to reproduce the behavior:**

1. Go to 'Quick Polls.'
2. Swipe to an open poll that has option to "End Vote"
3. Select "End Vote" by double tapping

**Expected behavior**
When TalkBack user selects "End Vote" they expect to hear a status message stating the poll voting was closed. I would also expect to be taken out of the end vote modal and back to the Quick Vote screen. 

**Actual behavior**
When TalkBack user selects "End Vote" they hear nothing but land on the back button of the Quick Polls screen. They have to swipe twice right to hear where they are and re-orient themselves.

**Screenshots**
![Screenshot_20220325-152515](https://user-images.githubusercontent.com/82892873/160196095-3e5e35e6-db0a-4599-a96f-4d853ced2002.png)

**Smartphone (please complete the following information):**
iPhone XR- iOS 14.6, Pixel 4a- Android 12

**Additional context**

**Comment by TodorBachvarov** [comment]
Added announcement "Poll ended successfully" when End Poll is clicked and "Poll voting ended successfully" when Done Voting button is clicked. Added in version 3.3.8. 
Regarding the default focused element when we close the dialog and land back on the Quick Polls Panel(back button) - This is the default flutter behaviour and we can't manipulate it. Flutter do not provide mechanism to customize the AccessibilityFocus so we have to stick with the default behaviour.

**Comment by acovher2** [comment]
Verified as resolved in 3.3.8. Closing.
