### ISSUE TITLE
[USABILITY] Problems when features require authentication at privacy level 3 or lower.   (v3.2.37)

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1508]
**Describe the usability issue**

Now that we require Privacy Level 4 and 5 to login with NetID, users are experiencing a few problems and confusions. 

Some features require authentication with NetID, and they allow users to authenticate when their privacy level is set to 3 or lower. With that privacy setting, the user can successfully go through authentication (Shibboleth w/ 2FA), but when they return to where they started in the app, the users still can't use the feature that requires authentication. The users continues to see a requirement to sign in, and they can't use the feature.

Examples of such features are:

- Groups
- Quick Polls
- Browse > Illini Cash
- Browse > Meal Plan
(I think that's all, but not sure. The Wallet is hidden at Level 3 and below, so Wallet and Bus Pass don't present this problem. The Wallet widgets that are double-listed on the Browse panel are problematic.)

After the user has authenticated once, their phone caches a login status token (apparently), so that the next time they tap "Login" or try to open a feature that requires sign in, the Shibboleth page is displayed for a split second, then the screen where they started is display, with users being still unable to use the desired tool. This outcome is inexplicable to the users. They report that they "have already logged in" but the app doesn't recognize it. Or they report that they are "caught in a login loop". 

Nowhere does the app warn that they have the wrong privacy level setting for logging in.

**To Reproduce**

_Quick Polls_
1. Set privacy to 3
2. Tap Browse > Quick Polls
3. Tap the "Login" button
4. Authenticate at SSO
5. View the Quick Polls screen. 
You are not able to create a poll. The Login button is still visible.
6. Tap "Login" again. You will briefly visit SSO and then return to the Quick Polls page

_Groups_
1. Tap Browse > Groups
2. Authenticate at SSO
3. View the Groups screen. "Failed to load groups" is displayed.

_Try Groups again_
1. Tap Browse > Groups
2. SSO screen appears briefly.
3. View the Groups screen. "Failed to load groups" is displayed.

![failed to load groups](https://user-images.githubusercontent.com/66988329/160950522-58459c4b-490e-4c75-b8bc-a20d262b5f32.png)

_Illini Cash_
1. Tap Browse > Illini Cash
2. Tap Log in to view

**Expected Behavior**
Following are some partially thought out alternatives that might be better. 

- The app could hide features that require Privacy Level 4 or higher. Like the app already hides the Wallet. (or)
- The app could hide the "Login" buttons until they have Privacy Level 4 or higher. (or)
- When the user taps "Login" or opens the Groups widget, the app could tell the user through a pop-up that they need a higher level privacy setting to sign in. "You must set Privacy Level to 4 or higher to sign in and <do whatever action they need to sign in for>." Provide a dismiss button. (or)
- Going a bit farther, a modal dialog could ask if the user wants to change privacy level so they can sign in.
: "You must set Privacy Level to 4 or higher to sign in and <>. Would you like to change your privacy level and sign in"? [ Y ] [ N ] 
: "Yes" could take them to the Privacy Center. 
: Or, "Yes" could give them a chance to "Set privacy level to 4" (announced by "Setting Privacy Level to 4"), followed by taking them to the SSO page, and then by taking them back to the widget they were trying to use. (I realize this last is a bit of a fantasy.)

Illinois app Version 3.2.37

**Comment by pmarkhennessy** [comment]
@dobromirdobrev Hold on this please. I am discussing privacy actions today and will let you know.

**Comment by TodorBachvarov** [comment]
I’ve added a message similar to the one for Groups. I’ve done it for Quick  Polls, Meal Plan and Illini Cash settings panels.

**Comment by joegrohens** [comment]
I am closing this, as the error messages for "login required" have become uniform throughout the app.
