### ISSUE TITLE
[BUG] Replace the "Skip" button with "Continue" if users watch till the end of the video

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1511]
**Describe the bug**
Once the user watches the full video, replace the "Skip" button with "Continue"

**To Reproduce**

1. Install the Illinois app
2. Proceed to onboard video
3. Wait for the video to complete

Actual Result
The "Skip" button still displays even after the completion of the video

**Expected behavior**
Replace the "Skip" button with "Continue" if users watch till the end of the video

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.3.8]

**Additional context**

**Comment by dobromirdobrev** [comment]
Fixed in version 3.3.9.
