### ISSUE TITLE
Inconsistent spacing in json strings file

### ISSUE THREAD

**Issue by karacw** [rokwire/illinois-app#1512]
@balicea
The localization team were asked to keep precise spacing in the localized versions of the json strings file, same as the English one. However, we have noticed inconsistent spacing in the English file which might be an issue even for English. 
See the attached screenshot, showing some strings with a space after the colon, other strings with no space after the colon. Please advise what is the required format.
![spacing-json](https://user-images.githubusercontent.com/73398661/161105602-bd1a1b2b-1c0b-4a22-b2e1-945015cd989b.png)

**Comment by pmarkhennessy** [comment]
The "horizontal" spacing is not so important. @mihail-varbanov was referring to the vertical spacing and keeping the entries in the same order so it is easy to see line differences. "x":"x" is the same as "x" : "x" or "x": "x" etc
