### ISSUE TITLE
[BUG] Group - Input box for Search field of select member is missing

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1513]
**Describe the bug**
The input box for the search field in select members for groups is missing

**To Reproduce**
1. Install the Illinois app
2. Proceed the app with University Student as a Role and login with netid/pwd
3. Procced to Groups and Tap on Create new Event
4. Fill in the required fields and tap on Select Members in Select the group member field

Actual Result
In the select member screen, the search field is displayed without an input box for Search field

**Expected behavior**
Place  input box for Search field

**Screenshots**
![input box](https://user-images.githubusercontent.com/26231179/161106983-63774f15-efcf-4429-9a5f-bde89748442b.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.3.8]

**Additional context**

**Comment by TodorBachvarov** [comment]
Fixed in version 3.3.11

**Comment by Priyaravi8** [comment]
Fixed
