### ISSUE TITLE
[USABILITY] Change "log in" to "sign in" in several screens.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1514]
**Describe the usability issue**
Illinois app uses the phrase "sign in" rather than "log in".

To maintain consistency of terms, please change the wording in the following screens as marked in the images.

- Settings
- Wallet
- Privacy Center
- Quick Polls
- Illini Cash
- University Housing Meal Plan

The attached zip file contains screen captures with the correct spelling and capitalization written in.

[v.3.2 Login Audit.zip](https://github.com/rokwire/illinois-app/files/8394404/v.3.2.Login.Audit.zip)

 Version: 3.2.37

**Comment by dobromirdobrev** [comment]
Done in version 3.3.10.
