### ISSUE TITLE
[BUG] Groups - Reply to  existing post "To" dropdown not functioning as expected

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#1517]
**Describe the bug**
The "To:" dropdown on the Create post screen does not open dropdown menu upon clicking. 

**To Reproduce**
1. Go to 'Group.' (Priya and I were using "student test grp")
2. Click on an existing post 'post'
3. Attempt to use the "to:" dropdown "Selected members (1)"

**Expected behavior**
Upon clicking the "to:" dropdown "Selected members (1)", a dropdown menu appears with options. (Expectation is same behavior as this dropdown on the Create Post screen or edit post screen) 
![expected](https://user-images.githubusercontent.com/82892873/161331494-165706af-5603-4d86-90fa-99aeeb53029e.PNG)

**Actual Behavior**
![actual_Groups  Reply to  existing post to dropdown not functioning as expected](https://user-images.githubusercontent.com/82892873/161331500-b105fd78-d3b9-4cc7-9399-9269a638af69.PNG)

**Screenshots**
![actual_Groups  Reply to  existing post to dropdown not functioning as expected](https://user-images.githubusercontent.com/82892873/161331513-c611410a-187c-4e4a-906b-bdac82dbc5e8.PNG)

**Smartphone (please complete the following information):**
Pixel 4a- Android 12

**Additional context**
Please see video, note that there are two different behaviors for the same "To" Dropdown menu.  
1. it begins on the Edit Post screen showing how the To dropdown opens to allow selection of members
2. next user arrows back and into the same post and tris to use the dropdown to edit whom they are replying to and unable to do so. 
https://photos.google.com/photo/AF1QipMtSlgX61iOKmiDKwzUSKa4EpajKimjriIzRl7H

**Comment by TodorBachvarov** [comment]
@acovher2 This dropdown is designed for Create and Edit post only. Sending reply to selected members is not supported.

**Comment by acovher2** [comment]
@TodorBachvarov Then why is the word "Replies" part of this screen?
