### ISSUE TITLE
[BUG] Groups - Post feature "To" field dropdown does not list all members of group

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#1518]
**Describe the bug**
Groups - Post feature "To" field dropdown does not list all members of group. User must choose "Select members" to be taken to a full list of group members for selection. 

**To Reproduce**
1.Go to 'Group.' (Priya and I were using "student test grp")
2. Click on '.Create Post.'
3. Click on "To:" dropdown

**Expected behavior**
Post feature "To" field dropdown lists all members of group and members can be selected directly from dropdown menu. 

**Actual behavior**
Post feature "To" field dropdown does not list all members of group. User must choose "Select members" to be taken to a full list of group members for selection. 

**Screenshots**
https://photos.google.com/photo/AF1QipMGgbt-E9r-4WQYVDzhhF_UFvwdLL45tYeNg3Za
![expected](https://user-images.githubusercontent.com/82892873/161331922-ade9f830-63e8-48ce-9b32-fd75f977f17f.PNG)

**Smartphone (please complete the following information):**
Pixel 4a- Android 12

**Additional context**

**Comment by pmarkhennessy** [comment]
As designed, the drop down could have 7000 or more members
