### ISSUE TITLE
[BUG]Groups - User is not notified when user sends a reply or Delete a post

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1520]
**Describe the bug**
When the user Reply to the post and Delete a post, a notification is not sent to the users

**To Reproduce**
1. Install the Illinois app.
2. Complete onboarding with university students as role
3. Navigate to a group
4. Reply to the post in a group
5. Delete a post in a group

Actual Result
Notification is not sent to the user when a user replies to a post and Deletes a post.

**Expected behavior**
User should be notified when the user sends a reply or Delete a post

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.3.8]

**Comment by pmarkhennessy** [comment]
This is as designed, we do not send notifications to replies or deletes
