### ISSUE TITLE
[BUG]Choose your Privacy level screen - Invalid Personalization text for Wallet 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1523]
**Describe the bug**
The personalizations description for Wallet is invalid on Choose Your Privacy Level screen.

**To Reproduce**
1. Install the Illinois app
2. complete onboarding and proceed to Setting screen
3. Tap on Manage and Understanding your privacy 
4. Tap on Wallet under the Features and Data collection section

Actual Result
The text displayed for Wallet is invalid to the topic.

**Expected behavior**
The relevant text should display for Wallet Personalization.

**Screenshots**
![wallet text](https://user-images.githubusercontent.com/26231179/161609830-fc5b2123-5109-4edd-98e1-ccda33f9aa70.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.2.37]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 please check 3.3.16
