### ISSUE TITLE
[BUG] White screen appears when user change the privacy level setting

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1525]
**Describe the bug**
A white screen appears on the Home and Browse screen for the first time when the user changes the privacy level setting from low to high. 

**To Reproduce**

1. Steps to reproduce the behavior:
2. Install the Illinois app
3. Set the Privacy level to 2 while onboarding and complete the steps and navigate to the Privacy center
4. Tap on Manage and Understand your Privacy
5. Change the privacy level from 2 to 5 and Connect to net id
6. Tap on the Home menu and the Browse menu

**Actual Result**
White screen displays on Home screen and Browse screen.

**Note** - This issue appears only for the first time when the user changes the privacy level setting.

**Expected behavior**
A white screen should not appear when the users change their privacy settings

**Screenshots**

https://user-images.githubusercontent.com/26231179/161842978-e6edbbc9-cede-42b6-b12a-4f4dba50ab5f.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 3.2.372]

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,

I'm not able to reproduce it. What is the version of the app that you test with? 
Here is what I see with the latest version 3.3.12:

https://user-images.githubusercontent.com/5978121/162198623-ee86f97e-32fe-4fbf-9ffe-430a31c7024c.mp4


Could you please try with latest version. If you still reproduce it, could you please make a video from the beginning ?
Thanks

**Comment by pmarkhennessy** [comment]
@Priyaravi8 Please check in the latest 3.3.16
