### ISSUE TITLE
[USABILITY] 3 Broken External Links

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#1555]
1) **Link location:** BROWSE > Athletics > **Tickets**
**Issue:** getting a "please activate cookies" message from Paciolan link
**Solution:** ??—is this an issue on our end or Paciolan's?

 
2)  **Link location:** Browse > Wellness > Spiritual Wellness > Interactive Activities > **Open Prayer, Relaxation, and Meditation Space** 
**Issue:** Broken link, can't find new link
**Solution:** @joegrohens @dr-mel is there a new link or should it be removed?
If there is no response, please remove link.

3) **Link location:**   Browse > Wellness > Spiritual Wellness > Office of Inclusion & Intercultural Relations  > **Interfaith**  
**Issue:** Access denied link, can't find new link 
**Solution:**  @joegrohens @dr-mel is there a new link or should it be removed?
If there is no response, please remove link.

App version: 3.3.16
Device: Android

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

Problem 1 - we've hidden "Tickets" button because the link does not work. We could show it when we have working link.
Problem 2 - link removed
Problem 3 - link removed

This is done in version 3.3.17.
