### ISSUE TITLE
[USABILITY] Update tutorial video to use new audio track

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1574]
**Describe the usability issue**

Can you check to see if you have the right version of The Illinois App Overview video?

The version on Mallory's VIMEO has a younger voice actor doing the voice-over narration.
https://vimeo.com/685533005/988cdee00b

I believe that this version is an update to the version of the video in the app. Check with Mallory to be sure, but I think you should be using the video with the younger voice actor.

**Comment by pmarkhennessy** [comment]
@joegrohens Will check on this. Thanks for letting me know.

**Comment by dobromirdobrev** [comment]
The video file is updated with the provided one (e.g. https://vimeo.com/685533005/988cdee00b).
