### ISSUE TITLE
Express pick up -End time is cut off and Time display format is not consistent 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#16]
**Describe the bug**
For Express pick up time format should be consistent in the app 

**To Reproduce**
1. Install Illinois app
2. Complete the onboarding process and verify the user as a university student
3. Tap Dining on Home screen
4. A list of dining locations is displayed. Tap on FAR Dining hall at Florida. 
5. Tap on the dropdown arrow next to Serving dinner until 8:00 PM

**Actual Result**
Express Pick up time format **4:30-8p** is not consistent with other time formats on the screen. Also, pick up end time is cut off.

**Expected behavior**
The time format should be consistent like **4:30 PM- 8:00 PM**. Pick up end time should display without cut off.

**Screenshots**
![time dining](https://user-images.githubusercontent.com/26231179/92033060-ad4ded80-ed30-11ea-81b5-484313fac197.png)

![express pickup](https://user-images.githubusercontent.com/26231179/91498221-01665700-e885-11ea-8f1f-fedc74ba31e0.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.2.12]

**Comment by TodorBachvarov** [comment]
Fixed. Please try with new version

**Comment by Priyaravi8** [comment]
This issue is resolved
