### ISSUE TITLE
[FEATURE] Beginnings Booklet request from Student Affairs

### ISSUE THREAD

**Issue by ToddNelson** [rokwire/illinois-app#160]
**Is your feature request related to a problem? Please describe.**
Request from Lisa Jackson (Director of New Student Programs)

She would like the "Beginnings Booklet" to be viewable from inside the Illinois App.  Booklet attached.
[illinois-beginnings-2019.pdf](https://github.com/rokwire/illinois-app/files/5495650/illinois-beginnings-2019.pdf)

**Describe the solution you'd like**

New students and parents/families are given the Illinois Beginnings Booklet when they attend New Student Registration.  In the past, this booklet has been a print publication and ready for distribution at the end of May.  In an effort to be more sustainable and also continue encouraging use of the Illinois app, I would like to see if it is possible that this booklet be added to the app?  It is approximately 32 pages and contains pictures and content from various offices throughout campus.  I’ve attached a copy of the 2019 booklet to this email to give you a visual.

**Comment by isaac-galvan** [comment]
Here is the 2020 edition as well.
[Illinois-Beginnings-2020.pdf](https://github.com/rokwire/illinois-app/files/5624371/Illinois-Beginnings-2020.pdf)

**Comment by pmarkhennessy** [comment]
@isaac-galvan I discussed it with JP when this first appeared and I will discuss it again. 

I think it would be best if it is hosted somewhere, is there such a place already? Can you pass me the link please if so?
