### ISSUE TITLE
[FEATURE] Update text on Dining menu items

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#171]
Per University Housing Dining request, please change the text “Eatsmart Website”  to “View full list of ingredients”.
This text is found here:  Select "Dining", choose a dining location, choose a menu item, scroll down past nutrition facts.

**Comment by kpecknold** [comment]
@pmarkhennessy Mark, will this change be in the next release? JP agreed back in Dec that it would be.

**Comment by pmarkhennessy** [comment]
@mdryankov If you didn't do this yet, please do, I assigned it back in December.

@kpecknold Yes

**Comment by mdryankov** [comment]
Fixed in 2.3.30
