### ISSUE TITLE
[BUG] Quick Polls freeze

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#174]
**Describe the bug**
The app freezes when opening the Quick Polls feature 

**To Reproduce**
1. Create a quick poll
2. Go to browse > Quick Polls
3. App freezes

**Expected behavior**
App displays my polls. 

**Screenshots**

[video example](https://uofi.box.com/s/qg2qpmq45p7b6e5o9phkf41dx3t2xvy1)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 and pixel 3a
 - OS: iOS 14 and android 11
 - Version 2.3.18

**Additional context**

**Comment by pmarkhennessy** [comment]
@dobromirdobrev Can you take a look at why this is happening please...

**Comment by mdryankov** [comment]
Fixed in 2.3.31
