### ISSUE TITLE
[BUG] Call to action buttons in Groups are stuck to the top of the keyboard

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#177]
**Describe the bug**
Call to action buttons are shown "stuck" to the top of the keyboard. The button is not necessary when typing and is only taking up space.

**To Reproduce**
1. As an admin, go to a groups settings page
2. Click on a form field to type (like Website Link)
4. See "Update Settings" button stuck to the top of the keyboard

**Expected behavior**
Make this change globally, where all buttons on any page with an "X" should NOT be stuck to the top of the keyboard or the screen.  Ideally the button does stay stuck to the bottom of the screen when the keyboard is not open. If that is not possible then make the button never stuck to the bottom of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/24440324/103030204-e77e0d80-4520-11eb-897f-def60ca5d85e.png)

**Comment by knguyenjahiel** [comment]
Closed: No longer applicable to current functionality and design. Pixo no longer working with the Ill App
