### ISSUE TITLE
[FEATURE] New content for Wellness section

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1794]
Mel Fenner has created three new pages for the Wellness content.

Health & Wellness > Mental & Emotional Health > HealthiestYou Telehealth
Health & Wellness > Nutrition > Food Resources
Health & Wellness > Mental & Emotional Health > Counseling Center

He requests that these be linked to three wide buttons in the Wellness section. You can use the following names for the wide buttons:

Telehealth
Food Resources
Counseling Center

Place these buttons at end of the current wide buttons.

Also, the pages will appear in the alphabetical listing below the wide buttons as well.

We want these three pages to appear in the Wellness section only, and not in the Campus Guide Section. I think the Content Manager may need to be set up to restrict where the page appears, because currently everything appears in Campus Guide.

**Comment by vburgett** [comment]
@joegrohens I will provide JP with a final list. Let's work together since JP asked that we don't give him the Wellness Resource content piece meal. Thank you!

**Comment by vburgett** [comment]
Here is the overarching content for Wellness > Wellness Resources page. 

https://docs.google.com/document/d/1jsra-7VvLEJYcp2I4aUgQOwl5jCKCAmdLrHsz35KVZg?authuser=vburgett%40illinois.edu&usp=drive_fs
