### ISSUE TITLE
[USABILITY] Sign In/Sign Out drop down title in Settings screen could be confusing

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#1797]
## Describe the usability issue
Sign In/Sign Out in the Settings screen could create confusion as there are also the Sign/In Sign Out options for authenticating. 

## To Reproduce

1. Go to Browse -> My Settings
2. See the Sign In/Sign Out buttons for setting preferences next to the Sign In or Sign Out option for authentication.

## Expected behavior
I understand that here the first Sign In/Sign Out refers to signing in and signing out of preferences/different items, but I think these two Sign In/Sign Out options could be confusing at the first look. I think "Choose your preferences ..." or "Preferences ..." or some other term can make it clear that this is about preferences and not about signing in or signing out of the app. Thanks.

## Screenshots
![image](https://user-images.githubusercontent.com/4306604/174881098-e46a53cb-b318-4ad4-9416-2ce9ac3b38ca.png)
![image](https://user-images.githubusercontent.com/4306604/174881182-4e89fbca-9025-4fe4-892c-5828784c4612.png)

## Smartphone (please complete the following information):

Device: Pixel 3
OS: Android
Version: 4.0.33

**Comment by vburgett** [comment]
Hi @sandeep-ps I am not sure what you're referring to with the below. Can you provide a screenshot? A

"See the Sign In/Sign Out buttons for setting preferences next to the Sign In or Sign Out option for authentication."

**Comment by vburgett** [comment]
Thanks for the screenshot and follow up, @sandeep-ps. Perhaps you thought that since this page was previously labeled "Setting Sections"?

**Comment by sandeep-ps** [comment]
Yes, that could have been why. I will go ahead and close this issue. Thanks.
