### ISSUE TITLE
[BUG] If you "request to join a group" and the group has no membership questions a blank 'request to join' screen shows.

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#184]
**Describe the bug**

**To Reproduce**
1. Select a Group card 
2. Click on 'Request to join'
3. If it's a group that does not have any request questions, you see a random page (see screenshot) . 

**Expected behavior**
If a Group has not input a question, do not show any screen after a user selects 'Request to join' a group.

![Screenshot_20201222-141414](https://user-images.githubusercontent.com/24440324/103031506-94598a00-4523-11eb-8f89-be842852d55b.png)

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design.

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
