### ISSUE TITLE
[BUG] Unable to add website to Group

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#186]
**Describe the bug**
As an admin of a group, I am not able to add a website url successfully. 

**To Reproduce**
1. Go to a group you're an admin of 
2. Click on 'Group settings'
3. Scroll down to 'Website Link' form field
4. Add a URL
5. Click on ' Confirm URL'
6. Receive error 
![Screenshot_20201222-135325](https://user-images.githubusercontent.com/24440324/103034788-4ea0bf80-452b-11eb-81e0-9656cd341482.png)
 

**Expected behavior**
I should be able to add a website URL to a group.

**Comment by knguyenjahiel** [comment]
Closed: item submitted in 12/2020.
