### ISSUE TITLE
[BUG] I am able to edit a group event I did not create. 

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#187]
**Describe the bug**
As a member of a group, I am allowed to "edit" an event that I did not create. 

**To Reproduce**
1. Go to 'An event on a group you do not belong to'
2. Click on 'the circle with three dots'
3. Click on 'Edit event'
4. You are now able to edit the event

**Expected behavior**
Only the person who originally created the event or admins of the group can edit an event.

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
