### ISSUE TITLE
[BUG] Can not create an event for a group I am creator/admin of

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#188]
**Describe the bug**
I created a group, and am not allowed to submit a new event for my group. 

**To Reproduce**
1. Go to 'a group you're admin of.
2. Click on 'Create an Event'
3. Input event information
4. Click 'Create event'
5. See error above keyboard 'Unable to create event'
![Screenshot_20201223-143519](https://user-images.githubusercontent.com/24440324/103035114-2d8c9e80-452c-11eb-9442-e51a79fa7126.png)

**Expected behavior**
If all required fields are filled, I should be able to create an event for a group I created.

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
