### ISSUE TITLE
[BUG] Event search feature seems to be missing

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#1885]
**Describe the bug**
The event search feature seems to be missing from the latest DEV build of the Illinois app.

**To Reproduce**
1. Go to App Sections -> Events -> Suggested Events
2. See that the search icon is missing

**Expected behavior**
If this was not a design decision, the search option should be visible to the user. Thanks.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Version: 4.0.44

**Additional context**

**Comment by sandeep-ps** [comment]
It looks like this was related to privacy levels. At privacy level 5, the search icon is visible, but there does not seem to be an entry related to this in the "Choose Your Privacy Level" screen. Please let me if there is one. I'm not sure if this would be considered a high priority. I will leave this issue open for future discussions. Thanks.

**Comment by mihail-varbanov** [comment]
Fixed in version 4.0.53.

**Comment by sandeep-ps** [comment]
Thanks, Misho!
