### ISSUE TITLE
[BUG] Broken link in Wellness section (v4.0.44)

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1888]
Vanessa -- I wasn't sure if I had the right URL. Once it is correct, you can assign the issue to Mark. - Joe

**Problem:**

The button _Wellness > Wellness Resources > Mental Health & Counseling_ has a broken external link.

Please point the button to this URL: https://wellness.web.illinois.edu/mental-health-resources/

**Comment by vburgett** [comment]
Two buttons under Wellness > Wellness Resources need fixing:

Mental Health & Counseling needs to go to https://wellness.web.illinois.edu/mental-health-resources

Sexual Misconduct needs to go to https://wellness.web.illinois.edu/sexual-misconduct

@pmarkhennessy @dr-mel @joegrohens

**Comment by mihail-varbanov** [comment]
Fulfilled in 4.0.50

**Comment by vburgett** [comment]
@joegrohens this ticket looks fulfilled to me. You too? Please close if yes.
