### ISSUE TITLE
[BUG] Space needed between [3] and word "Questions"

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#189]
**Describe the bug**
Add a space between the number and word "Questions" and lowercase the 'Q' in question. 
ex: 2 questions
ex. 1 question

![Screenshot_20201223-143716](https://user-images.githubusercontent.com/24440324/103035239-865c3700-452c-11eb-8718-580d40005b2e.png)

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
