### ISSUE TITLE
[BUG] "Reminder" is spelled incorrectly in the form "Add an item"

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1901]
**Describe the bug**
"Reminder" is spelled incorrectly in the form "Add an item"

**To Reproduce**
1. Install the Illinois app
2. Navigate to Wellness and tap on "To Do"
3. Tap on Add Item and tap on "Optional Fields" in the form

**Actual Result**
The word "Reminder" is spelled as "Reminmder"

**Expected behavior**
Correct the incorrect spelling of the word "Reminder"

**Screenshots**
![Reminder](https://user-images.githubusercontent.com/26231179/177601767-3a4f86a0-93f6-4e4f-81df-428e5ec220ad.png)

*Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.0.44]

**Comment by mihail-varbanov** [comment]
This had been fixed in 4.0.43. Please check it again on the latest build.

**Comment by vburgett** [comment]
Spelling error has been fixed.
