### ISSUE TITLE
[BUG] Spelling error for the word "Saved"

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1902]
**Describe the bug**
"Saved" is spelled incorrectly once the "Add an item" is submitted.

**To Reproduce**
**Steps to reproduce the behavior:**

Install the Illinois app

1. Navigate to Wellness and tap on "To Do"
2. Tap on Add Item and tap on "Optional Fields" in the form
3. Fill in all the fields and tap submit button. 
4. "To-Do"item Saved successfully message is displayed to the user

**Actual Result**
The word "Saved" is spelled incorrectly as "Sved".

**Expected Result**
Incorrect spelling of "Sved" should be fixed.

**Screenshots**
![Save](https://user-images.githubusercontent.com/26231179/177602872-e77ec798-12a0-4c38-939d-e27dcbae8773.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.0.44]

**Comment by mihail-varbanov** [comment]
Unable to recreate this in 4.0.49. Please check this again.

**Comment by vburgett** [comment]
The typo has been corrected.
