### ISSUE TITLE
[BUG] Star icon (Favorite) is missing for My Illini

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1903]
**Describe the bug**
Star (Favorite) is missing for My Illini.

**To Reproduce**
1. Install Illinois app
2. Tap on Browse meu
3. Tap on Academics under App Sections

**Actual Result**
The Star icon to Favorite is missing for "My Illini"

**Expected behavior**
Star icon is needed for the user to favorite My Illini

**Screenshots**
![Fav Star](https://user-images.githubusercontent.com/26231179/177636997-5fd96053-4ee2-4558-a615-bef0c345bcb4.png)

**Smartphone (please complete the following information):**
 - Version [e.g. 4.0.44]

**Additional context**

**Comment by mihail-varbanov** [comment]
Please define what should appear in Favorites panel in response of selecting this star. CC @pmarkhennessy.

**Comment by vburgett** [comment]
The Browse screen is a list of features that live **within** the app. Please remove "My Illini" from the Browse screen. (Keep "myIllini" as an option in the Academics dropdown menu.)  

(If this solution is not agreed on by all, I would argue that this is a low priority discussion right now.)

**Comment by mihail-varbanov** [comment]
Done in version 4.0.51.
