### ISSUE TITLE
[BUG] I see both "Delete" and "Remove" actions for a group event

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#191]
**Remove vs. delete:**
An event can both be deleted and removed depending on the type of event it is.
With the addition of groups feature we have two types of events:

- Created group specific events (only appear on that Groups detail page, and can not be discovered elsewhere in the app)

- Added campus wide events (existing events already in the app)

**How an admin interacts with events:**

- A group admin can remove an added campus wide event.

- A group admin can delete a group specific event that they—or another admin—have created for their group.

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
