### ISSUE TITLE
[BUG] "Updated about 2 hours ago" text on group cards is not changing or reacting to updates

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#192]
**To Reproduce**
1. Go to 'Browse'
2. Go to 'Groups'
2. Click on 'My groups'

**Expected behavior**
The text should update based on activity for that group. Activity for now includes, adding an event or commenting on an event. 

Some examples of variations to the text: 

-  for anything updated in under a minute: **Updated a moment ago**
-  for anything updated in between 1-60 minute: **Updated X minutes ago**
-  for anything updated over an hour: **Updated X hours ago**
- for anything updated in over 24 hours: **Updated X days ago*

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
