### ISSUE TITLE
[USABILITY] Can we tone down the "Whoops!" error msg? 

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1926]
When you follow a link in the app that has no contents, the app displays this message:

> Whoops! Nothing to see here.

![whoops](https://user-images.githubusercontent.com/66988329/178033727-9efd29a0-6f75-45d9-9831-b04efdf9ce89.png)
 
**Usability Problem:**

This message suggests that something went wrong. ("Whoops!" is  comparable to "Oh no! I accidentally [insert woeful mishap]!") 

But in cases where a user simply hasn't created a group, or hasn't saved a favorite, there is no a malfunction in the app, nor any mistake on the user's part. 
 
I think this message was written in the spirit of humor. But the facetious wording is not really funny when you are a user trying to figure out how the app works and getting notifications of an "error" when there is no error. The user may think the app isn't working, or that they did something wrong. ("Am I required to create a group?") And the exclamation mark indicates alarm.

The writer of this message and others may think it's cute and that it makes the app more fun. Which is why I have gone to the trouble to explain why I think it's a usability problem. Sorry to belabor the point.

===
**What would be better:**

Alternatives that are free of misleading connotations are:

- Nothing to see here. You have not created any groups yet.
- No items available. You have not created any groups yet.

Source: V 4.0.44 and 4.0.46

**Comment by pmarkhennessy** [comment]
@joegrohens try this in 4.0.47
