### ISSUE TITLE
[USABILITY] MTD pass should use "the operator" not "the bus driver"

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1929]
The Champaign-Urbana Mass Transit District asks that we use the term "operator" rather than "bus driver".

![bus driver](https://user-images.githubusercontent.com/66988329/178054859-4be82d83-0808-41cc-b32d-4579f282931e.png)

(this is not high priority, but should be scheduled for update)

**Comment by mihail-varbanov** [comment]
Fixed in version 4.0.47

**Comment by joegrohens** [comment]
confirmed fixed in 4.x
