### ISSUE TITLE
[BUG] Height of tabs is difficult to tap at current height. 

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#193]
Increase height of second bar. 

Do not make header stick to the top of the page. 

Update Explore Events/Dining header to match (currently they are styled differently and the tabs (including underline) should be consistent. 

![image](https://user-images.githubusercontent.com/24440324/103035875-d982b980-452d-11eb-8059-6fb5edb4499e.png)

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
