### ISSUE TITLE
[USABILITY] Alternate Login Text Updates

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#1931]
**Describe the bug**
After entering my verification code to sign in via a phone number, the screen went black and stayed black as I waited. I closed the Illinois app and reopened it—the app then displayed My Settings > Sign In/Sign Out and showed that I WAS indeed logged in with my phone number. (A second time trying the app displayed the Favorites screen instead of the Sign In/Sign Out screen.)

**To Reproduce**
1. Go to My Settings > Sign In/Sign Out
2. Tap "Continue"
3. Enter phone number and tap "Proceed"
4. Enter verification code
5. Screen goes black and stays black
6. Close app
7. Open app
8. Under My Settings, I am not logged in

**Expected behavior**
There should not be a black screen after entering your phone number verification number. Instead, the app should display the Settings > Sign In/Sign Out screen showing that the user is signed in with their phone number. 

The "phone number" login option only supports "mobile phone numbers." Please make attached text updates to make this clearer to the user.
 
**Additional context**
Could the issue be that I am signing in with a phone number that is NOT via the Android device I'm using the app on? I am using my iPhone 12 Pro iOS 15.5 phone number to log in. 

**Smartphone:**
Using the Illinois app on
 - Device: Android version 12, Pixel 6
 - Version: 4.0.46

**Screenshots**
[2022-07-08-ILAppPhoneEmailLogin-VB.pdf](https://github.com/rokwire/illinois-app/files/9074746/2022-07-08-ILAppPhoneEmailLogin-VB.pdf)

**Comment by mihail-varbanov** [comment]
Fixed in 4.0.49

**Comment by vburgett** [comment]
Works in 4.0.49—thank you!

**Comment by vburgett** [comment]
The requested text changes still need to be completed for 4.0 or the next release.

**Comment by mihail-varbanov** [comment]
The requested text updates are available in 4.0.50. The next time you would better create separate issues.
