### ISSUE TITLE
[USABILITY] Wording in Settings > App Feedback section

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1933]
I am submitting changes to two paragraphs of text under Settings > App Feedback

![smart healthy 1](https://user-images.githubusercontent.com/66988329/178078644-d003d4b0-20a3-42bd-8098-6511740fbc79.png)

**Change 1**

_Current text:_
> Enjoying the app? Missing something? The University of Illinois Smart, Healthy Communities Initiative needs your ideas and input. Thank you!

_Replace the current text with the following:_

Enjoying the app? Missing something? The Illinois app team needs your ideas and input. Thank you!

............ 
**Change 2**

![smart healthy 2](https://user-images.githubusercontent.com/66988329/178080330-04e1cbd0-3ccd-411e-bf9a-423cf2e9c380.png)

_Current text:_
>The Illinois app is the official campus app for the University of Illinois Urbana-Champaign. The app is powered by the Rokwire opensource software platform. The Rowkire project is an effort of the Smart, Healthy Communities Initiative, which is funded by the Office of the Provost at the University of Illinois.

_Replace the current text with the following:_
The Illinois app is the official campus app of the University of Illinois Urbana-Champaign. The app is built on the Rokwire [link to: rokwire.org] open source software platform. The Rokwire project and the Illinois app are efforts of the Smart, Healthy Communities Initiative [link to: smart.illinois.edu] in the office of the Provost at the University of Illinois.

_Please add:_

"Copyright © 2022 University of Illinois Board of Trustees" 

below the version number at the bottom of this screen.

**Comment by RokBill** [comment]
I'm good with Joe's proposed changes to the first paragraph and suggest we adopt them.

For the second paragraph:
- yes, let's link to smart.illinois.edu.
- Let's not mention the funding source and go ahead with Joe's language in the second bullet just above.
- I don't think there will be much demand for an "About the Illinois app" page and thus consider it a low priority at this moment.
- Yes, let's add the copyright statement that Joe mentions above.

Good work.

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,
After the  last comment it is not clear to me what should be the content of the second paragraph. Could you please type the exact text?
Thanks.

**Comment by joegrohens** [comment]
Hi @dobromirdobrev 

Thank you for asking for clarification. I will give the exact text for both paragraphs.

Please make the following changes:

**Change 1**

Current text:

> Enjoying the app? Missing something? The University of Illinois Smart, Healthy Communities Initiative needs your ideas and input. Thank you!

_Replace the text above with the following:_

Enjoying the app? Missing something? The Illinois app team needs your ideas and input. Thank you!

............
**Change 2**

_Current text:_

> The Illinois app is the official campus app for the University of Illinois Urbana-Champaign. The app is powered by the Rokwire opensource software platform. The Rowkire project is an effort of the Smart, Healthy Communities Initiative, which is funded by the Office of the Provost at the University of Illinois.

_Replace the text above with the following:_

The Illinois app is the official campus app of the University of Illinois Urbana-Champaign. The app is built on the [Rokwire](https://rokwire.org/) open source software platform. The Rokwire project and the Illinois app are efforts of the [Smart, Healthy Communities Initiative](https://smart.illinois.edu/) in the office of the Provost at the University of Illinois.

**Change 3**

_Please add a copyright statement below the version number:_

Illinois App Version: 4.0.55

Copyright © 2022 University of Illinois Board of Trustees

**Comment by dobromirdobrev** [comment]
Done in version 4.1.7
