### ISSUE TITLE
[BUG] Groups settings page

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#194]
**Describe the bug**
Styling of items and icons on the Groups settings page
![image](https://user-images.githubusercontent.com/24440324/103035974-2e263480-452e-11eb-8fbd-813db20c9db7.png)

**Expected behavior**
Using wrong icons next to "Discoverability" 

"tags" is not styled correctly. 

Sizing of section headers is too small. 

See Figma: https://www.figma.com/file/noq39ql9qZuHCFlm4eP4Ze/Groups?node-id=356%3A1514

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
