### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RokBill** [rokwire/illinois-app#1943]
In Maps, can we have a simple campus map without any Events shown. Can we add to the dropdown menu a title called Campus Map that links Map.Illinois.edu (Or point to the Campus Guide > Maps > Maps of campus.

**Comment by vburgett** [comment]
The original UI had a default Map app screen called "Campus View" that was set to the boundaries of campus. JP mentioned that was not possible with 4.0 but perhaps the next release can have it if we get the course classes and building data integrated in time.

**Comment by pmarkhennessy** [comment]
@RokBill will consider after we fix major issues
