### ISSUE TITLE
[BUG] Search and Done button is not functioning.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1945]
**Describe the bug**
The search and Done buttons are not functioning in POLL when the user selects the member for the poll.

**To Reproduce**
1. Install the app
2. Navigate to poll and create Poll
3. Fill in the required field and tap on the TO field and choose "Select Members" in the drop-down field.
4. Enter Name or UIN or Email in the search field and hit Search

**Actual Result**
The search is not functioning to display the search result. 
**NOTE** - "DONE" button at the bottom is also not working. So the user is stuck on this screen not able to go back or proceed further.

**Expected behavior**
1. Search has to display results as per the user search. 
2. Done button has to close out the current screen for the user to proceed further

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 4.0.46]

**Comment by pmarkhennessy** [comment]
@mihail-varbanov We should only be showing members from within Group Polls. When we get to Polls from Quick Polls there should be no member selections.

**Comment by TodorBachvarov** [comment]
Members selection is visible only for group polls. Fixed in version 4.0.51.

**Comment by TodorBachvarov** [comment]
@Priyaravi8 please retest

**Comment by Priyaravi8** [comment]
This issue is resolved in version 4.055
