### ISSUE TITLE
[BUG] FIX or ADD links from Wellness Resources menu to Campus Guide pages

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1946]
I updated this issue for Illinois App build 4.049 (some previous broken links were fixed)

**FIX these broken links:**

_Wellness > Wellness Resources > Mental Health & Counseling_ (page not found)
It should point to https://wellness.web.illinois.edu/mental-health-resources/

_Wellness > Wellness Resources > Sexual Misconduct_ (page not found)
It should point to https://wellness.web.illinois.edu/sexual-misconduct/

**ADD the following links to Campus Guide pages**
(Replaces the direct external link that we currently have)

- I want to make an appointment : point to Campus Guide > Health & Wellness > General Support > I want to make an appointment

- I want to help a friend, student, or co-worker : point to Campus Guide > Health & Wellness > General Support > I want to help a friend, student, or co-worker

- I'm not sure where to start : point to Campus Guide > Health & Wellness > General Support > I'm not sure where to start
 
![new wellness links at top](https://user-images.githubusercontent.com/66988329/178326873-e0b02cc5-f1b9-4875-b414-4f3bb209580a.png)

**Comment by vburgett** [comment]
That link is correct.

**Comment by vburgett** [comment]
@pmarkhennessy Please remove the external window icon in the Wellness dropdown menu for "I'm Struggling" now that it points to content within the app. 

(@joegrohens please indicate in Git when requesting link updates that open a website within the app or outside of the app that an external website icon is needed by the link text—or in this case, that the icon needs to be removed. Thank you!)
