### ISSUE TITLE
[BUG] Hide State Farm Wayfinding in 4.0

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#1947]
I am pretty sure that we decided to hide State Farm wayfinding in 4.0, until Nick Vance had a chance to find out how DIA is using it.

It still appears in **Browse > State Farm Center > Parking**

June7 Rokwire Weekly meeting minutes:
https://docs.google.com/document/d/1cCpHRx7wleiy57BiVnyvKWiocglNmFmNzRzcLRXOndY/edit

Double check with JP to see if he has changed his mind. But I think the feature is supposed to be hidden.

**Comment by vburgett** [comment]
Parking should not be hidden and is currently presenting correctly in 4.0.53.
