### ISSUE TITLE
[BUG] 4.0.49  Text changes for Dining widgets

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1948]
Please use the following text for the Dining widgets:
Residence Hall Dining widget: “Students, faculty, staff, and guests are welcome to eat at any residence hall dining location.” (Repeat text in Browse under Dining)
Residence Hall Dining Open Now widget: “Quick access to any locations that are currently open.”

**Comment by dobromirdobrev** [comment]
Done in version 4.1.4

**Comment by kpecknold** [comment]
Done
