### ISSUE TITLE
[BUG] Group Call to action buttons are not styled correctly or consistently

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#195]
**Describe the bug**
The buttons at the bottom of the screen should all be the same width and height, not changing size depending on the content. 

**Examples seen**
On the Add Membership Questions screen 
![image](https://user-images.githubusercontent.com/24440324/103036087-83fadc80-452e-11eb-8e5a-fe53b73a6f57.png)

On the Request to Join screen
![image](https://user-images.githubusercontent.com/24440324/103036122-98d77000-452e-11eb-8c12-2752efa69f79.png)

**Expected Behavior** 
The buttons at the bottom of the screen should all be the same width and height, not changing size depending on the content. 

See example for styling: https://www.figma.com/file/noq39ql9qZuHCFlm4eP4Ze/Groups?node-id=356%3A1514

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
