### ISSUE TITLE
[BUG] 4.0.49  Illini Cash and Meal Plan Balances not displaying

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1950]
My Illini Cash and meal plan balances shows as "0". This is not correct.

@clint156

**Comment by pmarkhennessy** [comment]
I believe this is now fixed 4.0.51, but may need Clint's Gateway BB deployed in Prod

**Comment by clint156** [comment]
Confirmed earlier today. I can add Illinois cash and the balances display correctly. I'll work with Tim and Mike tomorrow to get the bb deployed on test and production.

The only thing we're still waiting on is a production api key for the laundry service requests

Clint Stearns
Systems Development Architect
Student Affairs Technology
________________________________

**Comment by kpecknold** [comment]
Confirmed fixed.
