### ISSUE TITLE
[BUG] 4.0.49 Need a Laundry app section to be able to create "My Laundry"

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1951]
It is impossible for a new student to find the laundry feature in order to create a "My Laundry" entry that will function. 

I believe Vanessa has suggested to create a Laundry app section and somehow the "View All" option should incorporated as consistent with other sections.

@vburgett

**Comment by vburgett** [comment]
Yes, please see issue #1916 for request details.
