### ISSUE TITLE
[BUG] 4.0.49  Groups - prompt to add an event to multiple groups is broken

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1952]
**Describe the bug**
After creating an event inside a group, a popup appears that says "Select". It used to show the list of groups for which you are an admin, but there is no list now. 

**To Reproduce**
1. Make sure you are an admin for more than 1 group
2. Go into a group and create an event
3. You should see the attached screen shot

**Expected behavior**
A list of all groups for which you are an admin should appear so that you can choose which ones to copy the event to.

**Screenshots**
![image](https://user-images.githubusercontent.com/69397705/178355781-97d76afb-f9d6-454c-bd4e-d48c8de9221d.png)

**Comment by mihail-varbanov** [comment]
Fixed in version 4.0.53.

**Comment by kpecknold** [comment]
Confirmed fixed.
