### ISSUE TITLE
[BUG] Groups - editing group settings kicks out all members

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#1955]
**Describe the bug**
I have gotten "kicked out" of a couple of groups I've created. I believe it's when I modify a group setting. In particular, I was adding a group website URL.

Kathryn's Dev Group
Kathryn 4.1 Group

are 2 groups that I used to be the admin of and now I believe they have no admin or members.

**Comment by mdryankov** [comment]
@kpecknold this is fixed on Dev - backend side. Please retest and give a feedback. Thanks.
