### ISSUE TITLE
[BUG] Create a group title error is not legible with styling

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#196]
**Describe the bug**
When creating a new Group, and inputing a title, if you add a name that's already in use, an error appears under the form field. 

**Expected behavior**
Styling of this box should match design: https://www.figma.com/file/noq39ql9qZuHCFlm4eP4Ze/Groups?node-id=358%3A603

Currently background color makes it not possible to read. 
![image](https://user-images.githubusercontent.com/24440324/103036247-eeac1800-452e-11eb-8734-1d3ee28e3e96.png)

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
