### ISSUE TITLE
[UX EDIT] To-Do List Tool | Update "Reminders" nav bar tab to read "Weekly"

### ISSUE THREAD

**Issue by jake-fava** [rokwire/illinois-app#1967]
![image](https://user-images.githubusercontent.com/109174739/178573289-efb936fd-c236-4401-b056-6e55ce1237cd.png)

**Comment by vburgett** [comment]
@pmarkhennessy IF this text edit is as simple as it appears, can we get this edit into the 4.0 release? I believe this update will solve a large portion of the current user frustrations with the to-do list. Thanks for considering.

**Comment by dobromirdobrev** [comment]
Done in version 4.1.3
