### ISSUE TITLE
[FEATURE] To-Do List Tool, Weekly View | Implement drag-and-drop of to-do items

### ISSUE THREAD

**Issue by jake-fava** [rokwire/illinois-app#1970]
When an unassigned item is pressed and held -> drag-and-drop to assign item to a day; update “DATE(S)” with selected day

![image](https://user-images.githubusercontent.com/109174739/178580238-cdc1eeee-2806-4c1f-9586-7e02c1af6c00.png)

When a dot is pressed and held -> drag-and-drop to assign item to a different day, update “DATE(s)” to selected day

![image](https://user-images.githubusercontent.com/109174739/178580388-1f3a848e-e328-4fc9-a274-fcbbce44e4f8.png)

**Comment by vburgett** [comment]
@jake-fava let's hold off on this intended functionality in light of @acovher2's recent Git post about dragging and dropping not being accessible without a clear alternative offered to the user. Can you go ahead and close the comment for now?

**Comment by jake-fava** [comment]
Closing for now until an accessible drag-and-drop alternative is included

**Comment by acovher2** [comment]
@jake-fava and @vburgett Thank you both for considering accessibility. When the time comes to discuss solutions, here is a link with examples of how to ensure a single pointer solution is included. https://w3c.github.io/wcag/techniques/general/G219
