### ISSUE TITLE
[ACCESSIBILITY] Color contrast for name tooltip and status message not meeting contrast ratio

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#1973]
**Describe the accessibility issue**
The orange used on tooltip and linked text in status message, orange on navy is not meeting contrast standards. 
[WCAG 1.4.3 Contrast (minimum) (AA)](https://www.w3.org/TR/WCAG21/#contrast-minimum)

**To Reproduce
Steps to reproduce the behavior:**

1. Launch app
2. Upon logging in with NETID first time there is a welcome message with User's Name and a tooltip
3. Click tooltip and status message appears with more orange foreground text on navy background. 

Expected behavior
This color contrast needs to meet 4:5:1 ratio for regular sized text. 

Screenshots
![Screenshot_20220712-132528](https://user-images.githubusercontent.com/82892873/178585812-5dd4ef2c-e349-4beb-a0e2-89e91de729db.png)

![IMG_0048](https://user-images.githubusercontent.com/82892873/178585943-d2121261-7eea-485b-aafb-8bdafa8d8595.PNG)

Smartphone (please complete the following information):
iPhone XR- iOS 14.6,

Additional context

**Comment by vburgett** [comment]
I would make this link white with the existing underline still in place.

**Comment by acovher2** [comment]
@pmarkhennessy Vanessa's proposed solution meets CCR ratio. Can we please implement that? 
Thank you,
Amanda

**Comment by mihail-varbanov** [comment]
Fixed in 4.0.52.

**Comment by vburgett** [comment]
This is now fixed. @acovher2 can you close this ticket?
