### ISSUE TITLE
[USABILITY] Add "not logged in with NetID" for "My Groups" tab. 

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#198]
**Describe the usability issue**
Indicate that logging in with your NetID will allow you to join groups. 
![image](https://user-images.githubusercontent.com/24440324/103036442-6417e880-452f-11eb-83e4-34183c54bfb7.png)

**Change text to:**
"Only users with a University of Illinois NetID can create and join groups. 
Add button: "Login with NetID"  (that links to NetID login screen)

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
