### ISSUE TITLE
[BUG] My Calendar Settings wrong checkmark selection logic 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#1980]
Under My Settings > My Calendar Settings, a user can NOT select "prompt when saving events to calendar" when "Add saved events to calendar" IS checked.

**To Reproduce**
1. Go to My Settings > My Calendar Settings when logged in via netid
2. Check "Add saved events to calendar"
3. Try to check "prompt when saving events to calendar" and see that you can not
4. Uncheck "add saved events to calendar"
5. Check the "prompt when saving events to calendar" and see that you CAN select it

**Expected behavior**
A user should only be able to check "Prompt when saving events to calendar" when "add saved events to calendar" IS checked.
If "Add saved events to calendar" is NOT checked, a user should NOT be able to check "prompt when saving events to calendar"

**Smartphone (please complete the following information):**
 - Device: Android
 - Version [4.0.49]
 
![Screenshot_20220712-155513](https://user-images.githubusercontent.com/1044905/178597105-0dc2ac04-1885-42eb-9586-a456f60ac655.png)

**Comment by mihail-varbanov** [comment]
Fixed in 4.0.52

**Comment by vburgett** [comment]
Fixed. Thank you!
