### ISSUE TITLE
[BUG] Failed to edit the group reply

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1983]
**Describe the bug**
The user cannot edit the group reply. Failed to edit error message is displayed.

**To Reproduce**
1. Install the Illinois app
2. Log in as a university student and navigate to a group
3. Create a group and add events and posts to the group.
4. Reply to the post.
5. Edit the reply.

**Actual Result**
Failed to edit reply message is displayed to the user

**Expected behavior**
The user is should be able to edit the reply without a failure notice.

**Screenshots**
![edit grp](https://user-images.githubusercontent.com/26231179/178600495-deba6bc5-8108-42d0-a871-c9c151045b08.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 4.0.49]

**Additional context**

**Comment by mihail-varbanov** [comment]
@Priyaravi8, I was unable to recreate this on 4.0.51 against dev environment.

**Comment by Priyaravi8** [comment]
Prod - https://rokwire-ios-beta.s3.us-east-2.amazonaws.com/Installs/Illinois-4.0.51-prod.apk

**Comment by Priyaravi8** [comment]
This issue is fixed in version 4.0.53-prod.apk
