### ISSUE TITLE
[BUG] View Polls displays Error message

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1995]
**Describe the bug**
404 not found Error message is displayed for View Polls

**To Reproduce**
1. Install the Illinois app
2. Login as Student user and navigate to Browse Menu
3. Tap on "View Polls"

**Actual Result**
Quick polls screen is displayed with Server Response Error:404 Not Found

**Expected behavior**
Polls should display without error message

**Screenshots**

![poll error](https://user-images.githubusercontent.com/26231179/178823280-7b7a1409-4969-43b5-91f7-fd5e66889b5b.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 4.0.51]

**Additional context**

**Comment by mihail-varbanov** [comment]
@Priyaravi8, I was unable to recreate this on 4.0.51 against dev environment. Which environment did you use. Production could be not properly configured yet.

**Comment by Priyaravi8** [comment]
@mihail-varbanov - Prod - https://rokwire-ios-beta.s3.us-east-2.amazonaws.com/Installs/Illinois-4.0.51-prod.apk

**Comment by Priyaravi8** [comment]
This issue is resolved in version 4.055
