### ISSUE TITLE
[BUG] Courses not loaded for Academics

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1996]
**Describe the bug**
"Failed to load courses. Please try again later." is displayed for Academics

**To Reproduce**
1. Install the Illinois app
2. Login with the University student role.
3. Navigate to Academics and tap on My courses in the drop-down menu

**Actual Result**
The message "Failed to load course. Please try again later." is displayed to the user.

**Expected behavior**
The app should load the course without an error message.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 4.0.51]

**Comment by mihail-varbanov** [comment]
@Priyaravi8, I was unable to recreate this on 4.0.51 against dev environment. Which environment did you use. Production could be not properly configured yet.

**Comment by Priyaravi8** [comment]
This issue is fixed in version 4.0.53-prod.apk
