### ISSUE TITLE
[BUG] Failed to create Wellness ring

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1997]
**Describe the bug**
The users not able to create a wellness ring

**To Reproduce**
1. Install the Illinois app
2. Login as a University Student
3. Navigate to Wellness  and tap in Create New Ring
4. Select any ring for eg choose Hobby Ring
5. fill in the required field in Create Wellness Ring screen and tap on Create button

**Actual Result**
Failed to create a Wellness Ring message displayed to the user

**Expected behavior**
The user should be able to create the Ring without any issues

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Andoid]
 - Version [e.g. 4.0.51]

**Comment by mihail-varbanov** [comment]
@Priyaravi8, I was unable to recreate this on 4.0.51 against dev environment. Which environment did you use. Production could be not properly configured yet.

**Comment by Priyaravi8** [comment]
@mihail-varbanov - Prod Env

**Comment by Priyaravi8** [comment]
This issue is fixed in version 4.0.53-prod.apk
