### ISSUE TITLE
[BUG] Failed to Save To-Do item

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1998]
**Describe the bug**
The users are not able to create a To-Do item

**To Reproduce**

1. Install the Illinois app
2. Login as a University Student
3. Navigate to Wellness and tap inTo-Do List and Add Item
4. fill in the required field in Add an item screen and tap on the Save button

**Actual Result**
Failed to Save to-Do item message displayed to the user

NOTE - The same issue is reproduced for Create a category on Manage Categories screen

**Expected behavior**
The user should be able to create To-Do items without any issues

**Smartphone (please complete the following information):**

Device: [e.g. iPhone and Andoid]
Version [e.g. 4.0.51]

**Comment by mihail-varbanov** [comment]
@Priyaravi8, I was unable to recreate this on 4.0.51 against dev environment. Which environment did you use. Production could be not properly configured yet.

**Comment by Priyaravi8** [comment]
@mihail-varbanov  - Prod

**Comment by dr-mel** [comment]
@mihail-varbanov @pmarkhennessy will either of you let us know when prod is properly configured?

**Comment by Priyaravi8** [comment]
This is fixed
