### ISSUE TITLE
[BUG] Issue in starting Poll

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#1999]
**Describe the bug**
Poll is not started when user taps on the button "Start Poll Now" button

**To Reproduce**
1. Install the Illinois app
2. Login as a University student and navigate to Create a Poll
3. Fill in the required field and tap on the "Start Poll Now" button

**Actual result**
The poll is not started and no action is produced while tapping the "Start Poll Now" button

**Expected behavior**
Poll should start without any issues

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 4.0.51]

**Additional context**

**Comment by mihail-varbanov** [comment]
I was unable to recreate this with 4.0.51 against dev environment:

![Simulator Screen Shot - iPhone 13 - 2022-07-14 at 17 10 32](https://user-images.githubusercontent.com/5631487/179002773-c04f50a7-ccc2-4a5d-a422-163090a60482.png)

Can you confirm that you still get reproduce this problem? Which environment you are linked to?

**Comment by Priyaravi8** [comment]
@mihail-varbanov - Prod

**Comment by Priyaravi8** [comment]
This issue is resolved in version 4.0.55
