### ISSUE TITLE
[BUG] Favoriting logic for favorite widgets with multiple items

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2000]
Under Favorites and Browse, when an item within a **favorite widget with multiple items** is unfavorited, the overarching widget also becomes unfavorited while still containing other favorited items.

**To Reproduce**
1. Go to Favorites (or Browse)
2. Tap on the star by "Meal Plan" under Wallet to deselect the favorite
3. Wallet now appears as also deselected while there are still favorited items within it (Bus Pass, Illini Cash, Illini ID). This also happens to other Favorites that include multiple items like Dining.

**Expected behavior**
If a user unfavorites "Meal Plan" under Wallet on the Favorites or Browse screens while "Bus Pass" is still favorited, "Wallet" will remain favorited.  

Android, app version **4.0.51**

**Additional context**
This issues applies to other Favorites that include multiple items like Dining under both the Favorites and Browse screens

![Screenshot_20220713-160655](https://user-images.githubusercontent.com/1044905/178841572-68985678-2073-4100-8e38-9a7ef3613bee.png)
![Screenshot_20220713-160617](https://user-images.githubusercontent.com/1044905/178841583-e3e84e26-a81c-4779-8e63-66cb77dccb72.png)
![Screenshot_20220713-160650](https://user-images.githubusercontent.com/1044905/178841595-b2dc644d-0b83-4801-a44c-2fd7f8123200.png)
.

**Comment by kpecknold** [comment]
@mihail-varbanov @vburgett @pmarkhennessy 
I would like to add my voice to this request. I would expect that if at least one subitem is orange, then the widget star should be orange. Only when all subitems have ben de-selected, should the widget star be gray.  I don't know why #1891 was requested, can someone give the reasoning?

**Comment by pmarkhennessy** [comment]
@kpecknold In browse: Empty star (white) for not selected, partial selection is gray and all selected is Orange. GIT 1891 was requested by JP.

**Comment by pmarkhennessy** [comment]
Currently deferred

**Comment by vburgett** [comment]
@mihail-varbanov @pmarkhennessy  JP explained the current logic this morning:
**orange star:** favorite selected by user
**white star outlined in grey:** favorite deselected by user
**solid grey star:** a compound widget with at least one item favorited and at least one item unfavorited

This logic was not evident to me and I worry it won't be to other users. Something for us to consider for future releases.

**Comment by vburgett** [comment]
Checking in on the above @mihail-varbanov

**Comment by mihail-varbanov** [comment]
@vburgett, what do you expect me to do?

**Comment by vburgett** [comment]
@mihail-varbanov Under "Customize" the same overall widget star logic should be applied. Under "Current Favorites" a white star should never display but only solid grey or orange stars. 

With the above example in the screenshot, the wallet should display a solid grey star.

Can the solid grey star be replaced throughout the app with a lighter orange star without being time intensive? If not, please disregard at this time. 
[Icon-PartialSelectionWidget.zip](https://github.com/rokwire/illinois-app/files/9310504/Icon-PartialSelectionWidget.zip)

**Comment by vburgett** [comment]
Closing and reposting as a new ticket.
