### ISSUE TITLE
[BUG] Missing favorite button for Notifications

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#2008]
We are unable to make a notification favorite while we have My Notifications category in Favorites / Browse.

**Comment by mihail-varbanov** [comment]
The favorite star was removed by request in "2022-07-03-ILAppUpdates-VB.pdf" / Page 19 [#1910].

We should either remove "My Notifications" entry/widget from Favorites and Browse panels, if notifications cannot be selected as favorite, or bring the favorite button back.

CC @pmarkhennessy.

**Comment by vburgett** [comment]
No longer a relevant topic with 4.2 developments.
