### ISSUE TITLE
[BUG] Polls section within a group is loading indefinitely

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#2012]
**Describe the bug**
The circular loading icon is displayed indefinitely in the Polls section within a Group

**To Reproduce**
1. View an existing public or private Group or create a new Group
2. View Group Details and view the Polls section within it.
3. See that the polls are loading indefinitely

**Expected behavior**
An empty Polls section should be displayed soon after checking if no polls are present.

**Screenshots**
![image](https://user-images.githubusercontent.com/4306604/179022293-2ffab289-7201-4c38-a42a-85c78aee004a.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Version: 4.0.51 [PROD] as shared in Slack.

**Additional context**

**Comment by pmarkhennessy** [comment]
Please retest in Prod 2022/07/15. The BB is being updated

**Comment by sandeep-ps** [comment]
This is present in 4.0.53 [PROD]. Thanks.

**Comment by sandeep-ps** [comment]
This issue is not present after the recent updates to the Polls BB. I will close this.
