### ISSUE TITLE
[ACCESSIBILITY] Today's Wellness tip colors not meeting contrast ratio

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#2021]
Describe the accessibility issue
The white on orange is not meeting contrast standards.
[WCAG 1.4.3 Contrast (minimum) (AA)](https://www.w3.org/TR/WCAG21/#contrast-minimum)

To Reproduce

Launch app
Upon reaching the Wellness area of app there is "Today's wellness tip" in white on orange colors. 
 
Expected behavior
This color contrast needs to meet 4:5:1 ratio for regular sized text.

Screenshots
![Screenshot_20220715-151820](https://user-images.githubusercontent.com/82892873/179309782-1ab34906-b2be-4b2c-b94c-34b4a3476e5d.png)

Smartphone (please complete the following information):
Android Pixel 4a- Android 12

Additional context

**Comment by acovher2** [comment]
![2021_ still in V4 0 53](https://user-images.githubusercontent.com/82892873/179544059-18a0f9d0-bc01-4a89-bbd3-8cda5c5d9a20.PNG)

**Comment by vburgett** [comment]
I don't believe that background color is one of the intended three colors. 

Based on this input, let's update Today's Wellness Tips to rotate once a day among these three background colors: 
#0071CE (2022 Illini Industrial Blue)
#007E8E (2022 Illini Patina)
#FF5F05 (2022 Illini Orange)

**Comment by vburgett** [comment]
@acovher2 I have not seen the Illini Orange applied to the background for Today's Wellness Tip within the actual app—have you? 

@pmarkhennessy what colors are in the rotation for the background colors of the Wellness Tip? I'm fine with just using these two and closing this ticket afterwards.

#0071CE (2022 Illini Industrial Blue)
#007E8E (2022 Illini Patina)

**Comment by acovher2** [comment]
@vburgett Yes in the screenshot attached it was once applied to the background of Today's wellness tip back in v4.1.19. The two colors you mentioned pass for level AA criteria. I'll close this as I havent seen the orange since version 19 or so. 

#0071CE (2022 Illini Industrial Blue)
#007E8E (2022 Illini Patina)
