### ISSUE TITLE
[BUG] The "Blue" category is not applying a color. 

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#2040]
**Describe the bug**

**To Reproduce**
1. Go to 'WEllness area of app...'
2. Click on '.Manage Categories..'
3. Select "Blue" (light blue) circle and provide a name for the category

**Expected behavior**
A new category is created and given the color light blue selected. 

**Screenshots**
![20220718_104156](https://user-images.githubusercontent.com/82892873/179549730-88188f86-ce60-4cd6-b60d-5a9b0dc2be96.jpg)
![20220718_104311](https://user-images.githubusercontent.com/82892873/179549753-195d7892-5a5e-4619-9880-8b7725db6663.jpg)

**Smartphone (please complete the following information):**

iPhone XR- iOS 14.6, Pixel 4a- Android 12

**Additional context**

**Comment by dobromirdobrev** [comment]
This is fixed in version 4.1.1. In order to verify it, please first delete the existing "blue" categories and re-create them.

**Comment by vburgett** [comment]
This looks fixed now. Can you confirm, @acovher2? Thank you!

**Comment by acovher2** [comment]
@vburgett I am running into an issue where the To Do items do not save and appear in to do list in version 4.1.19 so I'm not able to verify at the moment.  I'm opening a bug.

**Comment by acovher2** [comment]
Verified as fixed, able to save blue category and have it appear as blue. Unable to test on an actual to do item due to 2326
