### ISSUE TITLE
[USABILITY] Wording change in Groups Policy Statement

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2041]
The second sentence in this policy statement is ambiguous. It can be interpreted as "report content offends or harrasses group admins".

![groups policy screenshot](https://user-images.githubusercontent.com/66988329/179600608-3fd00a98-23d9-47ec-9792-13195fb8a3f6.png)

I submit this revision for clarity:
 “Users may submit a report to group administrators about obscene, threatening, or harassing content.”

**Comment by dobromirdobrev** [comment]
Fixed in version 4.0.55
