### ISSUE TITLE
[BUG] Dining Payment Types Not Filtering Correctly

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#205]
1. 57 North and Caffeinator are showing as accepting Classic Meals, but they do not
2. All locations are showing as accepting Cash, but they do not

1. Go to Dining
2. Choose "All Payment Types"
3. Select "Classic Meals"'
4. See error: 57 North and Caffeinator show up in list, but shouldn't

**Expected behavior**
These two locations should only be displayed for these values:
57 North: ["CafeCredits","IlliniCash","CreditCard","GooglePay","ApplePay"]
Caffeinator: ["CafeCredits","IlliniCash","CreditCard","GooglePay","ApplePay"]

No locations should be returned for a filter value of "Cash"

**Comment by mdryankov** [comment]
Fixed in 2.3.29+429  CC @pmarkhennessy
