### ISSUE TITLE
[BUG] Wellness Ring - Random characters input in Quantity field is accepted

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2063]
**Describe the bug**
Inputting random characters in the Quantity field in the "Create Wellness Ring" screen is successfully creating a Ring.

**To Reproduce**

1. Install the Illinois app
2. Log in as a University student 
3. Navigate to Wellness and create a new ring
4. Enter a random character in the quantity input field and tap Create button

Actual Result
A wellness ring is successfully created 

**Expected behavior**
A message should display to the user to provide the correct input.

**Screenshots**
![Wellness quantity](https://user-images.githubusercontent.com/26231179/179838655-012b0502-d826-462e-896f-e1d3f700cb9d.png)

![quantity wellness 1](https://user-images.githubusercontent.com/26231179/179838676-968e462e-4399-4065-96b9-12c4e3f17196.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 4.0.55]

**Comment by TodorBachvarov** [comment]
Fixed in version 4.1.7
