### ISSUE TITLE
[USABILITY] change wording for "log in" to sign in - multiple places v4.0.51

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2064]
The attached PDF has screen captures showing the usage of the term "log in" and variants of it.

We want to use "sign in" rather than "log in" consistently.

Please follow requested changes in the PDF - which are in a red typeface.

[v.4.0.51 login audit2 jg.pdf](https://github.com/rokwire/illinois-app/files/9158998/v.4.0.51.login.audit2.jg.pdf)

Thanks,

Joe

**Comment by vburgett** [comment]
@joegrohens for items one and two in your PDF, could you change the wording request to ". . . signed in with your NetID . . ." These pop-up messages are populated when a user IS signed in via their email or mobile phone number which makes this text as is currently confusing.

**Comment by joegrohens** [comment]
@vburgett I updated the first two items to include "NetID".

**Comment by pmarkhennessy** [comment]
@joegrohens Is this still an issue?
