### ISSUE TITLE
[BUG] Groups > "Promote This Group" QR code > 404 error

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2065]
When you are the admin of a Group, the "Promote this group" option creates a QR code that leads to a 404 error page. 

**To Reproduce**
1. Go to Browse > Groups > My Groups
2. Tap on any group you are an admin of
3. Tap "Promote this group"
4. Save QR code to photos
5. Access QR code in your photos and go to the link
6. Receive a 404 error

**Expected behavior**
I expect users invited to join a group via the QR code to be directed to that specific Group in order to request membership OR be automatically granted membership. 

**Smartphone:**
 - Version 4.0.55 on an Android Pixel 6 (AND on an iPhone 13 app version 3.3.22)

(@kpecknold I am not marking this as a showstopper but please do if you believe it is one.)

**Comment by dobromirdobrev** [comment]
This issue is a consequence of two problems:
1. Bug in the app source code which is fixed in version 4.1.0 and
2. Missing file in app's production assets. I asked the operations team to upload it and waiting their answer.

**Comment by dobromirdobrev** [comment]
The file from point 2 is available, so this could be verified.
