### ISSUE TITLE
"Building access" wording appears in privacy settings 

### ISSUE THREAD

**Issue by nelshopp** [rokwire/illinois-app#2082]
The phrase "Building access" appears in privacy settings though we don't use that feature anymore.

**To Reproduce**
1. Go to Manage and Understand your Privacy
2. Tap on either privacy level 4

"Building access appears in the description (see screenshot)

See screenshot

Smartphone (please complete the following information):**
 - OS: [e.g. Android ]
 - Browser [chrome]
 - Version [8.0]

**Comment by nelshopp** [comment]
![Screenshot_20220722-125233_Illinois](https://user-images.githubusercontent.com/91676531/180560014-bc82cb55-d3b0-4826-a5be-903a83baf09c.jpg)

**Comment by dobromirdobrev** [comment]
Done in version 4.1.4

**Comment by vburgett** [comment]
Great catch, @nelshopp. Looks fixed in 4.1.26.
