### ISSUE TITLE
[USABILITY] Poll Options 3 and 4: No Option to Delete

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2085]
When a user goes to create a poll, they can currently add up to four different "options." Once the fields for options 3 and 4 are added, there is no way to delete them so a user can either start the poll as is with two blank poll options or start over entirely.

Please add the "X" by options 3 and 4 under "Create a Quick Poll" to match the "Membership Questions'" "X" when creating a Group.

**To Reproduce**
Go to Browse > Create a Poll 
Tap "Add Option +" twice
Try to remove options three and four or proceed to see how the poll has two empty poll options

Device: iPhone 13
App Version 4.0.55

(Please also see ticket #1591 for an older ticket about Polls that still needs addressing.) 

![IMG_5812](https://user-images.githubusercontent.com/1044905/180814464-2b67f8a0-e15f-47f1-88eb-bf9ce8f88a4b.PNG)
![IMG_5813](https://user-images.githubusercontent.com/1044905/180814481-b049fae8-db9f-4df0-974b-c1b9fafaa89c.PNG)

**Comment by pmarkhennessy** [comment]
@mihail-varbanov While you are in polls...

**Comment by mihail-varbanov** [comment]
Added in version 4.2.39.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov! The X to remove options three and above is in place for v4.2.40
