### ISSUE TITLE
[FEATURE] Add a "MyMcKinley Patient Health Portal" link to “Wellness Resources”

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#2098]
2. Add a "MyMcKinley Patient Health Portal" link to “Wellness Resources” (in alpha order under "McKinley Pharmacy") with a default selected star (link to infotype “MyMcKinley Patient Health Portal”)
a. Position the “MyMcKinley Patient Health Portal” item to show up first under the “My Wellness Resources” Favorites widget

[4.1 IL App-2022-07-26-VB.pdf](https://github.com/rokwire/illinois-app/files/9196114/4.1.IL.App-2022-07-26-VB.pdf)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.1.4.

**Comment by vburgett** [comment]
Updated—thank you! @dr-mel
