### ISSUE TITLE
[FEATURE] Remove Athletics Teams widget from Favorites panel

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#2102]
5. Widgets to eliminate:
b. MyAthleticsTeams (widget is a shortcut to a setting without variable content).

[4.1 IL App-2022-07-26-VB.pdf](https://github.com/rokwire/illinois-app/files/9196923/4.1.IL.App-2022-07-26-VB.pdf)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.1.4. Please note that Athletics / Teams entry in Browse panel does not have a favorite star (button) any more as it does not have a corresponding widget to show in Favorites panel.

**Comment by vburgett** [comment]
Since "Teams" is already under the settings icon, can we remove "Teams" from Browse > Athletics?

**Comment by mihail-varbanov** [comment]
Athletics / Teams entry from Browse panel is removed in version 4.1.16.
