### ISSUE TITLE
[FEATURE] Split compound Wellness widget into standalone widgets

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#2107]
6. For the "Wellness" Favorites widget, extract all three sub-widgets to be their own top-level Favorites widget (right now a user can't find their to-do list under Customize if they don't connect Wellness and a To-Do List).
a. Rename "DailyTips" widget to "DailyWellnessTip" (not plural "tips")
b. UnderBrowse > Wellness, change "To Do" to "To-Do List"

[4.1 IL App-2022-07-26-VB.pdf](https://github.com/rokwire/illinois-app/files/9197376/4.1.IL.App-2022-07-26-VB.pdf)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.1.4.

**Comment by vburgett** [comment]
Updated—thank you!

**Comment by vburgett** [comment]
This edit still needs to be made: 
Under Browse > Wellness, change "To Do" to "To-Do List" and "Daily Tips" to "Daily Tip"

**Comment by mihail-varbanov** [comment]
Text updates in Browse / Wellness section are resolved in version 4.1.6.
