### ISSUE TITLE
[FEATURE] Repeat content of My section from Browse

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#2112]
8. Under Browse, repeat My tools in their overarching sections and put the My section in alpha order.

[4.1 IL App-2022-07-26-VB.pdf](https://github.com/rokwire/illinois-app/files/9198200/4.1.IL.App-2022-07-26-VB.pdf)

**Comment by mihail-varbanov** [comment]
Аfter some wondering about the meaning of "repeat My tools in their overarching sections" I decide to do what I suspect that is most probably wanted. The following entries from "My" section had been duplicated in their category sections from Browse:

My Athletics Events => Athletics
My Athletics News => Athletics
My Game Day => Athletics
My Events => Events
My Dining => Dining
My Laundry => Laundry
My Notifications => NA
My Campus Guide => Campus Guide

Resolved in version 4.1.4.

**Comment by vburgett** [comment]
That logic matches the request. None of the duplicated items listed above link anywhere when tapped in Browse on an Android 4.1.4. (See Browse > Events > My Events).

**Comment by mihail-varbanov** [comment]
Thanks for pointing this out! Fixed in 4.0.16.
