### ISSUE TITLE
[BUG] Meal plans and balances not displayed

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#212]
**Describe the bug**
Reported by @clint156:
> Meal plans and balances are not being displayed for people. I have verified this on both IOS and Android with my account. Here's the json coming back from the balances call for one of the UINS that have reported the issue:

`{"MealPlanName":"CLASSIC 10/45 CC             ","MPBalance":9,"IllinCashBalance":0.0,"CafeCreditBalance":38.25,"Status":"Success","HousingResidentStatus":true}`

**To Reproduce**
1. Open wallet
2. See no Illini Cash balance or meal plan details

**Expected behavior**
Meal plan and balance details should be shown.

**Smartphone (please complete the following information):**
 - OS: iOS and Android
 - Version 2.3.18

**Additional context**

**Comment by kpecknold** [comment]
I saw the same behavior in 2.2.26, but when I added "student" as who I am, and revisited, the meal plan displayed. I was only "employee" before. The meal plan display should not be linked to the audience.

**Comment by isaac-galvan** [comment]
@kpecknold @clint156 I've added meal_plan for "student OR employee" via talent chooser.  Previously it was just "student".
 Does this resolve the issue?

**Comment by clint156** [comment]
It looks like it resolves it in my case. I am going to attempt to verify that the student did not have the “University Student” option selected.


Clint Stearns
Systems Development Architect, Student Affairs Technology

[Illinois-Wordmark-Horizontal-Full-Color-RGB_185px]
