### ISSUE TITLE
[BUG] login to MyMcKinley traps 2fa and prevents access

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2147]
**Describe the bug**
There are a few places where Illinois app provides a link to MyMcKinley patient health portal.

When users follow such a link, they are unable to successfully log in at MyMcKinley.

The two-factor authentication sequence never authorizes the display of the MyMcKinley target web page.

This problem was also seen last January when a link to MyMcKinley was provided on the home screen of Illinois app, and people couldn't access it due to a 2fa trap. The solution at that time was to open the MyMcKinley page in an external browser rather than in the app's internal browser. I don't know technically why that solved the problem.

**To Reproduce**
1. Go to _Campus Guide > Health & Wellness > General Support > MyMcKinley Patient Health Portal_
2. Tap "Visit Website" (https://mymckinley.illinois.edu/)
3. At the login screen, tap "University of Illinois Urbana-Champaign". Shibboleth login appears, followed by 2FA.

**Result:** 
After 2FA is confirmed through the user's 2FA client app, the user must manually find Illinois app again.  The MyMcKinley Portal Login screen is still shown. Some users describe this as being caught in a login loop.

**Expected behavior**
The Illinois app internal browser should receive 2fa confirmation, the Illinois app should automatically become the active app again on the phone, and the app's internal browser should display the message "logging you in" and allow progress to the medical records page. There the user can read lab results and upload vaccination records.

**Note:** 
If the solution to this bug is to open the destination page in an external browser, I will need a method to force that to happen in Illinois Admin. 

**Screenshots**
![Screenshot 2022-08-01 at 9 54 38 AM](https://user-images.githubusercontent.com/66988329/182178325-e2534c7a-8cf5-49a3-b2ef-862349b5a9c6.jpeg)

-------------------------------------------------------------------------------------------------

![duo copy](https://user-images.githubusercontent.com/66988329/182201432-8d0bdf4f-5c9c-42e3-8ecd-65b483f73e54.jpeg)

-----------------------------------------------------------------------------------------------
![mymckinley copy](https://user-images.githubusercontent.com/66988329/182242068-99ab92f2-3bc9-48b0-b13a-1b4d77aa22d9.jpeg)

**Other links to MyMcKinley in Illinois app**

* The following Daily Wellness Tip has a link to MyMcKinley.  (in 4.0.55, this link did not succeed past 2FA)
![wellness tip w mymckinley](https://user-images.githubusercontent.com/66988329/182242771-d2557f2c-bf80-48df-b271-b82ce908224b.jpg) 

* _Wellness > Wellness Resources > MyMcKinley Patient Health Portal_ (in 4.1.4 on android this link allows a successful login; therefore, not a bug)

=====
If the 2FA problem is fixed in 4.1.x, great. The MyMcKinley page in Campus Guide is not currently in dev, and needs to be added to test if the login works.

**Comment by vburgett** [comment]
_Wellness > Wellness Resources > MyMcKinley Patient Health Portal (in 4.1.4 on android this link allows a successful login; therefore, not a bug)_
**In 4.1.4, I have the same "login loop" issue on an Android** where I can access the MyMcKinley website, enter my login and password, and once I leave the Illinois app to go to Duo Mobile for 2FA, I am right back at the beginning at  MyKcKinley webpage https://mymckinley.illinois.edu in the Illinois app.

**Comment by joegrohens** [comment]
@vburgett I just tried again the link to MyMcKinley from the Wellness Resources submenu in 4.1.4. I was able to log in and access the lab results page.

You might want to specify your phone type to provide clues about why this works for me and not for you.

My phone is Google Pixel 3.

**Comment by vburgett** [comment]
I'm using a Google Pixel 6. (I also just tried again and did have the same issue of being in a login loop via 4.1.4.)

**Comment by kpecknold** [comment]
Hmmm... I just tried using a Google Pixel 2 and it worked fine in 4.1.4

**Comment by joegrohens** [comment]
Confirm that this is fixed for links coming from Campus Guide. All have been made to open in an external browser. (CF #2155)
