### ISSUE TITLE
2FA issue with MyMcKinley? 

### ISSUE THREAD

**Issue by nelshopp** [rokwire/illinois-app#2148]
**Describe the bug**
After logging into MyMckinley from the app and going through 2FA process, it returns to the app and not the MyMckinley page.

**To Reproduce**
Wellness 
--> 
Wellness Resources ---> 
McKinley and go the McKinley page within the page 

tap “My McKinley”

there seems to be a 2FA or authentication issue.  It lands back on the Illinois app and not the portal.

**Expected behavior**
Tapping MyMckinley should take it back to the MyMcKinley portal.

**Screenshots**
![Screenshot_20220801-135603_Illinois](https://user-images.githubusercontent.com/91676531/182243351-771cf577-ef30-4038-bb5e-fafb95852972.jpg)

**Comment by TodorBachvarov** [comment]
Visit website button for McKinley Health Center will open external browser. Implemented in version 4.1.8

**Comment by joegrohens** [comment]
This 2FA issue is still not fixed for https://github.com/rokwire/illinois-app/issues/2147
