### ISSUE TITLE
[BUG] Quick Polls - Creator can't delete in 4.1.4

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2153]
**Describe the bug**
While polls within groups can be deleted, a regular quick poll cannot be deleted

**To Reproduce**
1. Create a quick poll
2. Vote
3. End the poll
4. See there is no option to delete

**Expected behavior**
The creator of the poll should be able to delete it.  (Creator + Admin if a group poll, this works in 4.1.4)

**Comment by mihail-varbanov** [comment]
Implemented in 4.1.16

**Comment by kpecknold** [comment]
@mihail-varbanov it does delete the poll, but there is no success message and you have to exit and come back in to see if it is deleted. Can we add a success message and refresh the list?
