### ISSUE TITLE
[BUG] After closing the app, the order and list of favorites seem to be resetting

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#2154]
**Describe the bug**
After closing the app (not uninstalling), the order and list of favorites seem to be resetting.

**To Reproduce**
1. Have the favorite widgets customized in some way
2. Close the app by swiping up
3. Open the app and see that the current list of favorites has returned to the initial setting

**Expected behavior**
The favorites list (including unused favorites) and order should persist between app uses. Thanks.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS
 - Version: 4.0.55

**Additional context**

**Comment by pmarkhennessy** [comment]
This will be fixed in 4.1.17 or 4.1.18, I will let you know

**Comment by sandeep-ps** [comment]
Thanks, Mark. This looks fixed in 4.1.19. I will close this issue.
