### ISSUE TITLE
[BUG] 2FA trap prevents login to Due Date Catalog in Campus Guide

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2155]
**Describe the bug**
Seen in V 4.0.55

1. Go to _Campus Guide > Academic Support > Course Management Tools > Due Date Catalog_
2. Tap "Visit Due Date Catalog Website" button.
3. Sign into the Due Date web app by using NetID
4. Authenticate with 2FA.

The result is that you are returned to the Log In page w/o being logged in. (Same problem as with MyMcKinley.)

![IMG_1461](https://user-images.githubusercontent.com/66988329/182443220-cd9b8e4f-4939-480d-8545-7d171a5edd21.jpeg)

![Screenshot 2022-08-02 at 12 59 10 PM](https://user-images.githubusercontent.com/66988329/182443270-0d27118c-42fe-4a7c-b227-86135861f97c.jpeg)

**Comment by pmarkhennessy** [comment]
@TodorBachvarov Please make all Campus Guide links use an external browser. Check with @mihail-varbanov on how if needed.

**Comment by TodorBachvarov** [comment]
All Campus Guide links use external browser. Fixed in version 4.1.14.

**Comment by joegrohens** [comment]
confirmed fixed
