### ISSUE TITLE
[USABILITY] Update main profile icon when a photo has been uploaded

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2157]
Can we update the profile icon in the upper right hand corner of the app to update to the user's photo, when applicable? (This is the behavior that's in place for the user's profile icon under Groups.) 
Otherwise the generic default profile icon reads as if the user has not successfully updated their profile image.

**Comment by mihail-varbanov** [comment]
This is implemented either in 4.2.49, or in 5.0.0 - whatever we build first.

**Comment by vburgett** [comment]
Complete in 4.2.52—thank you!
