### ISSUE TITLE
[FEATURE] Request App Rating & Review

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#2162]
**Re: University Monday 2022/08/01** / 2022-08-03

5.3 Android and iOS App Stores/Ratings/Reviews etc.

5.3.1 Stephen will add to a user's account in Core BB a field that will dictate if the user should do a review/rating and also an API or field to set when a rating is done. Until we get this just do the below items to do the ratings etc. Let me know if it cannot be done or you don't understand me.

5.3.2 Show a popup before doing the rating etc that asks the user "Would you like to rate this application?" Yes or No. We will ask 3 times but will wait until 3 weeks between each time we ask the user to rate the app

5.3.3 Can you add to the app config, if this is the correct place, this wait value in hours that we will set to 3 weeks that will be used for item 5.3.2

5.3.4 If we know that the rating/review is actually done then don't show it again or if the user presses "No" to item 5.3.2 then wait before asking again

5.3.5 JP does not want the popup and ratings etc to show when the app runs. Can you make a timer or something that will show this so it is not immediate please

**Comment by joegrohens** [comment]
Suggestion for future enhancements to this method: 

I have read that it is good to ask for an app review immediately after the user has completed a (useful) task successfully. You are more likely to get positive reviews that way.
