### ISSUE TITLE
[USABILITY] Blue Star Inconsistency

### ISSUE THREAD

**Issue by nataliehelregel** [rokwire/illinois-app#2165]
@pmarkhennessy As discussed in our Rokwire Weekly meeting yesterday, here are all the Favorite stars that still highlight as a blue color instead of orange when active. 
- Under Wellness- The Healthy Illini Podcast screen
![Screenshot_20220804-102606_2](https://user-images.githubusercontent.com/96087558/182886580-bf11ba58-f755-41ed-ba22-64c4946a102b.png)

- Under Wellness- The "I'm Struggling" screen 
![Screenshot_20220804-102631_2](https://user-images.githubusercontent.com/96087558/182886614-66f52732-a791-4bee-8a0e-e23a4edb0e17.png)

- Items under "My Campus Guide"
![Screenshot_20220803-151954_2](https://user-images.githubusercontent.com/96087558/182711495-f69a6aa7-b597-452b-877c-1e0b9fe78dd1.png)

- Items under "My Athletic Events"
- Items under "My Athletic News"
![Screenshot_20220803-151949_2](https://user-images.githubusercontent.com/96087558/182711669-a604df91-1011-4ae9-9063-b74a413da949.png)

- Items under "Athletic Events"
- Items under "Athletic News"
![Screenshot_20220803-151939_2](https://user-images.githubusercontent.com/96087558/182711801-688c1afb-1cbf-4339-ae1b-733d776d7a1c.png)

- Items under "Campus Guide Highlights"
- Items under "Recently Viewed"
![Screenshot_20220803-151910_2](https://user-images.githubusercontent.com/96087558/182711895-8491d69a-00f1-432e-a3a3-aafff9e8a9ca.png)

- Items under "Campus Reminders"
![Screenshot_20220803-151854_2](https://user-images.githubusercontent.com/96087558/182711960-3a5d3687-8cc3-4978-b5e3-c82b75803105.png)

@vburgett @johnmpaul

**Comment by vburgett** [comment]
Still an issue in 4.2.47

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.48

**Comment by vburgett** [comment]
Complete in 4.2.52—thank you! 
(@nataliehelregel I will close this one for us.)
