### ISSUE TITLE
[BUG] User unable to create an event in a group

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2166]
**Describe the bug**
A student user reported trying to create an event and getting the error message "There was an error creating this event for the following groups: ur mom, but better (UMbb)"

![image](https://user-images.githubusercontent.com/66988329/182726864-650b1d63-8e3a-403f-a7d3-05c2a99d3e47.png)

He said:

> I am creating a in person event, full day, included event title, description, category, event is set at free. All other options were not altered. 

Version: 4.0.55
Phone: Android Samsung Galaxy s21

....
@sandeep-ps @kpecknold 

This student submitted the report via the app's Feedback channel. I can ask him for further information as needed, or you can. I forwarded his whole email to you both.

Please reassign this to Mark when you think it has sufficient info.

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,
I was not able to reproduce this behaviour. I checked different app version, environments and groups. All works as expected to me. 
However, I'm not a member of this group in production environment. 

As a next, I would suggest someone with access to production instances could check AWS for any error logs regarding this group. cc @pmarkhennessy

**Comment by sandeep-ps** [comment]
Hi, Dobromir, we are tracking this as a backend GitHub issue at https://github.com/rokwire/rokwire-building-blocks-api/issues/996. Once we implement this change and get it deployed, we should be able to re-test in the Illinois app. I don't think an app bug fix is needed now.

**Comment by joegrohens** [comment]
I am closing this as it is marked DONE in platform. I don't know how to test it.
