### ISSUE TITLE
[USABILITY]  "You need to be logged in to access

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2167]
@vburgett  - would you please review this proposal and modify it to your liking? If and when you think it's ready, you could assign it to Mark. Thank you.

**Problem**

Users who are not signed in with NetID get the following message when they touch a feature that requires NetID.

![Screenshot 2022-08-02 at 6 30 38 PM copy](https://user-images.githubusercontent.com/66988329/182758650-eb0fe77d-0250-4d7d-8c78-846b6a7e0ae1.jpeg)

This error message has a number of deficiencies:

- It should say "sign in" not "log in" for consistency throughout the app
- It should mention NetID. Because signing in with cell phone or email address will not give access to features that require NetID.
- It should help the user see how to sign in. 
- It should help the user set their privacy level to 4 or 5 if they are at a lower level.

**Suggested Solution**

- Change the current message to: "You need to be signed in with your NetID to access < >."
- Add a sign-in button. Maybe the two buttons in this dialog would be "Sign In with NetID" and "Cancel".
- If the user taps "Sign In with NetID", Shibboleth is invoked.
- If the user has privacy level of 3 or lower when they tap "Sign In with NetID", a second dialog appears. The second dialog would say:

 "With your privacy level of [1] you cannot sign in with a NetID. You need to change your privacy level to [4] or [5]. Do you want to change your privacy level so that you can sign in?"
 
 Answer Buttons: [ Set to 4 ] [ Set to 5 ] [ Cancel ]
 
 This could look sImilar to the following dialog box from v3.3
 
![bldg access warning copy](https://user-images.githubusercontent.com/66988329/182759667-6a91470d-ed8a-4611-b91a-98f0fd2a9a0f.png)

**Comment by vburgett** [comment]
When logged in via email or mobile phone (or not at all), the notification bell icon, Customize, Illini Cash, Meal Plan, Illini ID, and MTD Bus Pass should have a clearer error message reading: 

**“You need to be signed in with a NetID and a privacy level of 4 or 5 to access [Notifications].”**
"signed in with a NetID" = underlined link to "sign in/sign out" screen under My Settings
"privacy level of 4 or 5" = underlined link to My App Privacy Settings

([Reference p18 of older PDF for a visual](https://drive.google.com/open?id=1Odef_pA856POy7C5f7wR8JfbkZbPETrq&authuser=vburgett%40illinois.edu&usp=drive_fs))

**Comment by joegrohens** [comment]
closing issue to propose a simpler solution
