### ISSUE TITLE
[USABILITY] Remove reference to "Building Access" in "Connect to Illinois" widget.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2168]
When a user is signed out of the app, the "Connect to Illinois" widget appears in favorites.

![connect to Illinois (netid) copy](https://user-images.githubusercontent.com/66988329/182760507-2d2b47b9-3f07-4852-9317-bfb6133d038d.jpeg)

Please remove the sentence in parentheses that says:

> (A NetID sign-in is REQUIRED to be able to use the Building Access feature).

Building Access has been discontinued.

We could consider replacing that sentence with:

> A NetID sign-in is needed to use all features that are based on your University identity.

**Comment by joegrohens** [comment]
Yes - I agree with final wording from @vburgett

**Comment by RokBill** [comment]
I agree as well. Nice work.
Bill

On Aug 4, 2022, at 9:50 AM, Joseph Grohens ***@***.******@***.***>> wrote:



Yes - I agree with final wording from @vburgett<https://urldefense.com/v3/__https://github.com/vburgett__;!!DZ3fjg!6EgWhOux72V4wnPSt_Dyc0Ho27piv7EdKyDE46KfiTuyCcp2PDK_3-xTDqadRPJCvQ5xJ2Jaig2IecFDn_UreAdkjVBG$>

**Comment by TodorBachvarov** [comment]
Text changed in version 4.1.14.
