### ISSUE TITLE
[USABILITY] Extend My Calendar Setting dropdown menu and greyed out bg 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2174]
The greyed out background and drop down menu region needs to be extended for Settings > My Calendar Settings. 

Google Pixel 6
Ver 4.1.4

![Screenshot_20220804-104325](https://user-images.githubusercontent.com/1044905/182898655-d2a8633d-e653-45a9-8651-f866d5483b48.png)

**Comment by vburgett** [comment]
This is not resolved in 4.1.14. A user cannot see the entire drop down menu when under Settings > My Calendar Settings due to this issue.

**Comment by mihail-varbanov** [comment]
Fixed in 4.1.16
