### ISSUE TITLE
[FEATURE] include background location usage disclosure

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#218]
**Is your feature request related to a problem? Please describe.**
We are required to add a disclosure before the request for location permissions that states why the app needs to request background location access.  This is to comply with Play store policy.

**Describe the solution you'd like**
Please add the following the the location permission explanation screen text:

_Bluetooth-enabled features such as Quick Polls require permission to access your location in the background._

**Additional context**
Here is the screen to be updated:
![Screenshot (Jan 29, 2021 10 52 44 AM) (1)](https://user-images.githubusercontent.com/11352701/106309249-77e9f500-6227-11eb-8dfd-789d40df3c1d.png)

**Comment by mihail-varbanov** [comment]
Fixed in upcoming version 2.4.0.
