### ISSUE TITLE
[BUG] "My Gies Canvas Courses" screen in Academics screen is broken

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2189]
**Describe the bug**
"My Gies Canvas Courses" screen in Academics screen is broken. The information about "My Gies Canvas course" is broken on the screen.

**To Reproduce**

1. Install the Illinois app.
2. Login as University Student
3. Navigate to the Academics screen and tap on "My Gies Canvas Courses" in the drop-down list

**Actual Result**
The information displayed for "My Course" is broken on the screen

**Expected behavior**
All the information on "My Course" should display correctly to the user correctly

**Screenshots**
![gies course](https://user-images.githubusercontent.com/26231179/183511641-a397a616-4c0a-43ce-bfa4-873daa144261.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.055]

**Comment by mihail-varbanov** [comment]
@Priyaravi8, I was not able to recreate this using 4.1.16. Could you please check this again using the latest build of 4.1? Also, in case the problem persists, could you tell what is the content of "My Gies Canvas Courses" widget from Favorites panel, and what do you see when you select Academics / My Gies Canvas Courses entry from Browse panel?
