### ISSUE TITLE
[USABILITY] Text edit: My Settings to Settings

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2202]
For consistency's sake, please update the header title associated with the gear icon from "My Settings" to "Settings." (The other two icons in that grouping are "Profile" and "Notifications.")

![image](https://user-images.githubusercontent.com/1044905/183781079-ac1d748d-c9f1-4b3d-b0b5-5fbece2c75c3.jpeg)

Cc: @joegrohens

**Comment by mihail-varbanov** [comment]
Resolved in 4.0.16
