### ISSUE TITLE
[BUG] Map - Selecting Courses needs to gracefully handle no courses

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2216]
**Describe the bug**
On the map, if I select "My courses", I get a blank screen because I don't have any courses. I can't exit out gracefully. I have to close the app and reopen.

**To Reproduce**
1. Use an account that doesn't have any courses
2. Go to Map
3. Choose "My courses"
4. See blank screen and inability to exit gracefully

**Expected behavior**
Handle the error, allow exit. Or, don't display the My courses option to people who don't have courses.

**Comment by mihail-varbanov** [comment]
@kpecknold, I was not able to recreate this problem on version 4.0.16. If we fail to load user courses or if the user does not participate in any courses we display the map without any markers added inside it. Could you check it again if you still can recreate the problem?

**Comment by mihail-varbanov** [comment]
@kpecknold, I managed to recreate the problem. The "blank screen" is a Map View that is zoomed so much that you do not see anything else. This is fixed in 4.1.17
