### ISSUE TITLE
[USABILITY] Typo in "Poll has been edned"

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2217]
**Describe the usability issue**
When a poll ends, a message is sent (to some members?) that says "Poll <title> has been edned."

This string should be revised as follows:

"Poll <title> has ended."

![poll has ended jg copy](https://user-images.githubusercontent.com/66988329/184071151-6060d25a-a26b-4103-a977-876cad6ea9d6.jpeg)

![poll has ended jg](https://user-images.githubusercontent.com/66988329/184071152-78d36a95-374a-46d3-b6c7-6e0bc29d8404.jpeg)

**To Reproduce**
I am actually not sure how to reproduce. I just tried to reproduce and couldn't make it happen.

However, if you know where this string is stored, you could fix the spelling and grammar.

**Comment by mihail-varbanov** [comment]
@joegrohens, this text does not come from Illinois client app (the repo that you opened this issue). It is generated by the polls-building-block backend service. I created an issue for this there: https://github.com/rokwire/polls-building-block/issues/18.

**Comment by pmarkhennessy** [comment]
@joegrohens please validate this when the new Polls BB is deployed, Friday 08/12 or Monday 08/15

**Comment by joegrohens** [comment]
@pmarkhennessy - I will ask someone to help me validate. It seems to me that the "poll ended" message is only sent to people who voted on the poll who are NOT the poll creator. That's why I wasn't able to figure out how to reproduce.

Thanks for your help. To be continued.


Joe

**Comment by joegrohens** [comment]
Fix confirmed in 4.3.13
