### ISSUE TITLE
[BUG] Favorites - Athletic News section not rendered correctly

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2239]
**Describe the bug**
The athletic section in Favorites is not delivered correctly

**To Reproduce**
1. Install the Illinois app
2. complete the onboarding 
3. Sign in as a University student and navigate to the Favorite screen
4. Scroll down to the Athletic news section

**Actual result**
The Athletic News section and its content information are not rendered correctly

**Expected behavior**
The Athletic News section and the information inside should deliver correctly to the user.

**Screenshots**
![Athletic news](https://user-images.githubusercontent.com/26231179/184212927-f429fb9d-1a36-4f81-8ff1-07d046bda29b.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.1.16]

**Additional context**

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,
We're not able to reproduce this issue. Could you please verify it once again? And if it exists, could you please provide more details? OS version, device and most valuable for us would be any logs. 

Thanks.
