### ISSUE TITLE
[USABILITY] Provide an External link icon to the button "Order Online"

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#224]
**Describe the usability issue**
In the detailed dining screen, provide an external link icon to the button "Order Online," which explains that it navigates outside of the Illinois app.

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding steps of the app
3. Select University student as a role and verify the identity
4. Tap Dining in the Home screen
5. Tap one of the Dining Hall in the Dining hall list
6. Detailed dining hall screen is displayed.

**Actual Result**
In the detailed dining screen, an external link icon is missing on the button "Order Online."

**Expected behavior**
In the detailed dining screen, add an external link icon to the button "Order Online," which explains to the user that it navigates outside of the Illinois app.

**Screenshot**

![external icon](https://user-images.githubusercontent.com/26231179/106513262-580d3800-6498-11eb-8ba0-babc789366a5.png)

**Smartphone (please complete the following information):**

Device: [e.g. Android]
App Version - 2.4

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
