### ISSUE TITLE
[USABILITY] Text edits: Profile > ADA

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2240]
Issue: How does a user know that the “ADA” section under My Profile directly affects the building entrances they will see under Map > My Courses? Or can it be assumed that all map views in the app will provide ADA accessible building entrances when this is toggled on?

Solution: change the “ADA” header to “Accessibility Needs” with a toggle that reads “Display ADA accessible building entrances (on the map) or (for My Courses)”

**Comment by mihail-varbanov** [comment]
This is updated in 4.1.17.

FYI, the only place that this setting takes effect is when the user navigates to a course the destination point to be the closest building entrance that is ADA compliant. If the ADA option is not selected we just target the route to the closest building entrance nevertheless it is ADA compliant or not.
