### ISSUE TITLE
[USABILITY] Notification messages from Groups activities lack precision

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2253]
When users vote on polls in a Group, the notification message refers to it as a "post".

"A new post has been published in <nameofgroup> group."

![notifications](https://user-images.githubusercontent.com/66988329/184448513-c794d84b-826d-4edf-af56-573a6275aefa.png)

The message should (ideally) say "A Poll has been voted on in <nameofgroup> group."

If that's too specific to implement now, you at least could modify the current message to say "There is new activity in <nameofgroup> group."

But eventually, actions in Polls, Events, and Posts should get different notification messages, in my opinion.

A user (Daniel Ochida) brought this up through app feedback.

**Comment by pmarkhennessy** [comment]
@joegrohens Do you still see this issue?

**Comment by joegrohens** [comment]
confirmed fixed in 4.2.42
