### ISSUE TITLE
[USABILITY] Sometimes "My Groups" doesn't load any of my existing groups

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2254]
I  have "My Groups" on the Favorites page.

Frequently today when I have been going to **Favorites > My Groups**, it doesn't show my groups, but instead says "You have not created any groups yet."

But **Browse > Groups > My Groups** shows all of my groups.

Then when I go back to **Favorites > My Groups**, the array of groups is there.

![no groups yet](https://user-images.githubusercontent.com/66988329/184453490-039427ca-2d63-4834-9e66-9b6d9859b9d0.png)

Maybe there is a lag because of the horizontal display of the groups?

This problem appears in both v4.0.55 and v4.1.17.

**Comment by dobromirdobrev** [comment]
Fixed in version 4.1.29.
