### ISSUE TITLE
[USABILITY] Report of offensive speech automatic title

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2255]
When reporting a post to admins as offensive speech, the report creates an automatic title: 

"Report Obscene, Harrassing, or Threatening Content to Group Administrators"

Can you please change the wording to:

"Report _of_ Obscene, Harrassing, or Threatening Content to Group Administrators"

That way it doesn't look like a command.

![offensive report](https://user-images.githubusercontent.com/66988329/184454622-c5010049-93b5-4ef8-94ee-1918062ea267.png)

**Comment by mihail-varbanov** [comment]
Hi @joegrohens, this subject comes from Groups BB who builds the report abuse notification, not from the Illinois client app. I created a separate issue for this in groups repository: rokwire/groups-building-block#328.

**Comment by mdryankov** [comment]
@joegrohens, This issue is fixed on server side. There is a new deployment on Dev which is ready for test. 

Please verify and let us know

**Comment by mdryankov** [comment]
Note there was a typo within the expected subject. 

The actual subject will be: "Report of Obscene, Harassing, or Threatening Content to Group Administrators ..."

**Comment by joegrohens** [comment]
I looked to test this in V3.3.13, but I don't think there is an assisted method for sending such a message anymore. It appears that a user who wants to send such a message would DM the admin, and manually write their own subject line.

Therefore, I am closing this. Unable to verify fix, but thank you for doing it.
