### ISSUE TITLE
[BUG] Groups - Direct messages - Not private!

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2256]
Admins can see all group direct messages.

1. Request to join "Groups Feedback"
2. See previous DMs between admins and members

**Comment by pmarkhennessy** [comment]
@kpecknold I was not able to recreate this. The original Post must not be to All. Please provide better steps if possible.

**Comment by kpecknold** [comment]
Confirmed fixed in 4.2.47
