### ISSUE TITLE
[BUG] Group Events - Adding an existing event does not prompt to add to other groups

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2257]
**Describe the bug**
After adding an event to a group, admins are no longer prompted to add the event to the rest of their groups. 

**To Reproduce**
1. Go to a group for which you are an admin (make sure you are an admin for at least 1 other group)
2. Add an event that is existing 
3. Note that you do not get prompted to add the event to the other groups

**Comment by joegrohens** [comment]
@Courtney, Kathryn A ***@***.***> and @Mark Hennessy
***@***.***>

I just created an event in a group using v4.1.17. It did ask me to share to
my other groups.

I suspect that either Kathryn has no other groups where she is an admin, or
it has something to do with the event being an existing event.

**Comment by kpecknold** [comment]
Please follow the steps to reproduce using an existing event. This was the behavior for me and one of my stakeholders.

**Comment by pmarkhennessy** [comment]
@kpecknold We only show the ability to post the event to other groups if the recipients are "All"

**Comment by kpecknold** [comment]
@pmarkhennessy   I don't know what recipients has to do with adding an existing event...  that's only for posts, right?
