### ISSUE TITLE
[FEATURE] Add sound file: checking off To-Do List item

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2258]
Please add the attached sound for a user to hear when checking off an item on their to-do list both under Wellness and within the Favorites widget. (When initially creating this tool, many students mentioned the satisfaction they had when physically checking something off their list or scratching it off on paper.)

Can this be done in time for the December release? We are happy to provide additional file formats, if needed. Thank you!

[ToDoList-CheckOff.zip](https://github.com/rokwire/illinois-app/files/9333993/ToDoList-CheckOff.zip)

**Comment by vburgett** [comment]
Still an active request. Thank you!

**Comment by vburgett** [comment]
Is this update an option or should I close it? @pmarkhennessy

**Comment by TodorBachvarov** [comment]
@vburgett this was done in version 6.0.29.

**Comment by vburgett** [comment]
Thank you, @TodorBachvarov! Can the sound only play when the check mark is toggled on and _not_ when a to-do item is toggled off (or removing the checkmark)?

**Comment by mihail-varbanov** [comment]
@vburgett, this was done in version 6.0.31.

**Comment by vburgett** [comment]
Confirmed as completed. Thank you!
