### ISSUE TITLE
[BUG] QR Code for promoting groups does not work

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2259]
When you scan a QR code that is supposed to promote a group, it doesn't take you to the Illinois app, let alone the group.

![image](https://user-images.githubusercontent.com/69397705/184566327-74a1dd36-cd09-4ea8-bfbe-34edae773b1b.png)
![image](https://user-images.githubusercontent.com/69397705/184566393-dabda5d5-50de-4e46-8d5c-eec80fe7c1c4.png)

**To Reproduce**
1. Go into a group
2. Tap "Promote this group"
3. Save the QR code
4. Send it somewhere that you can scan it with a QR code reader on your phone
5. See that it doesn't take you to the Illinois app or the group

**Comment by pmarkhennessy** [comment]
We cannot recreate this, it is working for me

**Comment by nelshopp** [comment]
I am getting the same issue on my Pixel 3a.  
![Screenshot_20220815-144215](https://user-images.githubusercontent.com/91676531/184708203-3ef954b4-1f34-41b3-81e3-06bca76fe27e.png)

**Comment by pmarkhennessy** [comment]
![PXL_20220815_173436934](https://user-images.githubusercontent.com/5613085/184727406-429d9b92-f620-4945-9552-224c3b95bb65.jpg)

Does this work for you? @kpecknold @nelshopp

**Comment by vburgett** [comment]
That QR code worked for me in 4.1.19. @pmarkhennessy

**Comment by kpecknold** [comment]
Works now for me too in 4.1.19  @pmarkhennessy @vburgett

**Comment by nelshopp** [comment]
yep, that worked!
