### ISSUE TITLE
[BUG] iOS - Connect your NetID screen is not displayed 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#228]
**Describe the bug**
Connect your NetID screen is not displayed for the University student to verify his identity

**To Reproduce**
1. Install the Illinois app
2. Complete the onboarding steps
3. Select University student as a role
4. Proceed to the next screen

**Actual Result**
Connect your NetID screen is not displayed to verify student identity

**Expected behavior**
Connect your NetID screen should display to the user who chooses University student as his role

**Smartphone (please complete the following information):**
 - Version [e.g. 2.4.0]

**Comment by mihail-varbanov** [comment]
I was not able to recreate this, please see the attached video. I also looked carefully at all related source code. I do not see any tweak that could potentially cause this behavior (e.g. if some HTTP request fails).

Most probably the talent chooser service did not acknowledge the selected role, assumes that the user is not an employee or student and directs it to the phone login flow. However, as I said, I do not see how we could fall into this situation.

https://user-images.githubusercontent.com/5631487/107046763-ab9cc000-67cf-11eb-90c4-6eaafc357f90.mov

**Comment by isaac-galvan** [comment]
@mihail-varbanov  I was able to recreate what @Priyaravi8 is seeing. Here is a screen capture. This capture also shows the issue in #229 

https://user-images.githubusercontent.com/11352701/107067762-61064e00-67a5-11eb-9131-a852191671bc.MP4
