### ISSUE TITLE
[BUG] Seeing non-Gies courses under My Gies Canvas Courses

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2284]
Under Favorites and Academics, I see my actual fall Canvas class which is not a Gies course under My Gies Courses. 

 - Version 4.1.19

![Screenshot_20220815-153935.png](https://user-images.githubusercontent.com/1044905/184714949-8c486e86-9736-455e-8a5c-68204c0eb269.png)

**Comment by pmarkhennessy** [comment]
You are a member of Canvas Beta and that is what drives the Gies Courses. The users in that Group would only be Gies Canvas so this is not a bug.

**Comment by vburgett** [comment]
@pmarkhennessy I'm confirming that Jake as a student NOT in the Gies Group(s), cannot see the My Gies Canvas Courses drop down option in 4.1.19.
