### ISSUE TITLE
[BUG] My Courses and map

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2285]
Under Map > My Courses I see no map view. It's just blank with the navigation. I have one online class for the fall semester. 

I expect to see either a map with no class locations shown or no map and a message "You appear to not have any in-person courses at this time."

Version 4.1.19 

![Screenshot_20220815-153945.png](https://user-images.githubusercontent.com/1044905/184715613-f15632c9-676d-4f2c-bcb6-e7139cba3784.png)

**Comment by pmarkhennessy** [comment]
@vburgett The behaviour has changed in 4.1.19. Only Students will see My Courses. If you can still see this issue can you see if the map is zoomed in to some crazy level please.

**Comment by vburgett** [comment]
I am a student and this was my experience in 4.1.19. @pmarkhennessy

**Comment by kpecknold** [comment]
@pmarkhennessy Are you saying that someone has to identify themselves as a student in the "Who are you" in order to see MyCourses?

**Comment by vburgett** [comment]
Confirming that I am in 4.1.19, and I am not zoomed in under Map > My Courses. The screenshot I originally included is still accurate. 

(I am marked as a student under Who Are You, and I am truly registered for a Canvas course in the fall.)

**Comment by vburgett** [comment]
In 4.1.26, I am having the same experience as above with the same question (8/30 post from me). @pmarkhennessy @clint156  

"In version 4.1.20, I see a map with no locations indicated when I go to Map > My Courses. As a student with one online course, should I see My Courses under the Map dropdown or should students with only online courses have My Courses hidden from the Map?"

**Comment by clint156** [comment]
I’m not sure there’s a way around this. The course list isn’t loaded until the user selects the MyCourses option. The app has no way of knowing before hand who only has online courses vs. who does not until the course list is requested. I’m not the app developer, so I could be completely wrong, but I don’t think there is a programmatic way around this.

Clint Stearns
Systems Development Architect, Student Affairs Technology

[Illinois-Wordmark-Horizontal-Full-Color-RGB_185px]
