### ISSUE TITLE
[BUG] no image with courses

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2286]
Courses have an empty image spot. 

Version 4.1.19

Can this attached image be the default image for all classes in the app for this particular view?

![Screenshot_20220815-154011.png](https://user-images.githubusercontent.com/1044905/184715913-9ddec597-4f73-4f95-b4e5-751662ecb5b6.png)

![UofIlogo-DefaultILApp.jpg](https://user-images.githubusercontent.com/1044905/184716024-63e27f8d-a7a1-4788-a0c1-28799fa78c15.jpg)

**Comment by pmarkhennessy** [comment]
@vburgett Which view are you talking about, it is unclear to me?

**Comment by vburgett** [comment]
@pmarkhennessy this is the view I see in Academics > My Courses after tapping on the course I have that is listed.

**Comment by vburgett** [comment]
Confirming this is still an active request. V4.2.47
Thank you, @TodorBachvarov.

**Comment by TodorBachvarov** [comment]
Fixed in version 5.0.51

**Comment by vburgett** [comment]
Thank you, @TodorBachvarov! Confirmed as complete in 5.0.52.
