### ISSUE TITLE
[BUG]  Group post - link to pdf never loads

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2287]
In a group post, I tried to add  a link to a pdf:
https://housing.illinois.edu/-/media/fy22/fy23-move_in_map-champaign-web2.ashx?la=en&hash=A3AD99E73263D478E6F45193F5EEC63D0D77B6EA

Should this work?
Regular webpage link works. 
https://housing.illinois.edu/Tools/move-in-2022

See the post in the groups called "Groups Feedback"

**Comment by pmarkhennessy** [comment]
@kpecknold We have had to do much work for PDFs but I suspect there is no way of knowing what type of link this is.

**Comment by vburgett** [comment]
@kpecknold is it by chance the length of the url? Does a shorter pdf link work?
