### ISSUE TITLE
[BUG] Groups - approving a pending member throws error

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2289]
1. When I go into manage members, pending members should be the default if there is a pending member
2. When I filter to pending members and approve, I get a message "Failed to load members"
3. BUT, when I go out and back in, that person IS a member

**Comment by pmarkhennessy** [comment]
We will work on this for 4.2 version or the next 4.1 if we make a sub version of it @kpecknold.

**Comment by pmarkhennessy** [comment]
@dobromirdobrev If the last pending member is approved or rejected then close the panel to land on the main group panel or show all members

**Comment by dobromirdobrev** [comment]
We'll show pending users by default if such exist. 
If the last pending user is approved or rejected, we'll show all members. 

Fixed in version 4.1.30
