### ISSUE TITLE
[USABILITY] Users can't find login prompt. Suggest more verbose error messages.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2290]
**Describe the usability issue**

Sometimes when users are not signed in, they can't find a login prompt because their privacy level is set too low.

At privacy 3 or lower, the NetID login prompt is not visible. So when a users gets an error message like this:

![you need to be logged in](https://user-images.githubusercontent.com/66988329/184756203-625f5682-9e47-4204-9c4d-19d684d6fa23.jpeg)

They look around for a way to log in, but only find this:

![settings no NetID copy](https://user-images.githubusercontent.com/66988329/184756016-484a3c7f-02bb-4e37-83dd-ebfeaf9b445b.png)

**Solution**

Messages like these lines that I see in strings.en.json could be changed.

 ```
  "panel.browse.label.logged_out.illini_cash": "You need to be logged in to access Illini Cash.",
    "panel.browse.label.logged_out.meal_plan": "You need to be logged in to access University Housing Meal Plan.",
    "panel.browse.label.logged_out.bus_pass": "You need to be logged in to access MTD Bus Pass.",
    "panel.browse.label.logged_out.illini_id": "You need to be logged in to access Illini ID.",
    "panel.browse.label.logged_out.create_stadium_poll": "You need to be logged in to create a Stadium Poll.",
    "panel.browse.label.logged_out.inbox": "You need to be logged in to access Notifications.",

```

... changed to provide more precise information about how to log in. Like this, for example:
 ```
  "panel.browse.label.logged_out.illini_cash": "You need to be logged in with your NetID to access Illini Cash. Set your privacy level to 4 or 5 in your Profile. Then find the sign-in prompt under Settings.",
```
etc.

I am not sure about the one for "create a Stadium Poll" - I have never seen that message used.

And I don't know if you are allowed to have a string that long.

**Comment by dobromirdobrev** [comment]
Done in version 4.1.20 and 4.2.0.

**Comment by joegrohens** [comment]
I am using 4.1.20, but I don't see any additional content added to the "You need to be logged in..." messages.

Also, the "you need to be logged in" message for "Meal Plan" is giving the one for "Illini Cash".

**Comment by mihail-varbanov** [comment]
@dobromirdobrev was wrong, this had been completed in 4.1.21 and 4.2.0.

**Comment by joegrohens** [comment]
confirmed fixed
