### ISSUE TITLE
[FEATURE]  Please update link for Mobile Privacy Notice

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#230]
The Mobile Privacy Notice for Illinois app has been revised, and is now hosted in a new web location.

Please replace the URL that is linked at Browse > Privacy Center > Privacy Statement with this new URL: 

> https://go.illinois.edu/illinois-app-privacy

Note: This new URL is a permanent shortcut that can be edited outside the app, in the event that the Privacy Notice web page is relocated again in future.

@isaac-galvan 

![IMG_0534](https://user-images.githubusercontent.com/66988329/106811899-9a6b7c00-6634-11eb-9f76-a94637379d93.PNG)

**Comment by isaac-galvan** [comment]
I set a 301 redirect on the current page to https://go.illinois.edu/illinois-app-privacy.
The app config should still be updated to point directly to the new url.

**Comment by mihail-varbanov** [comment]
A new 2.4 app config is created. It's 'privacy_policy_url' points to "https://go.illinois.edu/illinois-app-privacy".

**Comment by joegrohens** [comment]
Confirmed resolved.
