### ISSUE TITLE
[BUG] MyGroups doesn't display member count correctly in 4.1.19

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2309]
The display of group cards in the horizontal scroll view in "My Groups" shows 0 members for all groups. Tapping into the group shows correctly, also viewing the groups in the "All groups" view shows correctly.

**Comment by dobromirdobrev** [comment]
Hi @kpecknold ,
This is a backend issue. It will be fixed later today. No need from a new app version. Please test when you have a chance and let us know. cc @pmarkhennessy @mdryankov

**Comment by kpecknold** [comment]
looks good now
