### ISSUE TITLE
[BUG] Course listing am/pm problem with courses at 12:00 pm

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2310]
**Describe the bug**

In Academics > My Courses, courses that meet at 12:00 pm, or 12:30 pm, are listed as meeting at 12:00 am or 12:30 am.

See example in screenshot.

![6 - tapped on the 3 unmapped courses copy](https://user-images.githubusercontent.com/66988329/185832432-84702b4f-3671-4f3b-aa2d-df3efbb48773.png)

Should I be submitting bugs like this somewhere else, such as in  building block repo?

**Comment by mihail-varbanov** [comment]
This is fixed in 4.1.22 and 4.2.1 (both are upcoming releases).

**Comment by joegrohens** [comment]
confirmed fixed
