### ISSUE TITLE
[BUG] My Courses Widget does not show (online?) course

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2312]
My online course correctly shows up under Academics > My Courses but the My Course Favorite Widget incorrectly shows me that I have no Fall 2022 courses. This one course is an online course. 

iPhone
Version 4.1.20

![image](https://user-images.githubusercontent.com/1044905/185977147-3600a417-c6e1-42d0-8436-ecf0d1b4106c.png)

![image](https://user-images.githubusercontent.com/1044905/185977162-6b2a73b9-a26e-4436-9764-e27f3847eb3f.png)

**Comment by mihail-varbanov** [comment]
@vburgett, can you recreate this permanently, or it happened just once and accidentally? If yes, what is the recreation scenario starting from application launch? Is there a term that you have no registered courses for it?

**Comment by vburgett** [comment]
It doesn't seem to be an issue any longer. Thank you!
