### ISSUE TITLE
[BUG] Campus Guide: mailto: and tel: urls don't open

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2315]
**Describe the bug**
In Campus Guide, the contacts and locations section of a guide article includes URLs to phone numbers and email addresses.

Tapping on these phone numbers and email addresses doesn't open a mail or phone client.

We can't remember exactly, but I think these worked in 3.x.

**To Reproduce**
Campus Guide > Academic Support > Books > Illini Union Bookstore

![iub phone and email](https://user-images.githubusercontent.com/66988329/186245704-742f2feb-eccb-4244-973b-3672e0156a6f.jpeg)

**Comment by nelshopp** [comment]
More info:
This works for me on my work phone (Google Pixel 3a).  

I do get the same problem as Joe on my older Samsung Galaxy S7.  

Both are updated to the latest version. 

Tom

**Comment by joegrohens** [comment]
Our tests were all on iphones.

**Comment by mihail-varbanov** [comment]
This is fixed in 4.1.22 and 4.2.1 (both are upcoming releases).

**Comment by joegrohens** [comment]
confirmed fixed
