### ISSUE TITLE
When not logged in with NetID, cannot add illini cash using my UIN [BUG] 

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2324]
If I am logged into the app using my phone number or email address, I should be able to add Illini Cash to a UIN. Use Case- a parent wanting to add Illini Cash to their child's UIN. After logging in with my gmail address, I can enter the information for adding Illini cash, but get a user ineligible message when I submit the request to add.

**To Reproduce**
1. Log into the app with your phone number or email address
2. On the favorites screen, in the wallet scroll to Illini Cash and click the "+" sign
3. Enter a valid UIN, name, email address, amount and CC information
4. Agree to terms and submit the request
5. Error message "The recipient is not eligible to buy Illini Cash" is displayed.

**Expected behavior**
If the UIN and name are valid and all criteria in the dining systems are met, the purchase should be allowed to proceed. I verified my UIN as eligible by logging into the app with my NetID on a different phone and adding Illini Cash with my UIN - 657427043

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto G7
 - OS: Android 11
 - Browser NA
 - Version App build 4.1.19

**Additional context**

**Comment by clint156** [comment]
In the app, when adding Illini Cash, I don't see any calls to the ICEligible endpoint in the Housing APIs. We rolled that information into the StudentSummary endpoint looks like it gets called on app launch, but StudentSummary requires a valid campus access token. ICEligible does not require that token. I don't know if that helps or not, but thought I should include it

**Comment by mihail-varbanov** [comment]
Thanks for your [hint](https://github.com/rokwire/illinois-app/issues/2324#issuecomment-1228911576), @clint156. This was the exact the problem. I fixed this in version 4.1.25.

**Comment by mihail-varbanov** [comment]
@clint156, I am assigning this issue back to you. You can test it to make sure the problem is fixed or straightly close it, if you like.

**Comment by mihail-varbanov** [comment]
Hi @clint156, JP posts occasionally intermediate builds in "general" channel of Rokwire's Slack organization. My feeling is that today he will post the 4.1.26 build. CC @pmarkhennessy.

**Comment by clint156** [comment]
Verified fixed in 4.1.26
