### ISSUE TITLE
[BUG] v4.1.30 Unable to save to do list items. 

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#2326]
**Describe the bug**
Upon creating a new To Do list item, I get a message stating it saved successfully but then when I'm redirected to the to do list after, there are 0 items listed. Please advise. 

**To Reproduce**
1. Go to '.Wellness..'
2. Using dropdown menu, select  '.To Do List'
3. Select ".Add Item'
4. Give item a name
5. Select a category 'Light blue' (this was to retest 2040)
6. Then scroll down and select 'Save'

**Expected behavior**
User gets confirmation message stating "To-Do item saved successfully." Then user is redirected to To-Do list screen where new item is listed with a checkmark and an edit icon. 

**Actual behavior**
User gets confirmation message stating "To-Do item saved successfully." Then user is redirected to To-Do list screen where there are no items listed with a checkmark and an edit icon. 

**Screenshots**
Video attached. 

https://user-images.githubusercontent.com/82892873/187454243-58d78108-d10f-451b-92a0-0acdd87aa989.mp4

**Smartphone (please complete the following information):**
iPhone XR- iOS 14.6, Pixel 4a- Android 12

**Additional context**

**Comment by mihail-varbanov** [comment]
@acovher2, I was unable to recreate this problem. I tested it on 4.1.25 but I do not think we have done anything there since 4.1.19. Can you check again please if you can recreate this problem?

**Comment by acovher2** [comment]
I retested with another account and could not reproduce. I dont understand why my acct would have this issue only. 
??

**Comment by acovher2** [comment]
Verified as fixed in 4.2.34
