### ISSUE TITLE
[BUG] Event card within a group is not clickable at all places

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#2328]
**Describe the bug**
It looks like the event card within a group is not clickable in all places. Only the title seems to be clickable.

**To Reproduce**
1. Go to a group with at least one event.
2. Click on the date or the image within the event card.
3. See that the event card detailed view is not showing up.

**Expected behavior**
I think the event card within a group needs to be clickable at all places, like how it is in the Suggested Events screen.

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Version: 4.1.19

**Additional context**

CC: @vburgett, @Priyaravi8

**Comment by mihail-varbanov** [comment]
This is fixed in version 4.1.25.

**Comment by sandeep-ps** [comment]
Thanks, Misho and Priya.
I can check this in the next version whenever that becomes available and close this issue after that.

@Priyaravi8, please let me know if you would like this to be assigned to you for verification.

**Comment by sandeep-ps** [comment]
@mihail-varbanov, I tested this change in version 4.1.36. I see that now almost all regions of the event card within a group are clickable, and clicking on the photo does not seem to change anything. In the Suggested Events / My Events section, when I click on a photo on an event card, it is now enlarged. Would it be better to have uniform behavior (if enlarging the photo is preferred) on event cards, whether it appears within a group or in the Events talent? Thanks.

**Comment by sandeep-ps** [comment]
Retested this on version 4.2.36. I can confirm that the event is clickable in all places, and clicking on the photo shows the image popup. I will close this issue. Thanks.
