### ISSUE TITLE
[BUG] Created group does not show up immediately

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#2329]
**Describe the bug**
A created group does not immediately appear on the "My Groups" screen. I saw this behavior when testing creating a group in the TEST instance. This is was using a test user account, and it was the test user's first group.

**To Reproduce**
1. Click on create group icon, enter details, and press submit button
2. See that created group does not appear immediately in the "My Groups" screen
3. It shows up after refreshing the screen with a pull-down gesture

**Expected behavior**
The group should be displayed soon after creating it. 

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Version: 4.1.19

**Additional context**

CC:  @Priyaravi8

**Comment by Priyaravi8** [comment]
@sandeep-ps  - I am able to reproduce this issue.

**Comment by sandeep-ps** [comment]
Thanks, @dobromirdobrev. I tested this with version 4.1.36 and I can see the group right after creating it.

@Priyaravi8, I will close this issue, but please feel to reopen it if needed. Thanks.
