### ISSUE TITLE
[BUG] MyMcKinley login not possible with an embedded web page

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2333]
The same issue for the campus guide #2147 exists with Wellness Resources > MyMcKinley Patient Health Portal. Please update the link to open outside of the Illinois app. 

1. Go to Wellness Resources > MyMcKinley Patient Health Portal
2. Tap logo, enter login and password
3. Go to 2FA duo app
4. Return to Illinois app to be prompted to start at step two all over again.  

 - iPhone
 - Version 4.1.20

**Comment by mihail-varbanov** [comment]
Fixed in 4.1.24. All links from Wellness resources are launched in an external browser, similarly to what we do in Campus Guide pages.

**Comment by vburgett** [comment]
Confirming that wellness resources with an external link are now launching in an external browser in 4.1.26. Thank you! Cc: @Priyaravi8
