### ISSUE TITLE
[FEATURE] Allow group admins to add new members

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#2337]
**Re: University Monday 2022/08/29** / 2022/09/01

2.2 In Groups/Member listings, for Admins only, can you put a "Add Member+" link style button in the title or header bar that shows a popup with label UIN, edit control and OK/Cancel buttons. Call the API in Groups BB we use to add members for attendance type groups.

**Comment by dobromirdobrev** [comment]
Done in version 4.1.24

**Comment by pmarkhennessy** [comment]
@kpecknold This is a partial solution for now. The 4.1.x release is not a major feature release. This is the start of something you asked for a while back. In 4.2 we can extend this and also give an option to add or invite. Also, this is for Admin's only. I am aware of what your latest request was for.

**Comment by kpecknold** [comment]
@pmarkhennessy If it adds someone to a group without their permission/action, I don't think we should implement it this way. Any student can become an admin of a group just by creating it. Then they could add anyone to their group - their professor, the Chancellor, someone they are harrassing. Each person should be in control of what groups they join, unless it is a university-managed group.  In my list of suggestions, the copy link on the promote page, would be an easy way to implement this while preserving each user's rights/agency.
