### ISSUE TITLE
[FEATURE] Add reactions to group posts

### ISSUE THREAD

**Issue by shurwit** [rokwire/illinois-app#2354]
**Is your feature request related to a problem? Please describe.**
Currently if many people want to acknowledge a post, they will have to send a reply which will take up a lot of space and create visual noise for a single emoji.

**Describe the solution you'd like**
We should add several standard reaction emojis below each post that a user can tap to send that reaction. Each reaction should have a count of users that sent that reaction. If the current user has sent the reaction, they should see the reaction emoji highlighted. The user may send multiple reactions. We should also allow display the names of the users that sent each reaction on long press.

**Comment by kpecknold** [comment]
@shurwit Hi Stephen, I made a similar request recently in an email, and included the assets and designs from @vburgett . I will forward to you so you know what we have asked for. - Kathryn Courtney

**Comment by kpecknold** [comment]
@shurwit What email address is best for you?
