### ISSUE TITLE
[USABILITY] Remove External Link Icon in Academics Dropdown Menu (Due Date Catalog)

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2356]
Please remove the external link icon from the Academics dropdown menu next to Due Date Catalog. (This link goes to in-app content before going to an external link.)

Version 4.1.2

![image](https://user-images.githubusercontent.com/1044905/188774247-3aa25d04-f8b1-45ee-aec7-db15200d6f70.jpeg)

**Comment by mihail-varbanov** [comment]
Fixed in version 4.1.27

**Comment by vburgett** [comment]
Done in 4.1.31—thank you!
