### ISSUE TITLE
[BUG] Wellness Resource - External link crashing the app

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2366]
**Describe the bug**
On the Wellness resource screen, the external link is crashing the app

**To Reproduce**
1. Install the Illinois app
2. Navigate to Wellness resource and tap on any of the external links - "Campus Service Units"

**Actual Result**
It takes time to load the website and it doesn't open in a separate window.  Also when the user minimizes the app, it's crashing.

NOTE - I am not able to reproduce this issue all the time. 

**Expected behavior**
App should work without crashing.

**Screenshots**

https://user-images.githubusercontent.com/26231179/188957947-7c605c50-ad9a-4553-8c39-1928addbc545.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.1.19]

**Comment by mihail-varbanov** [comment]
We changed in version 4.1.24 our links handling in Wellness resources. Now they open in an External Browser. Please retest this in some recent 4.1 build (4.1.24+).

**Comment by vburgett** [comment]
@Priyaravi8 see ticket #2333.

**Comment by Priyaravi8** [comment]
This issue is fixed in the version 4.1.26
