### ISSUE TITLE
[USABILITY] Text update: Promote this group 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2372]
Go to a group you serve as an admin, choose "Promote this group."

With the new share button, please make the following text edits for clarity. 

Change the paragraph at the top of the screen to:
Invite others to join this group by sharing a link or the QR code after saving it to your photo library. 

Update button text to "Save QR Code" and "Share Link"

Android app version 4.1.26

![Screenshot_20220908-110559~2.png](https://user-images.githubusercontent.com/1044905/189172455-4254cea1-338c-401e-8eb2-bde9d2bc991c.png)

**Comment by dobromirdobrev** [comment]
Done in version 4.1.28

**Comment by vburgett** [comment]
Complete in 4.1.31—thank you!
