### ISSUE TITLE
[BUG]: Customize > Current Favorites > Incorrect Compound Widget "Partial Selection" Star Icon   

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2373]
1. With the Wallet widget selected as a Favorite, deselect "Meal Plan" from the Favorites screen with at least one other Wallet item selected.
2. Go to Customize, and see how "Wallet" is a white star outlined in grey instead of a solid grey star under "Current Favorites."

Following our current favoriting logic, the Wallet should be a solid grey star under "Current Favorites" in "customize." Any other Favorites compound widget (like the Wallet) that has only partial items within the widget selected should also show up as a solid grey star under "Current Favorites" in "customize." 

Version 4.1.26

Our current favoriting logic as a reminder:
**orange star:** favorite selected by user
**white star outlined in grey:** favorite deselected by user
**solid grey star:** a compound widget with at least one item favorited and at least one item unfavorited

![Screenshot_20220908-115510](https://user-images.githubusercontent.com/1044905/189183758-5941c4b9-ff7c-40ed-8771-79e9206d2b26.png)
![Screenshot_20220908-115545](https://user-images.githubusercontent.com/1044905/189183765-347ee689-4e14-4d09-bfc5-de1024d04d48.png)

**Comment by dobromirdobrev** [comment]
Fixed in version 4.1.30

**Comment by vburgett** [comment]
Confirming, fixed.
