### ISSUE TITLE
[FEATURE] Display illegible Illini Cash status

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#2378]
Re: University Monday 2022/09/05 / 2022-09-08

2.1.2 There is an issue Clint reported: “A user cannot see any data in the Dining feature of the app. We cannot find a cause for this problem so I thought I would run it by you.  See attached screenshot. Just to add some more detail, I can see the call to student summary for this student, and all of the calls for transaction history. What never seems to happen is the call to the balances end point.”

![dining plan](https://user-images.githubusercontent.com/5631487/189295925-f88e9b23-033a-41b8-bb5b-4124fd242b46.png)

**Comment by kpecknold** [comment]
@mihail-varbanov   What is the message that gets displayed if a user is not eligible?  I can't see it because I'm eligible. Thank you!

**Comment by mihail-varbanov** [comment]
@kpecknold, I am sorry for the late response, I was OOO previous week. These are the messages displayed if the user is not eligible:

**Illegible**
You are not eligibile for Illini Cash, or
You are not eligibile for Meal Plan

https://github.com/rokwire/illinois-app/blob/develop/assets/strings.en.json#L1008
https://github.com/rokwire/illinois-app/blob/develop/assets/strings.en.json#L1009

https://github.com/rokwire/illinois-app/blob/develop/assets/strings.en.json#L1087
https://github.com/rokwire/illinois-app/blob/develop/assets/strings.en.json#L1088

https://github.com/rokwire/illinois-app/blob/develop/assets/strings.en.json#L2662
https://github.com/rokwire/illinois-app/blob/develop/assets/strings.en.json#L2663

https://github.com/rokwire/illinois-app/blob/develop/assets/strings.en.json#L2669
https://github.com/rokwire/illinois-app/blob/develop/assets/strings.en.json#L2670

**Comment by joegrohens** [comment]
The spelling of illegible should be changed to ineligible.

_illeligible_ means writing that cannot be read 
_ineligible_ means not eligible

**Comment by mihail-varbanov** [comment]
Thanks @joegrohens. I fixed this in the application codebase but I am afraid the upcoming 4.1.34 release will still have it.
