### ISSUE TITLE
[BUG] Updating an event does not reflect in the group immediately

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#2383]
**Describe the bug**
Updating a group does not get reflected within the group immediately 

**To Reproduce**
1. Create a group or go to a group that you are an admin of
2. Create a new event or choose an existing event
3. Update the event by changing one or more fields (title, description, etc.), and tap submit
4. In the event detail view that gets immediately displayed, the changes are visible. 
5. Go back to the Group's main screen where the event is listed
6. See that the event is displaying the old data within the group even though there was no error during the update

**Expected behavior**
The updated event data needs to be displayed to the admin as a confirmation of the successful update.

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android
 - Version 4.1.19

**Additional context**
I do not know this for sure, but this may be caused by a cache in the Events BB endpoint used by the app to display the event in the group. A cache is enabled in certain Events BB GET endpoints to avoid database calls for the same request that happens within a 10 min window. So, this may eventually be a backend fix, but I'm creating this issue to start the conversation. Thanks.

CC: @bingzhang

**Comment by sandeep-ps** [comment]
Could someone share the endpoint called by the app to display an event soon after updating it? Thanks.

**Comment by sandeep-ps** [comment]
Hi, @dobromirdobrev, I have updated the steps to repeat to clarify what I was observing. It looks like I might have been describing the event cards that appear on the Group's home screen after an event is updated. Sorry for the missing detail earlier. Please try the updated steps when you get a chance. I can upload some screenshots later if needed.

**Comment by dobromirdobrev** [comment]
Hi @sandeep-ps ,
I'm still unable to reproduce this problem. Here is a video of what I do. All works as expected to me. Please let me know if this is not the scenario.

https://drive.google.com/file/d/1VraT9jZUyxxceDrCBAdr0L2biz6YwJVx/view?usp=share_link

**Comment by sandeep-ps** [comment]
Hi, Dobromir, Thanks for the video. I will test this again with the latest version in Slack and get back.

**Comment by sandeep-ps** [comment]
Hi, @dobromirdobrev, 

I tried the steps listed in the description (version 4.2.36), and now, it looks like the event details are also getting updated on the main group screen. So possibly, this may have only happened in the previous version. I'm almost sure as I had seen this behavior in the production version and that's how I could write down the steps to repeat. I will close this issue then. Thanks for checking.
