### ISSUE TITLE
[BUG] Group member lists are visible to all members 

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2384]
**Describe the bug**
 
The list of members is visible to all members. The member list should be seen only by admins.

![squirrel group cover](https://user-images.githubusercontent.com/66988329/189538931-f5c0a270-8a0a-47ca-96fa-ccf501dfff76.png)

![squirrel members](https://user-images.githubusercontent.com/66988329/189538932-6042e8ec-f8b8-43b9-8957-9b7c84fdde48.png)

This can be seen in both v 4.1.20 and v 4.1.26, on Android and iPhone.

**Comment by joegrohens** [comment]
Note: This bug does not apply to managed lists.

**Comment by pmarkhennessy** [comment]
@joegrohens This is not a bug. Member lists have been viewable by members and admins for a long time.
