### ISSUE TITLE
[BUG] Athletics - All Staff tile link is displayed along with Coaching Staff tile list

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#239]
**Describe the bug**
In the Athletics screen, the "All Staff" tile link is displayed along with the "Coaching Staff" tile list

**To Reproduce**
1. Install the Illinois app
2. Complete onboarding steps and verify the role as a University student
3. Tap on Athletics on the Home screen
4. On the Athletics screen, scroll down to "All Illinois sports" section
5. Tap on any of the sports listed in it.
6. Team screen is displayed. Scroll down to the section "Coaching Staff".

Actual Result
"All Staff" tile link is displayed along with the "Coaching Staff" tile list

**Expected behavior**
Remove the "All Staff" tile link from the "Coaching Staff" tile list. As the button "All Staff" link is already available  below the section "Coaching Staff" 

**Screenshots**
![coach 1](https://user-images.githubusercontent.com/26231179/114212737-c6062d80-9927-11eb-8207-fcc8b84a374d.png)
![Coach](https://user-images.githubusercontent.com/26231179/114212748-c999b480-9927-11eb-8161-84c19ab15ff2.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]

 - Version [e.g. 2.4.5]

**Comment by mdryankov** [comment]
The both tile buttons for All rosters & All staff have been removed - to keep consistency. 
Also the section will be hidden of there are no records at all.
