### ISSUE TITLE
[BUG] Wellness -  PDF links is not loading in web view

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#240]
**Describe the bug**
Wellness - Financial - Your legal health PDF link is not loading in web view. The blank white screen is displayed.

**To Reproduce**
1. Install the Illinois app
2. Complete onboarding steps.
3. Proceed to the Wellness screen.  
4. Tap on the Financial link tile. On the Financial wellness screen, tap on the "Your Lega Health" link

**Actual result**
The blank white screen is displayed as the "Your Lega Health" is PDF file and it's not opening in Web view

**Expected behavior**
The "Your Lega Health" is a PDF file and it should display in Web view

**Screenshots**
![health](https://user-images.githubusercontent.com/26231179/114214517-01a1f700-992a-11eb-887f-b43d65086b95.png)
![pdf](https://user-images.githubusercontent.com/26231179/114214520-036bba80-992a-11eb-86b9-e92cd0750709.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.4.5]

**Additional context**
**It works in iOS**

**Comment by mdryankov** [comment]
Fixed. PDFs must be opened externally
