### ISSUE TITLE
[BUG] To Do List > Updated Category Color does not update existing task color in that category

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2401]
When you have a to-do task already assigned to an existing category, the color of that task does not update when the category color is updated. The new category color should also update the color of any tasks assigned to that category. 

**To Reproduce**
1. Go to Wellness, To-Do List
2. Add a category with a color assigned to it
3. Create a task and assign to the category from step 2
4. Go to Category, Manage Categories
5. Tap the edit icon next to the category created in step 2
6. Change the category color
7. See how your task in step 3 does not update to the new category for when it should

Screen capture: 
https://drive.google.com/file/d/1WEupQyMwDwNsVqtHcb6YlYZ06aE0mmo8/view?usp=drivesdk

Android Pixel 6
App v4.1.31

**Comment by dobromirdobrev** [comment]
Fixed in version 4.1.33
