### ISSUE TITLE
[BUG] One Group Request = Multiple Admin Instances of that One Member

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2406]
In version 4.1.2 on an iPhone 13 iOS 15.7, when I get **one** member request as the admin for the public group "Gus," I get 10 requests from that same person under pending members. 

I approve one instance, and it automatically approves all 10 instances of that single member. 

The Groups total membership number is accurate with it totaling plus one after the approval. 

![image](https://user-images.githubusercontent.com/1044905/190922046-0a706238-fc99-4a73-aac9-87a10c2a4844.jpeg)

**Comment by vburgett** [comment]
This isn't an issue in 4.1.31 on a Pixel 6 Android.

**Comment by dobromirdobrev** [comment]
Hi @vburgett , 
This seems to be the same as #2413 . I left a [comment](https://github.com/rokwire/illinois-app/issues/2413#issuecomment-1269807759).
