### ISSUE TITLE
[USABILITY] Dropdown menu needs extending in Groups Manage Members

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2407]
Under a Group you administer, see the Admin and Pending dropdown menus under Manage Members in version 4.1.31 on an Android Pixel 6. The menus are cut off and need to be extended on the screen. 

![Screenshot_20220918-224042.png](https://user-images.githubusercontent.com/1044905/190946581-292a2c25-58b8-4e04-a33b-0a50b094cfb8.png)

![Screenshot_20220918-224017.png](https://user-images.githubusercontent.com/1044905/190946599-314b3c64-2099-4305-9ed5-e8a23d5ae92d.png)

**Comment by pmarkhennessy** [comment]
@vburgett Yes have also seen this and will get it resolved in not too far future...4.2...

**Comment by vburgett** [comment]
In 4.1.36, this is fixed for all Groups "Members" dropdown menus except under Members > Admin (for a Group you are the admin in). The background still needs to be extended when expanding the menu under Admin. @pmarkhennessy

**Comment by vburgett** [comment]
All dropdown menus under Manage Members in Groups need extending in version 4.2.15 on a Google Pixel 6.

**Comment by vburgett** [comment]
The background still needs extending in a Group you administrate under all dropdown sections: 
Manage Members > Rejected
Manage Members > All
Manage Members > Admin
Manage Members > Pending
Manage Members > Member
Manage Members > Rejected

V4.2.47
![Screenshot_20221222-135236](https://user-images.githubusercontent.com/1044905/209215512-b605ae50-f223-49df-9012-7709da6c1dca.png)

**Comment by TodorBachvarov** [comment]
Fixed in version 5.0

**Comment by vburgett** [comment]
Complete in 4.2.52—thank you!
