### ISSUE TITLE
[BUG] Emotional Wellness -  Kognito At Risk linked to incorrect URL

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#241]
**Describe the bug**
"Kognito At Risk" linked to incorrect URL in Emotional Wellness results "Page not Found" whereas the same "Kognito At Risk" link in the Wellness screen linked correctly and displays the correct result.

**To Reproduce**
1. Install the Illinois app
2. Complete the onboarding screen
3. Proceed to the Wellness screen and tap on to Emotional tile.
4. On the Emotional Wellness screen, scroll down to Counseling Center and tap on **Kognito At Risk (counseling Center)**

**Actual Result**
"Kognito At Risk" linked to incorrect URL in Emotional Wellness results "Page not Found"

Note - Whereas the **same "Kognito At Risk"** displayed under the section **Interactive activities in the Wellness** screen linked correctly and displays the correct result.

**Expected behavior**
"Kognito At Risk" needs to be linked to the correct URL in Emotional Wellness.

**Screenshots**
![Kognito](https://user-images.githubusercontent.com/26231179/114225386-df16da80-9937-11eb-856a-85cf7d20538c.png)
![Kognito1](https://user-images.githubusercontent.com/26231179/114225400-e211cb00-9937-11eb-9e7c-49211781b5e8.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 2.4.5]

**Additional context**

**Comment by pmarkhennessy** [comment]
@Priyaravi8 These needs to be fixed in the page source not the app
