### ISSUE TITLE
[BUG] Groups uses user legal name, not preferred name

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2411]
**Describe the bug**

Groups displays users' legal name rather than their preferred name.

In the screenshot below, my legal name "Joseph" is used. My preferred name is set in Banner as "Joe".

![groups legal name joe joseph sm](https://user-images.githubusercontent.com/66988329/191513467-6e88fa1a-0b41-4daf-a2db-9c0f08f46b44.jpeg)

**Expected behavior**

Groups should pull the same first name that we use on the Favorites screen.

**Comment**
The use of legal name can have significant negative social impact on some users -- trans users, for example. It can provoke derision or attacks from others. It would definitely interfere with users ability to use social functions of the app.

We would like to see this issue given high priority.

@RokBill @vburgett @kpecknold

**Comment by pmarkhennessy** [comment]
@joegrohens We are testing the fix in Dev...

**Comment by joegrohens** [comment]
I can confirm that in v4.1.36 this issue is fixed. Groups shows the preferred first name of members.

I note that previously published posts and replies still show the author's legal name. 

Closing this issue.
