### ISSUE TITLE
[BUG] Groups - MTD Buss Pass Group should be hidden from members

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2417]
MTD Buss Pass Group should be hidden from members

**Comment by pmarkhennessy** [comment]
@kpecknold This should be fixed in 4.1.36

**Comment by pmarkhennessy** [comment]
@TodorBachvarov Please make sure if a Group is Authman/University Managed and Hidden that it only appears for Admins in My Groups
