### ISSUE TITLE
[BUG] Onboarding location screen has a button labeled as 'Share my location' instead of 'Continue'

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#242]
**Describe the bug**
The onboarding location screen has a button labeled as 'Share my location' instead of 'Continue'

**To Reproduce**
1. Install the Illinois app
2. Proceed further until user reach Share your location screen

**Actual Result**
Share your location screen has a button labeled as 'Share my location' instead of 'Continue'

**Expected behavior**
Replace the label 'Share my location' to 'Continue'

**Screenshots**
![location](https://user-images.githubusercontent.com/26231179/114231523-2f923600-9940-11eb-8d42-588d8242d020.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]

**Additional context**

**Comment by mdryankov** [comment]
@Priyaravi8 this is wrong and misleading and it will bring us to potential rejection from the app stores
In fact the "Share my location" is requesting the user to share his/her location and then continues. It doesn't functions just as continue button. I believe the current names are appropriate according the use case and they represent clearly the two possible outcomes
