### ISSUE TITLE
[BUG] Searching in Groups is now case sensitive 

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2420]
**Describe the bug**
Some time back (V3.x ?) it was decided to make search case insensitive. In 4.1.x somewhere the search has started requiring your search string to match the exact capitalization of a group name.

**To Reproduce**

1. Go to Browse > All Groups
2. Search for "MTD bus pass". Return will be null. 
3. Search for "MTD Bus Pass". The group will be found.

v 4.1.34 prod

**Comment by pmarkhennessy** [comment]
@TodorBachvarov This group may be hidden now so search will not work on this, but you can make sure in Dev with 4.2 that search for groups is not case sensitive. 

Hidden groups are not searchable, private groups must be the exact group name but not case sensitive and public groups can be partial search and not case sensitive.

**Comment by joegrohens** [comment]
It works as Todor described.
