### ISSUE TITLE
[FEATURE] Rename “Campus Guide Highlights” to “Campus Safety Resources”

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#2488]
**University Monday 2022/10/31** / 2022-10-31

2.1  For the existing UIUC 4.1.x in the stores, can you rename “Campus Guide Highlights” to “Campus Safety Resources”. I presume you can place a new strings.json

**Comment by joegrohens** [comment]
This change is confirmed on both iOS and Android?
