### ISSUE TITLE
[FEATURE]  Name change -  "Cafe Credits" to "Dining Dollars"

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#250]
University Housing has changed the name of Cafe Credits to Dining Dollars. Everywhere the term Cafe Credits appears in the app, please change to Dining Dollars. Clint will also make any necessary changes in the API.

**Comment by mdryankov** [comment]
@kpecknold @pmarkhennessy, 
I have updated the text. However we need appropriate translations for Spanish & Chinese.
