### ISSUE TITLE
[BUG] MTD Bus Pass Group needs to be hidden  from members

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2505]
The MTD Bus Pass group is still showing up for members under My Groups. The group needs to be hidden from members. (With that many members, the odds are high that a student who has requested to make their name confidential via FERPA is public via this list.)
Version 4.1.36 
iPhone 13 iOS 16.0.2

![image](https://user-images.githubusercontent.com/1044905/200002702-d4bed9c0-e9a4-4bfb-af25-f23db47d12ff.png)
![image](https://user-images.githubusercontent.com/1044905/200002724-feb5ba41-1a55-4b56-b266-0390efa827ea.png)

**Comment by pmarkhennessy** [comment]
@vburgett done, not a bug. I changed the group to hidden. Please test and close.

**Comment by vburgett** [comment]
Fixed. Thank you!
