### ISSUE TITLE
[BUG] Illini Cash isn't displaying unless logged in

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#252]
The ability to see the Illini Cash tile in order to add Illini Cash should be visible to all audiences and should not require the user to be authenticated. This is because parents and families add Illini Cash for their students. All they need to know is the UIN of the person they are adding for.

**To Reproduce**
Disconnect your NetID
Go to the home screen, see the Illini Cash tile is missing.

Google Pixel2, Android,  - Illinois app version 2.4.4

**Comment by pmarkhennessy** [comment]
@mdryankov All you need to do is make sure Illini Cash is available regardless of what type the user has selected in Onboarding or Settings

@kpecknold

**Comment by mdryankov** [comment]
@kpecknold @pmarkhennessy I have added "Add Illini Cash" button in the Browser tab. It's always visible (logged/not logged user). I believe this is the best way how to handle this use case whiteout  impacting the current UI and Talent chooser. 

Also please consider the default Spanish & Chinese translations.

**Comment by kpecknold** [comment]
@pmarkhennessy @TodorBachvarov This is still a problem. The Illini Cash tile normally appears on the home screen in the Campus Resources section, and should appear there with or without authentication for Students, Employees, Parents. This link allows them to add Illini Cash, which is something that non-students do frequently. They just have to know their student's UIN to be able to add to the account.

**Comment by mdryankov** [comment]
@kpecknold @pmarkhennessy  This is fixed within the talent chooser & local resource and Dev talent chooser. 
Production is not fixed yet and I'm awaiting your confirmation shall I fix it there

**Comment by pmarkhennessy** [comment]
@mdryankov Please fix Prod for 2.5 and upcoming 2.6

**Comment by mdryankov** [comment]
@pmarkhennessy it's done. Please retest and give feedback

**Comment by kpecknold** [comment]
Resolved
