### ISSUE TITLE
[BUG] Map not appearing when location is turned off

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#254]
**Describe the bug**
When access to my location is disabled, and I select an address from an event, I do not see a map of the location. 

**To Reproduce**
1. Turn off location sharing
2. Open app
2. Go to an event detail page 
2. Click on the address for the event

**Expected behavior**

**Video**
https://user-images.githubusercontent.com/24440324/119723505-22b79c00-be33-11eb-81ba-316031f9eadc.MP4

**Smartphone:**
 - Device: iphone XS
 - OS: iOS 14.4.1
 - Version 2.4.4

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design.
