### ISSUE TITLE
[BUG] Groups - fix acknowledge and reply icons on posts

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2560]
The thumbs up icon and reply icon are not active in posts

**To Reproduce**
1. Go to a group
2. Add a post or open an existing one
3. Note that the thumbs up and reply icons are not active

Has been tested on iOS and Android versions in 4.2.18+, still a problem in 4.2.23

**Comment by TodorBachvarov** [comment]
The Thumbs up icon is fixed. The reply icon should just scroll to the reply input field, so when there are no other replies and the input field is visible - the reply button don't make any visual change. 
@kpecknold please retest the thumbs up button
