### ISSUE TITLE
[BUG] Group members search icons 

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2561]
**Describe the bug**
Group search can only be activated  by tapping in the white space on the left. The magnifying glass should also active it.  And the "X" should also produce an action

**To Reproduce**
1. Go to a group, tap into members
2. Tap on magnifying glass 
3. Tap on "X"
4. See no result from taps

**Comment by TodorBachvarov** [comment]
Implemented: Search icon will request focus to the text field (if not already focused). "X" icon will remove focus (if focused). Implemented in version 4.2.28. @kpecknold please retest.

**Comment by kpecknold** [comment]
Fixed
