### ISSUE TITLE
[BUG] Pixelated "Who Are You?" icons

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2577]
The icons under Who Are You? are pixelated. Here are the [icon files](https://drive.google.com/drive/folders/1iKXHwmLhjfXewURBJqD5LXBex-5PCrhr?usp=sharing) with four sizes. 

4.2.28 Android Pixel 6

**Comment by dobromirdobrev** [comment]
The icons are updated with the provided from the link. This is done in version 4.2.44. Please, verify.

**Comment by vburgett** [comment]
Thank you!
