### ISSUE TITLE
[USABILITY] Browse screen should be in alpha order

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2579]
The Browse screen headers and sub-header links should be in alpha order.

**Main Headings**
Laundry should be listed after Groups.

**Sub Headings**

**Academics**
Campus Reminders
Due Date Catalog
My Courses

**Athletics**
My Events
My Game Day
My News
News
Upcoming Events

**Dining**
My Dining Locations
Residence Hall Dining
Residence Hall Dining Open Now

**Events**
My Events
Suggested Events

**Feeds**
Daily Illini
Twitter
WPGU 107.1 FM

**My**
Move "MyMcKinley Appointments" to the end of the "My" list
"My Laundry" should go above "My Research Projects"

**Research at Illinois**
My Research Participation
Open Research Projects

**Wallet**
Add Illini Cash
Bus Pass
Illini Cash
Illini ID
Meal Plan

**Wellness**
Daily Tip
Illinois Health Screener (change "Wellness" to "Illinois")
MyMcKinley Appointments
Resources
Rings
To-Do List

4.2.28 Android Pixel 6

**Comment by pmarkhennessy** [comment]
@vburgett We have sorted the sub items for 4.2 In 4.3 we can address this further.

**Comment by vburgett** [comment]
Thank you, @pmarkhennessy. Was skipping this edit intentional? 

**Wellness**
Daily Tip
**Illinois Health Screener (change "Wellness" to "Illinois")**
MyMcKinley Appointments
Resources
Rings
To-Do List
