### ISSUE TITLE
[BUG] two versions of text needed for default empty "My Research Participation" favorite widget  

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2588]
The default empty widget text for the "My Research Participation" favorite widget is currently directed to the principal investigator (PI). Based on a convo with JP this morning, there should be two versions of this default text implemented for either 1) the PI or 2) users who are not PIs. 

**My Research Participation**
**Existing** default empty widget message for principal investigators:
**You have not created any research projects yet.**
 
**New** default empty widget message for users who are not set as principal investigators:
**You are currently not participating in any research projects. View current studies that match your Research Interest Form to opt in and become part of the study’s recruitment pool.** (Link "View current studies" to Browse > Research at Illinois > Open Research Projects" and link "your Research Interest Form" to the "Research Interest Form" currently under "Profile.")

**Why?**
As a user who is NOT a PI, I see the message "You have not created any research projects yet." in "My Research Participation" favorite widget. I am not allowed to created research projects so I should not see this text.

Version 4.2.28
Android Pixel 6

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.31.

**Comment by vburgett** [comment]
Thank you! The new text is in v 4.2.40.
