### ISSUE TITLE
[BUG] Telehealth zoom link not showing in appointments

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2589]
**Describe the bug**
For McKinley Appointments, OnLine (telehealth) appointments, the zoom link for the appointment is not being shown in the appointment details

**To Reproduce**
1. Select Wellness
2. Choose MyMcKinley Appointments from the drop down
3. select a Telehealth appointment
4. 

**Expected behavior**
The zoom link for the appointment should be listed under "Telehealth"

Seen in build 4.2.28
![Screenshot_20221129_144343_Illinois](https://user-images.githubusercontent.com/57494808/204644741-340234e9-de1f-46bb-905b-98dfd0315045.jpg)

**Comment by pmarkhennessy** [comment]
@clint156  Please test in Thursday 2022/12/01 build

**Comment by clint156** [comment]
Verified fixed in 4.2.32
