### ISSUE TITLE
[BUG] Groups Messaging and Don't show UINs

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2605]
**Describe the bug**
Remove UIN and Email buttons from interface inside Groups/Posts/Message to Select member, only have 1 list that has name with email address under it.

Never show UINs to anyone in Groups. Combine name with email (put email under name in same list)

**Comment by pmarkhennessy** [comment]
@TodorBachvarov These are the selection tabs/buttons for how to look at members when making a post

**Comment by kpecknold** [comment]
@TodorBachvarov @pmarkhennessy   In group settings, advanced settings, "View NetID" is still an option but should not be.
