### ISSUE TITLE
[BUG] MyMckinley Appointments are not being shown

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2614]
**Describe the bug**
After uninstalling the previous version and installing build 4.2.31, my Mckinley appointments are no longer being displayed.

**To Reproduce**
1. Log into the app with your netid
2. Click on Wellness 
3. Select "MyMckinley Appointments"
4. I get the message that I currently have no upcoming or past appointments linked with the app. 

I verified with Stephen and Mark that I have pushed up at least one future appointment today (12/1/2022).
I went into settings and unchecked the the MyMckinley display appointments slider. This did result in
"There is nothing to display as you have chosen not to display any past or future appointments" being displayed. Setting it back returned me to the no upcoming or past appointments message. So the slider appears to be working correctly. 

The appointments just aren't being displayed.

**Expected behavior**
All upcoming and past appointments that have been pushed to Rokwire should be displayed.

 - OS:Android'
 - Build 4.2.31

**Additional context**

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.32. Please verify and let us know if it works.

**Comment by clint156** [comment]
verified fixed in 4.2.32
