### ISSUE TITLE
[USABILITY] State Farm Parking function check

### ISSUE THREAD

**Issue by ToddNelson** [rokwire/illinois-app#2616]
Describe the usability issue
The State Farm Parking feature in the app does not seem to be functioning properly. Please investigate if this feature is expected to work, or if it should be removed. See attachment from Tom and Joe with more details, and contact them with any questions regarding recent testing.

[state farm parking test screens 2021-2022.pdf](https://github.com/rokwire/illinois-app/files/10138169/state.farm.parking.test.screens.2021-2022.pdf)

**Comment by pmarkhennessy** [comment]
@ToddNelson We will look at it tonight

**Comment by knguyenjahiel** [comment]
Closed: State Farm Parking functionality has been removed from the app
