### ISSUE TITLE
[BUG] Skills Self evaluation result is invalid

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2624]
**Describe the bug**
The result displayed after submitting skills self-evaluation is invalid

**To Reproduce**
1. Install the Illinois app
2. Navigate to Academics and select Skills Self-evaluation in the drop-down list. Tap on the "Get started" button
3. Select the choice in Skills self-Evaluation and submit.

**Actual Result**
The result displayed is not correct

**Expected behavior**
The app should display the skills result as per the selected choices.

**Screenshots**
![self evaluation](https://user-images.githubusercontent.com/26231179/205384740-2f475cb8-9442-4cc4-9219-a034f751adf2.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.2.31]

**Additional context**

**Comment by shurwit** [comment]
This will be addressed by #2612

**Comment by Priyaravi8** [comment]
This is fixed
