### ISSUE TITLE
[BUG] New Group: auto-join toggle not working

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2642]
When creating a new Group in 4.2.34 (Android Pixel 6) the "Groups can be joined automatically" toggle is not responsive to a tap. You can toggle on and off "Enable group attendance" to intermittently change the auto-join toggle state. (Once on, auto join _does_ allow someone to automatically join the Group.)

 ![Screenshot_20221206-115616.png](https://user-images.githubusercontent.com/1044905/205987968-6d44a129-7994-404e-9953-1f194325cedc.png)

**Comment by TodorBachvarov** [comment]
Fixed in version 4.2.36

**Comment by vburgett** [comment]
Working in 4.2.36—thank you!
