### ISSUE TITLE
[BUG] Order of All Notifications 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2644]
Under each sorting category, notifications should list the most recent notification at the top under Today. It isn't currently.

Version 4.2.34

![Screenshot_20221206-130024.png](https://user-images.githubusercontent.com/1044905/205999265-2f977538-38aa-4505-84e4-972076df5c42.png)

**Comment by TodorBachvarov** [comment]
This was fixed on the backed, so please retest.

**Comment by vburgett** [comment]
This is now working in 4.2.46. Thank you!
