### ISSUE TITLE
[BUG] Group-Level Notification Preferences

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2648]
When I go to a Group that has notifications turned on, the bottom five toggles should be in the checked state. 

**To Reproduce**

1. Go to a Group that has notifications turned on by the user via the global notifications preferences only 
2. Tap on the Notification text UNDER the Group name 
3. See how all of the options are checked as set on but none of the correlating settings below match?

V 4.2.34 Pixel 6

![Screenshot_20221206-221901.png](https://user-images.githubusercontent.com/1044905/206088331-6e7ada95-6067-4aba-b30c-7d5fdd3397f7.png)

**Comment by Priyaravi8** [comment]
Usability Issue - Remove the title "Use this notification preference for this group" along with the toggle button to avoid confusion to the users.

**Comment by vburgett** [comment]
@pmarkhennessy, yes, keeping the "override" _on_ makes sense. 

Now or later, can we make this text clearer changing "Use these notification preferences for this group" to "Override my global notification settings with:" (link and underline "my global notification settings"). If later, let me know so I can submit it later.

**Comment by TodorBachvarov** [comment]
Changed switch label to "Override my global notification settings with:" also "my global notification settings" is underlined and linked to open MyNotificationPreferences panel. 
Changed in version 2.4.36

**Comment by vburgett** [comment]
Updated in 4.2.42—thank you!
