### ISSUE TITLE
[USABILITY] Rename Group-level Notifications to Notification Preferences 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2649]
Rename all Group-level "Notifications" text to "Notifications Preferences" by the bell icon in the area below the Group's name. 

(When you go to a Group and see the text "Notifications" and a bell icon, I expect to see notifications from that Group when it's actually that Group's notifications preferences. The functionality is right but the wording is wrong. Updating this text will increase the user's understanding of this new option for choosing when and if to be notified by Group tenfold.)

![Screenshot_20221206-223528.png](https://user-images.githubusercontent.com/1044905/206089426-d54768c8-bb5f-4cbb-a8d8-73f8e6cf345c.png)

**Comment by pmarkhennessy** [comment]
@TodorBachvarov Rename the menu entry "Notifications" to "Notifications Preferences"

**Comment by TodorBachvarov** [comment]
Button renamed in version 4.2.36

**Comment by vburgett** [comment]
The button is renamed—thank you!

Once you have changed your custom group notifications, the first line of text reads as if those settings are for that particular group and not the global settings. Please change to:
**Current group notifications preferences > Current global notification settings for Groups:** (underline entire line and link to global notifications preferences) 

Once you have changed your custom group notifications, the second line of text reads as if the custom settings change ALL of the global settings. Please change to:
**Override my global notification settings with: > Override the above settings for this group:**
![Screenshot_20221212-144531](https://user-images.githubusercontent.com/1044905/207153232-cd7c9473-53f9-403d-993d-b2a6c65a0b80.png)

**Comment by TodorBachvarov** [comment]
Wording was updated during other updates for this panel.
