### ISSUE TITLE
[BUG] appointment instructions are not being displayed in the app

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2653]
**Describe the bug**
Appointments being pushed up from McKinley with the "instructions" property populated are not displaying the instructions in the app.

I used postman to push this appointment to Rokwire:
[{
	"source_id": "57",
	"provider_id": "1",
	"appointment_date_time": "2023-01-30T20:00:00.000Z",
	"cancelled": false,
	"type": "Online",
	"location": {
		"id": "McKinley Health Center, Mental Health Clinic, Third Floor",
		"title": "McKinley Health Center, Mental Health Clinic, Third Floor",
		"latitude": 40.10295291956433,
		"longitude": -88.21989804371852,
		"phone": "217-333-2700"
	},
	"account_id": "c905d2bc-d554-11ec-adaf-0a58a9feac02",
	"host": {
		"first_name": "Jennifer",
		"last_name": "Laprise MD, Ph.D."
	},
	"online_details": {
		"url": "https://illinoismckinley.zoom.us/my/337",
		"meeting_id": "",
		"meeting_passcode": ""
	},
	"instructions": "These are instructions for the appointment"
}]

**Expected behavior**
Based on the design document attached, the instructions should be displayed as "Required Preop". I have verified that the information is not being displayed with both online and in person appointments.

Build 4.2.34

**Additional context**
[Pages from Illinois_App_MyAppts_2022-09_21 - prep.pdf](https://github.com/rokwire/illinois-app/files/10177728/Pages.from.Illinois_App_MyAppts_2022-09_21.-.prep.pdf)

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.36. Please verify.

**Comment by clint156** [comment]
Verified Fixed in 4.2.36
