### ISSUE TITLE
[BUG] v4.2.34 Favorites Widget for Courses - Locks when tapping a course

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2654]
**Describe the bug**
In Favorites > [Courses widget]* 

Touching a course card locks up the app, requiring a restart.

*By the way, this widget does not have a title. I think it should say "My Courses" in the title bar of the Favorites Widget

Testing on Pixel 3

**Comment by dobromirdobrev** [comment]
Hi @joegrohens , both issues (locked screen and missing title) are fixed in version 4.2.36. Please, verify.

**Comment by joegrohens** [comment]
Confirmed fixed in 4.2.36. Tapping on the course card now opens the screen for the course. And the title "My Courses" is displayed in the favorites widget.
