### ISSUE TITLE
[USABILITY] Skills Self-Evaluation formatting

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2655]
Please make the paragraph text at the top of the Skills Self-Evaluation survey smaller and not bold (Proxima Nova Regular). 

Please re-format the text "Not at all well, Pretty well, and Extremely well" to fit the word "Extremely" on one line. I suggest either making it Proxima Nova Regular OR slightly smaller. 

Go to Academics > Skills Self-Evaluation > Get Started
V 4.2.34

![Screenshot_20221207-103003](https://user-images.githubusercontent.com/1044905/206236466-2285d433-c2ec-4865-9c06-cd0da47972b9.png)

**Comment by roberlander2** [comment]
This will be handled by https://github.com/rokwire/illinois-app/issues/2647
