### ISSUE TITLE
[BUG] Browse - My - "My research Projects" link is not functioning

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2656]
**Describe the bug**
The "My research Projects" link is not navigating to the desired screen.

**To Reproduce**
1. Install the Illinois app
2. Navigate to the Browse screen and scroll down to the section "My"
3. Tap on "My Research Projects"

**Actual Result**
The "My research Projects" link is not navigating to the desired screen.

**Expected behavior**
The "My research Projects" link should navigate to the desired screen.

**Screenshots**
![research](https://user-images.githubusercontent.com/26231179/206237203-27c6672f-27ce-46e9-be49-8db214bb7554.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. android]

 - Version [e.g. 4.2.34]

**Comment by mihail-varbanov** [comment]
Resolved in 4.2.36

**Comment by Priyaravi8** [comment]
Fixed
