### ISSUE TITLE
[BUG] Cancelled appointments are still showing in the app

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2657]
**Describe the bug**
An appointment previously pushed to the app and then updated with the cancel flag set to true is still showing in the app.

**To Reproduce**
Push this appointment into the app: (change the source_id to something other than 57 and use your rokwire account_id from dev.

[{
	"source_id": "57",
	"provider_id": "1",
	"appointment_date_time": "2023-01-30T20:00:00.000Z",
	"cancelled": false,
	"type": "Online",
	"location": {
		"id": "McKinley Health Center, Mental Health Clinic, Third Floor",
		"title": "McKinley Health Center, Mental Health Clinic, Third Floor",
		"latitude": 40.10295291956433,
		"longitude": -88.21989804371852,
		"phone": "217-333-2700"
	},
	"account_id": "c905d2bc-d554-11ec-adaf-0a58a9feac02",
	"host": {
		"first_name": "Jennifer",
		"last_name": "Laprise MD, Ph.D."
	},
	"online_details": {
		"url": "https://illinoismckinley.zoom.us/my/337",
		"meeting_id": "",
		"meeting_passcode": ""
	},
	"instructions": "These are instructions for the appointment"
}]

Verify that it shows up in the MyMckinly appointments. Push the appointment up again setting the cancelled property to true.
The appointment is still displayed in the app.

**Expected behavior**
The appointment should no longer be there.

Build 4.2.34

**Comment by pmarkhennessy** [comment]
@clint156 Will pass you a build if I have not already with the fixes for this

**Comment by clint156** [comment]
Verified that The word Cancelled is now displayed in the app once an appointment is cancelled. There may be a bigger future discussion on how this should work in the future, but currently it works as expected.

**Comment by clint156** [comment]
Verified that The word Cancelled is now displayed in the app once an appointment is cancelled. There may be a bigger future discussion on how this should work in the future, but currently it works as expected.
