### ISSUE TITLE
[BUG] MyMcKinley Appointments message for Privacy level 3 or lower

### ISSUE THREAD

**Issue by dr-mel** [rokwire/illinois-app#2658]
**Describe the bug**
For a user with Privacy level 3 or lower, no message says they should be logged in to use the feature.

**To Reproduce**
1. Use app with Level 3 or lower
2. Go to Wellness > MyMcKinley Appointments

**Expected behavior**
A message saying, "You need to be signed in with your NetID to access MyMcKinley Appointments. Set your privacy level to 4 or 5 in your Profile. Then find the sign-in prompt under Settings."

**Comment by roberlander2** [comment]
This will be addressed by #2668
