### ISSUE TITLE
[BUG] MyMcKinley Appointment image behavior

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2660]
Under Wellness > MyMcKinley Appointment > Specific Appt Screen: the image when tapped does not display the image. 

Under Wellness > MyMcKinley Appointment: The thumbnail of the same appointment does **not** match the actual appointment image.

V 4.2.34 Pixel 6

![Screenshot_20221207-111903](https://user-images.githubusercontent.com/1044905/206247014-c6505422-f9dc-4eeb-89c5-4725888a933a.png)

![Screenshot_20221207-111344](https://user-images.githubusercontent.com/1044905/206247010-ab4b7b1c-d23b-4154-ab90-91c580a3f0ae.png)

**Comment by TodorBachvarov** [comment]
Fixed in version 4.2.36
