### ISSUE TITLE
[BUG] MyMcKinley Favorite Widget + stars

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2661]
The MyMcKinley Appointments favorite widget should have the appointment cards favorited with an orange star (when a user is set to privacy level 4 or 5 and is logged in with their NetID with their MyMcKinley appointments set to show under Settings > MyMcKinley Appointments.)

A user can then remove an appointment from appearing in this widget on their Favorites by unstarring that particular appointment. 

V 4.3.34 Android Pixel 6

![Screenshot_20221207-112214](https://user-images.githubusercontent.com/1044905/206248839-1bae345a-d961-408b-b147-ef87d8d7d795.png)

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.39. Please verify.
