### ISSUE TITLE
[USABILITY] MyMcKinley: new text needed to reflect syncing delay

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2662]
Please add a **second** paragraph to the MyMcKinley pop-up text linked to from Wellness > MyMcKinley Appointments > "Need to cancel or reschedule?" and the text at the bottom of every MyMcKinley appointment screen.

"Cancellations and appointment changes may take up to 20 minutes to appear in the Illinois app. The two-hour cancellation fee will be based on the time you cancel via MyMcKinley.illinois.edu."

Please also change the default text a user sees when they have no upcoming appointments to see yet under Wellness > MyMcKinley Appointments to: 

"You currently have no upcoming appointments linked within the Illinois app. New appointments made via MyMcKinley.illinois.edu may take up to 20 minutes to appear in the Illinois app."

V 4.3.34 Android Pixel 6
Cc: @dr-mel 

![Screenshot_20221207-111103](https://user-images.githubusercontent.com/1044905/206263399-1f9568ab-127d-4db3-9d8e-25f849cbf159.png)
![Screenshot_20221207-111903](https://user-images.githubusercontent.com/1044905/206263402-8a2f7580-e502-4e3f-adfc-3410c3ebb84e.png)

**Comment by dobromirdobrev** [comment]
Done in version 4.2.36. Please verify.

**Comment by vburgett** [comment]
Complete in 4.2.40—thank you!
