### ISSUE TITLE
[BUG] MyMcKinley appointment times being shown in 24 hour time

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2663]
**Describe the bug**
MyMcKinley appointments are being shown as 24 hour time; so afternoon appointments are showing as 13:00 or 14:00 instead of 1:00pm and 2:00 pm.

**To Reproduce**
Schedule an appointment for an afternoon time. The display time shows as 24 hour instead of 12 hour time.

**Expected behavior**
12 hour time (am/pm) should be used

Build: 4.2.34

**Comment by pmarkhennessy** [comment]
@dobromirdobrev From UTC in JSON to device local time and not in 24hr format please

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.36. Please verify.

**Comment by clint156** [comment]
Verified fixed. Times are showing in 12 hour format now.
Build 4.2.36
