### ISSUE TITLE
[BUG] Map > MyMcKinley In-Person Appointments 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2664]
Under Map > MyMcKinley In-Person Appointments, upcoming appointments show up as "2 Explores" with details leading to an Explore panel with incomplete MyMcKinley appointment cards.

- Change "2 Explores" to "2 Appts."

- The Detail button should lead to MyMcKinley appointment cards that match the cards in style and information as they appear under Wellness > MyMcKinley. (These cards when tapped _do_ lead to the correct appointment screen.) 

V 4.2.34 Android Pixel 6

![Screenshot_20221207-115858](https://user-images.githubusercontent.com/1044905/206264795-85859a9e-1f48-4903-a65b-c7ba896f8e53.png)

![Screenshot_20221207-115855](https://user-images.githubusercontent.com/1044905/206264789-1a5330e3-0513-42f2-9ecb-cd8b3829356e.png)

**Comment by pmarkhennessy** [comment]
@mihail-varbanov "Explores" should be "Appointments"

**Comment by mihail-varbanov** [comment]
I think I resolved the issue. The fix will be available in 4.2.36.

**Comment by vburgett** [comment]
In 4.2.36, the map now says "2 Appointments." 

The appointment cards still need addressing:
- The Detail button should lead to MyMcKinley appointment cards that match the cards in style and information as they appear under Wellness > MyMcKinley. 

@mihail-varbanov

**Comment by mihail-varbanov** [comment]
@vburgett, I am sorry, I missed the second part of this issue. I think it should be resolved in version 4.2.41.

**Comment by vburgett** [comment]
Thank you! The MyMcKinley Appointment cards appear under Map > MyMcKinley In-Person Appointments > Details > Explore correctly in 4.2.43.
