### ISSUE TITLE
[BUG] Privacy level is not getting saved property

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2666]
**Describe the bug**

**To Reproduce**
1. On dev, start with a privacy level of 5. Check the privacy level with a call to https://api-dev.rokwire.illinois.edu/core/tps/accounts?Limit=200
2. In the app, set your privacy level to 3
3. Call https://api-dev.rokwire.illinois.edu/core/tps/accounts?Limit=200
4. The endpoint is still returning a privacy level of 5.

**Expected behavior**
The privacy level should be returned as a 3. While the app does behave like the privacy level is at 3, the mismatch between the app and the data being returned means the mckinley appontment integration is pushing data to Rokwire for users that have not consented or removed consent by changing the privacy setting.

**Comment by shurwit** [comment]
The issue is that when we set the privacy level to 3 or lower the app automatically logs you out of your account. This occurs before the preferences are updated which means that the account record on the Core BB is never updated with this change. To fix this, we would need to save the updated privacy level to the account before logging out.

**Comment by shurwit** [comment]
We noticed a couple of graphical issues when changing the privacy levels that we could fix here as well:

When changing privacy level to 3, the slider indicator appears over the 3rd "settings" icon, however when you come back to this panel after setting your privacy level to 3, the slider appears over the 4th "notifications" icon:
![Screenshot_20221207_141910_Illinois](https://user-images.githubusercontent.com/10472810/206291983-233fe531-38da-427a-8dda-e1152160267e.jpg)

The explanation text is being cut off vertically when privacy level 1 is selected:
![Screenshot_20221207_141919_Illinois](https://user-images.githubusercontent.com/10472810/206292008-1d3c0e8e-4c09-4c57-9343-148e475ca4b3.jpg)
