### ISSUE TITLE
[BUG] Close icon "X" display in MyMckinley appointment detail screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2667]
**Describe the bug**
On the details screen of  MyMckinley appointment, the close icon "X" displayed randomly.

**To Reproduce**
1. Install the Illinois app
2. Navigate to the details screen of MyMckinley appointment
3. Tap on the Back arrow at the top left

Actual result
 The close icon "X" is displayed randomly on the screen

**Expected behavior**
The screen should display without any "X" icon

**Screenshots**

![close icon](https://user-images.githubusercontent.com/26231179/206293263-395e7923-a353-453a-921d-d77b0642211e.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. android]
 - Version [e.g. 4.2.34]

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,

This behaviour happened not when user taps on the "back" button but when he taps on the image. It is fixed in version 4.2.36. Tapping on the image will show it in popup (like anywhere else). Please verify.

**Comment by Priyaravi8** [comment]
Fixed
