### ISSUE TITLE
[BUG] Connect your NetID screen is not displayed with Privacy level 2

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#267]
**Describe the bug**
With users Privacy level 2, Illinois Home screen is displayed without displaying Connect your NetID screen 

**To Reproduce**

1. Install the Illinois app and open the app
2. Tap on the Continue button on the Initial screen
3. Select University student as a role and tap on the continue button
4.  In the "Control your data" screen tap on Begin button 
5. Enable location services and continue button
6. Disable App activity and tap on the continue button
7. Tap on the Start Exploring button

**Actual Result**

Connect your NetID screen is not displayed. With users Privacy level 2, the Illinois Home screen is displayed directly.

**Expected behavior**
Users would be expecting a "Connect your NetID" screen to log in before proceeding to the Home screen

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android ]

 - Version [e.g. 2.4.16]

**Additional context**

**Comment by pmarkhennessy** [comment]
@Priyaravi8 This is as designed - 1 and 2 levels just go to home screen

**Comment by Priyaravi8** [comment]
As designed. Closing this issue.
