### ISSUE TITLE
[BUG] Tapping on academic course card locks up app

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2682]
**Describe the bug**
If you tap on a course card, anywhere other than the underlined location, the app locks up

**To Reproduce**
1. Go to course list, either from favorites widget or under academics "My courses"
2. Tap anywhere on course care, EXECPT on underlined location

**Expected behavior**
App should not lock up

**Comment by joegrohens** [comment]
Confirmed fixed in 4.2.36. Tapping on the course card now opens the screen for the course. And the title "My Courses" is displayed in the favorites widget.

**Comment by kpecknold** [comment]
Yes, fixed
