### ISSUE TITLE
[USABILITY]  Group Notifications wording change

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2684]
Please change the wording under Group notifications

1. Top section, change "Current group notification preferences" to
"Global group notification settings"
and also provide a link to the settings where those could be changed

2. Bottom section, change "Use these notification preferences for this group" to
"Use custom notification settings for this group"

**Comment by pmarkhennessy** [comment]
@TodorBachvarov Use the wording I gave you that is nearly the same as above

**Comment by TodorBachvarov** [comment]
Wording is changed.

**Comment by kpecknold** [comment]
thank you
