### ISSUE TITLE
spelling error: "Notificaitons" occurs three times in asset.json

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#27]
https://github.com/rokwire/illinois-app/blob/b4bed184678d5dbb5be2bf50db0364dba9364701/assets/assets.json#L485

https://github.com/rokwire/illinois-app/blob/b4bed184678d5dbb5be2bf50db0364dba9364701/assets/assets.json#L546

https://github.com/rokwire/illinois-app/blob/b4bed184678d5dbb5be2bf50db0364dba9364701/assets/assets.json#L668

Please change to "Notifications"

**Comment by joegrohens** [comment]
If you want to see this spelling error in a screen:
Browse > Privacy Center > Manage and Understand Your Privacy > Events and Dining Around Campus

and also under 
> Athletics
> Student and Community Involvement

![IMG_0243](https://user-images.githubusercontent.com/66988329/93135917-b3cd5500-f6a0-11ea-9bbf-411490151790.png)

**Comment by TodorBachvarov** [comment]
Fixed in version 2.3.8
