### ISSUE TITLE
[BUG] Cannot make a post in a group where i'm the admin

### ISSUE THREAD

**Issue by dr-mel** [rokwire/illinois-app#2701]
**Describe the bug**
In a group where I'm an admin, I cannot create a post, even if the group has members. I CAN post to a group where I'm only a member.

**### NOTE: This seems to happen only with new groups that we create today.**

**To Reproduce**
1. Go to a group as an admin
2. Tap + to create a post
3. Give a subject and body text
4. Press Send
5. Toggle off the option to post other groups that I'm an admin of
6. Press Select
**Expected behavior**
Post would be made to the group.

**Screenshots**
![Screenshot_20221209_102918_Illinois](https://user-images.githubusercontent.com/95657673/206748145-dcd00d56-4c1f-41cb-8afd-a0f629d639f6.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Note 20
 - OS: Android 13

**Comment by pmarkhennessy** [comment]
@TodorBachvarov I am presuming this is just noise while you finish the groups settings

**Comment by TodorBachvarov** [comment]
@dr-mel I'm not able to reproduce this behaviour with the latest version. Could you try again and if you still experience this issue please let me know. Also a screenshot of the group setting will be helpful.

**Comment by dr-mel** [comment]
Mark replied in slack last week that this issue was likely related to a new Groups BB deployment that was likely occurring while I was testing. I'll check again and confirm.

**Comment by joegrohens** [comment]
@TodorBachvarov @dr-mel I am also unable to post in my group. I get the same error msg as Mel. Using v4.2.36

**Comment by kpecknold** [comment]
@TodorBachvarov I also still get this error when I create a new group.
