### ISSUE TITLE
[BUG] Saved Wellness To-do list item text is not visible.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2702]
**Describe the bug**
The added to-do list item title is not visible on the screen. Also, the font of the title items is big.

**To Reproduce**
1. Install the Illinois app.
2. Navigate to wellness and select the To-do list
3. Tap on add item.
4. Enter the Item name and tap the Save button

Actual Result
1. The saved to-do item title is not visible on the displayed section bar
2. Also the visible item title's font is big.

**Expected behavior**
The saved item title should be visible to the user

**Screenshots**
![todo](https://user-images.githubusercontent.com/26231179/206759722-604e224f-d954-457d-b0f3-bfb29ee195a8.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. android]

 - Version [e.g. 4.2.36]

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.39. Please verify

**Comment by Priyaravi8** [comment]
Fixed
