### ISSUE TITLE
[BUG] Privacy Settings 1-3, "Create a Poll" template is accessible to write a question and response options. Then, "Start Poll Now" gives a confusing notice

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2705]
**Describe the bug**
At Privacy Settings 1-3, the "Create a Poll" template is accessible for one to write a question and response options. Then, touching "Start Poll Now", a confusing notice displays: Failed to create poll. Please fill in all fields and try again.

**To Reproduce**
1. Go to Polls --> Create a Poll
2. Write question and response options
3. Touch Start Poll Now

**Expected behavior**
At Privacy Settings 1-3, "Create a Poll" shouldn't be accessible. 
When "Create a Poll" is touched, display message: You need to be logged in with your NetID to create a poll. Set your privacy level to 4 or 5 in your Profile. Then find the sign-in prompt under Settings.

**Screen Shot**

![Screenshot_20221209-143141](https://user-images.githubusercontent.com/118769169/206818202-d635fc4d-2157-4621-8ee5-7552fc55e722.png)

**Comment by mihail-varbanov** [comment]
Fixed in 4.2.39.
