### ISSUE TITLE
[USABILITY] Change wording on "Research at Illinois" button

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2729]
Add the word "in" to the end of this description on the Research at Illinois button.

"Start your own research projects or discover other projects to participate in."

![research at illinois copy](https://user-images.githubusercontent.com/66988329/207384567-cb588eb4-8bc7-41a3-9c9e-476b4c4e021c.png)

**Comment by mihail-varbanov** [comment]
Description updated in version 4.2.41

**Comment by joegrohens** [comment]
confirming: fixed in 4.2.42
