### ISSUE TITLE
[BUG] Group-Level Notification Preferences > Delete "Invitations" from member overrides

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2730]
When you go into a Group as a member or an admin, there is the notification preference override option for "invitations." A Group member wouldn't get notified when a person joins a Group, can we delete the "invitations" override circled in the attached screenshot for members?

V 4.2.36 Android Pixel 6

![Screenshot_20221213-112816](https://user-images.githubusercontent.com/1044905/207403378-622874d3-c783-4bde-abfc-84d92c83a315.png)

**Comment by pmarkhennessy** [comment]
@vburgett This is deferred to 4.3. For now it is renamed to Group Membership.
