### ISSUE TITLE
[USABILITY] Group Notification Preferences > Invitations text change to Membership Requests

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2732]
Please change the Group Notification preference "Invitations" to "Membership Requests" in the following two locations: 1) a user's global notification preferences and 2) for Group admins under their group-level notification preferences. 
V4.2.36
![Screenshot_20221213-120050](https://user-images.githubusercontent.com/1044905/207410624-07adb579-8214-4656-ad60-7c0a717291a1.png)
![Screenshot_20221213-115956](https://user-images.githubusercontent.com/1044905/207410707-30668bc3-aae0-4795-8371-1a1c6f072748.png)

**Comment by pmarkhennessy** [comment]
We will change it to Group Membership and you can test it with the new build on Thursday latest

**Comment by vburgett** [comment]
Why Group Membership and not Membership Requests? Does this preference notify members of group members as well? @pmarkhennessy

**Comment by pmarkhennessy** [comment]
@vburgett We want to use this also for when a user gets booted from a group having been a member. We feel this is a better term as it covers anything about membership. This will have to get fixed on the backend at some point but does not stop this release as we can just publish a new Groups BB when done.

**Comment by vburgett** [comment]
Thank you for the explanation. I will close this ticket. Perhaps the wording could be "Member Status"? @pmarkhennessy
