### ISSUE TITLE
[USABILITY] Change Name of Settings > My Favorites

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2735]
The menu item "Settings > My Favorites" opens the "Customize" tool on the Favorites screen.

This might be confusing to users, who could expect "My Favorites" to be a menu of personal favorites.

I suggest we rename this menu item to "Settings > Customize Favorites".

@vburgett

**Comment by vburgett** [comment]
Agreed. Please change My Favorites in the Settings drop-down menu to Customize Favorites. 
![Screenshot_20221213-145024.png](https://user-images.githubusercontent.com/1044905/207441539-6d798386-e5f4-4bc7-bd85-93a47c0d1d3b.png)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.41.

**Comment by joegrohens** [comment]
Verified fixed in 4.2.42
