### ISSUE TITLE
[BUG] Description of Privacy Level 3 for Health & Wellness is Inaccurate

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2738]
_Android dev build v 4.2.40_

**Describe the bug**

The description for Health & Wellness : "Personalizations", which includes MyMcKinley appointments and health screener results, is enabled at Privacy Level 3.

These functionalities require the user to sign in with NetID, which is only enabled at Privacy Level 4.

**To Reproduce**

1. Go to: _Profile > Manage and Understand Your Privacy_ 
2. Set Privacy Level to 3
3. See that the Health and Wellness section of Privacy Center is enabled.
4. Touch "Set Privacy"
5. A notification appears that "You currently have no upcoming in-person appointments linked within Illinois app".
6. Try Wellness > Illinois Health Screener. A notification appears that "You need to be logged in with your NetID to access the Illinois Health Screener."

_QED_

**Expected behavior**
The Privacy Center should show that these "Personalizations" for appointments and health screener are enabled at level 4. 

If you want always to enable "Personalizations" at level 3, for consistency, then you could put these capabilities for health screener and appointments under the heading of "Identity" or "Notifications", which are both always associated with level 4.

For example, all mention of Appointments could be kept under the heading of "Notifications". [Move it out from "Personalizations".]

The mention of the Health Screener could be put under the heading of "Identity", maybe.

**Screenshots**

![Screen Shot 2022-12-13 at 11 11 10 PM](https://user-images.githubusercontent.com/66988329/207511352-88c5c32b-c946-4e39-ba59-c81dfbfa8c2e.png)

**Comment by pmarkhennessy** [comment]
@joegrohens Handled a little differently, please check 4.2.42 build

**Comment by joegrohens** [comment]
This is fine for now.
