### ISSUE TITLE
[USABILITY] Privacy Center should mention Self Quiz and Research Participation Survey

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2739]
Describe the usability issue

Two features that require NetID authentication, and therefore a minimum Privacy Level of 4, are:

- Research Participation Interest Survey
- Skills Self Evaluation

I believe that these features should be mentioned in the Privacy Center.

I can't find the Research Participation Interest Survey anymore though.

**Comment by pmarkhennessy** [comment]
@joegrohens This has been handled differently, please check 4.2.42 build

**Comment by joegrohens** [comment]
I see that Research Survey is mentioned under General :: Personalizations and Notifications. I don't see the Skills Inventory mentioned (that's what I mean by "Self Quiz"), but maybe that is not important.
