### ISSUE TITLE
[BUG] Problems when Creating Research Project 

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2740]
_Android dev build v 4.2.40_

**Describe the bug**

1. Tapping the "Create Project" button (which is dimmed) brings up the "how to report abusive content" notification for Groups. Do we want this notification on research groups?
2. User can dismiss this modal notification window with either "OK" or "Cancel". In both cases, user returns to the "Create Project" button, which is still dimmed.
3. Tapping the "Create Project" button again only brings up the "abusive content" notice.

It appears to be impossible to complete the creation of a research project group.

![Screenshot_20221213-235317](https://user-images.githubusercontent.com/66988329/207517630-5fbe9827-8826-403f-8ab7-54ad64419c19.png)
![Screenshot_20221213-235332](https://user-images.githubusercontent.com/66988329/207517631-3cc0313e-b77e-44e3-bd45-6e5ef4525296.png)

**Comment by pmarkhennessy** [comment]
@mihail-varbanov Do not show the abuse popups for research groups as Joe says. Also we only show the create button if the user has the Core BB role of "research_group_admin"

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, we do only show the create button if the user has the Core BB role of "research_group_admin".

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.42.

**Comment by joegrohens** [comment]
Confirming: The issues mentioned above have been fixed in 4.2.42
