### ISSUE TITLE
[BUG] Required sign-in message to access individual Group information not displaying properly

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2756]
**Describe the bug**
For Privacy Settings 1-3, the required sign-in message to access detailed group information isn't displaying properly. The pop-up shows just an image of the selected privacy level.

**To Reproduce**
1. Set Privacy Settings to 1-3
2. Browse > Groups > All Groups
3. Select a group (e.g., Awesome Frozen Plants)

**Expected behavior**
Pop-up should display: You need to be logged in with your NetID to access detailed Group information. Set your privacy level to 4 or 5 in your Profile. Then find the sign-in prompt under Settings.
 
**Screenshots**
![Screenshot_20221213-100029](https://user-images.githubusercontent.com/118769169/207658367-9fb76f90-586e-4ad0-a38a-1e899e2c8e6c.png)

**Smartphone (please complete the following information):**
 - Version 4.2.40

**Comment by mihail-varbanov** [comment]
Fixed in version 4.2.43.

**Comment by knguyenjahiel** [comment]
Can we use the same text that's used across the app to be consistent? 
"You need to be logged in with your NetID to access detailed Group information. Set your privacy level to 4 or 5 in your Profile. Then find the sign-in prompt under Settings."

Thanks

**Comment by vburgett** [comment]
@knguyenjahiel We are no longer using “logged in.” I believe the wording as implemented is correct. @joegrohens, can you confirm?

**Comment by knguyenjahiel** [comment]
**@vburett**, **@ joegrohens**: Should we implement the new wording to the rest of the app? The old text (You need to be logged in with your NetID to access [xxx]. Set your privacy level to 4 or 5...) pops up in various places (e.g., All Notifications, Unread Notifications)

**Comment by knguyenjahiel** [comment]
For now, closing this request for 4.2 release. Thank you, Rokmetro, for your amazing work!

**@vburett** & **@joegrohens** Proposing consistency audit after 4.2 release.
