### ISSUE TITLE
[BUG] Formatting changes in build

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2757]
Please match the formatting of the circled areas to the Illinois app that is available in the stores now. See the areas in the 4.2.40 build that need changing back in the attached screenshot. 

![Screen Shot 2022-12-14 at 11 16 48 AM](https://user-images.githubusercontent.com/1044905/207663355-63d2b6eb-7c58-4957-a3aa-c892d198fc64.png)

**Comment by mihail-varbanov** [comment]
These must be fixed in version 4.2.43.

**Comment by vburgett** [comment]
Thank you!
