### ISSUE TITLE
[USABILITY] Polls: Vote button should dim after possible options are chosen

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2776]
android dev build 4.2.40

![Vote button copy](https://user-images.githubusercontent.com/66988329/207955222-d4c43de6-943e-4211-afe5-e9f68c4fe190.png)

When a Poll has "Allow selecting more than one choice", the Vote button remains enabled even after a user has voted for all available choices.

**To reproduce:**

1. Create a Poll (either inside or outside of a Group)
2. Turn on  "Allow selecting more than one choice"
3. Start the Poll

Vote for all of the options in the poll. Exit the poll. You will see that the "Vote" button is still enabled for that poll.

**Expected behavior:**

The Vote button should be dimmed, as it is when you can vote for only one choice.

**Comment by vburgett** [comment]
Or the active "vote" button should allow a user to change their current vote. Right now, if there is a poll that allows multiple selections, a user can tap the Vote button and see their results again to _add_ answers to their poll but not remove an answer.

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.43. Please verify.

**Comment by joegrohens** [comment]
fixed
