### ISSUE TITLE
[BUG] Notifications Favorite Widgets Not Sorting by Time

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2787]
v 4.2.43
The All Notifications Favorite widget shows me the notifications in no particular sequence related to time. The first 11 notifications were "sent about 4 months ago" followed by a research project notification from "11 days ago" followed by two Group notifications from "about 4 months ago" followed by a Group notification from "10 days ago" etc.

I would expect the All Notifications widget to show the most recent notification first followed by the next most recent and so on and so on.

The Unread Notifications Favorite widget is also not showing up in any order based on time. My expectation would be the same as stated above. 

(If these two Favorite widgets cannot work for 4.2, I would vote for hiding them as a Favorite widget option on the favorite panel and under Customize as well as hiding them as items under Browse. The Global notification setting working would be the priority and the new main location for a user to see their notifications.)

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
This was a backend issue and should be fixed now. You could verify it with the most recent version of the UIUC app. 
Note: By the time I write this message, the issue is fixed only in dev environment.

**Comment by vburgett** [comment]
@dobromirdobrev the order is fixed as of v4.2.46. Thank you!
