### ISSUE TITLE
[BUG] Link option in a Group post not working

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2789]
As a member of the group Cute Kids, I tried posting twice using the "link" message option . Neither post showed the linked text or the link. When I went to update the post, the text and link html disappeared. 

V 4.2.43

![Screenshot_20221216-152850](https://user-images.githubusercontent.com/1044905/208193073-dabeaee7-058c-459c-88fa-4eed055aa517.png)
![Screenshot_20221216-152901](https://user-images.githubusercontent.com/1044905/208193075-835f5eae-9a98-4517-b4f4-90ab1328b1c2.png)

**Comment by pmarkhennessy** [comment]
@vburgett This works great for me. You won't see it as a link until you "Send". The actual post has the link in it.

![Screenshot_20221218-144648](https://user-images.githubusercontent.com/5613085/208323398-1901bc2f-3b5b-456d-ae4e-e056814f6bf8.png)

**Comment by vburgett** [comment]
Just tested again in Groups Hangout on 4.2.43 as the initial post and a reply. The link doesn't show up in either spots. (I have always been hitting Send.) @pmarkhennessy 

![Screenshot_20221218-165306.png](https://user-images.githubusercontent.com/1044905/208323750-3f60145f-b58b-42a0-9c85-4989982ba095.png)![Screenshot_20221218-165312.png](https://user-images.githubusercontent.com/1044905/208323756-ac424bfb-a44a-4a19-86cf-5b7d2fc083f8.png)![Screenshot_20221218-165321.png](https://user-images.githubusercontent.com/1044905/208323765-9bdc9e9d-da20-4a4b-81ce-d88be3052da3.png)![Screenshot_20221218-165403.png](https://user-images.githubusercontent.com/1044905/208323777-2f47ad2c-a175-4f17-8afc-914802a522f4.png)

**Comment by vburgett** [comment]
I manually added html paragraph tags to a link in Groups, and it worked. (Obviously adding html is not intuitive or common knowledge for many users.)

![Screenshot_20221218-170511.png](https://user-images.githubusercontent.com/1044905/208324105-b04e8931-1b14-4f4e-9701-c8abfd7f0b9e.png)![Screenshot_20221218-170515.png](https://user-images.githubusercontent.com/1044905/208324113-58872312-7e43-41f9-b37f-5f3a85665a9a.png)

**Comment by vburgett** [comment]
After testing in 4.2.47 with @kpecknold, this appears to be a bug only in Groups created pre-4.2. @pmarkhennessy
