### ISSUE TITLE
[USABILITY]Enable toggle button are placed closed to each other

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#279]
**Describe the usability issue**
Food filter screen - Enable toggle button are placed closed to each other

**To Reproduce**

Install Illinois app

1. With the user role as a University student, Complete onboarding steps
2. Tap on browse menu and proceed to Privacy center
3. Tap on Personal Information
4. On the Personal Information screen, tap on the Food filter

**Actual Result** 
In the food filter screen, Enable toggle button are placed closed to each other

**Expected behavior**
From the user's view, the toggle button is placed close to each other. It would be better to have some space between the toggle button

**Screenshots**
![Toggle](https://user-images.githubusercontent.com/26231179/121224539-47a60900-c84e-11eb-82ce-6dd1808488b1.png)

Smartphone (please complete the following information):

Device: [e.g. iPhone and Android]
App version - 2.4.17

**Comment by isaac-galvan** [comment]
This seems to be the case on the Settings-> privacy center-> notifications screen as well.
![Screenshot (Jun 9, 2021 3_24_02 PM)](https://user-images.githubusercontent.com/11352701/121424417-eb6ae400-c936-11eb-92c5-8ae2fc27eb29.png)

**Comment by Priyaravi8** [comment]
This is fixed.
