### ISSUE TITLE
[BUG] Group direct message between members can not be deleted

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2791]
A group member cannot delete their own direct message to another member after posting. The member trying to delete to their direct message by tapping on the orange trash can icon will get a pop-up error that says "Failed to delete post." 

I expect a member to be able to delete their own direct message since there is a tappable orange trash can icon available to the group member. This was tested in the group "Cute Kids." Cc: @knguyenjahiel @kpecknold 

(A member CAN delete their own post to ALL members within a group, as expected.)

v 4.2.43

![Screenshot_20221216-164513](https://user-images.githubusercontent.com/1044905/208202010-1e181673-395d-42ab-8fe9-2c88b06c1114.png)

**Comment by knguyenjahiel** [comment]
Also, unable to delete Post to Selected Members. Delete post to All Members works.

**Comment by mihail-varbanov** [comment]
@vburgett, this is backend issue. I created an issue for this in [groups-building-block](https://github.com/rokwire/groups-building-block) repository: rokwire/groups-building-block#321

**Comment by mdryankov** [comment]
@vburgett , There is a new groups bb deployment which is addressing the issue. Please retest and give a feedback. 

Thank you!

**Comment by vburgett** [comment]
I am still getting the "Failed to delete post" in 4.2.44 when trying to delete a message I sent to a selected member. I get this message from direct messages sent in groups I am a member of AND in groups I am an admin of. @mdryankov

**Comment by mihail-varbanov** [comment]
@mdryankov, a little more light. As an admin of a group I can delete my post. As a member of a group DELETE post request still fails with the same error code and description:
`500 unable to find post with id (13f4b697-92e3-4427-95eb-c73271b63699)` 
_(This was achieved on Large membership group 1000 on dev)_

**Comment by mdryankov** [comment]
@vburgett, I think this was a double strike by https://github.com/rokwire/groups-building-block/issues/326 as an additonal effect. Please test again and give a feedback. Thanks!

**Comment by vburgett** [comment]
Thank you, @mdryankov. I am still getting the same error.

Group: Groups Feedback
I'm a member, the message I am trying to delete was sent to one select member as a direct message. 
Error "Failed to delete post."
v4.2.45
Android Pixel 6

**Comment by vburgett** [comment]
It worked in 4.2.46—thank you!!
