### ISSUE TITLE
[USABILITY] Polls Options display confusing

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2802]
Currently, Polls Options are presented with radio buttons that already have checkmarks in them. This is confusing because it appears that all the options have been “selected.” We'd like to display the Polls Options in the same way as the Research Survey Options (with empty radio buttons).

Current display:
![4 2 Polls_sm](https://user-images.githubusercontent.com/118769169/208488552-b5dbdbb0-ab65-433b-8684-294784de272f.png)

Change to:
![4 2 Research Survey_sm](https://user-images.githubusercontent.com/118769169/208488609-d222f652-fb35-4b4c-8a0a-06d6f774cdab.png)

Thanks,
Kim

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.47

**Comment by knguyenjahiel** [comment]
@mihail-varbanov & @yoonlees, thank you! I'm closing this item for now and suggest to have a UXD discussion at a later date with the UXD team. I hope I didn't cause you too much work! Kim
