### ISSUE TITLE
[BUG] 4.2.44 - failed to load research questionnaire

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2803]
After onboarding I got the invitation to participate in research.

I tapped "Yes".

Then I got "Failed to load research questionnaire."

Pixel 3 prod build v2.44

![failed to load questionnaire](https://user-images.githubusercontent.com/66988329/208499851-bb15172c-e037-4eb1-b3ba-93f0c2a7a01f.png)

**Comment by mihail-varbanov** [comment]
@joegrohens, research questionnaire content was not uploaded on production. Now it is. Please check it again. This is not related to any client development and particular app version, this was rather dev ops work.

**Comment by joegrohens** [comment]
it works now
