### ISSUE TITLE
[BUG] Sub-item Toggles under New MyMcKinley Appointment Notification Settings not responsive

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2805]
**Describe the bug**
Toggles for sub items under New MyMcKinley Appointments Notification Settings are not responsive when New MyMcKinley Appointments is Checked.

**To Reproduce**
1. Notifications > My Notification Preferences
2. Toggle New MyMcKinley Appointments to "Check"
3. Error: cannot change toggles for individual sub items

**Expected behavior**
When New MyMcKinley Appointment is checked, I should be able to change the toggles for individual sub items.

**Screenshots**
![Notification Preferences](https://user-images.githubusercontent.com/118769169/208529416-88294e52-68a7-4f9b-8a7a-96e8fd37a422.png)

**Desktop (please complete the following information):**
  - Version 4.2.44

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.47. As of the moment of writing this message - only in dev environment.

**Comment by knguyenjahiel** [comment]
Fix verified in 4.2.47 publicly released version. Thank you!
