### ISSUE TITLE
[BUG] 4.2.44 All Groups failing to load, My Groups not listing at Privacy Levels 4 & 5  

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2806]
**Describe the bug**
- All Groups failed to load at all Privacy Levels in 4.2.44. Error message: Failed to load groups.
- Groups of which I am a member or admin do not display. Error message: You are not a member of any groups yet

**To Reproduce**
1. Set Privacy Levels to 1, 2, 3, 4, or 5
2. Browse > Groups > All Groups 
3. Error message: "Failed to load groups"
4. Set Privacy Levels to 4 or 5
5. Browse > Groups > My Groups
6. Error message: You are not member of any groups yet

**Comment by knguyenjahiel** [comment]
All Groups and My Groups are loading/displaying as they should, now. Not sure why...

**Comment by pmarkhennessy** [comment]
@knguyenjahiel This appears to be working now. It was broken earlier today, Monday 2022/12/19. If this is still an issue please re-assign this to me.

**Comment by knguyenjahiel** [comment]
@pmarkhennessy I'll take a look at it tomorrow (2022/12/20). It does appear to be working, now. Not sure what broke it today (2022/12/19). Thanks for your hard work!

**Comment by knguyenjahiel** [comment]
@pmarkhennessy All Groups and My Groups are displaying properly. Thanks!
