### ISSUE TITLE
[BUG] Starring MTD stops--no relationship to overarching compound stop?

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2822]
In 4.2.44 (Android Pixel 6) for MTD under All Stops, I would expect the overarching bus stop card to automatically be starred if I have the two stops within that card starred. See screenshot.

When all three are starred, I would also expect to see the two stops included within that overarching stop to show up **once** under My Stops (rather than twice—see screenshot). 

![Screenshot_20221220-105601](https://user-images.githubusercontent.com/1044905/208732724-5cf03a8a-d73f-43c9-ab0c-79a6c7d0ab5e.png)
![Screenshot_20221220-105631](https://user-images.githubusercontent.com/1044905/208733111-71f2eb1a-9c87-46f8-8494-fa2c3e9760c7.png)

**Comment by mihail-varbanov** [comment]
Fixed in version 4.2.47.

**Comment by vburgett** [comment]
Confirming—this is updated in v4.2.47. Thank you!
