### ISSUE TITLE
[USABILITY] "Favorites Tutorial" title conflicts with title card in background

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2823]
See the Favorites Tutorial video widget at the top of the Favorites screen.

![favorites tutorial copy](https://user-images.githubusercontent.com/66988329/208734017-47739daa-c760-4577-b4b6-b1302f96c4c0.png)

Although the title card has been masked with a gray overlay, the words on the title card still conflict with the white type above the play button.

Can you remove the overlaying title "Favorites Tutorial", but leave the play button?

And then, can you please remove the masking on the **title card** so that the type and color of the image display the same as in the "Video Tutorials" favorites widget? 

![favorites tutorial in faves widget copy](https://user-images.githubusercontent.com/66988329/208735273-d129d73c-166b-4ef8-8b6f-950e26a72b89.png)

**Comment by joegrohens** [comment]
@dobromirdobrev @pmarkhennessy 

The overlaid title has been removed from the Favorites Video. (You call it the "Welcome Video" in #2831)

However - The title card image still has a gray mask making the color brown and the printed title gray. Can you replace the image used in this top position (Welcome Video, as you call it) to be the same image used as the title card for "Favorites Tutorial" in the favorites widget for Video Tutorials?

I am attaching the image file here.

![Favorites - Customizing](https://user-images.githubusercontent.com/66988329/208988848-ba5d685a-ac78-4ab6-8430-35ccb2840353.jpg)

**Comment by joegrohens** [comment]
And thank you!

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,
We already use the same image. There was a dimmed foreground decoration so that the play button contrasts with the text.

Now this foreground decoration is removed and we show the original images as are.
I left the play button. Please verify with version 4.2.28 and let us know your thoughts. Thanks.

**Comment by joegrohens** [comment]
fixed in 4.3.13
