### ISSUE TITLE
[BUG] McKinley Appointments not showing

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2824]
I have uploaded multiple appointments to my account in prod, receiving a 200 status with each push with a response content of "Success". None of the appointments are showing up in the application.

JSON being pushed:
[{
	"source_id": "101",
	"provider_id": "1",
	"appointment_date_time": "2022-12-21T19:00:00.000Z",
	"cancelled": false,
	"type": "InPerson",
	"location": {
		"id": "McKinley Health Center, West 2 Clinic, Second Floor",
		"title": "McKinley Health Center, West 2 Clinic, Second Floor",
		"latitude": 40.10295291956433,
		"longitude": -88.21989804371852,
		"phone": "217-333-2700"
	},
	"account_id": "35c09746-a3dc-11ec-bf06-0a58a9feac02",
	"host": {
		"first_name": "Future",
		"last_name": "Appt APRN, CNP"
	},
	"online_details": null,
	"instructions": "This is a future in person appointment"
}, {
	"source_id": "102",
	"provider_id": "1",
	"appointment_date_time": "2022-12-01T19:00:00.000Z",
	"cancelled": false,
	"type": "InPerson",
	"location": {
		"id": "McKinley Health Center, West 2 Clinic, Second Floor",
		"title": "McKinley Health Center, West 2 Clinic, Second Floor",
		"latitude": 40.10295291956433,
		"longitude": -88.21989804371852,
		"phone": "217-333-2700"
	},
	"account_id": "35c09746-a3dc-11ec-bf06-0a58a9feac02",
	"host": {
		"first_name": "Past",
		"last_name": "Appt APRN, CNP"
	},
	"online_details": null,
	"instructions": "This is a past in person appointment"
}, {
	"source_id": "103",
	"provider_id": "1",
	"appointment_date_time": "2022-12-23T19:00:00.000Z",
	"cancelled": true,
	"type": "InPerson",
	"location": {
		"id": "McKinley Health Center, West 2 Clinic, Second Floor",
		"title": "McKinley Health Center, West 2 Clinic, Second Floor",
		"latitude": 40.10295291956433,
		"longitude": -88.21989804371852,
		"phone": "217-333-2700"
	},
	"account_id": "35c09746-a3dc-11ec-bf06-0a58a9feac02",
	"host": {
		"first_name": "Future",
		"last_name": "Appt APRN, CNP"
	},
	"online_details": null,
	"instructions": "this is a future cancelled appointment"
}, {
	"source_id": "104",
	"provider_id": "1",
	"appointment_date_time": "2022-12-22T15:00:00.000Z",
	"cancelled": false,
	"type": "Online",
	"location": {
		"id": "McKinley Health Center, West 2 Clinic, Second Floor",
		"title": "McKinley Health Center, West 2 Clinic, Second Floor",
		"latitude": 40.10295291956433,
		"longitude": -88.21989804371852,
		"phone": "217-333-2700"
	},
	"account_id": "35c09746-a3dc-11ec-bf06-0a58a9feac02",
	"host": {
		"first_name": "Kim",
		"last_name": "Smith APRN, CNP"
	},
	"online_details": {
		"url": "https://zoom.link.here/a/b/c",
		"meeting_id": "",
		"meeting_passcode": ""
	},
	"instructions": "this is a future telehealth appt"
}]

This was tested with build 4.2.45 on production.

**Comment by dobromirdobrev** [comment]
Hi @clint156 ,
It was a mistaken production url. The fix was applied in app config so no new build is required. Please just "kill" and re-launch your existing app to verify if it's fixed. Thanks.

**Comment by clint156** [comment]
Verified Fixed with the 4.2.45 production build.
