### ISSUE TITLE
[USABILITY] MTD bus stop cards leading to a schedule is inconsistent

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2825]
When tapping on an MTD bus stop card, I expect to see the bus schedule. The attached screenshots show in red when a tap does NOT lead to a bus schedule and in green where a tap leads to a bus schedule. I would expect the circled red options to lead to a bus schedule.
4.2.45 Android Pixel 6
![Screenshot_20221220-140011](https://user-images.githubusercontent.com/1044905/208758710-d564aae3-ec76-4d9d-9321-2c6eaa057ab9.png)
![Screenshot_20221220-141348](https://user-images.githubusercontent.com/1044905/208758714-12c110e8-654f-44c5-a518-54319b352574.png)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.47 as part of the work in #2851.

**Comment by vburgett** [comment]
Confirming—this is updated in v4.2.47. Thank you!
