### ISSUE TITLE
[BUG] NetID and Sign-in prompted at Privacy Level 3 during onboarding 

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2826]
**Describe the bug**
During onboarding (with clean install), NetID and Sign-in are prompted for Privacy Level 3. NetID and Sign-in should be prompted only at Privacy Levels 4 & 5.

**To Reproduce**
1. Do a clean install
2. Begin "Control Your Data Privacy"
3. Toggle "Yes" for "Enable location services", select "While using app" or "Only this time" --> Continue
4. Toggle "Yes" for "Store my app activity and my preferences" --> Continue
5. Toggle "No" for "Don't share my activity" --> Continue
6. This will set Privacy Level at 3 --> Save Privacy Level
7. Error: Connect your NetID panel displays

**Expected behavior**
After touching "Save Privacy Level" (at Level 3), user should be taken to the Favorite panel.

**Screenshots**
Onboarding Privacy Level set at 3
![Screenshot (Dec 20, 2022 2_50_32 PM)](https://user-images.githubusercontent.com/118769169/208764429-ded4b511-b6a5-49e3-9ba1-44dcf3326663.png)

Prompt for NetID and Sign-in -- this panel should not display
![Screenshot (Dec 20, 2022 2_55_52 PM)](https://user-images.githubusercontent.com/118769169/208764892-a27abbb2-cac3-4160-b21e-ac95e12783a4.png)

**Smartphone (please complete the following information):**
 - Version 4.2.45

**Comment by mihail-varbanov** [comment]
Fixed in version 4.2.47.

**Comment by knguyenjahiel** [comment]
Resolution verified. Thank you!
