### ISSUE TITLE
[BUG] Privacy level3 - View poll results Server response error

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2827]
**Describe the bug**
"Server Response Error:401 Unauthorized" is displayed when a user with Privacy level 3, taps on the View poll

**To Reproduce**
1. Install Illinois app
2. User with Privacy level 3
3. Navigate to Browser -> POll and tap on View poll

**Actual Result**
"Server Response Error:401 Unauthorized" is displayed when a user with Privacy level 3, taps on the View poll

**Screenshots**
![poll er](https://user-images.githubusercontent.com/26231179/208769185-97fbbe15-dd01-4c24-a60c-487eac78244d.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. android]
 - Version [e.g. 4.2.45]

**Comment by joegrohens** [comment]
Similar to #2777
