### ISSUE TITLE
[USABILITY] Text edit: change "Event" to "Events" 

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2829]
In Global Group Notifications and Individual Group Customed Notifications, please change "Event" to "Events".

Screenshots
![Screenshot_20221220-174739](https://user-images.githubusercontent.com/118769169/208789797-a31175f9-9fc2-4246-b6f7-e79b826363ef.png)

![Screenshot (Dec 20, 2022 5_48_02 PM)](https://user-images.githubusercontent.com/118769169/208790051-14f5bd1b-d157-45f3-ab17-34befe6b85cc.png)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.27

**Comment by knguyenjahiel** [comment]
Resolution verified. Thanks!
