### ISSUE TITLE
[USABILITY] Text edit: change "View Email" to "View Email Address" 

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2830]
**Describe the usability issue**
In Group Settings --> Advance Settings (only displayed for group admin), please change "View Email" to "View Email Address"

**Screenshots**
![Screenshot (Dec 20, 2022 6_20_46 PM)](https://user-images.githubusercontent.com/118769169/208792323-c9c6c6db-8b78-473b-9e9a-a4674fa81997.png)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.27

**Comment by knguyenjahiel** [comment]
Resolution verified. Thank you!
