### ISSUE TITLE
[BUG] Groups - Reporting obscene, threatening, or harrassing content to group admin - not working

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2838]
In prod build 4.2.45 - showstopper

As a group admin, I am not getting a notification of bad content. Does this occur via a notification or an email?  I get neither. Although, I am both the person reporting and an admin. Will keep testing it with others.

**Comment by pmarkhennessy** [comment]
![Screenshot_20221221-111236](https://user-images.githubusercontent.com/5613085/209004817-edd4713c-cd79-40ce-899b-d6aff0e8a1dd.png)
![Screenshot_20221221-111318](https://user-images.githubusercontent.com/5613085/209004831-5f7d47dc-2e8e-4d9c-8269-b63131de4be1.png)
@kpecknold I cannot reproduce this issue.

**Comment by kpecknold** [comment]
@pmarkhennessy Does it only work for members?  Admins should be able to report to Dean of Students at the very least. It would be ok if an admin could report to admins, as there may be multiple admins.

**Comment by kpecknold** [comment]
tested in 5.0.65
