### ISSUE TITLE
[BUG] Onboarding design + content revisions 2.4.16

### ISSUE THREAD

**Issue by AlliePixo** [rokwire/illinois-app#284]
Annotated in Miro are a list of the found inconsistencies from the initial designs to the 2.4.16 APK 

**UI inconsistencies:** https://miro.com/app/board/o9J_l_3DyGs=/?moveToWidget=3074457360021281649&cot=14
**Content inconsistencies:** https://miro.com/app/board/o9J_l_3DyGs=/?moveToWidget=3074457360021357031&cot=14

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
