### ISSUE TITLE
[BUG]  Maps Showstopper in 4.2.26

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2841]
1. Residence Hall Dining never loads in maps
2. McKinley appts never loads in maps if you follow these steps"

1. Go to Maps, choose MyMcKinley appts, see map
2. Tap Wellness
3. Tap back to Map
4. Map never loads

**Comment by pmarkhennessy** [comment]
@mihail-varbanov I agree dining map does not work. Also, the 2nd issue is a problem with Events also. It seems being in a map and then using the Nav bar to go away from maps, then Nav bar back to map is an issue for Appts and Events.

**Comment by mihail-varbanov** [comment]
These both issues must be fixed in version 4.2.47.

**Comment by kpecknold** [comment]
Confirmed fixed in 4.2.47
