### ISSUE TITLE
[BUG] MyMckinley appointments are going to midnight when added to the calendar

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#2842]
**Describe the bug**

Create a MyMckinley appointment, Star the appointment and allow it to add to your calendar.
The end time will be shown as midnight.
I believe this is a result of no end time for appointments as part of the json being supplied to or required by the building block.
Can we default the length of meetings to 1 hour when adding meetings to the calendar?

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.48

**Comment by clint156** [comment]
Verified fixed in 4.2.49
