### ISSUE TITLE
[BUG] Privacy Level 3 - Users - App results users not signed in 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2844]
**Describe the bug**
Though the users with privacy level 3 signed in while onboarding, the app shows users are not signed in.

**To Reproduce**
1. Install the Illinois app
2. Users are set with privacy level 3 and sign in as University students with their netid/pwd

**Actual Results**
Though the users with privacy level 3 signed in while onboarding, the app shows users are not signed in.

Though a user with privacy level 3 signs in while onboarding, On the favorite screen, displays
 "You are not logged in" for Myresearch participation" and Polls section displays with the "Login" button"

**Expected behavior**
The app should display as users are logged in with their details.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version - 4.2.46

**Comment by mihail-varbanov** [comment]
@Priyaravi8, you have observed a side effect of #2841. It must be fixed now in version 4.2.47.

**Comment by Priyaravi8** [comment]
This is fixed
