### ISSUE TITLE
[USABILITY] Better wording for "Failed to load research projects".

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2845]
**Describe the usability issue**

The language in "Open Research Projects" favorites widget could be improved.

When there are no research projects, the Open Research Projects favorites widget says "Failed to load research projects".

![failed to load research projects copy](https://user-images.githubusercontent.com/66988329/209002547-fa4a5589-a2f8-4364-b43b-28ceb9392906.png)

This language sounds like a system error. 

**Suggested:**
Use the language that is used in Browse > Research at Illinois > Open Research Projects:

"There are no opened research projects at the moment."

![there are no research projects copy](https://user-images.githubusercontent.com/66988329/209002776-952fe798-ccbf-4ed0-9a36-0d3db6424f38.png)

**Comment by pmarkhennessy** [comment]
@joegrohens I believe this error is that the API call failed, not there are no projects. @mihail-varbanov please confirm.

@joegrohens, wouldn't "open" be better than "opened"?

**Comment by joegrohens** [comment]
@pmarkhennessy 

Yes, Mark. "Open" would definitely be better than "opened".

I have entered the phase of "request the minimal and what seems easiest".  :-)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.27

**Comment by joegrohens** [comment]
Confirmed fixed in 4.2.47
