### ISSUE TITLE
[BUG] All Notifications Favorite widget ends with an empty card and spinning progress wheel

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2846]
In v4.2.46 on Android, I have five notifications from today, and I am seeing those five notification cards in the All Notification favorite widget. However there is a sixth card at the end of the horizontal scroll that is blank with a spinning progress wheel (see screenshot). 

I would expect this widget to show all notifications from the past starting with the most recent OR show a set number of my most recent notifications (a user can use "View All" if they want to go back further.)
 
![Screenshot_20221221-155446](https://user-images.githubusercontent.com/1044905/209010504-98628709-585e-465c-b1a3-688163d895b3.png)

**Comment by dobromirdobrev** [comment]
Fixed in version 4.2.47. Please verify.

**Comment by vburgett** [comment]
Confirming—this is updated in v4.2.47. (It appears as though the logic for the All Notifications Favorites widget is to scroll through past notifications indefinitely. Noting this in case it's useful in the future.) 

Thank you!
