### ISSUE TITLE
[BUG] Unread Notification Favorites widget: default text is inaccurate

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2847]
In v4.2.46, the Unread Notifications Favorites widget defaults when empty to text that says "Notifications are available right now." See below screenshot. 

I would expect this text to say "You have no unread notifications. View all notifications." with the entire last sentence underlined and linked to Settings > All Notifications. 

![Screenshot_20221221-155324~2](https://user-images.githubusercontent.com/1044905/209010871-4686aeef-25b1-488a-9294-24e116fa40e3.png)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.47.
