### ISSUE TITLE
[BUG] Illinois Health Screener: wrong name under Browse Wellness

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2848]
Under Browse > Wellness, please rename "Wellness Health Screener" to "Illinois Health Screener" and move it under "Daily Tip" to keep the list in alphabetical order. 

v4.2.46

**Comment by mihail-varbanov** [comment]
Fixed in version 4.2.47.

**Comment by vburgett** [comment]
Confirming—this is updated in v4.2.47. Thank you!
