### ISSUE TITLE
[USABILITY] Update language in invitation to participate in research

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2849]
**Describe the usability issue**

Feedback suggests that the language in the invitation to participate in research is misleading.

This screen is displayed after startup for the first time.

![res participation prompt copy](https://user-images.githubusercontent.com/66988329/209029603-6173f6dd-83ce-4351-8634-e2dd36b03e38.png)

Bill Sullivan has revised the text of this dialog box. Please replace the current two paragraphs with the following text.

> Illinois is one of the world’s great research universities. As a member of the university, you can help scientists answer questions that lead to new discoveries. 

> Would you like to get invitations to become a research participant via the Illinois app? Many studies offer incentives. 

@RokBill

**Comment by mihail-varbanov** [comment]
Resolved in 4.2.47

**Comment by joegrohens** [comment]
confirmed fixed in 4.2.47
