### ISSUE TITLE
[BUG] Add Image button needs white background

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2868]
When creating a Group and uploading a cover image, the Add Image button does not have a white background. I expect it to in order for a user to be able to see and read the button. 

4.2.47
Android Pixel 6

![Screenshot_20221222-131841.png](https://user-images.githubusercontent.com/1044905/209211669-fc3465a1-f478-4ca7-8f9b-a3c5987f5904.png)

**Comment by mihail-varbanov** [comment]
Fixed in 4.2.48

**Comment by vburgett** [comment]
Complete in 4.2.52—thank you!
