### ISSUE TITLE
[USABILITY] Revise the confirmation message after completing demographic survey

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2873]
Per Bill Sullivan, please revise the confirmation message that appears after a user completes the demographic survey for potential research participation.

After submitting the survey, the following screen appears.

![thank you research screen copy](https://user-images.githubusercontent.com/66988329/209233814-de7e0dfd-1e01-48d7-8fcf-da1897b1f0cf.png)

We want to leave the first paragraph as is, and delete the second paragraph.

> View current research studies that match your completed Research Interest Form under "Browse > Research at Illinois. Opt in and become the study's recruitment pool.

@RokBill

**Comment by mihail-varbanov** [comment]
Resolved in version 4.2.48.

**Comment by joegrohens** [comment]
Verified fixed in V4.3.13.
