### ISSUE TITLE
[BUG] Yes-No buttons are cut-off in the "Your New Privacy" confirmation screens at levels 1 and 2 (4.2.47 publicly released)

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#2891]
**Describe the bug:**
Yes-No buttons are cut-off in the Your New Privacy screens at levels 1 and 2. User unable to finalize privacy level settings. 
*Please note*: 
1. Bug appears on iPhone SE, iOS 15.6.1; not on Android.
2. Previous versions did not have this bug.

**Steps to reproduce the behavior:**
1. Go to Profile -> My App Privacy Settings
3. Select 1 on the privacy level slider (Repeat for level 2)
4. Touch Set My Privacy button
5. See error

**Expected behavior:**
The Yes-No buttons should completely fit on Your New Privacy Level confirmation screen for levels 1 and 2.

**Screenshots:**
![Privacy Setting 1 cut-off](https://user-images.githubusercontent.com/118769169/210657624-2c133f5e-e6cb-4df1-ab95-fd39a3211ef5.png)

![Privacy Setting 2 cut-off](https://user-images.githubusercontent.com/118769169/210657664-73538b33-ae2d-4a05-a21d-f9b1aacbc975.png)

- Version: Publicly Released 4.2.47

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 15.6.1

**Comment by mihail-varbanov** [comment]
Fixed in version 4.2.49*.
* Please note that in smaller screens it is possible the content not to fit vertically. In this case it is cut off but the user is able to scroll it.

**Comment by knguyenjahiel** [comment]
It's odd that the content previously fit properly in 4.2.27-prod

**Comment by mihail-varbanov** [comment]
Most probably the bullets list content had been extended after 4.2.27. Anyway, it is a lost fight to try to fit some content on any device screen as they can vary too much.

**Comment by knguyenjahiel** [comment]
I made a mistake. I meant 4.2.47-prod (the last test version)

**Comment by mihail-varbanov** [comment]
No, the content did not fit in 4.2.47 and it is seen on the screenshots that you have attached. The problem was that this raised an excepion that leaded to this inconsistent look. Currently in 4.2.49 only the bottom gutter beneath the Yes and No buttons does not fit on iPhone SE screen so the user does not have to scroll.
