### ISSUE TITLE
[BUG] i-card incorrectly showing as expired 

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#2892]
A user reported that their i-card is showing as expired in the Illinois app, but the card is actually not expired.  This person actually has a "retired faculty/staff" card, which does not contain an expiration date. I believe the logic needs to be updated to correctly handle an empty expiration date.

670565234

**Comment by mihail-varbanov** [comment]
Fixed in version 4.2.49

**Comment by mihail-varbanov** [comment]
FYI, I just noticed that web.housing.illinois.edu service returns "Users has an expired I-Card" as AccountStatus in IlliniCash eligibility when the expiration date is an empty string (that is my case, UIN: 655618818). Maybe @clint156 should fix this on the backend either. This status is currently observable in Illini Cash and Meal Plan cards in Wallet widget in Favorites tab.
