### ISSUE TITLE
[BUG] Phone verification / Shibboleth login fails after multiple logins

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#29]
**Describe the bug**
For users who are using both methods to login, we might be reusing their UUIDs which could result in missing UUIDs at top of the list in their PII records.

**To Reproduce**

1. Select your role as student or employee during the onboarding screen
2. Skip login using Shibboleth during the onboarding process
3. Go to Settings screen
4. Click on "Verify your phone number" and complete phone number verification 
5. Click on "Disconnect your phone"
6. Click on "Connect your NetID" and login using Shibboleth
7. In "Personal info" screen click on "Remove my information"
8. Select your role as student or employee during the onboarding screen
9. Skip login using Shibboleth during the onboarding process
10. Go to Settings screen
11. Click on "Verify your phone number" and try to complete the phone verification
12. "Failed to verify code" error appears in the app

**Expected behavior**
Phone verification should complete successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/4306604/84161797-4a043600-aa35-11ea-9dce-10b1dd0597e8.png)

**Smartphone (please complete the following information):**
 - Device: Android and iPhone
 - Version 2.0.39/2.0.40

**Additional context**
It looks like the issue here is that we are reusing UUIDs after the user "disconnects their phone". Now, if the user logs in using Shibboleth and clicks on "Remove my information" both their new PID as well as the previous UUID gets deleted. After this, when they try to login using phone verification, there is a situation where the first UUID in the PII record is missing in the Profile database, since it got deleted during "Remove my information".

This behavior is not appearing if the user does Shibboleth login first, then sign out, does phone verification next, removes their information and then does Shibboleth login again. So, most likely this case is applicable only for the specific situation mentioned in this bug report. @Priyaravi8 had this issue couple of times and we fixed this in the database. I also saw at least 2-3 other users in the same situation when I checked the database. So, people are running into this, though this is not frequent.

**Comment by mdryankov** [comment]
@sandeep-ps this is a regression of two issues:
1. Mark asked to keep the profile until next login (which produces the duplication mapping) Feb 24
2. POST ​/profiles​/pii API which expected user uuid

In order to fix the above issue we need to stop providing uuid in POST ​/profiles​/pii API. Also this API will create profile & profile pii pair only once at the beginning based only on email or phone params. In this way we will drop any possibility to duplicate uuid mapping between netId & phone authentications.

What do you think?

CC @mihail-varbanov @pmarkhennessy

**Comment by sandeep-ps** [comment]
In my opinion, we should not be keeping the UUID after one user signs out. At that time, any other user could sign in, right? For example, one user giving the phone to a friend to try it out. When a user signs out, can we do the following from the app?

1. Remove local copy of previous UUID
2. Make a call to /profiles to get new UUID and use the default data to populate Non-PII content. This way we will be ready for whoever is going to sign in the next time. If the same person signs in again, we will get back the UUID. If a different user signs in, we will potentially create a new PII profile.

**Comment by mdryankov** [comment]
If I understand correctly - In your propose the user will have one profile record  for each clean install and another profile record for each logout in order to cleanup the old state. 
In my propose above the idea is to create  single record on fresh install and keep it as backup storage. On login -> the client will load the first from pii. Once logout the client will start using the backup profile again

**Comment by sandeep-ps** [comment]
The initial idea was to keep PII and Non-PII profile endpoints separate as they refer to accessing personally identifiable and non-personally identifiable data. So, combining that into one (if that was the suggestion), will change that basic structure. 

Based on my understanding of your suggestion, how will you create a new profile before user log in? There are preferences/likes a user can set without signing in, right? According to your idea, could you please describe the calls to the profile building block that you plan to make right after a user installs the app?

**Comment by mdryankov** [comment]
@sandeep-ps I tried to use create profile on each logout. but it produces a lot of troubles. E.g the user lose everything even the privacy level & selected user roles and observed a lot of unpredicted cases in the UI. Actually that was the reason to keep the profile until the next login without breaking the UX.

**Comment by mdryankov** [comment]
@sandeep-ps, I have applied that fix and now the client will create new profile after logout and will migrate the savings there
It's testable with 2.2.18

**Comment by pmarkhennessy** [comment]
@mdryankov Is this all done now? If so please assign back to @sandeep-ps so he can close it please

**Comment by mdryankov** [comment]
Yes. It has been applied already. Assign it back to @sandeep-ps  cc @pmarkhennessy

**Comment by sandeep-ps** [comment]
Currently, I'm unable to test this as "Remove my information" is not present in the Privacy Center of Illinois app 2.2.18 (#46). Checking with @pmarkhennessy on if there is a feature change. I will close this issue after testing this.

**Comment by sandeep-ps** [comment]
Please disregard my above message. Found the "Forget all my information" button after chatting with Mark. I tested this again and can confirm that this issue has been fixed. Closing. Thanks.
