### ISSUE TITLE
[BUG] My Courses: Fall 2023 link broken

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2901]
When choosing "Fall 2023" from the drop-down menu, it leads to Spring 2023. I expect it to lead to a message about having no courses for Fall 2023. 

This is an issue in the Favorites widget and on the My Courses screen. 

iPhone 13 Pro
iOS 16.0.2
V 4.2.47

![image](https://user-images.githubusercontent.com/1044905/211158729-5e349803-e382-4681-b031-0fcb898e5a46.png)

**Comment by dobromirdobrev** [comment]
This is not an app issue.

Hi @clint156 ,
The problem here is a result of that the Gateway BB returns the same `termid` for `Spring - 2023` and `Fall - 2023`.

Example:
GET: `/gateway/api/termsessions/listcurrent`
Response code: `200`
Response body:
```
[
  {
    "term": "Fall - 2022",
    "termid": "120228",
    "is_current": false
  },
  {
    "term": "Spring - 2023",
    "termid": "120231",
    "is_current": true
  },
  {
    "term": "Summer - 2023",
    "termid": "120235",
    "is_current": false
  },
  {
    "term": "Fall - 2023",
    "termid": "120231",
    "is_current": false
  }
]
```

Here the UIUC app would expect different `termid` for `Spring - 2023` and `Fall - 2023`.

**Comment by clint156** [comment]
As of 2/21/2023 a new version of the building block is on dev. Pointing 4.2.52 to dev though, I'm still seeing that when I select Fall 2023, it returns back to Spring 2023. I have verified that https://api-dev.rokwire.illinois.edu/gateway/api/termsessions/listcurrent does return the correct information now.
[{"term":"Fall - 2022","termid":"120228","is_current":false},{"term":"Spring - 2023","termid":"120231","is_current":true},{"term":"Summer - 2023","termid":"120235","is_current":false},{"term":"Fall - 2023","termid":"120238","is_current":false}]

**Comment by vburgett** [comment]
This appears to be working in 5.0.57. @clint156 if you agree, can you close this ticket? Thank you!
