### ISSUE TITLE
[BUG] No building names for MTD destinations

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2902]
When adding a campus building as an MTD destination by starring it under Map > MTD Destinations, the building name shows up as "Location" with coordinates and no building name or address. This is also true for the My MTD Destinations Favorites widget. 

I expect to see the building name at a minimum plus the address, if possible. 

See attached screenshots for the locations: Siebel Center for Design and Krannert Center for the Performing Arts. CC: @clint156 

Version 4.2.47
iOS 16.0.2
iPhone 13 Pro

![image](https://user-images.githubusercontent.com/1044905/211234616-fb4514ab-9bb9-4343-9178-ed8cf36acfe8.png)

![image](https://user-images.githubusercontent.com/1044905/211234624-2be46467-b929-4888-853a-147b28eb7a87.png)

![image](https://user-images.githubusercontent.com/1044905/211234626-d708e1c1-5a5d-4722-bbfa-dccb614809f4.png)

![image](https://user-images.githubusercontent.com/1044905/211234638-a4cc82f0-c930-4cfe-b3b3-337ee1e16c10.png)

**Comment by mihail-varbanov** [comment]
@vburgett, when you type inside a building the notification that GoogleMaps fires is the same as if you have typed on a green field - just the two location coordinates and nothing else. However if you type on a building marker (or whatever other marker placed by Google) we get a different notification that contains the tapped place name. In this case we store this name for for the saved favorite location.

Example: Univ Illinois Library Urbana-Chmp

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-20 at 14 24 34](https://user-images.githubusercontent.com/5631487/220108088-94fe03ae-f7ca-42ac-93bd-b717a3546260.png)

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-20 at 14 23 37](https://user-images.githubusercontent.com/5631487/220108166-9540b930-7874-4ef4-91c4-19a186177d74.png)
