### ISSUE TITLE
[USABILITY] Wrong notification text under My MTD Destination

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2903]
Under My MTD Destinations there is a toggle to turn on notifications for upcoming events. I would like to provide new text. What type of notifications does this toggle actually provide? 

Version 4.2.47
iPhone 13 Pro iOS 16.0.2
![image](https://user-images.githubusercontent.com/1044905/211235318-5be751ef-4876-48b7-b733-d19c2ef9507a.jpeg)

**Comment by vburgett** [comment]
@mihail-varbanov I agree. Have you already "removed this switch from the Saved panel, for all favorite types"? If not, let's proceed with that update. Thank you!

**Comment by mihail-varbanov** [comment]
Removed in version 4.3.52.
