### ISSUE TITLE
[USABILITY] Change wording of "Display ADA accessible building entrances for My Courses"

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2918]
@vburgett - what do you think of this change?

**Problem**

The setting _Profile > "Display ADA accessible building entrances for My Courses"_ is potentially misleading.

The description implies that a symbol will indicate ADA entrance locations on a map.

According to JP, the maps will not actually indicate the location of ADA-accessible entrances. Maps will, however, provide directions to one of a building's ADA-accessible entrances when this setting is turned on.

**Recommendation**

Change the wording of this setting to:

"Navigate to ADA accessible building entrances for My Courses"

![Profile Display ADA copy](https://user-images.githubusercontent.com/66988329/212904734-39eede5e-4381-4f01-afb9-c5654fa9dbb9.jpeg)

**Comment by vburgett** [comment]
Your new text is clearer. Thank you, @joegrohens.

**Comment by joegrohens** [comment]
This text has been updated.
