### ISSUE TITLE
[USABILITY] Add padding to notification number and red circle

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2919]
To improve readability of the notification number, please increase the padding around the number and the circle's edge. See below screenshots. 

Version 4.2.47
iPhone 13, iOS 16.0.2

Illinois app
![image](https://user-images.githubusercontent.com/1044905/212973098-be8807ad-0da8-4fc3-98ca-17f6c022514d.jpeg)

Facebook example to match
![image](https://user-images.githubusercontent.com/1044905/212973153-41dfb491-9c69-4c71-934b-0e3d278f95b0.jpeg)

**Comment by TodorBachvarov** [comment]
Padding has been increased in version 4.3.43.

**Comment by vburgett** [comment]
Fixed in 4.3.47—thank you!
