### ISSUE TITLE
Potential bug with Z Fold??

### ISSUE THREAD

**Issue by nelshopp** [rokwire/illinois-app#2920]
I have received two tickets from customers in the last couple of days who use the Samsung Galaxy Z Fold.  They are experiencing Illinois app crashing upon launching. I just want to make this isn't indicative of something larger.    

Both customers say there are issues with crashing as soon as the app is launched.  Here is a quick look at both situations:

**Netid: gavinh4**
Model: Samsung Galaxy Z Fold 3
OS:
App version:  4.42.47
Behavior:  App closes immediately upon launching.  
Errors:  feedback reports this… exception class name is "java.lang.NoSuchMethodError”

**Netid: mathhar2**
Model: Samsung Galaxy Z Fold 4
OS: Android 13
App version:  4.42.47
Behavior: App closes immediately upon launching.  Screenshot attached. 
![image](https://user-images.githubusercontent.com/91676531/212998189-69294ece-4d66-45b0-afed-c8e298c6fd52.png)

This has worked in the past for both customers.

Let me know if you need further information.  

thanks!

Tom

**Comment by dobromirdobrev** [comment]
This crash should be fixed in version 4.3.4. Please verify and let us know. Thanks

**Comment by nelshopp** [comment]
This is indeed fixed per a customer who tested for me.
