### ISSUE TITLE
[BUG] Group Member Totals Display Incorrectly under My Groups Favorite Widget

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2939]
When viewing your Groups in the My Groups Favorites widget, the member totals are wrong. I expect the number to be accurate in the widget. 

See member numbers shown in this screen recording of version 4.2.47 on an iPhone 13 Pro (iOS 16.0.2) The My Group member tally for the three Groups does not match the actual, correct number tally shown on the specific Group panel. 

Adventures of Loki has 7 members and Illini Squirrel Enthusiasts has 985 but those numbers are reversed in the Favorites widget. 

I just approved a few members for Gus totaling 135 members but the My Groups Favorites widget shows 132. 

https://user-images.githubusercontent.com/1044905/214464445-7e00eb21-04b6-4da6-9e2a-ca469f6a950a.MOV

**Comment by mihail-varbanov** [comment]
Fixed in version 4.3.25.
