### ISSUE TITLE
[BUG] Specific Group Notification Settings Not Working for Group Admin

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2949]
For the Group "Illinois App Student Input: Share Your UX with App Design Team" (admin status) and "Illini Squirrel Enthusiasts" (member status), I can not tap on any of the five toggles to override my Group's global notification settings. 

I expected to be able to adjust my Group settings by the toggles being tappable in both Groups. 

iPhone 13 Pro
iOS 16.3
Version 4.2.47

![image](https://user-images.githubusercontent.com/1044905/215933550-4a0a8265-a3a9-4f52-b865-ec8b165651f4.png)

**Comment by mihail-varbanov** [comment]
@vburgett,
1. This behavior is as by design, as described in #2538;
2. Tapping the "My global group notification preferences" link on top of the panel navigates to the "My Notification Preferences" panel where these can be changed.
