### ISSUE TITLE
[BUG] Illinois App crashing while browsing through Dining

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#295]
**Describe the bug**
Illinois app is crashing while browsing through Dining screen with user role as University student

**To Reproduce**
1. Install the Illinois app
2. Complete onboarding steps and verify the role as a University student
3. Navigate the app to Dining

**Actual Result**
Illinois app is crashing 

**Expected behavior**
The app should not crash while browsing through the screen

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]

 -App Version [e.g. 2.4.19]

**Comment by kpecknold** [comment]
All of the dining halls are closed and there are no menus for the next 2 weeks. It's not handling the absence of a menu gracefully.

**Comment by mihail-varbanov** [comment]
Fixed in 2.4.24

**Comment by Priyaravi8** [comment]
This is fixed
