### ISSUE TITLE
[BUG] No Cropping for Cover Image When Creating An Event in Groups

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2950]
After uploading an image from my device to create a new event in a Group, I did not get the option to crop it like I do within the same UI for creating a new Group or a Group post. I expected to have the same cover image (tout) cropping option before the image uploaded when creating an event. 

iPhone 13 Pro
iOS 16.3
Version 4.2.47

@kpecknold

**Comment by TodorBachvarov** [comment]
This should be fixed.

**Comment by vburgett** [comment]
Complete in 4.3.46—thank you!
