### ISSUE TITLE
[USABILITY] Move To-Do List to Academics Section, Remove from Wellness

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2951]
Based on student input, we would like to move the To-Do List to be nested under Academics instead of Wellness. 

Please move the To-Do List to be listed under Browse > Academics and add it to the Academic section dropdown menu.
Please remove the To-Do List from Browse > Wellness and the Wellness section dropdown menu.

@dr-mel and I have discussed this.

**Comment by mihail-varbanov** [comment]
Implemented in version 4.2.53 & 4.3.17.

**Comment by vburgett** [comment]
Thank you!
