### ISSUE TITLE
[USABILITY] Update MTD text to include “Bus”

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#2952]
For our app users who are not yet familiar with “MTD,” please update the wording in the following locations:

**Browse > MTD **
- MTD Buses
- View MTD bus stop locations, routes, and availability.
    - All Bus Stops
    - My Bus Stops
    - My Destinations

**Browse > My**
- Change My MTD Destinations to My Destinations and move it to above My > My Dining Locations (alpha order)
- Change My MTD Stops to My Bus Stops and move it to above My > My Campus Guide (alpha order)

**Map Drop Down Menu**
- Change “MTD Destinations” to “My Destinations”
- Change “MTD Bus Stops” to “Bus Stops”

iPhone 13 Pro
iOS 16.3
Version 4.2.47

![image](https://user-images.githubusercontent.com/1044905/216150916-30436a13-984b-4b84-86be-25d936a0766f.jpeg) 

![image](https://user-images.githubusercontent.com/1044905/216150997-161f4f18-f590-4b84-aee9-dd143dc7120b.jpeg)

![image](https://user-images.githubusercontent.com/1044905/216150938-5279a702-c6ce-4f85-be18-b016e72827e1.jpeg)

**Comment by mihail-varbanov** [comment]
Resolved in 4.2.53 & 4.3.17

**Comment by vburgett** [comment]
Complete in v4.3.27. Thank you!
