### ISSUE TITLE
Improve geo wayfinding for ADA entrances

### ISSUE THREAD

**Issue by nelshopp** [rokwire/illinois-app#2955]
With an increased priority on more accurate wayfinding for ADA entrances, Rokwire wants to make sure the data we have is correct.  We have tested wayfinding to several ADA compliant entrances and have had a low success rate.  Either the app will take us to a non-compliant entrance, or it will loop us around the building past a compliant entrance.  

Best scenario:  with “Display ADA accessible building entrances for my “My courses” turned on, the Illinois app should wayfind the user to an ADA-compliant entrance that is closest to them and with the shortest distance.  

I am including some documents and screenshots which might be helpful.  If you need access to the Building and Ramp Survey Data, we can arrange that.  

Here are some notes from @joegrohens :  
“After looking up these entrance coordinates in Google Maps, I got the following results. 
(This is a screenshot of the Google map with my notes added manually.)

  
![google map view of six DCL entrances](https://user-images.githubusercontent.com/91676531/216652547-c49f033e-56b5-4010-b756-f606f79d9392.png)

And here is a screenshot of the Illinois app map showing its wayfinding directions for DCL. (I touched the pin on the DCL area of the Campus Buildings Map. Then I touched the Directions button in the resulting pop-up.)

 
![Illinois app wayfinding to DCL](https://user-images.githubusercontent.com/91676531/216652578-6974153a-b2b9-4e6e-af88-7ca6ec01ca0c.jpeg)

Based on the information in Chad’s entrance data spreadsheet, I am drawing the following conclusions.

1. When a user tries to navigate to the DCL building using Illinois app, the map tool directs them to the fourth entrance listed in the data set, which is near the loading dock. (40.11322137000, -88.22625476000)
 
2. This loading dock entrance is NOT marked as an “Accessible” entrance in Chad’s survey data. So, if Illinois app is using the data reflected in Chad’s spreadsheet, it is most likely an implementation error and not a data inaccuracy.

3. The two main entrances on the east and west sides of DCL, which most students use, and which have ADA signage and automated door openers, ARE marked as “Accessible” in this spreadsheet. It seems to me that Illinois app should navigate to one of these ADA entrances, depending on current location. (It does not.)

Therefore, it seems to me that we should really be looking into how the Illinois app is processing the data from Chad’s spreadsheet. Wherever the app directs a user to an entrance that the data set has designated as “NOT Accessible”, that should be viewed as a bug.

--- 
Please let us know if you need any further information.

**Comment by joegrohens** [comment]
Attached is an excerpt from buildinglist.json with my comments inserted. (Mark gave me this file.)

The building "Digital Computer Laboratory" (starts at line 10763 in the original buildinglist.json) is the building referred to as DCL in the problem report above.

The Illinois app directs ADA users to the loading dock of the building, which is not an ADA entrance. This is the third entrance in the list. (Line 10805 in the json file).  The json rule for this entrance is 

`"ADACompliant":` false,

So, it is an error that the app directs users there.

.............

My comments in the attached json refer to a "spreadsheet" - it means the data set that comes from University of Illinois Facilities and Services.

I thought that the entrance coordinates in buildinglist.json might be based on this University data set. I'm not sure now that I see the truncation of lat/long coordinates. The spreadsheet has 13-digit numbers; the json file has 7-digit numbers. And for some other buildings I looked at, there are significant differences in the coordinates of the json file compared to the coordinates of the UIUC data set. 

I don't have any actual knowledge of how the json file was produced.

If somebody wants the spreadsheet I am referring to I can send it or upload it somewhere.
.............

[buildinglist-excerpt.json.zip](https://github.com/rokwire/illinois-app/files/10583264/buildinglist-excerpt.json.zip)

**Comment by joegrohens** [comment]
Here is a second excerpt from buildinglist.json.

This excerpt is for the building named "Lincoln Hall". 

The app currently (and correctly) navigates to one ADA entrance: The West Center entrance.

Another ADA entrance is listed in the json file (East Center - on the Quad), but the app does not give directions to that entrance.

From what I can see in the satellite layer of google maps, a third lat/long location in the json points to the wheelchair ramp for this East Center entrance. That should, arguably, be also listed as an ADA entrance in the F&S data. I need to verify this ramp. But it then should be identified as an ADA coordinates in F&S data.

[buildinglist-excerpt2-lincoln hall.json.zip](https://github.com/rokwire/illinois-app/files/10679692/buildinglist-excerpt2-lincoln.hall.json.zip)

**Comment by joegrohens** [comment]
This is the spreadsheet that Chad Kuperschmid from Facilities and Services sent to the wayfinding group in August 2022. I have been using it to compare the results of Illinois app wayfinding with with what F&S knows. 

The file has my notes for Lincoln Hall and Digital Computer Lab


[FY23_DoorandRampSurveyData_082522 jg notes.xlsx](https://github.com/rokwire/illinois-app/files/10679716/FY23_DoorandRampSurveyData_082522.jg.notes.xlsx)

**Comment by nelshopp** [comment]
Closing this per @joegrohens.  His issue is entered here and explains in better detail.  https://github.com/rokwire/illinois-app/issues/2984
