### ISSUE TITLE
[USABILITY] Feedback form is not HTML-responsive

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2981]
**Issue**

The text input box in the Feedback form (_Settings > Submit Feedback_) is wider than a phone screen. When a user places the insertion point, the box expands, and part of the typed lines are always off the screen. 

It may be possible to pinch the form to resize it smaller. But not everyone thinks to do this. Why does it expand in the first place?

**To Reproduce**
1. Go to _Settings > Submit Feedback_
2. Tap in the Feedback box
3. Start typing

You will see that the box is wider than the screen of the phone.

**Expected behavior**
At a minimum, the text input box should not exceed the rhs boundary.

It would be very nice if the form would rotate when you turn the phone sideways. 

**Notes**
I experienced this on iphone 11, ios 16.

A user reported it on Feedback. I don't know her phone type, but I can ask if you want.

This Feedback form is an embedded form created on the UIUC Web Services "Form" tool. (webtools.illinois.edu). I created form that is currently being used.

If you think the fault is on our side, I will submit a ticket to the webtools people.

Joe

**Comment by pmarkhennessy** [comment]
@joegrohens This is web page hosted by the University, not by us. If you still think this is an app issue let me know

**Comment by vburgett** [comment]
The Feedback form not rotating when you turn the phone sideways is an Illinois app issue. The form rotates fine when viewing it via Safari. @pmarkhennessy 

(The Feedback field in the form being wider than the screen of the phone is a Webtools issue—there is the same UX problem when viewing the form in Safari).

**Comment by mihail-varbanov** [comment]
@vburgett, the UIUC app supports portrait mode only. Exceptionally, landscape mode is also supported only when we play video tutorials. You can observe a similar behavior in the Slack mobile app for iOS, for example.

Additionally, UIUC 4.2.52 iOS app launches the feedback URL in an external browser (#2909).
