### ISSUE TITLE
[BUG] Unable to get past app banner screen 

### ISSUE THREAD

**Issue by nelshopp** [rokwire/illinois-app#2987]
Since version 4.2.47, several customers are unable to get to the Illinois app onboarding screen and instead are presented with the banner screen which they are unable to bypass without using the back arrow button.  

A customer's comment:

"Recently, a change happened on the Illinois app on my phone. Now, every time the app is accessed, one cannot view any of the features or information on the app. Instead, a permanent pop-up screen appears (attached), without any way to exit the pop-up, or to access any features of the app, making the app useless. I have tried uninstalling and installing the app, several times, over a period of one week, without any success.”

I am unable to reproduce their behavior.  From the customer's comments though, they are tapping on Illinois app and they get the screen they are describing (two screenshots attached). 

This seems to be affecting iOS and Android alike.  The issue began with v. 4.2.47 with all customers who have reported this.  
![image](https://user-images.githubusercontent.com/91676531/218835726-f8c75e1e-a29e-4646-8de9-c5d7c9e39c27.png)

![image](https://user-images.githubusercontent.com/91676531/218835829-d3fb0e76-f572-4823-ba24-1797ab623b36.png)

**Comment by nelshopp** [comment]
@pmarkhennessy and I have communicated and he asked me to reach out to customers affected and ask them if they are using large fonts on their phones.  If they are, I will ask them to temporarily change it to the default size to see if it fixes the issue.  I will report back if I hear back.

**Comment by nelshopp** [comment]
Already heard back from one customer who switched away from large font.  

" Tom,

Thank you. I tried your recommendation and decreased the font size on my phone (I usually do have a larger font default setting because of sight issues). This worked! It enabled me to see the bottom of the screen and to select “no’, which gave me access then to the Illinois app.

Thanks so much for your help!

Steve"

thanks, @pmarkhennessy

**Comment by joegrohens** [comment]
Kim and I tested this in 4.2.52. It appears fixed. The display of the "participate in research" prompt scrolls, leaving the Yes / No / Not right now buttons visible.

![banner scrolling](https://user-images.githubusercontent.com/66988329/219702139-fd92291f-2298-41da-b2f1-c1a3ea2eece0.png)

**Comment by joegrohens** [comment]
Note: I needed to increase display magnification in my system settings and not just font size.

**Comment by pmarkhennessy** [comment]
@mihail-varbanov I think you already fixed this?

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, that's right, this is already fixed as #2985.
