### ISSUE TITLE
[FEATURE] Allow users to clear their Health Screener history, or not save it in the first place

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#2988]
Vanessa - This is a something that needs design. Mel said that he thinks the Health Screener should look and function similar to skills assessment.

**Problem**
When a user answers a symptoms quiz in the Illinois Health Screener, the history of answers, and any recommendations presented by the app, are saved in the Health Screener history.

Saving this record is not always desirable. A user might be just playing around to see what the feature will do, and then she's got a history of anxiety or depression saved in the app. Or a user might want to be more private, and see the result once, but not have it saved in the app.

The only way to erase health screener history currently is to delete your account, which may delete a lot of stuff you want to keep.

**Solution**

I suggest adding two functions:

1. "Don't Save My Results" (An on-off switch similar to the switch in the Skills Self-Evaluation tool.
2. "Clear My Health Screener History" (A button that let's you wipe out any previously saved record.) 

I don't know if you really need both.

....
Mel asked me to put this in Git, but I think it needs to go to you before it is implemented.

Joe

@dr-mel

**Comment by vburgett** [comment]
Thank you for opening this ticket, @joegrohens. The UI that is being implemented for 5.0 matches the skills self-evaluation UI and it does address some of the current issues. However even with this updated UI for 5.0, the issue would remain that  the "clear history" option needs to ONLY clear the user's Illinois Health Screener history and not the user's Illinois app account, as it currently does. 

[ILLINOISHealthScreener-ILAppV5-2023-03-06.pdf](https://github.com/rokwire/illinois-app/files/10902296/ILLINOISHealthScreener-ILAppV5-2023-03-06.pdf)

Cc: @shurwit @dr-mel

**Comment by shurwit** [comment]
Thanks @joegrohens @vburgett, yes we will get both of these features implemented along with the design changes to match the skills self evaluation.

**Comment by vburgett** [comment]
I should have also noted that the "wellness phone directory" reference in the UI may be an idea for the future rather than 5.0. Since users are on a phone, I imagined matching the attached sidebar resources listed (or some subset) from https://wellness.illinois.edu as a  new wellness phone directory panel for quick access as a convenience to the user or in the case that the user has a pressing wellness need. 
@dr-mel 
<img width="246" alt="Screenshot 2023-03-06 at 2 30 13 PM" src="https://user-images.githubusercontent.com/1044905/223224328-1b57788a-bba0-4566-b63d-007f246b28a9.png">

**Comment by vburgett** [comment]
@roberlander2 @shurwit attached is an updated design for the ILLINOIS Health Screener in the 5.0 app release. Ignore the "Submit Feedback" option for now. It is still being discussed. 
<img width="465" alt="Screenshot 2023-03-27 at 9 05 55 PM" src="https://user-images.githubusercontent.com/1044905/228108314-c2c0e9b1-2b27-40d8-b612-4980b8fccb11.png">
