### ISSUE TITLE
[BUG] Poll voting in group results Error message

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2994]
**Describe the bug**
Voting a poll in a group results in Error message

**To Reproduce**
1. Install the app
2. Navigate to Group
3. Create a poll in the group and start voting

Actual Result
Error message is displayed

**Expected behavior**
Voting should be successful without error message

**Screenshots**
![bad error](https://user-images.githubusercontent.com/26231179/219739233-9d09e324-669f-4798-ba74-84fd1a224846.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.2.52]

**Additional context**

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,

I cannot replicate this problem - all works as expected to me. Here is a video of what I'm observing: https://drive.google.com/file/d/1R6EUmizxAdCY8JnMUuJ1KGM6IDdNOkXT/view?usp=sharing 

Could you please give us more detailed steps to reproduce the problem? Or even a video would be best. Thanks

**Comment by Priyaravi8** [comment]
Not able to reproduce this issue anymore
