### ISSUE TITLE
[BUG] To Do list Reminder is not notified to the user

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#2995]
**Describe the bug**
The reminder is not notified to the user

**To Reproduce**
1. Install the Illinois app
2. Navigate to Wellness -> To Do list
3. Fill in the required fields and tap on Optional fields and enter the reminder -Time and date

Actual Result
The Reminder is not notified to the user on the specific date and time

**Expected behavior**
Notification should sent to the user

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.2.52]

**Additional context**

**Comment by dobromirdobrev** [comment]
This was fixed long time ago. But currently it is blocked by https://github.com/rokwire/illinois-app/issues/3082 (e.g. https://github.com/rokwire/wellness-building-block/issues/26 ). 

So, please verify this issue again when https://github.com/rokwire/wellness-building-block/issues/26 gets fixed. Thanks.
