### ISSUE TITLE
[BUG] outline of buildings not present in Map v2 > Campus Buildings (v4.2.52)

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3001]
**Describe the bug**
JP asked us to compare the new build of Maps to what we had in 4.2.47.

One difference I see frequently is the absence of building outlines when navigating to them using "Directions".

**To Reproduce**
(In this test I am using "English Building" on the middle west side of the "Main Quad".)
1. Go to  Maps > Campus Buildings
2. Touch a building on the map. 
3. Tap "Directions" and follow the route sequence until "Finish"
4. Zoom in.

**Results**

- On 4.2.47 an areal view drawing of the building is visible. As you zoom in, you can see the floor plan, room numbers, and some other labelling:

![engl bldg directions 4 2 47 iphone copy](https://user-images.githubusercontent.com/66988329/220180460-828d9d80-1f60-40af-944d-f5499701adfc.jpeg)
_`Fig 1. English Building Directions 4.2.47 (iphone)`_

- On 4.2.52 you can only see the building name -- no drawing:

![engl bldg directions 4 2 52 android copy](https://user-images.githubusercontent.com/66988329/220180548-0f82a2a4-3ef2-4725-b86b-854575a32def.png)
_`Fig 2. English Building Directions 4.2.52 (android)`_

- Also in 4.2.52, but in contrast to getting Directions, if you just touch a building and zoom in, you _will_ see a building drawing :

![engl bldg no directions 4 2 52 android copy](https://user-images.githubusercontent.com/66988329/220180658-209e5757-1c9b-451f-9df7-7273fb7a1160.png)
_`Fig 3. English Building NO Directions 4.2.52 (android)`_

**Expected Behavior**

The drawings of buildings should be visible when you finish the directions route.

**Comment by mihail-varbanov** [comment]
This behavior is by design. I was requested explicitly to hide building outlines and floor selector from maps.
