### ISSUE TITLE
[BUG] Map Direction  results error

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3048]
**Describe the bug**
Navigating to the location direction results error

**To Reproduce**
1. Install the Illinois app
2. Navigate to Map and tap on any of the locations for direction

**Actual results**
Error results for the direction

**Expected behavior**
The actual direction to the location needs to be displayed.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.3.27]

**Additional context**

**Comment by mihail-varbanov** [comment]
I tested this on 4.3.48 and see no problems. Maps were totally reworked so we might fixed the problem durning the development.
