### ISSUE TITLE
[BUG] blank My Destinations screen: FIRST-time user tap on the default text link goes to wrong panel  

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3060]
The "My Destinations" link in the default text under Browse > MTD Buses > **My Destinations** links to Map > Campus Buildings the FIRST time a user taps on it. The second time a user taps on the link, it goes to Map > My Destinations, as expected. 

Please update that first tap on the "My Destination" link to also link to Map > My Destinations like the subsequent taps do. 

 - Pixel 6, Android v12 
 - Illinois App v4.3.27
 
![Screenshot_20230328-161348_2](https://user-images.githubusercontent.com/1044905/228370910-9a2ad1f6-48a6-4090-8910-63cf193a586f.png)

**Comment by mihail-varbanov** [comment]
Fixed in version 4.3.40.

**Comment by vburgett** [comment]
Fixed in 4.3.50—thank you!
