### ISSUE TITLE
[FEATURE] Add "Mental Health Wellness Guide"

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#3062]
**University Monday 2023/03/27** / 2023-03-27

3 Dobromir (Admin App)/Misho (UIUC App) we need a new Guide type for "Mental Health Wellness Guide". 

3.1 In Wellness add another dropdown entry for "Mental Health Wellness Guide" that will use only this content.

3.2 In Admin we will need to be able to create/modify etc this new guide content.

3.3 Misho, you could clone a Guide item so we have one entry which Joe can edit/delete as he wants to get him going.

**Comment by mihail-varbanov** [comment]
MV: Dobromir and I decided not to do anything on this point as it is not clear what is exactly wanted.

You talk about "new Guide type" that is a new "content_type", used for a definition of a set of guide articles, e.g. campus reminders, highlights or safety resources. It sounds that the new dropdown item in the Wellness Home panel will do something similar to what we have in the"Wellness Resources" dropdown item - display a list of items, each of them launching a guide article. Such a new content type requires updates in the Admin app.

You also talk about "cloning a Guide item" that sounds something similar to what we do in "Healthy Illini Podcast" and "I'm Struggling" dropdowns entries from the Wellness home panel. This has nothing to do with the Admin app, like the above items are not treated in any specific way there.

So from what you wrote I see two possible tasks:

A. "Mental Health Wellness Guide" dropdown item will load a single guide article content like we do for "Healthy Illini Podcast" and "I'm Struggling" dropdown entries. In this case best of all would be if first Joe creates the new guide article for this, determining the right category and section where it would appear in the complete campus guide; and finally I create the new "Mental Health Wellness Guide" dropdown entry in the UIUC app that loads this article. We can optionally add this new article entry in the Wellness Resources list like we do for "Healthy Illini Podcast" and "I'm Struggling" entries. The Admin app and Dobromir will not be involved in any way.

B. Define a new content type "mental_health" that will identify a bunch of guide articles. Normally we would add a new entry in the "Campus Guide" or "Wellness" sections from the Browse panel that will display the list of article's cards of that content type. We will also add a new dropdown entry in the Wellness home panel that will display the article's cards of that content type, like we do for the "Wellness Resources" item. The Admin app will have to provide an ability to specify that a given guide article is from this new content type.

In this case best of all will be first Dobromir to update the Admin app to support this new content type (like highlights, safety resources, etc.); then Joe to create the articles with this content type, determining the right category and section where they would appear in the complete campus guide; and finally I to update the UIUC app to provide access to this new resource. I will need some UI guidance on how the article's cards list will look like - like [standard guide cards](https://rokwire-ios-beta.s3.us-east-2.amazonaws.com/Images/Simulator+Screen+Shot+-+iPhone+14+Pro+Max+-+2023-03-27+at+11.29.53.png) or like [wellness resource items](https://rokwire-ios-beta.s3.us-east-2.amazonaws.com/Images/Simulator+Screen+Shot+-+iPhone+14+Pro+Max+-+2023-03-27+at+11.30.05.png). 

Finally, here is a [snapshot](https://rokwire-ios-beta.s3.us-east-2.amazonaws.com/Images/Simulator+Screen+Shot+-+iPhone+14+Pro+Max+-+2023-03-27+at+11.01.46.png) of the current safety resources guide content on production. You can see the experiments that someone (most probably Joe) is doing there. These guys should learn to do these tests on dev.

**Comment by joegrohens** [comment]
> These guys should learn to do these tests on dev.

Noted.
