### ISSUE TITLE
[USABILITY] Text update: "My Groups" default text needs correcting

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3066]
Under Browse > Groups > My Groups, please update the default text to:
"You are not a member of any group. To join or create a group, see <All Groups>."
"All Groups" would be a link to the "All Groups" panel.

Attached is what a user sees in 4.3.27 on an Android. 
(cc: @joegrohens)

![Screenshot_20230328-162906](https://user-images.githubusercontent.com/1044905/228862960-f9d039cc-a534-40a1-adc2-6f649ef817ea.png)

**Comment by TodorBachvarov** [comment]
Updated in version 4.3.46

**Comment by vburgett** [comment]
Complete in 4.3.47—thank you!

![Screenshot_20230425-205048](https://user-images.githubusercontent.com/1044905/234611930-10edf59e-cd34-4508-b881-e58d23af5f28.png)
