### ISSUE TITLE
[BUG] Links going to incorrect resource

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#307]
**Describe the bug**
The entry describing Safer Illinois has two links that behave strangely.

The first link opens the phone dialer with a phone number unrelated to Safer Illinois. The phone number is for the Office of the Dean of Students. The link should open a webpage with the URL displayed.
The second link is unrelated to Safer Illinois.

This phone number and URL seems to be from the entry for "Get help from Community of Care" (under Acadmic Support > General Support)

**To Reproduce**
1. Go to Student Guide
2. Tap on COVID-19 under Health & wellness heading
3. Tap on Download the Safer Illinois app
4. Tap on the links next to the globe icons

![Screenshot (Jun 17, 2021 2_12_59 PM)](https://user-images.githubusercontent.com/11352701/122459913-1d9fc580-cf77-11eb-8d50-04ef7c194afc.png)

**Expected behavior**
The links should open to resources related to Safer Illinois and match what's displayed on the line.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 11
 - Version 2.4.25

**Additional context**

**Comment by knguyenjahiel** [comment]
Closing: Safer Illinois is no longer part of the app
