### ISSUE TITLE
[BUG] Wellness - Mental Health - No information 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3073]
**Describe the bug**
No information is displayed on the screen Mental Health - wellness screen

**To Reproduce**
1. Install Illinois app
2. Login with user credentials
3. Navigate to Wellness and tap on Mental health

**Actual Result**
No information is displayed on the screen

**Expected behavior**
Mental health information should be displayed on the screen.

**Screenshots**

![mental](https://user-images.githubusercontent.com/26231179/229614326-d4822ba1-c7aa-4aeb-bb4b-2f84e11426b9.png)

**Smartphone (please complete the following information):**
 - Device: [Android]
 - Version [e.g. 4.3.34]

**Comment by pmarkhennessy** [comment]
@dr-mel This I believe is all resolved now with build 4.3.49 and above
