### ISSUE TITLE
[BUG] Athletics Events filter not functioning in Athletics>Upcoming Events

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#3077]
The "Upcoming Events" link in the default text under Browse > Athletics > Upcoming Events links to all events instead of filtering Athletic events in 4.3.34

1. Go to 'Browse'
2. Tap on 'Athletics'
3. Tap on 'Upcoming Events'
4. See error - though 'Athletics' filter is visible, the events are not solely Athletics events as is expected

Please update the tap on the "Upcoming Events" link to Athletic Events (filter)

Pixel 7, Android v13
Illinois App v4.3.34

Note: Screenshot shows tap on the "Upcoming Events" link, widgets showing are "Community" and "Career Development" events, not "Athletics" events

![Screenshot_20230404-104857](https://user-images.githubusercontent.com/129777610/229852331-cfbcf7bc-8f62-49ea-91f5-009d957c5c8c.png)

**Comment by dobromirdobrev** [comment]
Fixed in version 4.3.47
