### ISSUE TITLE
[USABILITY] Update Layout of Daily Illini Stories

### ISSUE THREAD

**Issue by rohitc33** [rokwire/illinois-app#3079]
The Daily Illini web dev team would like to update how Daily Illini stories appear in the app according to this mockup:

![illinois-app-mockup](https://user-images.githubusercontent.com/70339497/229916094-2456ce7e-2c35-4f8c-ae75-a473ba233ee0.png)

The middle screenshot shows how stories currently appear in the app. We'd like to update the layout on the favorites screen to look like the mockup on the right, which shows one story with a photo and two more stories below.

We would also add a dropdown which lets users filter stories by category (news, opinion, sports, etc).

To be clear, we are not requesting any development work to be done on Rokwire's end -- the Daily Illini web dev team will implement the changes and make a PR.

**Comment by pmarkhennessy** [comment]
@rohitc33 You say the "_the Daily Illini web dev team will implement the changes and make a PR._" I want to point out that this is not HTML code it is Flutter code.

**Comment by rohitc33** [comment]
@pmarkhennessy Thanks for bringing this up. Our web devs are student volunteers who have experience with app development, so this will not be an issue for us.

Here's our fork: [https://github.com/Daily-Illini/illinois-app](https://github.com/Daily-Illini/illinois-app)

**Comment by TodorBachvarov** [comment]
@rohitc33, could you prove a PR as well please?

**Comment by pmarkhennessy** [comment]
@rohitc33 We need a PR to integrate this change please

**Comment by rohitc33** [comment]
@pmarkhennessy we haven't finished implemented the changes yet. Do you want a PR for tracking the work in progress?

**Comment by pmarkhennessy** [comment]
@rohitc33 When you have finished, assign this issue back to me and give me the PR link etc please. We would need it this week for a chance to get it into the next release.

**Comment by rohitc33** [comment]
@pmarkhennessy I don't think we can finalize the changes this week. When is the release after the next one scheduled for? We are fine if it's near the start of the fall semester.

**Comment by pmarkhennessy** [comment]
@rohitc33 Mid July would be 5.0
