### ISSUE TITLE
[BUG] webpage resource does not load

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#308]
**Describe the bug**
A webpage resource does not load from the Student Guide. It shows an error.

**To Reproduce**
1. Go to Student Guide > Mental & emotional health
2. Tap on Get help with drugs and alcohol
3. Tap on the web link https://go.illinois.edu/GetHelpWithDrugs
4. See error in the screenshot below

![Screenshot (Jun 17, 2021 2_28_15 PM)](https://user-images.githubusercontent.com/11352701/122460940-55f3d380-cf78-11eb-9018-20b2f1d5d6ba.png)

**Expected behavior**
The user can visit the webpage.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Version 2.4.25

**Additional context**
The short link in the URL redirects to an unsecured (HTTP not HTTPS) page, which may be part of the issue.

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
