### ISSUE TITLE
[FEATURE] Add user's profile image to daily wellness rings 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3081]
If a user has uploaded a profile photo, display that same image instead of the profile icon in the center of the daily wellness rings in two locations:

Wellness > Daily Wellness Rings
Favorites > Daily Wellness Rings favorites widget

![Screenshot_20230404-200348.png](https://user-images.githubusercontent.com/1044905/229956293-8f89e9cf-15b1-4102-a91b-a85fac6cf8db.png)

**Comment by dobromirdobrev** [comment]
This is done in version 4.3.47

**Comment by vburgett** [comment]
Confirming that this is complete in 4.3.47—thank you!
