### ISSUE TITLE
[BUG] External Links Have No In-App Navigation - Change to External Browser

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#3088]
The below four external links do not open in a browser (myIllini, Healthy Illini podcast, Rokwire, Smart Healthy Communities Initiative). In 4.3.34, the user has to quit and restart the Illinois app to get back to app navigation from these four links.

Please make these four links open in a browser app:

Link 1: myIllini
1. Go to 'Browse'
2. Tap on 'Academics'
3. Tap on 'Skills Self-Evaluation' or 'To-Do List'
4. Use the Dropdown menu top select 'myIllini'
5. See error - link opens in Illinois app rather than a browser app and the user must quit to return to other parts of the Illini app

Link 2: Healthy Illini podcast
1. Go to 'Wellness'
2. Tap on 'dropdown menu and select "Healthy Illini Podcast"
3. Scroll down and tap on "Listen Now" button
4. See error - link opens in Illinois app rather than a browser app and the user must quit to return to other parts of the Illini app

Link 3: Rokwire
1. Go to 'Settings'
2. Scroll down and click on the hyperlinked "Rokwire"
3. See error - link opens in Illinois app rather than a browser app and the user must quit to return to other parts of the Illini app

Link 4: Smart, Healthy Communities Initiative
1. Go to 'Settings'
2. Scroll down and click on the hyperlinked "Smart, Healthy Communities Initiative"
3. See error - link opens in Illinois app rather than a browser app and the user must quit to return to other parts of the Illini app

- Pixel 7, Android v13
- Illinois App v4.3.34

**Comment by TodorBachvarov** [comment]
Fixed in version 4.3.44
