### ISSUE TITLE
[BUG] Map displays wrong locations of many addresses listed in Events

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3101]
**Describe the bug**
Map displays wrong locations of many addresses listed for Events. Locations for buildings such as Coble Hall, ESB, Newmark point to Ecolar, Urbana. Others point to locations hundreds/thousands miles away (e.g., Info and map for Loomis Lab shows it to be 1754.2 miles away).

**To Reproduce**
1. Go to 'Events'
2. All Categories >> "Academic"
3. Find events scheduled on April 10
4. Select "CLACS Lecture Series. Francisco Rodriguez-Saurez and Isabella Hillman "Puerto Rico: a tale of two systems"
5. Note location info: 1.3 mi away, Coble 306. Map points to "Escola, Urbana, IL"
6. Select "Liberals, Conservatives, and the Climate of Fear: How Campus Free Speech is Failing and How It Can Be Saved"
7. Note location info: 1.3 mi away, Room C, College of Law. Map points to "Escola, Urbana, IL"
8. Select, "Nuclear Physics Seminar-Xing Wu (Harvard) "Decelerate Molecules to a Standstill: for Testing Fundamental Symmetries of Nature"
9. Note location information: 1754.1 mi away, 464 Loomis

**Expected behavior**
Correct map locations and distances should be displayed for addresses listed in Events.

**Screenshots**
Identical map and directions for different addresses listed for various events:
![Map of Event Locations](https://user-images.githubusercontent.com/118769169/230652778-6c51a89f-56d3-4b2f-837d-b3ef8418f05b.png)

Incorrect location information displayed for Loomis Laboratory
![Event 3](https://user-images.githubusercontent.com/118769169/230653238-ef6370b0-1f95-4e64-802f-b99925cdd1e0.png)

**Smartphone (please complete the following information):**
 - Device: Android
- Version 4.3.34

**Comment by mihail-varbanov** [comment]
@knguyenjahiel, this is not a problem of Illinois app but rather of event creators. When an event is created it allows specifying its geolocation coordinates. I was not able to access the first two sample events that you mention here, probably because I am doing this 10+ days after their expiration. However I was able to find the last sample event titled "Nuclear Physics Seminar - Xing Wu (Harvard)". Its location is defined as follows:
```
"description":"464 Loomis",
"latitude":38.8212889,
"longitude":-121.1930041
```
You can check in Google Maps that this coordinates define a place near Sacramento, CA so the application behaves correctly. I would suppose that the first two sample events fall in the same case - wrong geolocation coordinates. If you could locate other events with a wrong position on the map, that are late enough not to expire when I test this, you could send them to me to check what geolocation coordinates are defined for them.

**Comment by knguyenjahiel** [comment]
@mihail-varbanov, thanks for checking on this. "Escola, Urbana" Google map location was displayed for events from multiple departments (at least 10 departments in my sample). It's strange to me that they all made the same mistake.

@sandeep-ps, can there be other causes?

Thanks to you both.

**Comment by sandeep-ps** [comment]
Kim and I had a brief meeting about this. Most of these are cases of using the abbreviated building or place names. In the Events Manager application, the string "Urbana" is appended to the names to help locate some places with abbreviations. So, when the Google Maps API returns nothing, it puts Urbana as a default location. We could remove that; in that case, we will have empty geocoordinates in all of those cases.

**Comment by knguyenjahiel** [comment]
Keeping this issue open. Investigating with @sandeep-ps

**Comment by knguyenjahiel** [comment]
[Records of Inconsistent Google Maps Destinations for Events Locations](https://docs.google.com/spreadsheets/d/1hdw0v4zUmuRDqOqDumkXTDCOiEn-5rSt/edit?usp=sharing&ouid=102443513376978935369&rtpof=true&sd=true)

**Comment by knguyenjahiel** [comment]
@sandeep-ps, I'm experimenting with ChatGPT and comparing its results with Google Maps -- Web. ChatGPT came up with the correct destination while Google Maps -- Web failed to do so.

**Fig. 1: ChatGPT Return**
![image](https://github.com/rokwire/illinois-app/assets/118769169/e149c9bd-dd85-44c2-b462-8f6dfa4f55d5)


**Fig. 2: Google Maps - Web Return**
![image](https://github.com/rokwire/illinois-app/assets/118769169/8060fff3-4f2b-48a4-a8ca-fcfe0e251d6d)

**Comment by sandeep-ps** [comment]
> @sandeep-ps, is it possible to use the "University of Illinois" string rather than "Urbana, Il" string to narrow Google Maps destination for incomplete Events Location entries? I found that when "University of Illinois" is added to a building name or labs name that is missing complete street address, Google Maps - web points to the correct destination

Hi, Kim, Yes, that may work better. Thanks for your suggestion. We can try this in the development instance.
