### ISSUE TITLE
[USABILITY] Buttons are cut-off in 3 Residential Dining Hall listings

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3102]
**Describe the usability issue**
**1. 52 North Ikenberry Commons: "Retail Offerings" button is cut-off**
![52 North Ikenberry Commons](https://user-images.githubusercontent.com/118769169/230659583-8084ef9b-166a-41d8-a509-4451e763a3ef.png)

**2. Ikenberry Dining Center: "Light Lunch" button is cut-off**
![Ikenberry Dinning Center @ Ikenberry Commons](https://user-images.githubusercontent.com/118769169/230659610-437c632e-28c8-4c00-9ba8-3948e94865e6.png)

**3. TerraByte at Illinois: "Hot Food Daily Meal" button is cut-off**
![TerraByte at Illinois](https://user-images.githubusercontent.com/118769169/230659025-719b9a90-4574-497b-a312-7d9da262333d.png)

**Smartphone (please complete the following information):**
Device: Android
Version: 4.3.34

**Comment by TodorBachvarov** [comment]
This is as per design- the user can scroll horizontally to reach the rest buttons. These buttons are placed in HorizontalScroll so we can take as much with as we need, because for some Dining locations we may have many buttons with long names.

**Comment by knguyenjahiel** [comment]
This makes sense, now. Thanks. Am closing this issue.
