### ISSUE TITLE
[BUG] Skills Self-Evaluation Results - "Your Results" info and related video are missing in individual Skills Domain card

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3103]
**Describe the bug**
Individual Skills Domain cards (in Self-Evaluation Results) have no content under "Your Results" and their video links are broken (error message: Missing video). Current prod version (4.2.52) seem to have complete content -- information explaining an individual's result and relevant video. 

**To Reproduce**
1. Go to 'Academics' >> Skills Self-Evaluation
2. Answer all questions, Submit
3. Touch one of the Skills Domain in Results panel

**Expected behavior**
It is expected that each Skills Domain card provides an explanation of an individual's score in that domain and the video link will show the corresponding video. 

**Screenshots**
A screenshot of one of the Skills Domain card in version 4.3.34. Note empty content under "Your Results" and video. 

![Abstract Thinking Card](https://user-images.githubusercontent.com/118769169/230673886-35e66247-f909-4b74-9c21-638ddb0ad14a.png)

Below is a screenshot of one of the Skills Domain card, in the prod version 4.2.52, showing content. And, video displays.
![Cooperation Skills Card](https://user-images.githubusercontent.com/118769169/230672997-ba5e539f-9e57-48af-b7d3-2abf94f6ac81.png)

**Smartphone (please complete the following information):**
 - Device: Android
- Version: 4.3.34

**Additional context**
It seems there is a new version of the Skills Self-Evaluation (48 questions vs. 45; 11 skills domains vs. 5). Perhaps Brent is working on providing more content and additional videos. If so, please ignore this report.

**Comment by shurwit** [comment]
Thanks @knguyenjahiel, we have been working on some updates to the BESSI so it was in a partially completed state. We have applied some additional updates so it should now work as expected while testing in dev. Please note that while the evaluation itself is longer now, we will not be applying these changes in production until the 5.0 release with additional related functionality.
