### ISSUE TITLE
[USABILITY] 8 Dimensions of Wellness Image (4/7/2023 Today's Wellness Tip) is cut-off

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3104]
**Describe the usability issue**
The 8 Dimensions of Wellness image in 4/7/2023 Today's Wellness Tip is cut-off. This occurs in both Ill App dev 4.3.34 and prod 4.2.52.

**To Reproduce**
1. Tap on 'Wellness'
2. Select 'Today's Wellness Tip'
3. Tap on 'Learn more about the 8 dimensions"'
4. Error: Imageof 8 Dimensions of Wellness is cut-off

**Expected Behavior**
It is expected that images/graphics are completely displayed.

**Screenshots**
![8D of Wellness](https://user-images.githubusercontent.com/118769169/230676024-80f0cab5-3bea-46e7-a032-6d95b683be49.png)

**Smartphone (please complete the following information):**
Device: Android
Version: 4.3.34

**Comment by TodorBachvarov** [comment]
This is web page which is not part of the client (even if we open it in external browser, the image is still cut off). Please redirect this issue.

**Comment by pmarkhennessy** [comment]
@knguyenjahiel You need to get the author of this web page to do something, scale for device screen size?, as this is not an App issue.

**Comment by knguyenjahiel** [comment]
Thanks, @pmarkhennessy and @TodorBachvarov.
@dr-mel, would you be able to contact McKinley Center's web developer and request for them to make the image mobile device friendly?

**Comment by knguyenjahiel** [comment]
@dr-mel, any update from McKinley Health Center's web developers re: making the 8 Dimensions of Wellness mobile device friendly?
