### ISSUE TITLE
[BUG] After logging in with a phone number or email, login favorite stays on Favorites panel

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#3111]
After signing in via email or phone number from the Favorites "Connect to Illinois" widget, the user appears to be logged in under Settings but the "Connect to Illinois" widget is still displayed on the Favorites panel.

Please update to remove the "Connect to Illinois" widget from the Favorites screen immediately after phone or email authentication.

1. Begin as a logged-out user
2. Go to "Favorites"
3. Under Connect to Illinois > "Don't have a NetID," tap on the "Continue" button
4. Enter an email address or phone number and authenticate
5. The user still sees the "Connect to Illinois" widget on the Favorites panel despite already being logged in.

As a user logged in with my phone number or email address, I would expect to no longer see the "Connect to Illinois" widget on the Favorites panel.

Pixel 7, Android v13
Illinois App v4.3.34

*Screenshot taken after first-time phone number authentication via one-time code

![image](https://user-images.githubusercontent.com/129777610/230984952-764f2c03-5035-44d9-b385-7ac7e0c743d2.png)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.3.46
