### ISSUE TITLE
[BUG] Random message displayed on the top of Group screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3135]
**Describe the bug**
The random message is displayed on a detailed group screen.

**To Reproduce**
1. Install the Illinois app
2. Navigate to the group and create a new group
3. Tap on the created group

Actual Result
The random message is displayed on a detailed group screen

**Expected behavior**
Detailed group screen should display without random messages.

**Screenshots**
![Group title](https://user-images.githubusercontent.com/26231179/232138713-d0a6103d-cd87-41b5-add8-ee70880e62d1.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 4.3.39]

**Comment by pmarkhennessy** [comment]
@todor See my email sent 2023/04/18 for where to place these. I think this was already done, but only show "Managed Updated" if the Group is Authman/University Managed.

**Comment by TodorBachvarov** [comment]
Updated and moved to MembersPanel in version 4.3.44
