### ISSUE TITLE
[USABILITY] Change Menu Item Name for Map > Mental Health Resources

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3147]
**Describe the usability issue**

Please make the following menu name change, per @dr-mel and @vburgett 

Change _Map > Mental Health Resources_  to _Map > Find a Therapist_

This is a priority for 4.3

Thank you.

Joe

**Comment by joegrohens** [comment]
This issue is unresolved as of v4.3.47 dev.

**Comment by mihail-varbanov** [comment]
This should be resolved in version 4.3.50.
