### ISSUE TITLE
[BUG] Appointment reschedule results Error

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3156]
**Describe the bug**
"Failed to reschedule appointment:" error message is displayed when the user reschedules the appointment

**To Reproduce**
1. Install Illinois app
2. Navigate to Appointments in the Wellness screen
3. Tap on any of the appointments and reschedule
4. Fill in the necessary fields and tap the Next button. Fill in the Appointment questions and tap on Next button
5. Choose "**Inperson**" in the appointment Type field and Tap on Reschedule

**Actual Result** 
"Failed to reschedule appointment:" error message is displayed

**Expected behavior**
The user should be able to reschedule the appointment without error

**Screenshots**
![reschedule](https://user-images.githubusercontent.com/26231179/233421995-1f7b9a1d-bdfa-4460-9503-b89c08a81ea1.png)

**Smartphone (please complete the following information):**
 - Version [e.g. 4.3.43]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 This feature is not complete yet. Goal is to be complete before the 2023/04/27 latest
