### ISSUE TITLE
[USABILITY] Text update: to-do list notification

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3173]
Please change "TODO Reminder" notification text to "To-Do List Reminder"

Version 4.3.46

![Screenshot_20230424-135634.png](https://user-images.githubusercontent.com/1044905/234090611-a200308d-4d27-40ed-b455-8848195b5c45.png)

**Comment by TodorBachvarov** [comment]
This is not specified in the client, so it should be done in the Wellness BB (which sends the notifications). @pmarkhennessy could you redirect to the backend team when someone is available.

**Comment by TodorBachvarov** [comment]
I've created backend issue: https://github.com/rokwire/wellness-building-block/issues/35. Closing this one.
