### ISSUE TITLE
[BUG] Add Events to Group/Research Project Via Search

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3175]
When trying to search and add an existing event to a Group or Research Project there is no option to "add event to group."

As a PI (research project admin), go to your research project, and tap the + icon to add an existing event. Tap the search button and find the event you'd like to add. See there is no button to "add event to group" which I would expect.

Android
4.3.47

Adding an event from a research project WITHOUT searching (see button)
![Screenshot_20230424-141823.png](https://user-images.githubusercontent.com/1044905/234118510-2a879931-7caf-4657-a053-f4d3292a46e0.png)

Adding an event from a research project via searching (see there is no button)
![Screenshot_20230424-141851.png](https://user-images.githubusercontent.com/1044905/234118517-362dfb21-cdf4-47d3-a2ad-17b4fb6f3ee4.png)

**Comment by mihail-varbanov** [comment]
This should be resolved in version 4.3.49.

**Comment by vburgett** [comment]
Fixed in 4.3.50—thank you!
