### ISSUE TITLE
[BUG] Research Project: Cannot Create Event 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3176]
When trying to create an event in the research project "Pizza and our brains" as the PI/admin, I get the attached error. No event is created. 

4.3.47

![Screenshot_20230424-162335.png](https://user-images.githubusercontent.com/1044905/234120417-03cbc5aa-41c3-4d14-ac97-1df5829bdc24.png)

**Comment by mihail-varbanov** [comment]
This seems to be a backend problem. I [wrote](https://rokwire-workspace.slack.com/archives/CEXARQXQR/p1682503023657419) in Slack about it.
