### ISSUE TITLE
[USABILITY] Research Project Settings Defaults

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3177]
When creating a research project, the project default settings for "member posts" and "view other members" should be toggled to off. (Research participants generally should not interact or have the chance to influence others within the research pool.)

![Screenshot_20230424-171448.png](https://user-images.githubusercontent.com/1044905/234128495-55d9182b-2e5c-48bf-bf72-c92d31172d02.png)

Cc: @RokBill

**Comment by mihail-varbanov** [comment]
This should be resolved in version 4.3.49.

**Comment by vburgett** [comment]
Complete—thank you!
