### ISSUE TITLE
[USABILITY] v4.3.47 Map fails to load for Building Locations and Mental Health Resources

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3178]
In v4.3.47 dev
 
 Map > Campus Buildings

and 

Map > Mental Health Resources

both produce "Failed to load" errors.

![fail to load map 2](https://user-images.githubusercontent.com/66988329/234155892-edef9e5a-10d6-4678-856c-90953a9b4628.png)

![fail to load map 1](https://user-images.githubusercontent.com/66988329/234155808-3483df8e-039c-4235-b2a9-f342fd6ef7ba.png)

**Comment by knguyenjahiel** [comment]
@joegrohens and @pmarkhennessy, This seems to be a sporadic, but continual error. There are times when Maps loaded successfully and then suddenly it fails to load.

**Comment by mihail-varbanov** [comment]
This is a backend problem. I created an issue in Gateway building block repo for this: rokwire/gateway-building-block#18. Closing the current issue as it is not related to the client application.
