### ISSUE TITLE
[USABILITY] Rename "Specials" to "Dining News" in Residence Hall Dining

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3187]
Please rename the header (text in top blue title bar) on individual Dining News items from "Specials" to "Dining News" to make it consistent with how they are listed under "Residence Hall Dining."

**Steps to reproduce the behavior:**
1. From Browse or Favorites, touch Dining >> Residence Hall Dining
2. Select an item under "Dining News" (e.g., April 28: Urbana South Drag Show at PAR)
3. This will take user to detailed information about that Dining News item. Header text says "Specials" rather than "Dining News."

**Screenshots**
![Dining News - 2](https://user-images.githubusercontent.com/118769169/234327205-bcd9ea63-a834-4f35-8185-0d89ad8adb61.png)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.3.50.
