### ISSUE TITLE
[BUG] A pop-up window of the To-do list item and Add an item screen loops around

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3192]
**Describe the bug**
A pop-up window of the To-do list item and Add an item screen loops around. The user cannot navigate out of the loop to proceed further.

**To Reproduce**
1. Install the app.
2. Navigate to Academics -> To-Do List
3. Check on the radio button on any of the displayed To-Do lists (for example list named Orange) and tap on it (Orange).
4. Pop-up window of the selected list is displayed and tap the OK button.
5. Wellness screen with Add an item screen is displayed. Scroll down and tap on the "Save" button. Item is saved.
6. Again, Pop up window of the selected list is displayed. App loops between the 2 screens of the To-do list and Add an item.

**Actual Result**
A pop-up window of the To-do list and Add an item screen loops around. The user cannot navigate out of the loop.

**Expected behavior**
The user should be able to navigate to further screens without looping.

**Screenshots**

https://user-images.githubusercontent.com/26231179/234623982-16846faf-03df-453d-9e59-c87347920b8c.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. android]
 - Version [e.g. 4.3.47]

**Comment by dobromirdobrev** [comment]
The issue is not in the UIUC app.
The problem is that the Wellness BB sends fcm notification when an item with passed due date is updated. An issue in the relevant BB is created: https://github.com/rokwire/wellness-building-block/issues/29.
