### ISSUE TITLE
[USABILITY] Zoom links in events are often not active links. v4.2.52

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3193]
This is for version 4.2.52 iphone.

**Problem Description**

Case 1. When events have a zoom link in the _Top_ section (the date / time / location section), the link is not tappable. This seems to be always the case. I have not tested this exhaustively, but it is easy to find examples. I have found at least 10 such examples.

Case 2. When the zoom link is included in the _Description_ section, it sometimes is clickable. But usually in 4.2 the session does not open in zoom. (I get the "not supported by browser" error.) 

I'm assuming that's because it is trying to open zoom in the internal browser, and the internal browser does not support zoom. So maybe zoom links should be opened in an external browser?

In 4.3 dev that we're testing, it seems that more of the zoom links actually do open zoom. But that's on Android. 

**Suggested Remedies**

1. I see that you are researching an internal zoom plugin. But until you have that, I would recommend considering to send these links to an external browser. 

2. Also, the zoom links in the top section of the events screen should be made active links. They are just text now. Many online events that have the zoom link in the top section do not include the link in the description. And the link can't be copied and pasted into a browser. So the user is just out of luck to attend the event.

![zoom links copy](https://user-images.githubusercontent.com/66988329/234731235-f2b7aef6-8491-47b3-91dd-678cd57d9dda.jpeg)

![zoom links 2 copy](https://user-images.githubusercontent.com/66988329/234731247-6adb6430-f95a-4b1f-ac11-e6ba8d6c5ab2.jpeg)

**Comment by pmarkhennessy** [comment]
@mihail-varbanov This has nothing to do with the abandoned Zoom project you were working on. It looks to me like sometimes an event has a http/https link inside, see Joe's picture above with a Zoom link. Can you make these clickable please and also make sure they always open in an external browser for both ios and android.

**Comment by mihail-varbanov** [comment]
This should be resolved in version 4.3.50.

**Comment by joegrohens** [comment]
![url in event fixed copy](https://github.com/rokwire/illinois-app/assets/66988329/15a2e19b-1514-4fb8-a035-8725ab8ad3d8)
confirmed fixed in 4.3.61
