### ISSUE TITLE
[BUG] Font change for Athletic event titles, please change back and decrease size

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3210]
The event title font used for the Athletics event titles such as the attached Game Day widget has changed in 4.3.50 since the 4.2.52 release. (The attached "Illinois at Ohio State" is correct.)

Please revert back _and_ make it match to other non-athletic event titles which are smaller. Those attributes are:
"font_family": "extra_bold", "size": 20.0

![IMG_5569](https://user-images.githubusercontent.com/1044905/235183134-0deb0a8f-94ee-48f8-b271-5f508e4ba203.PNG)
![Screenshot_20230428-094345](https://user-images.githubusercontent.com/1044905/235183160-21611c78-dbea-4b30-8b57-2e769dbd08aa.png)

**Comment by mihail-varbanov** [comment]
This should be resolved in version 4.3.54.

**Comment by vburgett** [comment]
Confirmed as updated in 5.0.55. Thank you!
