### ISSUE TITLE
[USABILITY] Text color update: "Forgot Password"

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#3211]
Under "Sign In with Email," please update the color of the "Forgot Password" link to match a "View All" link from the Favorites Screen.

Screenshot 1: Currently, the text is very faint and is very difficult to see. The link is circled in red on the screenshot.

Screenshot 2: "View All" link from favorites is circled in red for reference.

Pixel 7, Android v13
Illinois App v4.3.50

![IMG_4973](https://user-images.githubusercontent.com/129777610/235219830-fbcbb6cf-76dd-4c4c-9e4a-942f3204b332.jpg)
![IMG_4977](https://user-images.githubusercontent.com/129777610/235219855-2b82a297-d9f7-443c-b79e-39cc1fa445e1.jpg)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.3.52.
