### ISSUE TITLE
[USABILITY] Text edit "Principal Investigator"

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#3212]
In every place that "Principle Investigator(s)" is referenced, please update to the text to "**Principal** Investigator(s)"
cc: @vburgett @joegrohens @RokBill 

NOTE: This relates to any/all research project screens currently using the word "principle" as part of the phrase "principle investigator(s)." Please change the spelling to "principal."

Pixel 7, Android v13
Illinois App v4.3.50

![Screenshot_20230428-113857](https://user-images.githubusercontent.com/129777610/235222429-549db991-10bc-496f-bd38-dd015157a509.png)

**Comment by mihail-varbanov** [comment]
Resolved in version 4.3.52.
