### ISSUE TITLE
[USABILITY] Removing or hiding two text field boxes within the To-Do List

### ISSUE THREAD

**Issue by nataliehelregel** [rokwire/illinois-app#3265]
Remove "Location" and "Days to Work on Item" from the Optional Fields in Adding an Item within the To-Do List. 

![image](https://github.com/rokwire/illinois-app/assets/96087558/12b0b4ca-6cfd-449b-a9b5-e48093361ef9)

**Comment by vburgett** [comment]
This ticket is a still a request.

**Comment by TodorBachvarov** [comment]
Done in version 6.0.39
