### ISSUE TITLE
[BUG] "Unable to load" and "You appear to be offline" intermittently displays across the app [ver. 4.3.57 prod]

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3272]
**Describe the bug**
The two messages below have been displaying intermittently across the app while networking or wifi works. Content loads appropriately only **after** I exit and then restart the app. A few sample screenshots follow.
- Failed to load [XXXX] service (e.g., Failed to load dining locations)
- You appear to be offline. No [XXXX] are available while you are offline (e.g., You appear to be offline. No upcoming events are available while you are offline)

**Screenshots**
**Fig. 1: Failed to load dining locations**
![Failed to Load 1](https://github.com/rokwire/illinois-app/assets/118769169/3b339b6a-4a30-4510-8d69-dfc67bd9a778)

**Fig. 2: Failed to load MTD stop locations**
![Failed to Load 2](https://github.com/rokwire/illinois-app/assets/118769169/467dcfa3-3f7d-4f06-9218-f25a53f7fa22)

**Fig. 3: Failed to load building locations**
![Failed to Load 3](https://github.com/rokwire/illinois-app/assets/118769169/09e2534e-057c-4970-bd63-275eaa1d608d)

**Fig. 4: You appear to be offline**
![Offline](https://github.com/rokwire/illinois-app/assets/118769169/5bda9c61-2bc8-4e0b-aea6-42fd91d04b82)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13
 - 4.3.57 prod

**Comment by dobromirdobrev** [comment]
Hi @knguyenjahiel ,
I'm not able to reproduce this. Or more precisely I reproduce this when the device is offline. My assumption is that there could be problems in the network and that's why you see these messages. 

It would be helpful if you can provide a concrete user scenario that will reproduce the problem and/or a logcat log from the device when this happens. 

Other than that the above messages are expected if the device is not connected to the internet or there is a problem with the connection. Thanks.

**Comment by knguyenjahiel** [comment]
Hi, @dobromirdobrev. The device was online and internet was working (I was able to access Teams and Slack). Unfortunately, these errors aren't occurring regularly, so I haven't been able to see any particular pattern. These could be similar errors reported by @joegrohens in ticket ##3178.

**Comment by knguyenjahiel** [comment]
Issue now is appearing in prod version  4.3.61: "failed to load" is occurring in multiple selections in Map (Find a Therapist, My Courses, Campus Buildings). Academics >> My Courses displays the correct message, "It appears you have no courses registered for the selected term." This has been noted in Slack on July 11 to @pmarkhennessy and @shurwit. 

On July 10, additional to the preceding list "failed to load" also occurred for All Groups and My Groups. They now are loading properly.

Prija tested with me last week and the same occurred for her.

Please note our Internet connections are excellent.

Per @clint156 on 7/17 via Slack:
![image](https://github.com/rokwire/illinois-app/assets/118769169/028eab5d-3c93-48db-b025-89bc839641b6)
