### ISSUE TITLE
[BUG] Laundry screen - Map is not working

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3299]
**Describe the bug**
Map in Laundry is not navigating the directions to the users

**To Reproduce**
1. Install the Illnois app
2. Navigate to Browse screen -> Laundry
3. Tap on any of the laundry in displayed list
4. Tap in View Map on detailed laundry screen

**Actual Result**
Map in Laundry is not navigating the directions to the users

**Expected behavior**
Tha app should provide direction to the location

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]

 - Version [e.g. 4.3.60]

**Comment by kpecknold** [comment]
This should never have become a bug, the "view on map" link for laundry was requested to be removed in issue #1674
@mihail-varbanov @Priyaravi8

**Comment by TodorBachvarov** [comment]
Button is removed in version 5.0.56.
