### ISSUE TITLE
Super Events - Date format should be consistent

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#33]
**Describe the bug**
Date format should be consistent throughout the Event 

**To Reproduce**

1. Install Illinois app
2. Complete Onboarding steps
3. Log in as "University student"
4. Tap on Events on the Home screen. Search for "Discover healthy Aging Series"
5. Discover healthy Aging Series Event is displayed with sub-events

**Actual Result**
The date format is not consistent for the event Discover Healthy Aging Series. Meaning it should display the actual date like Sep 3 -Sep24 but not **Thursday - Sep 24**

**Expected behavior**
Date format should be consistent

**Screenshots**
![date F](https://user-images.githubusercontent.com/26231179/91904757-0fdcb600-ec6b-11ea-8ea7-00a6477d9a5b.png)
![Date F 2](https://user-images.githubusercontent.com/26231179/91904762-12d7a680-ec6b-11ea-9f50-e6bed0676756.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.2.15]

**Comment by dobromirdobrev** [comment]
Fixed for version 2.2.18 and above. Please note that if the date is today or tomorrow, the label will remain respectively 'Today' or 'Tomorrow'. But it won't show anymore weekday labels.

**Comment by Priyaravi8** [comment]
Retested this issue. This issue is fixed.
