### ISSUE TITLE
[USABILITY] Pinch-to-zoom on images

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3305]
When a user taps on an image to open and view the entire image, can the user also pinch to zoom on that image? Below is an example where a user should be able to zoom in on an image. 

![image](https://github.com/rokwire/illinois-app/assets/1044905/c482320a-635c-4646-9f62-c64a736e4b33)

Illinois app version 4.3.61
iPhone 13 Pro, iOS 16.3

**Comment by TodorBachvarov** [comment]
Implemented in version 5.0.55

**Comment by vburgett** [comment]
Confirmed as updated in 5.0.55. Thank you!
