### ISSUE TITLE
[USABILITY] Broken link in Illini Cash screen

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3306]
**Problem**

A link to a webpage on the "Illini Cash" screen is broken. 

1. Go to Browse > Wallet > Illini Cash
2. In the text under "Buy Illini Cash", touch the link to 'other selected services'.

It returns "Page Not Found"

**Remedy**

Please update the link with this URL:
https://housing.illinois.edu/dine/purchase/illini-cash

**Screens**

![0](https://github.com/rokwire/illinois-app/assets/66988329/54451f1a-4653-4307-b91a-44570aa5cd3a)

![0-1](https://github.com/rokwire/illinois-app/assets/66988329/b20f78f0-2b41-430b-929d-0f00ee30e1a4)

Reported by @ayoung-illinois

@vburgett 
..................

Also, the Housing department at UIUC has overhauled their website, resulting in many changed locations for their pages. 

Is it possible to scan for broken links within app screens?

**Comment by mihail-varbanov** [comment]
Fixed. The update is in the app config service and is not related to a particular Illinois app build.

**Comment by joegrohens** [comment]
confirmed fixed via iphone 4.3.61
