### ISSUE TITLE
[BUG] Distorted splash screen when opening app

### ISSUE THREAD

**Issue by JosephShepin** [rokwire/illinois-app#3307]
Describe the usability issue
The Rokwire logo and background image are distorted on the app splash screen

To Reproduce
- Open the app

## On the screenshot I have overlayed the Illinois and Rokwire logos (shown in teal border) to demonstrate how the app is stretching everything compared to the correctly proportioned logos

Screenshots
<img width="282" alt="Screenshot 2023-06-03 at 10 56 47 PM" src="https://github.com/rokwire/illinois-app/assets/31457361/8d0cb7a1-bb6f-4328-b6aa-375c6d81f331">

Device: Pixel 7
OS: Android 13

**Comment by mihail-varbanov** [comment]
Resolved in version 4.0.55
