### ISSUE TITLE
[BUG] Disappearing dining hall card

### ISSUE THREAD

**Issue by JosephShepin** [rokwire/illinois-app#3314]
The dining hall card disappears when scrolled into view from the "recently viewed" section

https://github.com/rokwire/illinois-app/assets/31457361/5293ded0-469c-488a-8532-f4381ca89b8e

Android 13, Pixel 7

**Comment by TodorBachvarov** [comment]
@JosephShepin, could you test it again please. I'm not able to reproduce this issue and I assume it's already fixed.

**Comment by knguyenjahiel** [comment]
Confirming issue has been fixed.
