### ISSUE TITLE
[USABILITY] Missing bus times refresh

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3325]
**Describe the usability issue**
MTD bus stop screens do not update time-to-arrival  unless you exit the screen and re-enter.

This is misleading. Bus riders know that bus times are updated based on real-to me data, and a user may think the bus will arriving later than it really does. (And then miss their bus).

**To Reproduce**
1. Go to any bus stop. (Eg, Browse > MTD Bus Stops > All Bus Stops > Illinois Terminal > some-bus-stop)
2. Leave the screen open and watch the minutes number. 

It should automatically update every minute.

Pulling the screen down does not refresh. Neither does putting the app in background.

You must exit the screen and te-enter to update the time.

....
iPhone 
Illinois app v4.3.61

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.49.

**Comment by joegrohens** [comment]
confirmed fixed in v5.0.68
