### ISSUE TITLE
[USABILITY] GDPR item: Remove text referencing unused data in the app

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3332]
Describe the usability issue
As part of our GPDR compliance work, we have been advised to remove references to data currently unused in the app. Attached are the screenshots.

[Unused Data App Content.pptx](https://github.com/rokwire/illinois-app/files/11823908/Unused.Data.App.Content.pptx)

Please note that reference in the App Privacy Policy Notice will be removed by Communications (Joe's team).

Thanks,
Kim

**Comment by knguyenjahiel** [comment]
@pmarkhennessy, please hold off on addressing this ticket. Joe Grohens would like to consult with JP and Bill S. I'll keep you posted. Thanks, Kim

**Comment by pmarkhennessy** [comment]
OK Got it. Mark

**Comment by knguyenjahiel** [comment]
Hi @pmarkhennessy, I need to verify whether the app is currently processing or collecting the following data on users. If a type of data is being collected/processed, can you list the purpose for the collection?

* credit card number/information (currently collected to add Illini cash)
* library card number and barcode
* voter registration status
* whether they are signed up to vote by mail

Many thanks!
Kim

**Comment by mihail-varbanov** [comment]
Hi @knguyenjahiel,

I updated the strings in privacy panel.

We have no control on Privacy Notice content, that is located on https://go.illinois.edu/illinois-app-privacy. This should be done by someone else who maintains this web content.

On your question about data collection and processing:

**_credit card number/information (currently collected to add Illini cash)_**
I am not sure what meaning you put in the collection and processing. Yes, we collect credit card details when the user makes a transaction to Illini Cash. We send them immediately to the University's payments backend service located on https://housing.illinois.edu. We do not cash or store this data in any way. I do not know what happens on the backend but I am pretty sure that they use good security practices.

**_library card number and barcode_**
No.

**_voter registration status_**
**_whether they are signed up to vote by mail_**
Yes, this information is collected and stored for the user's account prefs on the backend. It is used only to populate the widget in the Home/Favorites panel that collects this information, and nothing else as far as I see. И realize that doesn't sound very meaningful, but this is what И see in the source code. This widget was created 3-4 years ago, it is currently disabled and to be honest I have no idea if it has ever been enabled and used. You can ask @johnmpaul or @pmarkhennessy  about what was the overall idea of this all.

**Comment by knguyenjahiel** [comment]
Thanks, @mihail-varbanov, for making the changes in the app and for the descriptions of how and why the listed data are being collected and used.

@joegrohens, would you update the Private Policy Notice [https://go.illinois.edu/illinois-app-privacy](url)? I think we can remove the statement regarding voter registration status and whether they are signed up to vote by mail.

Thanks,
Kim
