### ISSUE TITLE
[USABILITY] Event Feed Tweaks

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3392]
When creating an event in the Illinois app, please make the below updates.

- Change "Sponsorship and Contacts" to "Event Host Details" Remove "Speaker" field since this information would be included in an event description. Change "Sponsor" to "Event Host" Change "Set sponsor, speaker and contact to your event." to "Display event host and contact information."
- 
- The "Event Description" field should be a multi-line field (make the box taller)

Cc: @sandeep-ps 

Android
Version 5.0.23

**Comment by TodorBachvarov** [comment]
Done in version version: 5.0.51

**Comment by vburgett** [comment]
One edit was excluded. Please update Sponsor to Event Host as indicated on the below screenshot. 

Thank you!

![Screenshot_20230822-150530~2.png](https://github.com/rokwire/illinois-app/assets/1044905/dedd3b86-8a29-45a0-bbd4-8e12e40ff65e)

**Comment by TodorBachvarov** [comment]
Fixed in version 5.0.54

**Comment by vburgett** [comment]
Confirmed as updated in 5.0.55. Thank you!
