### ISSUE TITLE
Users are not able to toggle OFF/ON of Notification

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#34]
**Describe the bug**
Notification Preference of Privacy center, users not able to toggle OFF/ON of the Event Remainder, Athletic update, and Dining specials.

**To Reproduce**

1. Install Illinois app
2. Complete onboarding steps.
3. Verify the user role as University student
4. Tap on Privacy Center on Browse screen. On the Privacy center screen, tap on Notification Preferences.
5. The notification screen is displayed with the toggle OFF/ON button of the Event Remainder, Athletic update, and Dining specials.

**Actual result**
Tap on the toggle button to turn it ON/OFF of Event Remainder, Athletic update, and Dining specials.

**Expected behavior**
Users are not able to toggle OFF/ON Notification of Event Remainder, Athletic update, and Dining specials.

**Screenshots**
![Toggle button on](https://user-images.githubusercontent.com/26231179/91905890-da38cc80-ec6c-11ea-8c3b-2a2199e6f262.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.2.15]

**Comment by dobromirdobrev** [comment]
Cannot be reproduced. Please re-test with latest version (currently it is 2.2.17).
