### ISSUE TITLE
[FEATURE] Allow users on non-English OS to override their system localization and let the app use English in screens and system messages.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3423]
**Is your feature request related to a problem? Please describe.**
Periodically users submitted Feedback asking to let the app be in English rather than the language of their phone's operating system.

The number of complaints is not large. Not more than 10 in any semester. But the fact that users are motivated to comment on it means that it is producing friction in their user experience.

Chinese users say that the Chinese translation has problems that make it inconvenient to use. Some of the problems are that both Traditional and Simplified Chinese appear in the screens, as well as some English. And the Chinese translation has some errors in vocabulary and syntax.

Languages that we have not provided localization support for are automatically translated by the phone's operating system if the phone is set to a non-English language. The results are imperfect, but the user may still have a reason to want to keep the phone set to their home country language.

The context for using the Illinois app is an English-language campus, where all instruction is in English, students are required to have English proficiency, and the reading and speaking environment is primarily English. For these users, it is usually a better user experience to have the Illinois app in English than a flawed localization to another language.

Users I have talked to about this don't want to change the language setting of their phone's OS. They want to override the system language setting and use English.  

**Describe the solution you'd like**
Add a user-selected setting that allows the app to "Use English language instead of the language setting of your phone." 

**Describe alternatives you've considered**
We have suggested setting their phone's language to English. They do not want that.

**Comment by joegrohens** [comment]
Example user comments:

1. User one.
> Language Option in the App missing or hard to findI really like this app, but unfortunately, the default language on my phone is not English, and the app doesn't seem to have any language settings to switch it to English. The app's automatic translation feature is not very helpful, as it simply translates all the words without any revision or modification. As a result, it's difficult for me to understand the app, even though it's in my own language.

2. User two.
>Hey, I love the fact that there's an attempt to display things in my native language but I would really love an option to change the display language to English.Half Chinese half English content kinda hurts my eyes. Thanks!

**Comment by mihail-varbanov** [comment]
This is implemented in version 5.0.50.

**Comment by joegrohens** [comment]
confirmed. thank you!!
