### ISSUE TITLE
[FEATURE] Essential Skills Coach Dashboard

### ISSUE THREAD

**Issue by shurwit** [rokwire/illinois-app#3425]
**Describe the solution you'd like**
We should build out the UI for the landing dashboard of the Essential Skills Coach. This dashboard should include the BESSI skill that you are currently working towards and it's most recent score, assignments and resources, tasks, and a task completion progress bar.

**Additional context**
See Zeplin for design details

**Comment by shurwit** [comment]
This is blocked waiting for design updates

**Comment by roberlander2** [comment]
Resolved by #3924
