### ISSUE TITLE
[USABILITY] Wording update: event creator edit link

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3431]
Please change the link text “Event Admin Actions” to “Event Admin Settings” 

After testing events this morning, the group agreed this updated wording would be more clear to the event creator.

Illinois app 5.0.33

![Screenshot_20230724-120909~2](https://github.com/rokwire/illinois-app/assets/1044905/f679ab4a-0d2d-460b-b3a3-a188f2f4a827)

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.47

**Comment by vburgett** [comment]
Confirmed as complete in 5.0.52. Thank you!
