### ISSUE TITLE
[BUG] Create Event, Should See Event Admin Details Panel

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3432]
After creating an event in the app, the event details panel is _not_ displayed to the event creator as an admin. The event creator has to go to the event feed, find the event they just created, and _then_ they see the event admin settings in the event panel.

I expect an event creator to create an event and immediately see the event details panel as the admin with the corresponding admin settings.  

Android 12, Pixel 6
V5.0.33

![Screenshot_20230724-120818](https://github.com/rokwire/illinois-app/assets/1044905/c8d75287-3a51-4d61-ae1e-8b7e5eb255c6)
![Screenshot_20230724-120909](https://github.com/rokwire/illinois-app/assets/1044905/f2411f31-1fe0-4400-b84d-d080d47aa425)

**Comment by mihail-varbanov** [comment]
This was a backend issue, already reported in rokwire/calendar-building-block#200, that is already fixed. Please re-test again, it works well to me now.
