### ISSUE TITLE
[USABILITY] Change wording and default setting for "Cost" field in Create Event form. (5.0.33)

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3434]
**Describe the usability issue**
The "Create Event" screen has a field named "Cost"

This field has two options:
1. Free event.
2. Description of the cost.

Currently the "Free" option is selected by default (with a switch), with a label that says "Is this event free?"

This setting label is confusing. The user thinks they should answer Yes/No. The switch is already on, so user doesn't know what action to take. And that appears to be the only option, because the "Cost Description" text box is hidden..

**Recommended changes**
I recommend that we make two changes to improve clarity about this.

1. Rename the "free" option with this label: "This event is free." (The user action can still be a switch)
2. Set the switch default to "Off". Without the user taking an action, it is hard to interpret that the "Cost" section is already completed. 

**Additional change**
In #3461 Vanessa asks that the _Cost Description_ field be left visible for free events. You could consider changing the tooltip-like prompt in the text box to "Donation suggested" when "This event is free" is set to ON.

**Comment by joegrohens** [comment]
@vburgett

**Comment by vburgett** [comment]
This ticket is ready for Mark to assign. Thank you, @joegrohens.

**Comment by mihail-varbanov** [comment]
The things got changed after fixing #3461:

1. Cost description is available both for free and not free events;
2. If an event is selected as not free, the cost description is required

**_Rename the "free" option with this label: "This event is free."_**
The option currently says "Is this event free?", that has the same meaning for me.

_**Set the switch default to "Off"**_
I suspect that most of the events are free, and I want to pre-populate the most common selection. If I make the default to "Off" this will now require the user to populate the cost description. In general, I think that changing this default to "Off" will make the process of event creation harder, not simpler. 

Please reconsider the recommended behavior under the latest updates in create event logic.

CC @pmarkhennessy.

**Comment by joegrohens** [comment]
Thank you for the changes @mihail-varbanov. I will discuss the user experience with Vanessa. Leaving this open for not to remind us to talk about it.
