### ISSUE TITLE
[USABILITY] Remove period from end of all button text

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3435]
Remove periods from the end of all button text. 

For example, when creating an event in the app, the button for the cover image says  “Add event image.” or “Modify event image.” Please remove the periods.

Cc: @kpecknold 

v5.0.33
Android 12, Pixel 6

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.47:

I tried to remove all periods from button titles across the entire application. The buttons from the above example currently do not contain periods in their title but they used to have such before.

Please note that we keep periods in some other cases like labels (e.g. "I am a...") or text field hints (e.g. "Type your question here...").

Please me know please If you notice for other places with irregular use of periods.
