### ISSUE TITLE
[USABILITY] Broken links in the Wellness Resources screen

### ISSUE THREAD

**Issue by wchiaching6** [rokwire/illinois-app#3440]
**Describe the usability issue**
(@dr-mel: Would you please confirm these new URLs, and provide a URL for Other Wellness Resources, the last item on the list?)

[Updated per Mel’s comment below (8/1)]
Below is a list of broken links on the Wellness > Wellness Resources page with their current/correct Url underneath. 

Counseling Center (campus guide article)
Campus Guide > Health & Wellness > Mental and Emotional Health > Counseling Center
content ID: 996915de-2f43-40e1-b24a-40ec7be67c35.1

Accessibility and Accommodations (external link)
New link: https://wellness.illinois.edu/accessibility-accommodations

Financial Assistance (external link)
New link: https://wellness.illinois.edu/wellness-resources/financial-assistance

Fitness and Recreation (external link)
New link: https://wellness.illinois.edu/wellness-resources/fitness-recreation

Food and Nutrition (external link)
New link: https://wellness.illinois.edu/wellness-resources/food-nutrition

Mental Health and Counseling (external link)
New link: https://wellness.illinois.edu/mental-health-resources

Nature and Culture (external link)
New link: https://wellness.illinois.edu/wellness-resources/nature-culture

Wellness Events and Workshops (external link)
New link: https://wellness.illinois.edu/wellness-resources/events-workshops

Other Wellness Resources (external link)
New link: https://wellness.illinois.edu/mental-health-resources/online-resources

**Comment by dr-mel** [comment]
Mental Health and Counseling (external link) should be: https://wellness.illinois.edu/mental-health-resources

All others look great! Thanks for reviewing!

**Comment by mihail-varbanov** [comment]
The links are fixed on production. Please note that this is not a fix in Illinois app, this is a fix in the clouds, i.e. it is immediately applicable.

**Comment by wchiaching6** [comment]
Confirmed fixed.
