### ISSUE TITLE
[BUG] Event creation: "free" toggle bug

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3461]
When creating an event in the app, the free toggle should not affect the visibility of the cost description. The cost field should be visible regardless of whether an event is free. 

I expect a user to be able to create a free event AND be able to add a cost description of "donations suggested."

See v4.3.61 Groups > Create Event to see how the free toggle should continue to function. 

Illinois app v5.0.37
Android 12, Pixel 6

![Screenshot_20230801-124030.png](https://github.com/rokwire/illinois-app/assets/1044905/16a447da-7cba-447c-933a-23fc0f4d56d6)

**Comment by joegrohens** [comment]
@vburgett This issue overlaps with (and partly contradicts) https://github.com/rokwire/illinois-app/issues/3434 

Please comment on or edit 3434.

**Comment by vburgett** [comment]
Contradiction between the two tickets is resolved. Thank you, @joegrohens.

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.47:

1. Cost description is available both for free and not free events;
2. If an event is not free, cost description is required.
