### ISSUE TITLE
[USABILITY] Change "Event Feed" to "Events Feed"

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3486]
The item name "Event Feed" is not consistent with other category names in the UI.

We usually use a plural noun to identify a class of aggregated multiple content items. Academics, Athletics, Events, Favorites, Groups, Notifications, Polls, Settings, etc.

And every other heading in the Events section uses the plural form, "Events".

Due to this inconsistency, I recommend that we change: 

_Browse > Events > Event Feed_

to 

_Browse > Events > Events Feed_

This change is supported by @vburgett

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.42.

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.42.

**Comment by joegrohens** [comment]
No longer an issue due to renaming of Events submenu items. "Events Feed" is no longer used.
