### ISSUE TITLE
[BUG] Location marker on the event should be displayed only if there are geo-coordinates in the event location

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#35]
**Describe the bug**
If there are no geo-coordinates in the event location object, clickable location marker should not be displayed. Currently, such events are having a location marker and clicking on it is resulting in an error.

**To Reproduce**
1. In the Events talent, search for Discover.
2. Visit the "Discover Healthy Aging Series" event
3. Click on the location marker.
4. See error in the screenshot

**Expected behavior**
Location marker should not be displayed as this is a virtual event. For virtual events, we are trying not to set any default geo-coordinates in the backend. We would also be marking virtual events with an `isVirtual`=`true` flag. This can also be used when displaying location marker, but currently, missing geo-coordinates in location object means there is no location information.

**Screenshots**
![Image from iOS (1)](https://user-images.githubusercontent.com/4306604/91915921-694fdf80-ec81-11ea-8016-25a102b91ed5.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13
 - Version 2.2.13

**Additional context**
In this case, the event location data will look like this:
```
{
"description": "some location description"
}
```

**Comment by mdryankov** [comment]
@sandeep-ps it doesn't make sense to open Directions panel if there is no location at all. Shall we just ignore the tap action for the location entry?

**Comment by sandeep-ps** [comment]
This is fixed. Closing. Thanks.
