### ISSUE TITLE
[BUG] Shibboleth Error when courses.illinois.edu is selected from Illinois Assistant [ver. 5.0.41] 

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3509]
**Describe the bug**
Shibboleth error comes up when I select "courses.illinois.edu" and "www.senate.illinois.edu" in the Illinois Assistant. These links point to pdf files for one to download. They were results to my question, "Where are business courses taught?" Please note that I do not get a prompt to sign in via Shibboleth before being prompted to download the files. The Shibboleth error message remains in the background.

**To Reproduce**
1. Select Assistant from Menu
2. In text box, type: Where are business courses taught?
3. Select courses.illinois.edu external link
4. See error.
5. The same occurs when www.senate.illinois.edu link is selected

**Expected behavior**
I expect to see the prompt to download the pdf files without the Shibboleth error message.

**Screenshots**
![5 0 41_SibbolethError_External_Courses_Link_IA](https://github.com/rokwire/illinois-app/assets/118769169/f612ce29-a525-4947-9475-437dda600eef)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 13
 - Version 5.0.41

**Comment by knguyenjahiel** [comment]
I am encountering same Shibboleth error when selecting links that point to pdf files provided by the Assistant. 

1. Test with this question: What seafood dishes are being served in the dining halls? 
2. Select "www.isss.illinois.edu" link

**Comment by mihail-varbanov** [comment]
1. The UIUC app is not involved in user login process, it just launches the link URL that comes from the assistant backend service. It is up to the URL host what it will be displayed as a link content.
2. There was a problem with Shibboleth service (after they upgraded something) for maybe a week or more. I suspect the Shibboleth error pages attached to this issue are result of this malfunction.
3. At the moment all link URLs get opened properly (without Shibboleth errors), so i would say the problem does not persist any more.

**Comment by knguyenjahiel** [comment]
Confirming Shibboleth error message no longer displays. Thanks
