### ISSUE TITLE
[BUG] Long Event Titles 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3517]
In the Events Feed, please add an ellipsis to event titles that are truncated. In the below example of the event card, "Well this is the" should appear as "Well this is the . . ."

The event details panel shows the truncated event title. It should show the full event title. 

Version 5.0.53
Android 13, Pixel 6

![Screenshot_20230810-112128.png](https://github.com/rokwire/illinois-app/assets/1044905/8929bd21-2563-423f-8e02-a6954c0068b2)

![Screenshot_20230810-112135.png](https://github.com/rokwire/illinois-app/assets/1044905/09f35308-fec2-4bd0-b8b8-1f5a645358c7)

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.46.

**Comment by vburgett** [comment]
Thank you!!
