### ISSUE TITLE
[BUG]Error message is displayed when a appointment is rescheduled.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3554]
**Describe the bug**
Error message for Rescheduling the appointment

**To Reproduce**
1. Install the Illinois app
2. Navigate to the appointment via the Browse screen and Tap on the displayed appointment
3. Tap on Reschedule
4. Select the time and tap on the Next button. 
5. Fill in the required field and tap Next. Tap on Reschedule button.

**Actual Result**
Error message is displayed

**Expected behavior**
App should reschedule the appointment without any Error

**Screenshots**
![Appointment reschedule](https://github.com/rokwire/illinois-app/assets/26231179/62e80788-dea5-4e42-81e2-fdaae4d3b361)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 5.0.45]

**Comment by mihail-varbanov** [comment]
This is a backend issue not related to the UIUC client app. I created new issue in Gateway BB's repo (rokwire/gateway-building-block#30) and closing this one.
