### ISSUE TITLE
[BUG] Campus reminders are empty

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3556]
**Describe the bug**
No campus reminders are listed for the students

**To Reproduce**
1. Install the Illinois app
2. Navigate to Campus remainders under the Academics section and tap on it

**Actual Result**
There are no active campus reminder results for the students

**Expected behavior**
All the expected reminders should be displayed 

**Screenshots**
![Reminders](https://github.com/rokwire/illinois-app/assets/26231179/748a0ac5-feeb-43fa-9420-4b9a4e5cf7b3)

**Smartphone (please complete the following information):**
 - Version [e.g. 5.0.47]

**Comment by joegrohens** [comment]
@Priyaravi8 @TodorBachvarov @pmarkhennessy 

These reminders come from Campus Guide. The test build only has out-of-date reminders (most recent is May 12).

I will have someone post a reminder for a September date so that we can test the system.

**Comment by wchiaching6** [comment]
Hi, I have added three events to the Campus Reminders, Quad Day (8/20), First Day of Instruction (8/21), and Labor Day (9/4). Please re-test the system. Thank you.

**Comment by TodorBachvarov** [comment]
@Priyaravi8 Could you retest with v5.0.49

**Comment by Priyaravi8** [comment]
Fixed
