### ISSUE TITLE
[BUG] Groups - member and admin names are often displayed multiple times

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#3567]
This is in current prod build 4.3.61
Testing of university-managed groups is easier in prod

Many people (some admins and some members) are displayed multiple times when scrolling through the membership list. However, when you search for them, the search results only shows one record.

Examples:
1. In Babcock-Carr, Kristin Freel (freel2) appears at least 3 times and admin Mari Brocker Curry appears twice in the scroll when filtered to "admin"

**Comment by TodorBachvarov** [comment]
This sounds like a backend issue related with the pagination/offset when loading members from groups BB. @pmarkhennessy  could you redirect to the backend team when someone is available.

**Comment by TodorBachvarov** [comment]
I've created a backend issue for the groups building block: 
https://github.com/rokwire/groups-building-block/issues/387. Closing this one.

**Comment by mdryankov** [comment]
This probably fixes along with: https://github.com/rokwire/groups-building-block/issues/386

Please retest and give a feedback.
