### ISSUE TITLE
[BUG] Groups - Prompt Login button for unverified users

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#357]
**Describe the bug**
If the user **didn't verify his identity with Netid/Pwd**, App should Prompt the "Login button" when the user taps on the Groups tile.

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and **user didn't verify his identity with Netid/PWD**
3. Proceed to Browse screen and tap on Groups

**Actual Result**
App didn't display the "Login button" for the user who didn't verify his identity with Login/PWD.

**Expected behavior**
If the user didn't verify his identity with Netid/Pwd, App should Prompt the "Login button" when the user taps on the Groups tile.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]

 - Version [e.g. 2.4.31]

**Additional context**

**Comment by mdryankov** [comment]
Fixed.

**Comment by Priyaravi8** [comment]
Retested this issue. This is fixed.
