### ISSUE TITLE
[BUG] Can't Register for Events

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3579]
When tapping the "Register" button on an event (created within the app with in-app registration), a user is not able to register. An error message is displayed "Failed Error getting finding: error performing transaction."

v 5.0.47
Android 13, Pixel 6

![Screenshot_20230815-133610](https://github.com/rokwire/illinois-app/assets/1044905/bc7f4c53-0010-4757-8204-b028c4b20f9b)

**Comment by mihail-varbanov** [comment]
This is a Calendar BB's issue and I created a ticket for this in its GIT repository: rokwire/calendar-building-block#282.
