### ISSUE TITLE
[BUG] Event Admin Required to Fill Out Survey

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3581]
Create an event via the app, choose an event follow-up survey, and see how the survey preview fields are mandatory to fill out for the event creator to include a survey.

When creating an event, the event administrator shouldn't have to fill out the survey in order to include a survey with their event.

v 5.0.47
Android 13, Pixel 6

![Screenshot_20230817-103127](https://github.com/rokwire/illinois-app/assets/1044905/f3689322-6b9c-4498-86f4-4498d2df6b42)

**Comment by roberlander2** [comment]
Thanks @vburgett, just to clarify, the survey preview does not need to be filled out to create or update the survey. The event admin may fill out the survey and hit the "Continue" button to see what will happen if an event attendee fills out the survey as the event admin just did.

The survey is updated by hitting "Apply" in the upper right for an existing event. When creating a new event, a new survey is created by hitting the back arrow and creating the event (the new survey is created immediately after).

Please let me know if this makes sense and if you think the UI should be changed here to make things clearer.

**Comment by vburgett** [comment]
Thank you, @roberlander2 for that explanation. I did not understand that.

When and where a user taps apply or the back arrow is confusing when creating and filtering events. Let's try and address that in the 5.1 winter release.

For now, I would suggest implementing 1-3. (Number 4 seems out of scope at this point but I am mentioning it in case you disagree.)

1) add a line above "Survey Preview" 

2) add body text under "Survey Preview" that says "Optional: Fill out the below sample survey." 

3) For the Action pop-up message, update the text to "Thank you for testing your event follow-up survey. At this point, the survey would be submitted, and the results would be available to view under the event admin settings." 

4) Mimic the "create an item" to-do list optional field where "optional fields" says "Survey Preview" and the survey is only visible if the arrow is expanded. 

![Screenshot_20230822-150308~2.png](https://github.com/rokwire/illinois-app/assets/1044905/c15a9a28-f8d8-4f99-9a38-ab99d09f808c)

![Screenshot_20230822-165402.png](https://github.com/rokwire/illinois-app/assets/1044905/39919483-5e1b-4f8d-84f4-4516ae3c059f)

![Screenshot_20230822-164528.png](https://github.com/rokwire/illinois-app/assets/1044905/690e81d6-f8c1-49de-8032-2cebcdc8dae0)

**Comment by roberlander2** [comment]
@vburgett, apologies for the delay. I am going to implement your suggestions 1-3, so those changes should be in the next build.

**Comment by joegrohens** [comment]
I still find the experience confusing.

1. I suggest you add an "Apply" button to the survey screen. Otherwise, how does a user know that the settings for the survey have been saved?

(My request should be confirmed by Vanessa, though, before adding it.)

2. Also, please change the wording of the following test confirmation message.

![survey creation test confirmation](https://github.com/rokwire/illinois-app/assets/66988329/0afc141e-3b38-402c-b003-8b5eceaac7fa)

**New wording:**
This survey is ready to use. The survey will be sent to attendees by message in the app. Survey results will be available. Go back to the Create an Event screen and tap Create Event to save your changes.
