### ISSUE TITLE
[USABILITY] Note required field when adding an event survey

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3582]
When adding a survey to your event as an admin, the below field is required. Please add an asterisk to reflect this requirement.

"How many hours after the event ends before sending this survey to attendees?"

v 5.0.47
Android 13, Pixel 6

![Screenshot_20230817-103127](https://github.com/rokwire/illinois-app/assets/1044905/eba86063-4289-4a9c-a46e-cf2783947da7)

**Comment by TodorBachvarov** [comment]
Added in version 5.0.51.

**Comment by vburgett** [comment]
Thank you!
