### ISSUE TITLE
[BUG] Editing an event in the app and web admin app

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3583]
Create an event via the app and then try to edit the event via the web admin app. 

The event loses registration details and image in the app.

v 5.0.47
Android 13, Pixel 6

cc: @sandeep-ps

**Comment by dobromirdobrev** [comment]
This is a problem in the Calendar BB. A new issue is created in the relevant repo: https://github.com/rokwire/calendar-building-block/issues/286 

cc @pmarkhennessy , @vburgett

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

This issue is resolved in the Admin app version 5.0.25. Please verify when you have a chance
