### ISSUE TITLE
[BUG] Update link to web admin under Event Admin Settings Event Attendance

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3584]
As an admin of an event, when tapping "Event Admin Settings" in an event details panel, choose "Event Attendance."

Please update the text from "go.illinois.edu/ILappAdmin" to "go.illinois.edu/AppAdmin"
Make the link tappable, leading to https://go.illinois.edu/AppAdmin 

v 5.0.47
Android 13, Pixel 6

<img width="505" alt="Screenshot 2023-08-17 at 10 44 49 AM" src="https://github.com/rokwire/illinois-app/assets/1044905/7f2f131b-379e-49e8-bedc-cecc961207ea">

**Comment by mihail-varbanov** [comment]
Resolved in version 5.0.50

**Comment by vburgett** [comment]
Thank you!
