### ISSUE TITLE
[BUG] Event Creation: Time

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3585]
When creating an event, an event does _not_ currently require a user to put in a start time or end time. The event however _does_ display a start and end time. 

Please require a start time. If an event does not have a start time, it is not "an event." 

Please either require the user to put in an end time OR don't require it _and_ don't display an end time. 
(Many campus units add their events to Facebook where they are used to being required to add an end time to their events.)

(Without a required start time and end time, the entry more or less defaults to an all-day event. We eliminated all-day events to exclude "events" that were not adding value to the event section of the app.)

v 5.0.47
Android 13, Pixel 6

![Screenshot_20230817-113822](https://github.com/rokwire/illinois-app/assets/1044905/723fe2ef-3637-4c99-8cee-846d6903d08d)

**Comment by mihail-varbanov** [comment]
Hi @vburgett, I would disagree with you.

First, let's try to clarify something to avoid miscommunication. The UI differentiates the date and time parts. They both define a datetime object. While the date part is required for a datetime object, the time part is optional and it is assumed to be 12:00 am in case it is omitted.

**_When creating an event, an event does not currently require a user to put in a start time or end time._**
Assuming that by "start time or end time" you actually mean start and end datetimes as described above, I would disagree. We do require a start datetime while the end datetime is optional. You can check this in the read errors list under the "Create Event" button who lists "date and time" as missing until you select a start datetime.

Update: while I played with date and times I noticed that we did allow the end datetime to precede the start date time. This is now (version 5.0.50) handled and listed in the red errors list.

**_The event however does display a start and end time._**
No, it is prepared that start time can be omitted and takes care to make the proper analysis and display what is available. Please see the screenshots bellow.

![Screen Shot 2023-08-18 at 2 49 32 PM](https://github.com/rokwire/illinois-app/assets/5631487/6a9a94c2-d15e-419d-a5bc-70bc101158a7)

![Screen Shot 2023-08-18 at 2 49 37 PM](https://github.com/rokwire/illinois-app/assets/5631487/a6a70f82-ac41-471b-83fb-7e15677088e3)

**Comment by vburgett** [comment]
Thanks for the explanation, @mihail-varbanov.

I would vote for the start datetime to be a required field for the user rather than have the app fill in that detail for the user. The event creator could easily miss that their event is listed in the app as starting at 12:00 am when the event actually starts at a different time. We can prevent the user from showing up to an event at the incorrect time by requiring the user to enter the start datetime.

**Comment by mihail-varbanov** [comment]
@vburgett, if i understand you correctly you want to require both date and time parts in order to build event's datetime object. This is what I did in version 5.0.53, both for start and end datetimes, but still supporting optional end datetime.

**Comment by vburgett** [comment]
Confirmed as updated in 5.0.55. The attached event required I put a start time in as requested. I was able to leave the end date and time blank.

Thank you!

![Screenshot_20230825-123125](https://github.com/rokwire/illinois-app/assets/1044905/23eb3b21-d149-44b8-aabc-efc2ca5c0646)
