### ISSUE TITLE
[BUG] Super event start date is displayed incorrectly in the app

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#36]
**Describe the bug**
This is based on a bug report from @kpecknold. Super event start date being displayed in the app seems to be incorrect.

**To Reproduce**
1. In Events talent, search for the word `discover` or `aging`
2. Visit the "Discover Healthy Aging Series" event
3. The start date of the event is displayed as `Thursday - Sep 24`, which would probably mean that the start date is 09/03/2020 and end date is 09/24/2020. 
5. If you see the event data coming from the backend, the start date is set as `Fri, 04 Sep 2020 05:00:00 GMT`. As this is an all day event, it would be appropriate to display the start date as Friday (in which ever format the date needs displayed.)

**Expected behavior**
Displayed super event start date needs to match the start date in the API call results data.

**Screenshots**
![image](https://user-images.githubusercontent.com/4306604/91931187-5ac8ee80-eca8-11ea-85d3-5abb49460916.png)

**Smartphone (please complete the following information):**
 - Device: iPhoneSE
 - OS: iOS13.6.1
 - Version 2.2.13

**Additional context**

**Comment by mdryankov** [comment]
@sandeep-ps , I'm unable find such event at the moment (no matter dev or prod). Could you please help?

**Comment by kpecknold** [comment]
I can only find the event if I search for "aging"

**Comment by dobromirdobrev** [comment]
Hi @sandeep-ps  and @kpecknold ,

I checked this issue and I see no problem. The display date/time depends on the time zone of the device. For example, I changed my device time zone to be CDT / GMT-05:00 and it shows correctly the start date as "Today" (since today is Sept 4).

For example, if the device is on some other time zone, the start date could be different.

@kpecknold  what is the time zone of your device?

Here is a screenshot from today (Sept 4) for device with time zone GMT-05:00

<img width="321" alt="Screenshot 2020-09-04 at 10 17 25" src="https://user-images.githubusercontent.com/5978121/92212587-dbe7d780-ee9a-11ea-9f99-8ba4e3a0473d.png">

**Comment by sandeep-ps** [comment]
Hi Dobromir, we are in GMT-05:00, but up until yesterday, it was showing as starting on Thursday.

**Comment by sandeep-ps** [comment]
Yes, I also saw the issue. There is an event with the same title (Discover Healthy Aging Series) in the TEST instance. I have updated its start date for debugging. Currently, the test event starts on Sun, 06 Sep 2020 05:00:00 GMT.

**Comment by dobromirdobrev** [comment]
I just checked the event in TEST. It shows as expected for me - Sep 06.

<img width="316" alt="Screenshot 2020-09-04 at 11 21 32" src="https://user-images.githubusercontent.com/5978121/92217829-e1e0b700-eea0-11ea-8884-fc4909feaba3.png">

**Comment by pmarkhennessy** [comment]
@dobromirdobrev if this is fixed please re-assign to @sandeep-ps so he can close the issue

**Comment by dobromirdobrev** [comment]
@pmarkhennessy , I haven't done any action on this issue. I just tested it on my side and I couldn't reproduce it. 
Re-assinging this issue to @sandeep-ps .

**Comment by sandeep-ps** [comment]
Closing this as it was not possible to reproduce this issue the last time. Will reopen in the future if it shows up again.
