### ISSUE TITLE
[USABILITY] Event Type Filter Sub Groupings 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3605]
When filtering the events feed by "event type," there is a combination of "and/or" and "intersecting" logic. For example, a user can filter by either "Free" OR "Paid" but not both. However, a user can filter by "Free" AND "In-person."

To more clearly communicate these groupings within "event type," please increase the weight of the lines slightly in three spots—under "Paid," "Hybrid," and "Private."

v 5.0.47
Android 13, Pixel 6

![Screenshot_20230821-151554](https://github.com/rokwire/illinois-app/assets/1044905/a62b5a94-63d0-40c0-ac02-3be3e087171e)
![Screenshot_20230821-151554~2](https://github.com/rokwire/illinois-app/assets/1044905/7c2e4455-624b-49cf-8064-3763124be29d)

**Comment by mihail-varbanov** [comment]
Implemented in version 5.0.52

**Comment by vburgett** [comment]
Thank you!
