### ISSUE TITLE
[BUG] Event search is not working

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3608]
**Describe the bug**
Event search using the search icon is not working.

**To Reproduce**
1. Install the Illinois app
2. Navigate to Events via Event Feed
3. Tap on Search and type the word "Exhibits" and tap the search icon

**Actual Result**
No Events display for the search

**NOTE** 
If the user selects the filter and selects the Exhibits in the Event Category, an event from the Exhibit category is displayed.

**Expected behavior**
The event search should work successfully

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 5.0.47]

**Comment by mihail-varbanov** [comment]
This is a backend's issue and I created a ticket for it in Calendar BB's repo: rokwire/calendar-building-block#285.
