### ISSUE TITLE
[BUG] Map - Event feed - Search results "TBD" 

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3609]
**Describe the bug**
Search the event feed results "TBD" 

**To Reproduce**
1. Install the Illinois app
2. Navigate Map and select Event feed in the dropdown menu
3. Tap on the search icon

**Actual Result**
TBD message is displayed to the user

**Expected behavior**
App should display the Event locations but not the TBD message.

**Screenshot**
![TBD](https://github.com/rokwire/illinois-app/assets/26231179/ceb45c21-80d1-4f85-aa40-1de93752fbd1)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 5.0.47]

**Comment by mihail-varbanov** [comment]
Fixed in version 5.0.52.

**Comment by Priyaravi8** [comment]
This is fixed
