### ISSUE TITLE
[BUG] Display warning message if the admin delete the group

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#361]
**Describe the bug**
Admins should be able to delete a group but display a pop-up warning that "All members and the group will be deleted."

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and user verify his identity with Netid/PWD
3. Proceed to the Browse screen and tap on Groups
4. Create a group and add a member to the group
5. Leave the group

**Actual Result**
A warning message is not displayed If the admin delete his group

**Expected behavior**
Admins should be able to delete a group but display a pop-up warning that "All members and the group will be deleted."

**Smartphone (please complete the following information):**

- Device: [e.g. Android]
- Version [e.g. 2.4.31]

**Comment by dobromirdobrev** [comment]
Done in version 2.5.2. 
Implemented group deletion. For reference, please see #400 .

**Comment by Priyaravi8** [comment]
This issue is fixed.
