### ISSUE TITLE
[USABILITY] Rename Feeds > Twitter to Feeds > X/Twitter (?)

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3610]
**Describe the usability issue**
[Draft - I am currently undecided about this]

Twitter has been rebranded as X. 

I discussed this with Public Affairs, whose Twitter feed we have in the app. They recommend that we rename the feed X/Twitter. "X" alone is probably too ambiguous, and even Twitter is using X/Twitter on their website.

Comment on the AP Style Book recommendations:

https://www.outkick.com/ap-stylebook-wants-us-to-call-twitter-x-formerly-known-as-twitter/#:~:text=AP%20now%20advises%20journalists%20to,AP%20reporter%20Seung%20Min%20Kim.

**Comment by TodorBachvarov** [comment]
Changed in version 5.0.53
