### ISSUE TITLE
[USABILITY] Wording update, event filters

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3615]
Under Event Filters when "Big 10 Athletics" is selected as the category, please update "Select an athletics" to "Select a sport" under the Big 10 Athletics field. 

![Screenshot_20230822-082913.png](https://github.com/rokwire/illinois-app/assets/1044905/2c2f1390-4de1-4fcd-920e-b9b5c786d06f)

**Comment by TodorBachvarov** [comment]
Fixed in version 5.0.53

**Comment by vburgett** [comment]
Confirmed as updated in 5.0.55. Thank you!
