### ISSUE TITLE
[BUG] Events - Sort by Proximity Error

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3618]
Under Events Feed, Sort by Proximity results in the below error. 

V 5.0.52
Android Pixel 6

![Screenshot_20230822-174928.png](https://github.com/rokwire/illinois-app/assets/1044905/054a6a45-7e06-4c3d-80bf-b9bbd206dbd5)

**Comment by mihail-varbanov** [comment]
This is a backend's issue. I created a ticket in Calendar BB repo for this: rokwire/calendar-building-block#293
