### ISSUE TITLE
[BUG] In-app event registration - no register button

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3619]
When creating an event and choosing In-app registration, no register button is presented in the event details panel. See the event on 8/23 at 1pm CT called Sandwiches and Survey Test.

V 5.0.52
Android Pixel 6

![Screenshot_20230822-171122.png](https://github.com/rokwire/illinois-app/assets/1044905/6cf62566-9434-423e-aeaf-f4a7d8f58464)

**Comment by mihail-varbanov** [comment]
@vburgett, as an admin of this event, registration for it is not available to you. You can try "TB In-app registration" to check register button availability.

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-08-24 at 09 42 08](https://github.com/rokwire/illinois-app/assets/5631487/b15bfa12-e91b-4896-ab00-ab175606ce85)

**Comment by vburgett** [comment]
Thanks for that explanation, @mihail-varbanov. Since an admin shows up automatically on the attendee list of their own event, can we also automatically display the "Unregister" button for the admin? This will avoid confusion for the event admin and instill confidence that the in-app registration is indeed working.

5.0.55
Android Pixel 6

![Screenshot_20230825-121113.png](https://github.com/rokwire/illinois-app/assets/1044905/9dd44bc5-949f-4780-960f-50b944445548)

**Comment by vburgett** [comment]
An event admin may or may not attend their own event. The admin should be able to register or unregister as needed. 

Cc: @kpecknold (we discussed this)

**Comment by mihail-varbanov** [comment]
@vburgett, I do not think the current Calendar Event model can handle this. @petyos, is it possible to register/unregister an event admin for participation, bearing in mind the currently supported user roles for an event? CC @pmarkhennessy.

**Comment by mihail-varbanov** [comment]
Basing on this [comment](https://github.com/rokwire/illinois-app/issues/3656#issuecomment-1723014234) on a related problem, event admins cannot be participants or attendance takers.
