### ISSUE TITLE
[BUG] Group with one admin should not have option to leave their own group

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#362]
**Describe the bug**
Admin should not be able to remove themselves from a group if they are the only admin in the group. They can delete the group and therefore remove themselves

**To Reproduce**

Install the Illinois app

1. Complete the onboarding and user verify his identity with Netid/PWD
2. Proceed to the Browse screen and tap on Groups
3. Create a group 
4. Leave the group

**Actual Result**
The group with one admin should not have the option to leave their own group

**Expected behavior**
Admin should not be able to remove themselves from a group if they are the only admin in the group. They can delete the group and therefore remove themselves

**Smartphone (please complete the following information):**
Device: [e.g. Android]
Version [e.g. 2.4.31]

**Comment by dobromirdobrev** [comment]
Fixed in version 2.5.1 and above

**Comment by dobromirdobrev** [comment]
Reopen this issue so that @Priyaravi8 is able to verify it.

**Comment by Priyaravi8** [comment]
This issue is fixed.
