### ISSUE TITLE
[USABILITY] Add event - Event Description text update to prevent adding urls to this field 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3620]
When adding an event in the Illinois app, add the below text after the "Event Description" header. Please match the text style listed after the "Cost Description" header.

EVENT DESCRIPTION (Hyperlinks added to this field will not be active. Please add all urls to the appropriate fields such as the event type online url, event website link, or event registration external link.) 

![Screenshot_20230822-180836](https://github.com/rokwire/illinois-app/assets/1044905/bdb8eb3a-47c5-4e08-8c64-47ab178f7963)

**Comment by TodorBachvarov** [comment]
Added in version 5.0.53

**Comment by vburgett** [comment]
Confirmed as updated in 5.0.55. Thank you!
