### ISSUE TITLE
[BUG] Notifications timing is off

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3628]
In the app, I created an event (Sandwich and Survey Test) and set a survey to be sent out one hour after the event end time of 1:30pm on 8/23.
On 8/23 at 7:45am, I received a notification that said the survey was sent 14 hours ago (8/22 at 5pm).

In the app, I created a to-do list item with a reminder of 8am the morning of 8/23.
I saw the reminder notification at 7:45am on 8/23 with a timestamp of it being sent "15 hours ago" or approximately 4pm on 8/22.

I expect reminders to be sent at the time the user sets within the app.

v5.0.52
Android Pixel 6 

![Screenshot_20230822-175955](https://github.com/rokwire/illinois-app/assets/1044905/67b8ecc7-6ff9-4829-9532-431992cad50b)

![Screenshot_20230823-074059](https://github.com/rokwire/illinois-app/assets/1044905/0731c1a1-0711-4dc9-9670-1d85230a956f)

![Screenshot_20230823-073631](https://github.com/rokwire/illinois-app/assets/1044905/cfd8e56c-298e-4cb4-91a6-896d58539d58)

**Comment by joegrohens** [comment]
I got the notification of the survey for this event, but the survey was blank.

![Screenshot_20230823-151434](https://github.com/rokwire/illinois-app/assets/66988329/3aa108c6-4333-4b87-b7c1-29d18adb2a5c)
![Screenshot_20230823-151512](https://github.com/rokwire/illinois-app/assets/66988329/296ae256-fadc-4968-bc3c-dd8a13bc63e6)

**Comment by mihail-varbanov** [comment]
This is backend issue. I created a ticket in the relevant building block repo: rokwire/notifications-building-block#166
