### ISSUE TITLE
[BUG] Event survey notification sent but no survey presented

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3630]
I created an event, added attendees manually with netids, and set a survey for one hour after the event ends. The attendees received the survey notification (at the wrong time—see #3628) but the tap thru led to a blank event details panel. See attached screenshot. (As the admin, my survey notification tap thru went to the full event details panel.)

The event was 8/23 at 1:30 "Sandwich and Survey Test" with a survey set to be sent out one hour after the event end time.

v 5.0.52
Android Pixel 6

![Screenshot_20230823-161038](https://github.com/rokwire/illinois-app/assets/1044905/ee422f9e-f4c3-46ef-92f2-603a1dbf6b9d)

![Screenshot_20230822-175938](https://github.com/rokwire/illinois-app/assets/1044905/45e05917-6441-4e25-8fec-993442cd0a91)

![Screenshot_20230822-175955 (1)](https://github.com/rokwire/illinois-app/assets/1044905/7e705690-6e51-4832-8a1d-b89564d447ac)

![Screenshot_20230822-180156](https://github.com/rokwire/illinois-app/assets/1044905/3382bcef-e6ff-4156-b3a9-bd85450b3506)

**Comment by mihail-varbanov** [comment]
Hi @shurwit, I am re-assigning this to you as your team is maintaining the surveys in calendar events.

**Comment by roberlander2** [comment]
Thank you @vburgett, this appears to be a Calendar BB issue where the event is not being published, which results in only event admins being able to load the event and its survey.
https://github.com/rokwire/calendar-building-block/issues/290

**Comment by roberlander2** [comment]
This issue appears to have been resolved by https://github.com/rokwire/calendar-building-block/pull/299 (tested morning of 8/25/23).
