### ISSUE TITLE
[USABILITY] Update help text for Event Attendance screen (Event Registration)

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3640]
**Describe the usability issue**
Hi Kathryn - We are not sure of the meaning of this string for Event registration:

"panel.event2.setup.attendance.takers.label.info": "To check in a specific attendee, the **individual must be accounted for in your total number** of registrants within the Illinois app. No personal attendee information may be entered as part of taking attendance in the Illinois app.",

The marked phrase is giving the translators pause. And also, I think it should be more straightforward in English. 

I suspect that it means "the individual must already be registered".  Or does it just mean that you cannot take attendance beyond a set "number"?

Can you please clarify? Thank you.

Joe

@wchiaching6

**Comment by vburgett** [comment]
@joegrohens in the Illinois app (not the web admin), this language could say, as you suggested: 

"To check in a specific attendee, the individual must already be registered. No personal attendee information may be entered as part of taking attendance in the Illinois app."

**Comment by vburgett** [comment]
However, that text is not true as there _is_ a way to manually add an attendee with their netid. @kpecknold is this an issue? Attendance takers see the person's netid if they are scanning their Illini id. (Cc @joegrohens)

Mock up vs. 5.0.55

<img width="248" alt="Screenshot 2023-08-25 at 12 50 17 PM" src="https://github.com/rokwire/illinois-app/assets/1044905/996cefa2-fa9e-4c63-a988-80a50f1217d4">

![Screenshot_20230825-124713](https://github.com/rokwire/illinois-app/assets/1044905/de04c1ab-4325-4e59-af7b-3e793cd41033)
![Screenshot_20230825-124853](https://github.com/rokwire/illinois-app/assets/1044905/d2bcbe92-55be-4445-bd08-5bb68b037fc2)
![Screenshot_20230825-124858](https://github.com/rokwire/illinois-app/assets/1044905/f4d52543-028c-4c76-9327-d145292fa44c)

**Comment by vburgett** [comment]
With the current functionality, the below text is no longer relevant. Please delete this line of text and the icon.

"panel.event2.setup.attendance.takers.label.info"  "To check in a specific attendee, the individual must be accounted for in your total number of registrants within the Illinois app. No personal attendee information may be entered as part of taking attendance in the Illinois app." 

Cc: @joegrohens

**Comment by vburgett** [comment]
Please delete this text in both of the below places. Please also delete the circled text under Scan Illini ID and Allow Manual Attendance Check-In.

![Screenshot_20230825-124713~3.png](https://github.com/rokwire/illinois-app/assets/1044905/357b8060-1bd1-4d7f-a0e0-a82382f9c9a8)

![Screenshot_20230828-121345~4.png](https://github.com/rokwire/illinois-app/assets/1044905/36ec3d88-677a-4f55-9f54-d193918f27ed)

**Comment by joegrohens** [comment]
Closing this issue so Vanessa can refocus it properly.
