### ISSUE TITLE
[BUG] Old events show as upcoming in Groups

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3645]
Old events display under "Upcoming Events" in Groups. See attached example from today 8/25 with an event from 8/15 displaying. 

I expect "Upcoming events" to only show events in the future (or events that just started). 

V5.0.55
Android Pixel 6

![Screenshot_20230825-120046.png](https://github.com/rokwire/illinois-app/assets/1044905/d7dac3f1-7102-4943-b119-0631cb992ff4)

**Comment by TodorBachvarov** [comment]
Fixed in version 5.0.56

**Comment by vburgett** [comment]
Update reflected in 5.0.57. Thank you!
