### ISSUE TITLE
[USABILITY] Event attendance wording update

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3647]
Under event admin settings > event attendance, please change "Attendee List" to "Registrants" (Until a person is checked off, they are not yet an attendee.)

v5.0.55

![image](https://github.com/rokwire/illinois-app/assets/1044905/c5fb6bfb-c866-4c72-8696-af27e92b83c4)

**Comment by TodorBachvarov** [comment]
Changed in version 5.0.56

**Comment by vburgett** [comment]
Update reflected in 5.0.57. Thank you!
