### ISSUE TITLE
[BUG] Event Registration - Star Event so it appears in My Events

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#3655]
When a user registers for an event, the event should be "starred" so that the event appears in "My Events". 

Also, when I create an event, it should "star" the event so that it appears in "My Events".

**Comment by pmarkhennessy** [comment]
@kpecknold Please discuss with JP at the Rokwire meeting Tue, 29th Aug 2023. Perhaps a popup when saving that just asks the user if they want it starred/saved.

**Comment by mihail-varbanov** [comment]
Starring an event after registration had been already processed by #3692 and #4042. Starring an event after its creation is handled in version 6.0.2 in a similar manner as the one after registration - prompting the user whether to star the event.

**Comment by vburgett** [comment]
Confirming what @mihail-varbanov said as true in version 6.0.4 on dev.
