### ISSUE TITLE
[BUG] Group Event - Oversized font is displayed in the field Event title

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#366]
**Describe the bug**
Creating group event screen, the event title font is oversized.

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and user verify his identity with Netid/PWD
3. Proceed to the Browse screen and tap on Groups
4. Create a group
5. Navigate to the group and tap on Create Event
6. Fill in the required fields

**Actual Result**
The input field of the event title font is oversized.

**Expected behavior**
The font should be regular size to match with other fields.

**Screenshots**
![tiev](https://user-images.githubusercontent.com/26231179/123491867-70175c80-d5dd-11eb-8d09-19b1ad695b78.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.4.31]

**Comment by mdryankov** [comment]
@Priyaravi8 please consider with the UX design team, because the font is defined strictly in https://www.figma.com/file/noq39ql9qZuHCFlm4eP4Ze/Groups?node-id=301%3A586

and the same font size is used within the code. We need confirmation on both sides in order to make such changes

**Comment by pmarkhennessy** [comment]
@mdryankov Please just use a regular data entry field font as is used everywhere else. Ignore the UI design please.

@Priyaravi8

**Comment by mdryankov** [comment]
Fixed

**Comment by Priyaravi8** [comment]
This issue is fixed
