### ISSUE TITLE
[USABILITY] Delete Inaccurate Event Attendance Text

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3661]
With the actual functionality of event attendance, the below text is no longer relevant. Please delete this text and info icon in both of the below places. Please also delete the circled text under Scan Illini ID and Allow Manual Attendance Check-In.

"To check in a specific attendee, the individual must be accounted for in your total number of registrants within the Illinois app. No personal attendee information may be entered as part of taking attendance in the Illinois app."

v5.0.55
Android Pixel 6

![EventAttendance-TextUpdate01](https://github.com/rokwire/illinois-app/assets/1044905/618f3eff-33cc-481d-9665-bdd4a0644404)
![EventAttendance-TextUpdate02](https://github.com/rokwire/illinois-app/assets/1044905/6161c423-1145-4056-9f07-8c9cd48bfeb5)

**Comment by TodorBachvarov** [comment]
Removed in version 5.0.57

**Comment by vburgett** [comment]
Updates reflected in 5.0.57. Thank you!
