### ISSUE TITLE
[BUG] Groups - > Create an Event created screen -> Remove the field "To"

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3672]
**Describe the bug**
**Groups** -  Events created under groups should be displayed to all the group members, not to specific members. Remove the field "To" that would restrict to specific members

**To Reproduce**
1. Install the app
2. Navigate to Groups and create a new Group
3. Tap on the + icon to create a New Event under the group.
4. Scroll down on the screen "Create an Event" screen

**Actual Result**
The field "To" would restrict Event display to specific members

**Expected behavior**
**Groups** -  Events created under groups should be displayed to all the group members, not to specific members. Remove the field "To" that would restrict to specific members

**Screenshots**
![To field](https://github.com/rokwire/illinois-app/assets/26231179/efc4e6c8-8e73-4ce1-add6-2420edfe7f13)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 5.0.55]

**Comment by TodorBachvarov** [comment]
Removed in version 5.0.59

**Comment by Priyaravi8** [comment]
Fixed
