### ISSUE TITLE
[USABILITY] Webtools events in app do not include location details

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3673]
**Describe the usability issue**
v5.0.55 dev

The written Location of Events should be printed in the event screen.
The location pin knows where the event is, and will take you to a map to the building. But if the room number is not printed, a user will not know where to go.

Example:
This Number Theory event is located in 313 Gregory Hall. That address is shown in the webtools calendar:
<img width="733" alt="Screenshot 2023-08-29 at 10 07 41 AM" src="https://github.com/rokwire/illinois-app/assets/66988329/8a6c84c5-a0b8-42df-9480-01aae8d7c278">

....
However, in the app, the location is not printed.

![math talk event](https://github.com/rokwire/illinois-app/assets/66988329/35f9fd55-1562-4108-927d-8c38bba743e9)

....
When you tap the location pin, Map opens with directions printed as "Gregory Hall, 810 S Wright St., Urbana, IL 61801." But the Room number is not listed.
![math talk map](https://github.com/rokwire/illinois-app/assets/66988329/641b6413-36e3-4355-9aad-f11f1c8ae816)

**Recommended Change**

Print all of the printed address information in the event screen. 

Be sure to include the room number. Many buildings on campus have up to eight floors and hundreds of rooms. It is not enough to give only the building name and street address.

Users would like to read the address location when they are first glancing at an event. Location may determine whether they are even interested in going to the event. They don't want to have to open Google maps to find out where it is.

**Comment by mihail-varbanov** [comment]
This is is not a backend's issue and it is duplication of #3510, that is already resolved and awaits for verification. Closing this issue.
