### ISSUE TITLE
[BUG] Private events created in Groups not visible to members  

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3674]
In 5.0.55, when creating a private event in a Group as an admin, the members cannot see the event. The members do however receive a notification about the event being created but it does not lead to the event.

I expect group members to see a private event created in the Group like it does in 4.3.61. Please update the functionality and  add back the language in 4.3.61 when selecting "private" under Visibility to include  "This event will only show up on your group's page."  

![IMG_9281](https://github.com/rokwire/illinois-app/assets/1044905/414f061f-bade-41d4-b160-6f51acfa7164)

**Comment by TodorBachvarov** [comment]
Not possible with the calendar BB. After discussion with @petyos  it seems that this is as expected from Calendar’s BB perspective - Only the admins and participants of this event can see it. 
But this is in conflict with the old functionality of the Group Events, where the Group members (not necessarily event participants/admins) are expected to see the Private Event. @pmarkhennessy, could you suggest a resolution?

**Comment by vburgett** [comment]
When creating an event in a Group, instead of the "Visibility" options being "public" and "private" could they be "public" and a new option—"Limit to Groups"? @pmarkhennessy @TodorBachvarov @kpecknold

**Comment by vburgett** [comment]
Confirmed as fixed in 5.0.73. Thank you! 

As expected, the private event "private 5.0.73" in the Group "Grow your own" was _not_ visible to non-members under All Events via search and scroll.
Members of the group _could_ see the private event in the Group, via the event feed, and via search.
