### ISSUE TITLE
[BUG] Webtools events display incorrect sponsor/host in the app

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3676]
In 5.0.55 (Android) Webtools events are displaying "UG Director." In 4.3.61, Webtools events display the actual event sponsor/host. In the below event as an example, the event shows "Krannert Art Museum" instead of "UG Director" which is correct. 

I expect Webtool events to show the actual name of the event sponsor/host—Krannert Art Museum—as version 4.3.61 does. ("UG Director" should not display anywhere as it doesn't exist as an event sponsor/host.)

![Screenshot_20230829-114652](https://github.com/rokwire/illinois-app/assets/1044905/124f5146-7ffd-4812-96ab-52f970707de5)

![IMG_9283](https://github.com/rokwire/illinois-app/assets/1044905/77cc7fa6-50d0-44f4-a415-ed032aa6426a)

Cc: @sandeep-ps

**Comment by sandeep-ps** [comment]
This looks like a backend issue as the event data in Events BB has "Krannert Art Museum" as the sponsor, but in Calendar BB, it looks like it's storing test data.

**Comment by dobromirdobrev** [comment]
Sandeep is right - this is a backend problem. Here is the relevant issue: https://github.com/rokwire/calendar-building-block/issues/308 

cc @pmarkhennessy

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
According to that comment https://github.com/rokwire/calendar-building-block/issues/308#issuecomment-1699157546 this issue should be fixed. Could you please verify and let us know. Thanks

**Comment by sandeep-ps** [comment]
Hi, @dobromirdobrev, I have looked at the backend endpoint response in the Dev instance and reopened https://github.com/rokwire/calendar-building-block/issues/308. Please see my related [comment](https://github.com/rokwire/calendar-building-block/issues/308#issuecomment-1714658843) on that. Thanks.

**Comment by dobromirdobrev** [comment]
Hi @sandeep-ps and @vburgett ,
This seems to be resolved based on that [comment](https://github.com/rokwire/calendar-building-block/issues/308#issuecomment-1715330107). Please verify and let us know, thanks.

**Comment by sandeep-ps** [comment]
Thanks. @dobromirdobrev. I also think this is fixed. The event in this GitHub issue has expired, but I can see the correct sponsor for another Kranner Event called "Krannert Center Uncorked with The B-Sides". 

Hi, @vburgett, Please review and close this issue if you agree it's resolved. Thanks.

**Comment by vburgett** [comment]
Confirmed as fixed in 5.0.68. Thank you!
