### ISSUE TITLE
[USABILITY] To-do list edit screens have wrong section listed

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3677]
Go to Academics > To-Do List, and edit an existing to-do list item or create a new one. The top nav bar says Wellness. It should say To -Do List Item (or Academics).

V5.0.57
Android Pixel 6

![Screenshot_20230829-144400.png](https://github.com/rokwire/illinois-app/assets/1044905/e5d13905-0aaa-4ae8-9a5f-c64c260792de)

**Comment by dobromirdobrev** [comment]
This is fixed in version 5.0.58. The title is "To-Do List Item".

**Comment by vburgett** [comment]
Confirmed as completed in 5.0.60—thank you!
