### ISSUE TITLE
[USABILITY] Misleading information in an event

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#368]
An event shows spurious information not found in the source webtools calendar.

**To Reproduce**
In Events, search for "Summer 2021 tuition and fees are due."
Tap the event to view it. (see scrn 1)

**Problem**:

- The event is described as "in-person", when the fees actually could be paid online via credit card or by mail. And in fact the calendar is named "Engineering _Online_ Events".

- The cost is described as "Free", when the nature of the event is actually that fees may be owed.

The [calendar source for this event](https://calendars.illinois.edu/detail/4327?eventId=33404535) doesn't actually say "In-person" or "Free".  (see scrn 2 of web calendar)

**Expected result:**
The lines for "In-person" and "Free" should be empty. (In my opinion.)

Is it possible that the Events BB is providing default text when a field is empty? Doing this can produce incorrect meaning. I would suggest that when a field is blank, no line should be printed in the app's event screen.

**Equipment**
Device: Pixo3a
OS: Android 11
Illinois app: v2.4.31

**Screenshots**

![1  engineering tuition event](https://user-images.githubusercontent.com/66988329/123557530-f4411f80-d756-11eb-82be-b7beb1bd818d.png)
![2 engineering web calendar](https://user-images.githubusercontent.com/66988329/123557533-f86d3d00-d756-11eb-9805-66291313be70.png)

**Comment by joegrohens** [comment]
This "Free" Tuition Due incongruity still appears, and is a bug, in my opinion.

If you search Events for tuition, you will find some events that say "tuition due".

The event price information says "Free". 

The correct behavior, in my opinion, is that the price information field should be empty unless someone has explicitly chosen "Free" or a specific cost. (The default should be empty.) I suspect that a null value is being defaulted to "Free" somewhere.

I have tried to find the webtools calendar where this originates from, but haven't found it exactly. I think it originates from a registrar's office calendar. None of the events in the registrar's office calendars have price information. I think this is something that the Events BB is introducing.

**Comment by joegrohens** [comment]
This problem is still present in v3.2.33.

Has anyone even looked at this issue?

**Comment by sandeep-ps** [comment]
Hi, @joegrohens, 

In the data from WebTools, these boolean fields (for cost and the event type) were most likely false. I say most likely because that particular event has expired, but I see other events with similar data:

For example, in the same calendar (Engineering Online Events), another event titled "No refund of tuition is available after this date" has these fields:
```
<costFree>false</costFree>            // cost boolean
<cost/>                                               // cost description
<virtualEvent>false</virtualEvent> //virtual event booelan
```
Maybe in WebTools, they are only showing cost details when the boolean is true, and they are not showing it when it is false, which is the default value in WebTools. So, to answer your question, this is specified in WebTools data, and it's not something that we introduce as the default value.

**Comment by pmarkhennessy** [comment]
@joegrohens Not sure why this was missed. Can you point me to an example in 3.2.33 please, screenshot etc

**Comment by joegrohens** [comment]
@sandeep-ps @pmarkhennessy 

I'm attaching a screenshot of the event Sandeep refers to. 

![tuition event is 'free' 3](https://user-images.githubusercontent.com/66988329/159062019-62845b29-97dc-45e4-b3a8-7a9136ed42c4.png)

- The event is not "Free" - if you withdraw you lose your tuition
- The event is not a "Public Event" - it is only something that registered students can do.
- The event is not an "In-person event" ... withdrawal (like tuition payments and other things) can be submitted online. 

The display of the event has incongruous information. And the illogic can look to a user like "this is broken". Whether Rokwire has a hand in it or not, we have guilt by association.

I understand Sandeep's analysis, that the Boolean data is specified in Webtools. Therefore, nothing we can do about it on our end, other than turning off the display of false results. 

I think, though, that we could work with the Webtools people to modify their data input - maybe to require an explicit value be input in these fields. I heard they are redoing their calendar system anyway.
