### ISSUE TITLE
[USABILITY] Heading for Team Rosters has hardcoded years

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3682]
**Describe the usability issue**
v4.3.61

Mark: This is a problem in strings. If you agree with my proposed change, we will be happy to fix it in strings.en.json and the ES and ZH as well, on the next round. 

Alternatively, maybe you want to programmatically insert the current school year. In which case I leave it to you>

Assign it to me and I'll fix the strings files.
Joe

....
**Athletics Team Rosters are displayed with the heading "2019-2020 Roster".**

![football roster](https://github.com/rokwire/illinois-app/assets/66988329/55cb0911-16eb-4033-8ae0-5650e6856622)

This applies to other teams, such as Track & Field.

![track   field roster](https://github.com/rokwire/illinois-app/assets/66988329/2aa3248c-13fd-4906-a193-f515ce161b46)

This erroneous heading originates in strings.en.json:

- "panel.athletics_roster_list.label.heading.title": "2019-2020 Roster",
- "panel.athletics_coach_list.label.heading.title": "2019-2020 Coach",

**To Reproduce**
1. Go to: _Browse > Athletics > Teams > select a team_
2. Scroll down to Team Roster, or Coaching Staff sections.
3. Tap "Full Roster" (or "All Staff") button.

**Recommended Change**
Change Strings (in all languages) as follows.

- "panel.athletics_roster_list.label.heading.title": "2019-2020 Roster" :: _CHANGE TO "Full Roster"_

- "panel.athletics_coach_list.label.heading.title": "2019-2020 Coach" :: _CHANGE TO "All Staff"._

**Comment by dobromirdobrev** [comment]
Fixed in version 5.0.59.

**Comment by joegrohens** [comment]
confirmed fixed
