### ISSUE TITLE
[BUG] Two notifications for one to-do list reminder

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3683]
I received two notifications for one reminder set for a single to-do list item. 

I expect to receive one notification per reminder. 

V 5.0.57
Android Pixel 6

![Screenshot_20230830-211001.png](https://github.com/rokwire/illinois-app/assets/1044905/39bef8b6-a0a9-4303-821c-d5ac0d83eebd)

![Screenshot_20230830-211107.png](https://github.com/rokwire/illinois-app/assets/1044905/95909fd5-a0b0-4f8c-8bf1-1d929d548048)

**Comment by TodorBachvarov** [comment]
This is a backend issue. I've created [this](https://github.com/rokwire/wellness-building-block/issues/34) issue in the wellness bb and closing this one.
