### ISSUE TITLE
[BUG] Event - Changes applied to the event is not saved.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3712]
**Describe the bug**
Edit a category in the existing event but the edited item is not saved in the event. Event Capacity is edited, allowing more people to register. Users registering for that particular event display an "Error message".

**To Reproduce**
1. Install the Illinois app
2. Open the event that already exists
**NOTE - Event registration is closed as it reaches the Event capacity.**
3. Tap in the Event Admin setting and tap on Event Registration. Change the Event capacity number allowing more users to register.
4. The Register button is enabled for the user for the Edited Event. Tap on the Register button

**Actual Result**
Error message displayed to the user

**Expected behavior**
The user should be able to register without an Error

**Screenshots**

![event reg](https://github.com/rokwire/illinois-app/assets/26231179/413876ea-d7cc-492b-a334-d3336e01f93e)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 5.0.62]

**Comment by TodorBachvarov** [comment]
Hi @Priyaravi8, Which environment (dev/test/prod) are you testing on? When I test with dev environment I'm not able to reproduce this issue. The category was updated successfully and I was able to register for event successfully. Could you please retest as it is possible the issue to be fixed on the backend.

**Comment by TodorBachvarov** [comment]
Update: This may be related with the renamed category names. Tracked here https://github.com/rokwire/illinois-app/issues/3743. As I see from the screenshot, the Category of this event contains "&" which was renamed with "and". It's possible the Event to be created before the category renaming and to have invalid event category. Could you retest and try updating the event category (this will help track the problem).

**Comment by Priyaravi8** [comment]
Fixed
