### ISSUE TITLE
[BUG] Event survey notifications are not being sent to the right people 

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#3721]
I created an event called "Rokwire - Wellness" for Wed, Sept 6 3-3:45pm
9 were registered in advance
11 people were added to the guest list because I scanned 2 people who had not registered (I will create separate issue for this)

I took attendance in-person by scanning QR codes. 
1) Not everyone who attended got a survey notification
2) I (the creator of the event) got 8 duplicate notifications
3) At least one person (tjn) who was registered but did NOT get marked as attended, DID get a survey notification.

All people who are marked as having attended should get the survey notification. If they do not attend (even if registered), they should not get a survey notification.

Pixel 6
v 5.0.62
![image](https://github.com/rokwire/illinois-app/assets/69397705/be71180e-0bab-407f-b195-78b74de67494)
![image](https://github.com/rokwire/illinois-app/assets/69397705/92235d3e-8c9c-4991-989a-b6632eb789a9)
![image](https://github.com/rokwire/illinois-app/assets/69397705/8b8baa8a-c7d6-42b2-8954-82821256e018)

**Comment by TodorBachvarov** [comment]
I've created a backend issue: https://github.com/rokwire/calendar-building-block/issues/333 and closing this one

**Comment by mdryankov** [comment]
This is fixed on backend side. Please retest and give a feedback

**Comment by mdryankov** [comment]
@kpecknold ^
