### ISSUE TITLE
[BUG] Taking attendance should allow enforcement of required registration

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#3722]
I created an event called "Rokwire - Wellness" for Wed, Sept 6 3-3:45pm
9 were registered in advance
While taking attendance, I scanned 2 people who had not registered
They were automatically added to the guest list
Most times, an event host will want to limit attendance to those who are registered. Sometimes, they may want to make an exception.

For events where registration is required, upon scan of a QR code for someone who has not registered, can the attendance taker get a pop up informing them that the person is not registered and ask them whether they want to add them to the guest list or not? 

Pixel 6
v 5.0.62

![image](https://github.com/rokwire/illinois-app/assets/69397705/dbad356b-abf5-495f-87cd-fd7253b18bef)
![image](https://github.com/rokwire/illinois-app/assets/69397705/1f85c8c6-f3e1-4b2d-9d78-fd3b240e8873)

**Comment by mihail-varbanov** [comment]
**Re: University Monday 2023/09/11** / 2023-09-15

**N.B.** If there is Registration and Attendance then only the people who are registered can attend.

**Comment by mihail-varbanov** [comment]
We should resolve this issue first on the backend. I created a ticket for this in Calendar BB repo:
rokwire/calendar-building-block#353

**Comment by kpecknold** [comment]
@pmarkhennessy This is a showstopper.

**Comment by vburgett** [comment]
If an attendance taker is adding someone who hasn't registered to an event via scan or manual input, the attendance taker should be prompted with a pop-up that says "Not registered. Mark as attended? Yes | No"

**Comment by mihail-varbanov** [comment]
@pmarkhennessy, you keep changing the required logic.

**If there is Registration and Attendance then only the people who are registered can attend.**

is different than:

**If an attendance taker is adding someone who hasn't registered to an event via scan or manual input, the attendance taker should be prompted with a pop-up that says "Not registered. Mark as attended? Yes | No"**

In the second case the backend should revert their update for rokwire/calendar-building-block#353 and let the client do this check.

Also, there is a new requirement arised:

**If an attendance taker is adding someone to an event via scan or manual input when a set event capacity has been reached, the attendance taker should be prompted with a pop-up that says "At event capacity. Mark as attended? Yes | No"**

@pmarkhennessy, if we keep working in this way we will never release UIUC 5.0. Code freezing, defering anything that is not a fatal showstopper - did you forget about these? And if the above are really showstoppers, why I understand this two weeks after I have came up with some solutions for them?

**Comment by mihail-varbanov** [comment]
Latest requests fulfilled in UIUC client version 5.0.73. Please note that there are backend APIs that need to get implemented and deployed in order to see it working.

**Comment by vburgett** [comment]
Confirming this is complete in 5.0.73. Thank you!

**Comment by vburgett** [comment]
In 5.0.73, I received the appropriate pop-up messages in both scenarios of not being registered and being over capacity. 

When I said Yes to "Mark as attended," the person did not come through as checked off. When I tried to manually check them off, I received the below error. 

5.0.73

![Screenshot_20230928-210228.png](https://github.com/rokwire/illinois-app/assets/1044905/dd7bacd8-abbb-4eca-8572-20181de5ab51)

![Screenshot_20230928-210214.png](https://github.com/rokwire/illinois-app/assets/1044905/35d89538-ade1-4e89-963f-9585d874be21)

**Comment by mihail-varbanov** [comment]
Hi @vburgett,

**​​After tapping yes, can the person automatically be checked off?**
No. After you tap yes we make a call to Calendar BB to mark the person as attended. If the request succeeds we check off the person in the Guests List. If the request fails we popup an error message.

I have no explanation for the scenario that you described. The last two days I performed intensive testing of attendance taking functionality and did not fall in a case like this (actually I did not see any problem so far). So unless you provide the exact steps that lead to the situation above I cannot do anything.

**Comment by mihail-varbanov** [comment]
@vburgett, I actually guessed what happened. When a guest list item is not enabled we always display it as ![not selected](https://raw.githubusercontent.com/rokwire/illinois-app/develop/images/oval-orange.png) nevertheless that actual status of the user. This was the reason for the confusion. This is fixed in version 5.0.74.
