### ISSUE TITLE
[BUG] Create Event "+" is missing in the Events screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3732]
**Describe the bug**
Create Event "+" is missing in the Events screen.

**To Reproduce**
1. Install the Illinois app
2. Navigate to the Events screen.

Actual Result
Create Event "+" is missing in the Events screen.

**Expected behavior**
Display the Create Event "+" icon to create new events in the app.

**Smartphone (please complete the following information):**
 - Device: [e.g. Androis]
 - Version [e.g. 5.0.64]

**Comment by vburgett** [comment]
@Priyaravi8 you should have access now.

**Comment by Priyaravi8** [comment]
This issue is resolved.
