### ISSUE TITLE
[BUG] Can't create a private event in a Group

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3733]
When trying to create a private event in a Group, I receive the attached error. The event is not saved. 

5.0.64 (prod)
Android Pixel 6

![Screenshot_20230912-100908.png](https://github.com/rokwire/illinois-app/assets/1044905/dac144f8-7947-48a0-901e-7f5a6ed47934)

![Screenshot_20230912-100930.png](https://github.com/rokwire/illinois-app/assets/1044905/018f6774-7d59-4eb9-affe-f99d46d0d92e)

**Comment by vburgett** [comment]
Since creating this ticket, I now have permission to create events under Browse > Events > All Events AND I can now create an event in Groups. Are these two sets of permissions one of the same? 

The expectation was permissions to create an event in a Group would remain the same—events could be created in Groups by Group admins and/or group members depending on the Group settings. 

Permissions for creating events under All Events would be separate from Groups and limited to a specific group of people, yet to be determined.

**Comment by mihail-varbanov** [comment]
@vburgett, this issue involves mainly groups and calendar building blocks, who need to implement the different permission checks, and very little the UIUC client, who will have to provide the needed data.

I opened issues for this in the both building blocks:
rokwire/calendar-building-block#352
rokwire/groups-building-block#388

Let's keep this issue also opened because as I said above the client app will also get involved in resolving this.

**Comment by kpecknold** [comment]
Currently, for a groups admin to create a private event in their group and have it be seen by other groups members, they must choose to make it public. No one would intuitively figure that out, so the results is, group admins can't create private events for only their group to see.

**Comment by mihail-varbanov** [comment]
The UIUC client that resolves this issue is version 5.0.72. However we need to wait for the backend to get completed as it involves backend work as well.

**Comment by vburgett** [comment]
Fixed in 5.0.73. Thank you!
(A Group member _could_ create an event _without_ having permission to create events under Browse > All Events.)
