### ISSUE TITLE
[BUG] Sidearm sports display as online/in person 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3734]
Under All Events, Sidearm sports display as being both online and in person. These events are only in person. 

V5.0.65
Android Pixel 6

![Screenshot_20230912-122127.png](https://github.com/rokwire/illinois-app/assets/1044905/64a01d45-bc3b-48db-aa53-2ce6639c4ef2)

**Comment by dobromirdobrev** [comment]
This is a backend issue. A new one is created in the relevant repo: https://github.com/rokwire/calendar-building-block/issues/344
