### ISSUE TITLE
[BUG] Can't add Big 10 Athletics events to a Group

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3739]
In a Group that a user has permission to add events to, the user cannot add an Athletics event. The "Add Event to Group" button does not display.

**To replicate:**
In the Group, tap the plus sign by Upcoming Events.
Choose "Add existing event"
Tap on a Big 10 Athletics event
Scroll down on the event details panel and see there is no "Add Event to Group" button where there should be one.

v5.0.65 (prod)
Android Pixel 6

**Comment by TodorBachvarov** [comment]
Fix was applied in version 5.0.68.
