### ISSUE TITLE
[BUG] Event push notifications do not work

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3740]
I received a notification that a Group added an event via my Android lock screen. Tapping on it led to the app home screen. I expected it to bring me to the event detail panel within the group.

There was an event notification listed under the bell icon within the app that led to the Group (not the event detail panel within the group).

V5.0.65 
Android Pixel 6

![Screenshot_20230914-160133~2.png](https://github.com/rokwire/illinois-app/assets/1044905/564c3600-a1c8-46b2-8a91-4a6611c21bb4)

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

These are mine comments inline:

> I received a notification that a Group added an event via my Android lock screen. Tapping on it led to the app home screen. I expected it to bring me to the event detail panel within the group.

I was not able to reproduce that problem. Please see the attached video. When tapped over the notification, I was taken to the Group detail panel. Could you please check if you still observe that problem and let us know? If you still reproduce it, please share with some video.

> There was an event notification listed under the bell icon within the app that led to the Group (not the event detail panel within the group).

The Illinois app and the relevant Groups BB are designed to take the user to the Group detail panel when such notification is received. This behavior is implemented long time ago. So this is not a bug but a feature. cc @pmarkhennessy 


https://github.com/rokwire/illinois-app/assets/5978121/d1df146a-8bb2-4470-a6ad-ad8326b8a0b1
