### ISSUE TITLE
[BUG] Event Survey results Failed to load

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3744]
**Describe the bug**
Failed to load available survey message results to the user for Event Follow-up survey

**To Reproduce**
Instal Illinois app
Navigate to Create Event and tap on Event Follow-up Survey

Actual Result
Failed to load available survey message results to the user for Event Follow-up survey

**Expected behavior**
App should load the survey options.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 5.0.65]

**Comment by shurwit** [comment]
Hi @Priyaravi8, I assume that this was filed for the production envionment. The issue was just that we had not transferred the survey data to the production database. You should now see this working as expected but please let me know if you are still running into any issues. Thanks!
