### ISSUE TITLE
[USABILITY] Events Categories: "Other" is missing

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3754]
v5.0.68

1. Go to _Browse > Events > All Events > Create Event (+)_

2. Start a new event.

3. Go to set Event Category.

There is no category for "Other" or "Miscellaneous" or "Uncategorized"

A user is forced to classify an event according one of the 14 categories provided.

Sometimes a user has an event that doesn't fit one of these categories, and so they are forced to misclassify it. Or, alternatively, not to use the app for events creation. 

I thought that in the September 7, 2023 5.0 release meeting, JP said that we would add Other back to the categories.

@vanessa

**Comment by vburgett** [comment]
I don't believe we need "other" but you are correct that we all discussed and decided to add "Other" back into the event category options. We would however need to _exclude_ and not display Webtool events with the category "other" in the app.

**Comment by joegrohens** [comment]
So, are we not expecting to see it in this release?

**Comment by vburgett** [comment]
I'm not.

**Comment by joegrohens** [comment]
OK. I will leave this as an open issue.

**Comment by pmarkhennessy** [comment]
@TodorBachvarov You, added "Other" in Dev, needs also to be in Prod please

**Comment by TodorBachvarov** [comment]
Added from admin app so no new build is required.
