### ISSUE TITLE
[USABILITY] Mobile Illini ID shows empty FAQ pulldown menu.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3756]
v 5.0.68

Go to Browse > Wallet > Illini ID

The Illini ID appears. Behold the empty pulldown menu. According to Kathryn, this menu should be hidden.

![mila illini id copy](https://github.com/rokwire/illinois-app/assets/66988329/e92eff84-f318-4547-a9ae-fc792214b725)

Also, note that a fake test account (Mila Mariner as shown in the screen capture) is able to see the version of the ID w the pulldown. I presume that Mila is not on the mobile id test group, but maybe I'm wrong. If Mila is not on the list, then this suggests than anyone would see this version of the ID, which would be an additional problem. The mobileID capable version of Illini ID should be restricted to a managed list of testers.

....
ALSO - I really wish that we would adopt a uniform method for presenting help information on screens. The (i) circle i is another way.

**Comment by vburgett** [comment]
@joegrohens the menu should not be hidden. The FAQs should be hidden from the dropdown. Your screenshot looks as it should be IF there are no options in the dropdown.
