### ISSUE TITLE
[BUG] User cannot create an Event with Event survey

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3757]
**Describe the bug**
Failed to create event survey results that blocks the user to create an Event

**To Reproduce**
1. Install the app
2. Create an Event with Event survey option

**Actual Result**
Failed to create event survey results that blocks the user to create an Event

**Expected behavior**
User should create an even with Event survey without any failure

**Screenshots**

![event survey](https://github.com/rokwire/illinois-app/assets/26231179/1ec2d339-7743-441e-8abc-153a2b25f095)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]

 - Version [e.g. 5.0.69]

**Comment by shurwit** [comment]
Hi @Priyaravi8, I believe this was the result of a configuration issue in production that I have now resolved. Could you please try again when you get a chance and confirm that this is now working as expected? Thanks!

**Comment by Priyaravi8** [comment]
This is fixed
