### ISSUE TITLE
[USABILITY] Unclear Error Message for Additional Attendance Takers

### ISSUE THREAD

**Issue by bstandard** [rokwire/illinois-app#3762]
In the strings.en.json file posted September 22, the logic and wording of this string are unclear:

"panel.event2.setup.attendance.takers.duplicated_netids.error.msg": "Additional attendance takers can not also be listed as registrants. The following NetIDs cannot be promoted as attendance takers:\n\n%s"

Is the idea that an additional attendance taker is an admin and therefore would not register for the event?

Does this text more clearly convey the concept: Attendance takers cannot also be listed as registrants.

Or this: Additional attendance takers cannot be currently registered for the event. 

@joegrohens was unable to produce the error message.

**Comment by vburgett** [comment]
Thank you, Becky. As discussed, let's replace: 

"Additional attendance takers cannot be currently registered for the event. The following NetIDs cannot be promoted as attendance takers:\n\n%s" 

with 

"Registrants with the following NetIDs cannot be added as attendance takers until they unregister for the event: \n\n%s"

**Comment by mihail-varbanov** [comment]
The wording of this message is updated. I used to disable the preliminary check for this in the client, and let the backend API to fail updating the attendance list, displaying the raw error message as it comes from the backend, that is usually incomprehensible to the end user. Now I brought back this preliminary check on the client side so you should see the updated message. This was implemented in version 5.0.71.

**Comment by bstandard** [comment]
Confirmed this message appeared with vburgett on the guest list and added as an additional attendance taker in 5.0.73
