### ISSUE TITLE
[BUG] Post-event surveys fail to display for attendees [ver. 5.0.70 prod]

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3769]
**Describe the bug**
I received notifications for two post-event surveys for events where I am marked as an "attendee" (that is good). However, the surveys fail to display when I touch the notifications (not good). The screens that display seem to be a generic event information template (please see screenshot below).

**To Reproduce**
1. Create an event and set up post-event survey. Set timeframe for Survey Notification to be sent to attendees.
2. Have someone else register for the event, and take their "attendance"
3. "Attendee" should receive Survey Notification for the event at scheduled time
4. Have Attendee touch the Survey Notification for the event
5. See display below

**Expected behavior**
I expect to see the post event survey.

**Screenshots**
![PostEventSurvey_Link](https://github.com/rokwire/illinois-app/assets/118769169/a5a1a3a3-491d-4b26-97a8-74144332fed6)

**Smartphone (please complete the following information):**
 - Device: Pixel6
 - Version: 5.0.70 prod.

**Comment by pmarkhennessy** [comment]
@dobromirdobrev Please check

**Comment by dobromirdobrev** [comment]
Hi @knguyenjahiel ,

The Illinois app is designed to show the event detail panel when such notification is received. Ref: #3465 
If we want to show the survey itself then this should be a feature issue. Also even if we try to show the survey, it is not clear what the behavior has to be if the user has already filled the survey. Currently when a user has already filled the survey, the app does not allow him/her to open survey panel. These are edge cases which are not clarified and it would be risky to change that behavior just before the release.

Other than that about the "empty" event panel:
This can be achieved if for some reason the Calendar BB does not return the desired event - either it was deleted or something failed. We do not have access to production environment and we cannot estimate what could be the reason for the missing event. 

cc @pmarkhennessy

**Comment by knguyenjahiel** [comment]
Post event survey now displays when attendees taps on survey notification. Thanks.
