### ISSUE TITLE
[BUG] Past events visible in Groups 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3776]
Past events can be seen under "Upcoming Events" in Groups. I don't expect past events to be visible. 
(Same issue as #3645?) 

5.0.73 Android Pixel 6

![Screenshot_20230929-072218.png](https://github.com/rokwire/illinois-app/assets/1044905/c2eff402-da33-4770-a585-bd7aa2fcb824)

**Comment by dobromirdobrev** [comment]
This is a backend problem. A relevant Groups BB issue is created https://github.com/rokwire/groups-building-block/issues/396. We can verify it in the app when it is fixed.

cc @vburgett @pmarkhennessy

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
The relevant backend issue https://github.com/rokwire/groups-building-block/issues/396 is fixed. Please verify when you have a chance and close if the initial problem is fixed. Thanks

**Comment by vburgett** [comment]
This appears fixed in 5.0.78. Thank you!
