### ISSUE TITLE
[BUG] Speakers & Seminars under Academics not pulling events

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3780]
Under Academics > Speakers & Seminars, no events are displaying when there are events. 

iPhone 
App version 5.0.74

![image](https://github.com/rokwire/illinois-app/assets/1044905/436fffde-9fd8-4a4b-a20e-96cc536838a4)

**Comment by dobromirdobrev** [comment]
Fixed in version 5.0.75 and above.

**Comment by vburgett** [comment]
Confirmed as fixed in 5.0.76. Thank you!
