### ISSUE TITLE
[BUG] 5.0.74 privacy stuck at anonymous level.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3781]
**Describe the bug**
In v 5.0.74 iphone. 

I set privacy level to 2, and was signed out.

When I changed privacy back to 5, I could authenticate through Shibboleth. But after I came back from 2FA, the privacy level was still set to 2.

...
When I uninstalled and reinstalled, I was able to use privacy level 5 again.

But once I set privacy below 5 and signed out, I was unable to get level 5 to stick.

**Comment by knguyenjahiel** [comment]
Issue also occurs with switching from Privacy Level 4 to 1, 2, and 3.

Screen recording:
https://github.com/rokwire/illinois-app/assets/118769169/187c6351-154d-4791-bab4-f75ecac1ae66

**Comment by joegrohens** [comment]
issue also occurs on Android (pixel 3)

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,
This is fixed in version 5.0.76. Please verify when you get a chance and let us know.

**Comment by joegrohens** [comment]
confirmed fixed in 5.0.77 ios and android.
