### ISSUE TITLE
[USABILITY] Correct Privacy Notice for Groups

### ISSUE THREAD

**Issue by bstandard** [rokwire/illinois-app#3784]
In the Groups feature with a privacy level set to 2, a user sees the following error message:

![groups-privacy](https://github.com/rokwire/illinois-app/assets/141068526/8c582ace-2395-4bf9-a14d-4777483537fd)

Please use this text instead:
With your privacy level at 2, you can only view the list of groups.

v. 5.0.74
@joegrohens

**Comment by TodorBachvarov** [comment]
Message changed in version 5.0.75 and 5.1.1

**Comment by bstandard** [comment]
Confirmed that this is fixed in 5.0.76.
