### ISSUE TITLE
[USABILITY] do not display "My" section under Browse, keep "My" screens in related Browse sections

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3787]
Please do not display the “My” section under Browse but please keep the specific “My” screens listed as they are now under each of their related Browse sections.

"My Athletics Events" and "My Athletics News" are currently _only_ listed under Browse > My.  Please add these two sections to Browse > Athletics along with the below wording updates:

**Browse > Athletics**
> - Big 10 Events (renamed from “Upcoming Events”)
> - News 
> - My Big 10 Events (renamed from “My Athletic Events”)
> - My Big 10 News (renamed from “My Athletics News”)
> - My Game Day (renamed from “Teams”)

Thank you!

<img width="1694" alt="Screenshot 2023-10-04 at 1 54 59 PM" src="https://github.com/rokwire/illinois-app/assets/1044905/c3505a57-bb88-44c3-bd45-5f53ea59ed28">

**Comment by mihail-varbanov** [comment]
This had been resolved in 5.0.77 & 5.1.1.

**Comment by vburgett** [comment]
Thank you!
