### ISSUE TITLE
[USABILITY] Correct Text for Survey Acknowledgment

### ISSUE THREAD

**Issue by bstandard** [rokwire/illinois-app#3788]
When an event is created and a follow-up survey has been selected, the event admin sees this text on the main event screen: 

![survey-language](https://github.com/rokwire/illinois-app/assets/141068526/627da848-9dd9-4719-98db-3ea74b853b6f)

Change "follow-up survey is set." to "follow-up survey will be sent."
 
v. 5.0.74

@vburgett @joegrohens

**Comment by TodorBachvarov** [comment]
Changed in version 5.0.78

**Comment by bstandard** [comment]
Confirmed that this is fixed in 5.0.77.
