### ISSUE TITLE
[BUG] Users has no option to Delete or Modify the created events in the app

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3794]
**Describe the bug**
In detailed Event screen, the event setting is not available to the users to delete or update the created Events.

**To Reproduce**
1. Install the Illinois app.
2. Create an Event
3. Tap on the created Event and Event Detail screen is displayed.

**Actual result** 
Event setting is not available to the user to modify the created and/or delete event.

**Expected behavior**
Event setting should display to the user to modify the created event.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 5.0.74]

**Comment by dobromirdobrev** [comment]
HI @Priyaravi8 ,

I'm not able to reproduce this problem. I've created an event and there is a "Event Admin Settings" in the detail screen.
Please see attached screenshots:
![Screenshot_20231009-092301](https://github.com/rokwire/illinois-app/assets/5978121/a61f3964-a700-4679-8854-a93e6a20dd20)

![Screenshot_20231009-092331](https://github.com/rokwire/illinois-app/assets/5978121/f2823aa0-46fc-49c2-9c90-9153b74d8885)


I've also made a video which shows the relevant buttons. 

https://github.com/rokwire/illinois-app/assets/5978121/6aedf5f0-a825-40e9-98fd-d91b64136388

@Priyaravi8 , could you please double-check? If you still observe this issue, could you please provide us a video with the exact use case? Thanks

**Comment by Priyaravi8** [comment]
This issue is fixed.
