### ISSUE TITLE
[USABILITY] Apple app store lists support for iphone Wallet

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3800]
The Apple App store claims that Illinois App supports the Wallet. This is not true.

The issue was previously reported, and closed as fixed, in #[1851](https://github.com/rokwire/illinois-app/issues/1851) .

To verify, see: https://apps.apple.com/us/app/illinois/id1476075513

![Screenshot 2023-10-06 at 12 55 38 PM](https://github.com/rokwire/illinois-app/assets/66988329/d9fc6af6-619a-4481-8473-93080df7c905)

**Comment by mihail-varbanov** [comment]
Illinois app embeds HID Origo SDK for door opening feature. This SDK links to PassKit system framework that causes the Wallet support to appear in the App Store.
