### ISSUE TITLE
[USABILITY] Match Athletics widget names to Browse > Athletics listing 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3809]
Related to ticket #3787, please make the below wording updates to match the Browse > Athletics section listing.

**Please rename the following Favorites widget headings and the Favorites "customize" listing:
(Current > Requested Update)**
Athletics Events > Big 10 Events
My Athletics Events > My Big 10 Events
My Athletics News > My Big 10 News
Athletics News > Big 10 News

For the "My Athletics Events" panel, please update:
- the panel header from My Athletics Events > My Big 10 Events
- the linked text "Tap the [star] on items in **Big 10 Events** for quick access here."

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

This is done in version 5.1.16 of the Illinois app. Please verify when you have a chance. Thanks
