### ISSUE TITLE
[FEATURE] Integrate Essential Skills Coach With LMS Building Block

### ISSUE THREAD

**Issue by bsdworkin** [rokwire/illinois-app#3811]
**Is your feature request related to a problem? Please describe.**

Currently the essential skills coach is using hardcoded data with a non meaningful model. 

**Describe the solution you'd like**

Create the necessary model/service files and integrate the essential skills dashboard with the LMS building block providing it with meaningful data about the modules 

**Describe alternatives you've considered**

**Additional context**

**Comment by roberlander2** [comment]
Resolved by https://github.com/rokwire/illinois-app/pull/3899
