### ISSUE TITLE
[BUG] Private events not searchable by case sensitive event titles

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3813]
When searching a case sensitive private event title, the event does not display. 

I expect private events to be searchable by event title just like private groups are. 

To test this, go to All Events and search for "Private Event" with no filters applied. See how you do not get any results. 

Version 5.0.78
iPhone 13 Pro
iOS 16.6.1

![image](https://github.com/rokwire/illinois-app/assets/1044905/b2ff2588-c5b5-42c6-aa22-63a81f455dc8)

**Comment by mihail-varbanov** [comment]
This is a Calendar BB issue. I created [#437](https://github.com/rokwire/calendar-building-block/issues/437) in its repository and closing this issue.
