### ISSUE TITLE
[USABILITY] event, dining, athletic news detail panels: back arrow needs larger tappable area

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3827]
When tapping on the back arrow from an event, dining, or athletic news detail panel, the cover image preview often gets tapped instead. Can the tappable area of the back arrow be increased without making the icon larger? Or do we need an updated icon with a larger navy circle? Please advise.

v5.0.78
iPhone 13 Pro, 17.1.1

<img width="708" alt="detail panel back arrow" src="https://github.com/rokwire/illinois-app/assets/1044905/e60f71a5-b8a9-4588-b00f-6f892675cd35">

**Comment by mihail-varbanov** [comment]
This should be resolved in 5.1.30

**Comment by vburgett** [comment]
@mihail-varbanov this update works well in 5.1.34 on an Android but is not improved via iOS (5.1.34).

**Comment by vburgett** [comment]
Hi @mihail-varbanov, since the issue is probably the same for Android and iPhone, could the tappable area of the back arrow be increased more?

Here is an example event: 
"Test DD event with custom notifications" on 6/23/2024 via Illinois app v6.0.5 (dev) on an Android v14 Pixel 6

**Comment by mihail-varbanov** [comment]
Hi @vburgett,

**1. We used the standard material toolbar height (56px) that determine the back button size:**
![Screenshot 2024-06-20 at 1 58 53 PM](https://github.com/rokwire/illinois-app/assets/5631487/8814ffe6-bf1d-431a-8d06-115881160cfe)

**2. Now I increased the back button size to 72 x 72 (that increases the entire toolbar height as well):**
![Screenshot 2024-06-20 at 2 48 41 PM](https://github.com/rokwire/illinois-app/assets/5631487/37aa1a07-b285-446b-9d78-4d99f2c33d01)

**3. This is available in version 6.0.10.**

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov!
