### ISSUE TITLE
[BUG] Event filter: custom time can't be updated

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3828]
A user can filter events by a custom range of time, but the app will not accommodate changing that range of days. Instead a user must clear the range of time and start over. 

After filtering events by a range of time, I expect a user to be able to go back to the custom time filter to update a time or date.  

See the below screen capture. You'll see the final filter panel has "Clear" in the upper right hand corner instead of "apply."

iPhone 13 Pro
iOS 17.1.1
V 5.0.78 

https://github.com/rokwire/illinois-app/assets/1044905/47e5c7ff-91e9-49a8-a453-edb0ea30478c

**Comment by mihail-varbanov** [comment]
Fixed in version 5.1.9.

**Comment by vburgett** [comment]
Thank you for this fix, @mihail-varbanov. It looks like the change was at the expense of the "Clear" link. Can we add a "Clear" button under all the attribute options? 

![Screenshot 2024-01-16 at 3 49 00 PM](https://github.com/rokwire/illinois-app/assets/1044905/bc3b27ae-abd2-445e-acbb-eafc229da240)

**Comment by mihail-varbanov** [comment]
Clear button is available since version 5.1.12.
