### ISSUE TITLE
[BUG] Replace non-functioning Star with X on "Connect to Illinois" Favorite Widget

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3834]
The star associated with the "Connect to Illinois" Favorites widget does not have a purpose. Please replace it with an X for users who are _not_ signed in and do not wish to sign in (audiences = IlliniFest, Engineering Open House). Allowing users to close this widget on their Favorites will free up prime real estate for them to access and view privacy level one content like Events. 

v5.0.78
 
![Screenshot 2023-11-30 at 9 13 35 AM](https://github.com/rokwire/illinois-app/assets/1044905/a32f8d0a-9105-4f77-a64a-532879842de0)

**Comment by mihail-varbanov** [comment]
Implemented in version 5.1.31

**Comment by vburgett** [comment]
Working in 5.1.34—thank you!
