### ISSUE TITLE
[USABILITY] 5.1 UI Clean-up: icons + styles.json

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3837]
As part of our 5.1 UI clean-up efforts, here is a [list of icon updates ](https://docs.google.com/document/d/1Ao0gqsWWoLl-m9wjk1bcRi73GhzV1w7Ot9Bs7lSYqFg/edit?usp=sharing)along with an updated styles.json file (linked to from this doc). Some edits to the icons require the dev team and are _not_ fixed by our json file updates.

In the list is also a fix for #3317. 

Cc: @nataliehelregel @cdukeUX

**Comment by vburgett** [comment]
@TodorBachvarov thank you! 

Below are three icon edits in order of importance. 

1.0
The "star-grey" icon should actually be orange in both the Favorites panel and Browse. See screenshots. 

![Screenshot_20240207-225425~2.png](https://github.com/rokwire/illinois-app/assets/1044905/ae690bfa-a0da-4dda-9e12-33fe351c9e26)

![Screenshot_20240207-225437~3.png](https://github.com/rokwire/illinois-app/assets/1044905/9f5afb52-b142-4f98-807b-c3846ce770f9)

2.0
Add a new icon for Attendance under events using:
"attendance": {"src": "0xf7f3", "type": "fa.icon", "weight": "regular", "color": "fillColorSecondary", "size": 20},

[https://fontawesome.com/icons/clipboard-user?f=classic&s=regular](https://fontawesome.com/icons/clipboard-user?f=classic&s=regular) 

![Screenshot_20240207-225406~2.png](https://github.com/rokwire/illinois-app/assets/1044905/55296221-0b6a-4e2b-ab5a-e1612e359784)

3.0
Replace the below icon in the screenshot with this new icon:
 {"src": "0xf06a", "type": "fa.icon", "weight": "regular", "color": "fillColorSecondary", "size": 20},

https://fontawesome.com/icons/circle-exclamation?f=classic&s=regular

![Screenshot_20240207-225740~2.png](https://github.com/rokwire/illinois-app/assets/1044905/19441865-a5f6-4b39-8460-7269d8ebc1d6)

**Comment by TodorBachvarov** [comment]
Fixed. in version 5.1.29

**Comment by vburgett** [comment]
Thank you for this update in time for the 5.1 release, @TodorBachvarov! All looks good in 5.1.29.
