### ISSUE TITLE
[USABILITY] Logic for displaying "upcoming" events

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3839]
For those running late to an event or those events that span a long time period of time (ex: an open house from 8am-5pm), can an event display in the app following the below logic instead of ending immediately at the start time?

- If an end time for the event is provided, display event in the app until the end time. 
- If no end time is entered, display the event for 20 minutes after the start time.

V 5.1.3 dev

**Comment by mihail-varbanov** [comment]
Hi @vburgett,

**_If an end time for the event is provided, display event in the app until the end time._**
This is what the app currently does.

**_If no end time is entered, display the event for 20 minutes after the start time._**
This requires handling both on client and backend sides. The work in client is done, this should be available starting from version 5.1.12. The backend is not ready at the moment. You should look at rokwire/calendar-building-block#413 and test after is is stated to be completed, and the new calendar BB version is deployed on dev. CC @mdryankov.

**Comment by mdryankov** [comment]
Hi @vburgett, There is a new deployment of Calendar BB  on dev since today. Please test the above scenario from Misho's comment and give a feedback. CC @pmarkhennessy @mihail-varbanov

**Comment by Priyaravi8** [comment]
@vburgett - Tested this ticket - Both the below-mentioned scenarios work fine on the App side.
      If an end time for the event is provided, display event in the app until the end time.
      If no end time is entered, display the event for 20 minutes after the start time.

**Comment by vburgett** [comment]
Confirming as updated in 5.1.13. 
Interested via these two events with cat photos. You can see the events go away at the appropriate time based on the time in the screenshots. 

![Screenshot_20240124-164920.png](https://github.com/rokwire/illinois-app/assets/1044905/bd4d8f69-aa98-40ce-ad64-ee4532f4c134)

![Screenshot_20240124-165008.png](https://github.com/rokwire/illinois-app/assets/1044905/9cc64302-cdd4-48c6-ab04-7ac95ae0a8e9)

![Screenshot_20240124-180504.png](https://github.com/rokwire/illinois-app/assets/1044905/76712ec2-6402-4699-9670-14d06899bfdd)

@mihail-varbanov
