### ISSUE TITLE
[USABILITY] Display Location Building field with long entries as truncated with an ellipsis (. . . ) 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3842]
For an event card, please display longer "Location Building" field text entries with an ellipsis (. . . ). Right now, the text partially displays as desired but there is no indication that there is more text not displaying.

In the event details card, please display the complete text entry from the Location Building field.

 Illinois app 5.1.3 on dev 
 Event created via dev admin website 5.0.64

In the below example, the "Location building" text as entered from the Illinois admin website is "Even Longer Building Name to See How It Previews if it is really long wow this building was paid for by a gracious donor named John Paul Thank you, JP"
![Screenshot_20231213-171009](https://github.com/rokwire/illinois-app/assets/1044905/9ab9aa89-f029-4fbe-8cee-f3e4e1bfed29)
![Screenshot_20231213-171015](https://github.com/rokwire/illinois-app/assets/1044905/c66496e6-4dc1-4b65-b058-9dbcde1604c8)

**Comment by mihail-varbanov** [comment]
Fixed in version 5.1.9

**Comment by vburgett** [comment]
In 5.1.9, the event card correctly displays the longer "Location Building" field text entry with an ellipsis (. . . ). 

Please display the _complete text entry_ from the Location Building field on the event details panel. Thank you!

![Screenshot_20240116-144624](https://github.com/rokwire/illinois-app/assets/1044905/a746ed17-d4d5-47b3-ba2b-0d3c3a446e79)

**Comment by mihail-varbanov** [comment]
"_Please display the complete text entry..._"
Done in 5.1.10 (@vburgett)

**Comment by vburgett** [comment]
Complete in 5.1.11—thank you!
