### ISSUE TITLE
[USABILITY] Event "location address" field text does not display in the mobile app

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3843]
When creating an event and entering text in the "Location Address" field via the admin website, the text does not display in the mobile app.

The expectation is that the text would display in the event card and the event detail panel to communicate the address details to the user. We would like the text from "Location Address" to display as text under the "Location Building" building text. 

(All wayfinding would still be determined by the latitude and longitude as it is now. We understand a user could enter address text that is different than the latitude and longitude. We are ok with this risk at this time.)

Illinois app 5.1.3 on dev
Event created via dev admin website 5.0.64

**Comment by mihail-varbanov** [comment]
Fixed in version 5.1.9

**Comment by vburgett** [comment]
Confirming as complete in 5.1.9. Thank you, @mihail-varbanov!
