### ISSUE TITLE
[USABILITY] My Courses is not shown unless User Role -> University Student is set.

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3844]
**Describe the usability issue**

Recently a university dean who was enrolled in a course reported that they could not see their course listing in the app. The problem was solved when they selected "University Student" in Profile > Who Are You?

Experimenting with the settings reveals that the My Courses menu item is not shown  unless the user is both both signed in with NetID and has “University Student” selected as their user role in “Profile > Who Are You?” (The places where the My Courses item can be shown include Academics, Map, and Browse>Academics.)
 
As well, if a user has previously favorited My Courses and then unsets "University Student" as a user role, the favorites widget for My Courses disappears from their Favorites screen.
….
This behavior is inconsistent with other features that can be seen by any one and which display an error message on tapping that states required settings. ( “You must be signed in with NetID…., privacy set to 4/5, housing contract, etc.”)

Such features include:

- Bus Pass
- Meal Plan
- Illini ID
- Appointments – MyMcKinley, Grainger
- Polls
- Groups

This inconsistency makes it hard for a user to learn that a particular user role setting in Who Are You affects which features they can see and/or use. 

**Suggested Change**

As long as all other features are visible to every user, we suggest that User Role -> University Student not be required to show the My Courses menu item. Instead, show My Courses in the relevant appropriate screens, and provide an error message to explain required netid and privacy level.

@vburgett

**Comment by dobromirdobrev** [comment]
Hi @joegrohens ,

This is done in the Illinois app version 5.1.17. Please, verify when you have a chance.
