### ISSUE TITLE
[USABILITY] Survey responses and attendance attached to an Event in Groups cannot be found

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3845]
**Describe the usability issue**
There is no way to access survey results and attendance records for Events that have been created in a Group.

Once the event is over, the event is removed from the app. Thus, there is no way to look at the _Event Admin Settings_, where surveys and attendance would be listed.

**Recommendation**
Event creators need a way to access the attendance record, guest list, and survey responses after an event has ended.

**Comment by mihail-varbanov** [comment]
@vburgett, please provide a UI design how past events should get accessed by event admins. Please note that this is valid on only for group events but for regular calendar events as well.

**Comment by mihail-varbanov** [comment]
I believe https://github.com/rokwire/illinois-app/issues/3768 refers the same problem.
