### ISSUE TITLE
[FEATURE] Implement Voice recording and storing

### ISSUE THREAD

**Issue by TodorBachvarov** [rokwire/illinois-app#3846]
https://drive.google.com/file/d/1xqQLSwWB_2b2pKBhVMv2-4ZruvJuk2Bu/view?pli=1
Implement the section with name pronouncement voice recording. Record and playback for other users if available (in Groups for example).

**Comment by knguyenjahiel** [comment]
@TodorBachvarov, can you give priyar@illinois.edu and me (knguye@illiniois.edu) access to [google ](https://drive.google.com/file/d/1xqQLSwWB_2b2pKBhVMv2-4ZruvJuk2Bu/view?pli=1). I'm asking Priya to test this feature. Thank you.

cc: priyar@illinois.edu
