### ISSUE TITLE
[BUG] Required event capacity for registration is not clear and leads to errors

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3849]
A user can create an event with registration _without_ filling out the event capacity resulting in this bug: an event says registration is required but no Register button displays to the user.

For 5.1, which of the below fixes is easier?
1) do not make event capacity required and do not have the register button displaying dependent on event capacity having a number set.
2) add a red asterisk to the Event Capacity field under Event Registration in the app and via the admin website. The user should be unable to proceed with setting up an event with event registration without the Event Capacity field filled in.

Our event testing group prefers number one but we are fine with either option based on 5.1 constraints.

This ticket relates to [#398 in the illinois admin repo](https://github.com/rokwire/illinois_admin/issues/398). 

v5.1.4
Android Pixel 6

**Comment by vburgett** [comment]
Duplicate of #3847. I can close one depending on which route we go.

**Comment by vburgett** [comment]
Before the release, can we implement at least number 2 above? @pmarkhennessy @mihail-varbanov

**Comment by mihail-varbanov** [comment]
Hi @vburgett, I implemented option 2 above in version 5.1.16. In addition, the same rule applies for external link when the registration type is "via external link".

**Comment by vburgett** [comment]
Thanks for finding and adding the asterisks to the external link field as well @mihail-varbanov. 
Both asterisks are in place in 5.1.16.
