### ISSUE TITLE
[FEATURE] Athletics UI Cleanup

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#3867]
**Re: University Monday 2024/01/15** / 2024/01/17

1.3 Move on to the Athletics UI for UIUC 5.1 work

[UI-CleanUp-5.1-Ver05-1.pdf](https://github.com/rokwire/illinois-app/files/13962634/UI-CleanUp-5.1-Ver05-1.pdf)

**Comment by vburgett** [comment]
Thanks, @dobromirdobrev. I reviewed and here are [my notes](https://docs.google.com/document/d/1jywJqIZXacnkUileWaPLLiCEwUfUhf7C1GyboIk27zE/edit?usp=sharing). 

Cc: @pmarkhennessy

**Comment by dobromirdobrev** [comment]
@vburgett ,
The checked the tasks from your list that are done in version 5.1.14. Please note that this task is still in progress and not all of the features are implemented.

**Comment by dobromirdobrev** [comment]
Finished in version 5.1.17
