### ISSUE TITLE
Group Admin Cannot Create a Group Event for a Private Group

### ISSUE THREAD

**Issue by bstandard** [rokwire/illinois-app#3880]
When creating an event as an admin to the private group called Bunnies on Parade, an error message is generated when trying to get past the Select Group screen:

![Screenshot_20240123_152216_Illinois](https://github.com/rokwire/illinois-app/assets/141068526/131e87f5-4987-4e0e-87b8-dd0397169982)

Pressing the Send button generates an error message:

![Screenshot_20240123_152236_Illinois](https://github.com/rokwire/illinois-app/assets/141068526/e70e509e-26bb-41f8-97d7-ecf40887814c)

It's not possible to get past this point and create the event. I am an admin for the private group called Slug Fest (shown in the screen shot) too.

Android
Version 5.1.11

**Comment by vburgett** [comment]
This appears fixed in 5.1.17.

**Comment by bstandard** [comment]
Confirmed fixed in 5.1.19. Sorry--forgot to include @knguyenjahiel on the initial report.
