### ISSUE TITLE
[FEATURE] Global Settings UI Updates

### ISSUE THREAD

**Issue by TodorBachvarov** [rokwire/illinois-app#3883]
Implement the changes described on 3th page of this documents under section "Global Settings"
[UI-CleanUp-5.1-Ver05-1.pdf](https://github.com/rokwire/illinois-app/files/14035976/UI-CleanUp-5.1-Ver05-1.pdf)

**Comment by vburgett** [comment]
Comments based on 5.1.17. @TodorBachvarov 

1. Purple grey color throughout app—needs to match current grey (see screenshots: Sign In/Sign Out = wrong grey; Unread Notifications = correct gray, Who Are You: both grays present and clash)
2. Update app icon image under Sign In/Sign Out: https://zpl.io/zwkNZlA
3. Under Settings > Contact Us, update the Smart, Healthy Communities Initiative link to https://rokwire.illinois.edu/people-page, add hyphen to “Urbana-Champaign” and use university’s preferred block I logo https://zpl.io/zwkNZ0z
![1000000711](https://github.com/rokwire/illinois-app/assets/1044905/2d104459-28bd-4916-9668-ade77922d326)
![1000000712](https://github.com/rokwire/illinois-app/assets/1044905/14186d02-12d0-4c70-8a2d-eef75b2e0413)
![1000000713](https://github.com/rokwire/illinois-app/assets/1044905/3493230c-2563-48c3-8e09-81dbc6c963c9)

**Comment by vburgett** [comment]
@TodorBachvarov please add the app version text to the Contact Us screen for 5.1. Thank you!

![Screenshot 2024-02-02 at 10 14 22 AM](https://github.com/rokwire/illinois-app/assets/1044905/f4b3fc13-26a1-4847-a34a-6f04988e6f00)

**Comment by TodorBachvarov** [comment]
Updated in version 5.1.29. @vburgett could you retest.

**Comment by vburgett** [comment]
Thank you, @TodorBachvarov!
