### ISSUE TITLE
[USABILITY] Add link to app article on how events get published in the app 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3886]
To inform and invite our users to use the app for publishing their events, please add the info icon and text “How are events published in the Illinois app?” to the bottom of the “Event Filters” panel in the app. The entire question should be underlined and linked to the Campus Guide article "Adding Events" under App Help. See the below screenshot for a visual. 

(This particular placement is to proactively direct any stakeholder questions or corrections for the college, school, unit, or department listings.)

This request was originally part of ticket #3876.
  
![How are events published](https://github.com/rokwire/illinois-app/assets/1044905/19719cde-222f-4b40-bf27-2c0c843521fd)

**Comment by mihail-varbanov** [comment]
Resolved in 5.1.18

**Comment by vburgett** [comment]
Confirming as complete in 5.1.18 — thank you! 
CC: @bstandard
