### ISSUE TITLE
[BUG] App failed to create an Event

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3887]
**Describe the bug**
Failed error message is displayed when the user creates an Event in the group. The event is not created successfully.

**To Reproduce**
1. Install the app
2. Go to the Group and create a new Event
3. Fill in the required fields and tap on Create Event.

**Actual Result**
App displays Pop-up window "Select Group". Code is displayed when the user taps on the Cancel button. App failed to create an Event

**Expected behavior**
App should create an Event successfully without failure.

Screenshot
![Group event](https://github.com/rokwire/illinois-app/assets/26231179/b043eb4b-cdcf-49d3-b7ec-d5cd282601a9)

**Smartphone (please complete the following information):**
 - Device: [e.g. android]
 - Version [e.g.5.2.12]

**Additional context**

**Comment by dobromirdobrev** [comment]
This is a backend issue. Once it is fixed, we'll let you know.

**Comment by dobromirdobrev** [comment]
Hi @Priyaravi8 ,
This is fixed. Please, verify when you have a chance. Thanks.

**Comment by Priyaravi8** [comment]
This is fixed
