### ISSUE TITLE
[BUG] Athletics broken pdf web links

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3893]
Go to Teams under Athletics and choose basketball, and tap on a player under Team Roster. Tap a stat pdf web link and see how the web content opens up in the app. 

I am getting the Web Blocked error. Please open external web links under Athletics outside of the app. 

V4.0.78
iPhone 13 Pro
17.2.1

![image](https://github.com/rokwire/illinois-app/assets/1044905/b2c6a4c5-5283-4849-8a95-049f71626ecc)
![image](https://github.com/rokwire/illinois-app/assets/1044905/99f603dd-7221-4eba-a1ab-c548a610cdcc)
![image](https://github.com/rokwire/illinois-app/assets/1044905/eef6c4be-6c17-46f2-9fee-038955f62c29)

**Comment by dobromirdobrev** [comment]
This is done in version 5.1.17 - all external web links under Athletics are opened outside the app.

**Comment by vburgett** [comment]
Confirmed as fixed and completed in 5.1.17.
