### ISSUE TITLE
[BUG] Event creation still has old pop-up window for publishing to Groups

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3905]
When publishing an event in the app (v5.1.16), the Group publishing pop-up message is still populating. This is now redundant with "Event Groups" section. The pop-up should no longer appear.

To match the admin website, please rename "Event Groups" to "Illinois App Groups" and change the text to "Publish your event to Group(s) that you administer."

**Comment by vburgett** [comment]
Confirming that the pop-up is now gone in 5.1.18. Thank you, @mihail-varbanov 

The text still needs updating. To match the admin website, please rename "Event Groups" to "Illinois App Groups" and change "events" to "event"

![Screenshot_20240131-154300~2.png](https://github.com/rokwire/illinois-app/assets/1044905/8d6ff1c8-3486-4828-9db7-36fd3277a3ea)

**Comment by mihail-varbanov** [comment]
@vburgett, your latest request is resolved in version 5.1.19

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov.

**Comment by vburgett** [comment]
1. Within the Group "Group Hangout" I went to "Create new event"
2. Under Illinois App Groups, I accidentally chose the Group "Would you rather . . . " (The Group I was in—Groups Hangout—was toggled off. Can it be toggled on since I am creating the event from that group?)
3. I chose Group Members Only as the visibility.
4. I received the old Group pop-up message again when it should be no longer displaying. (see screenshot)
5. The event showed up in "Groups Hangout" and not in "Would you rather . . ."
6. (I tried all of the above steps again but this time chose both the group I was in—Groups Hangout—and "Would you rather . . ." under Illinois App Groups, and the event ONLY showed up in Groups Hangout.)

5.1.20
Android Pixel 6

![Screenshot_20240202-161703](https://github.com/rokwire/illinois-app/assets/1044905/66a26408-ff9e-4f90-9394-a5841e2c6d57)
![Screenshot_20240202-161759](https://github.com/rokwire/illinois-app/assets/1044905/09fb48eb-22d6-4602-8e0b-1253705e7a77)

**Comment by mihail-varbanov** [comment]
@vburgett, what you observed was a mixture/mess of the old and new ways to bind an event to a group. I removed the old handling that used to display groups selector UI in a popup dialog window, and now we are based only on the group binding available in the create event panel from Illinois App Groups section. This is available from version 5.1.22.

**Comment by vburgett** [comment]
Confirmed as fixed in 5.1.22. Thank you, @mihail-varbanov
