### ISSUE TITLE
[USABILITY] Update wording for the states of event visibility

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3906]
In the app, when creating an event under All Events, Event Visibility should include the options "Public" and "Uploaded Guest List Only."

**Comment by dobromirdobrev** [comment]
Done in version 5.1.19

**Comment by vburgett** [comment]
The wording is now correct. Thank you!

**Comment by vburgett** [comment]
Noting that the Group Member Only option is dynamic and only visible once a Group is selected. The same is not true on the admin website.
