### ISSUE TITLE
[BUG] Athletic "My" Sections Missing Team Filter

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3909]
Please add in the Team filters button to the screens "My News" and "My Big 10 Events."

Please update the default messages in the below screens to include "starred." The text should read "There are no starred events for the selected teams." and "There is no starred news for the selected teams."

v5.1.17
![Screenshot_20240130-215712](https://github.com/rokwire/illinois-app/assets/1044905/232bbe9c-752c-43c0-851f-4676d0457337)
![Screenshot_20240130-215937](https://github.com/rokwire/illinois-app/assets/1044905/0cc3dfb9-d50c-4246-ad45-fddd2c09ad26)

**Comment by dobromirdobrev** [comment]
Fixed in version 5.1.18
