### ISSUE TITLE
[USABILITY] Profile voice recording text edit 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3923]
Please delete "by students"
Add a space in between "Name," and "First"

5.1.18 

![Screenshot_20240131-170138~2.png](https://github.com/rokwire/illinois-app/assets/1044905/ce661df9-2cb1-4a21-aa44-3170c2a94203)

**Comment by TodorBachvarov** [comment]
Changed in version 5.1.23.
