### ISSUE TITLE
[BUG] Fix the ability to publish an event to "Group Members Only"

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3929]
In both the app and on the admin website, publishing an event to "Group Members Only" should publish that event to the Group members without
- auto registering all the Group members, if registration is set up
- Group members and the admins also seeing the event under All Events
The "Group Member only" visibility setting should not disappear after publishing the event, as it does now.

(I am adding this ticket and closing https://github.com/rokwire/illinois_admin/issues/402 as requested.)

**Comment by dobromirdobrev** [comment]
@vburgett ,

These should not be issues anymore. Could you please verify them once again? And if you experience one of them, please provide details and a scenario. Thanks

**Comment by vburgett** [comment]
Please see my response here: [https://github.com/rokwire/illinois_admin/issues/526](https://github.com/rokwire/illinois_admin/issues/526) @dobromirdobrev

**Comment by vburgett** [comment]
This ticket [526](https://github.com/rokwire/illinois_admin/issues/526) will be complete once #3954 is complete. 
---
To summarize, in both the app and on the admin website, publishing an event to "Group Members Only" publish that event to the Group members without:

- auto registering all the Group members, if registration is set up
- Group members seeing the event under All Events (Event admins WILL see their "Group Member only" event under All Events but it will show the "Group Member only" visibility status via the event detail panel.)

**Comment by dobromirdobrev** [comment]
@vburgett , please see my comment in [526](https://github.com/rokwire/illinois_admin/issues/526).

**Comment by vburgett** [comment]
I will close this ticket as it is now being cover by 419 and 3922.
