### ISSUE TITLE
[BUG] In event settings, "Illinois App Groups" section should not disappear

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3930]
When creating an event in the app or via the admin website, the "Illinois App Groups" section should not disappear after saving the event, as it does now. [View this screen recording.](https://github.com/rokwire/illinois_admin/assets/1044905/ea766c34-a6b5-4333-a634-bbe834de8a0f)

This ticket is related to https://github.com/rokwire/illinois_admin/issues/519.

**Comment by mihail-varbanov** [comment]
We need backend support for this: rokwire/groups-building-block#416 & rokwire/groups-building-block#417. When these got resolved we can acknowledge this in the client application and resolve this issue.

**Comment by mihail-varbanov** [comment]
@vburgett, this is resolved in version 5.1.23.

**Comment by vburgett** [comment]
Confirming that this works in 5.1.24.
