### ISSUE TITLE
[USABILITY] Global Utilities: add the app version text to Contact Us

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3935]
Related to the Global Setting UI Updates #3883, please see the below list in priority order: 

1. Add the app version text to the Contact Us screen for 5.1. See screenshot.

2. Purple grey color throughout app—needs to match current grey (see screenshots: Sign In/Sign Out = wrong grey; Unread Notifications = correct gray, Who Are You: both grays present and clash)

3. Update app icon image under Sign In/Sign Out: [https://zpl.io/zwkNZlA](https://zpl.io/zwkNZlA)

4. Under Settings > Contact Us, update the Smart, Healthy Communities Initiative link to [https://rokwire.illinois.edu/people-page](https://rokwire.illinois.edu/people-page), add hyphen to “Urbana-Champaign” and use university’s preferred block I logo [https://zpl.io/zwkNZ0z](https://zpl.io/zwkNZ0z)

![Screenshot 2024-02-02 at 10 14 22 AM](https://github.com/rokwire/illinois-app/assets/1044905/4f5224fc-a882-4364-8d29-6f46d0139f0e)
![PurpleSignInOut](https://github.com/rokwire/illinois-app/assets/1044905/2ec7f31f-d2a1-43a9-92ec-a0b8cdc91ff4)

![CorrectGrey-UnreadNotifications](https://github.com/rokwire/illinois-app/assets/1044905/f2579779-c811-4eb9-9878-2312342dc221)
![PurpleWhoAreYou](https://github.com/rokwire/illinois-app/assets/1044905/f86a4072-9992-4669-8e79-7dc6ef56a898)

**Comment by TodorBachvarov** [comment]
Fixed in version 5.1.23. @vburgett could you check and validate if all links (redirect) are correct, so I could update them on the Config.

**Comment by vburgett** [comment]
Thank you, @TodorBachvarov. Only one link needs correcting. "University of Illinois Urbana-Champaign" should go to https://illinois.edu

**Comment by TodorBachvarov** [comment]
Updated in version 5.1.29. @vburgett could you retest.

**Comment by vburgett** [comment]
All links under Contact Us work as expected in 5.1.19. Thank you, @TodorBachvarov!
