### ISSUE TITLE
[BUG] App displays Empty Event screen upon tapping Event survey notification

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3938]
**Describe the bug**
On tapping the event survey notification, the user encounters an Empty Event screen

**To Reproduce**

Create an event in Illinois dashboard and publish it in a group
Registered user receives the notification for the Event survey post-end time
Tap on the Notification

**Actual Result**
The app displays Empty Event screen upon tapping Event survey notification

**Expected behavior**
The user should see the Event survey screen

**Screenshots**
![Empty Event](https://github.com/rokwire/illinois-app/assets/26231179/5a841281-ac32-4c36-ac91-2f2788a85847)

**Smartphone (please complete the following information):**
Device: [e.g. Android]
App Version: [e.g. 5.1.19]

**Comment by mihail-varbanov** [comment]
@Priyaravi8, I was unable to recreate this problem. I created an event with a survey and after it ended I got push notification. Opening the push notification opened the event detail panel where the "Take Survey" button was available. Tested both on Android and iOS. Please check this again and if you still have the same issue provide a detailed recreation scenario.

![Screenshot 2024-02-05 at 9 23 53 AM](https://github.com/rokwire/illinois-app/assets/5631487/58713f68-014d-4e12-8170-727ad8dfa534)

![screen](https://github.com/rokwire/illinois-app/assets/5631487/88115d04-2d55-4d2d-9b57-8c8e14e7d731)

**Comment by Priyaravi8** [comment]
This issue is fixed.
