### ISSUE TITLE
[BUG] Group Admin and Event Admin roles should be treated separately

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#3977]
**Describe the bug**
Create an Event in Admin Dashboard
Publish the Event to the Group by Group Admin
In-app, Every Group Admin in the group became the admin of the published Events.
Group Admin and Event admin roles should be treated separately

**Expected Result**
Only the user who published the Event should be an Admin for the Event in the Group, but not all the Group admins.

**Comment by vburgett** [comment]
Adding on the additional bolded details:

1. Create a **"Group-Member Only" event** via the admin website **(5.0.85 prod)**
2. Publish the event to a group via the admin website 
3. In the app **(5.1.29 prod)**, all group admins became the admin of the published event.

**Comment by mihail-varbanov** [comment]
This is Groups BB's issue, not Illinois app's. Closing this issue and opening new one at the right location: https://github.com/rokwire/groups-building-block/issues/423.
