### ISSUE TITLE
[BUG] Incorrect event end times

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3978]
In 5.0.78 and 5.1.29, the incorrect end time of 11:59pm is showing up for many events. Some events show the correct end time. I am guessing this incorrect 11:59pm end time is the result of the user not entering an end time in Webtools and/or Fusion. 

I expect events without a designated end time coming from any source to display without an end time instead of 11:59pm.

Below is a screenshot of how an event displays in Webtools and then in the Illinois app.

<img width="1047" alt="Screenshot 2024-02-14 at 9 40 49 PM" src="https://github.com/rokwire/illinois-app/assets/1044905/1d1117b9-ab6d-4abc-ba04-d707e4c649e0">

![Screenshot_20240214-214042.png](https://github.com/rokwire/illinois-app/assets/1044905/ee07d3dd-3a55-4ea9-844f-f05b44434925)

**Comment by mihail-varbanov** [comment]
@vburgett,

1\. Please provide a recreation scenario, what app you have used to create such an event and what date & time values you did set up.

2\. Please consider that most probably the problem is not in the way that the Illinois app displays event times because it displays the times as they are defined in the event data. The problem is rather in the way such an event had been created and what end time was exactly set.

**Comment by vburgett** [comment]
@mihail-varbanov these are not events I created. These are various events published in the Illinois app 5.1.29 on production to the All Events feed. I realize this could be a calendar bb issue and not an app issue. 

1. Go to Browse > All Events
2. See how many events extend to 11:59pm.
3. As one example we _can_ compare on the frontend, find an event with this issue in the app, and see what end time shows on the [Webtools](https://calendars.illinois.edu/list/7) website for that event from the same data. (Usually an event without an end time.)

**Comment by mihail-varbanov** [comment]
@vburgett, the fact that there are such end times does not necessarily mean that there is a problem in the Illinois app. These events could simply have been created with such end times.

I found events with such end times and they seem to come from Events web service. However I was not able to find them in the [Webtools](https://calendars.illinois.edu/list/7) web app. We dig further with the guys from Calendar BB and located for example, that the event **Microbiology Student Seminar:  "Tori Boyle/Hatoum-Aslan Lab and Mireille Farjo/Brooke Lab** on **Tue, Feb 20 @ 4pm CST** with **Speakers and Seminars** category comes from Events web service as data listed below. Please pay attention to the value of **endTime** field. If you still think that there is a problem please address the issue to whoever maintains Events web service / webtools.

```
{
  "allDay":false,
  "calendarId":"6991",
  "category":"Speakers and Seminars",
  "contacts":[
    {
      "email":"dtsevele@illinois.edu",
      "firstName":"Diane",
      "lastName":"Tsevelekos",
      "phone":"217-333-1736"
    }
  ],
  "createdBy":"dtsevele@illinois.edu",
  "dataModified":"2023-08-28T05:00:00",
  "dataSourceEventId":"33467052",
  "dateCreated":"2023-08-25T05:00:00",
  "endDate":"Wed, 21 Feb 2024 05:59:00 GMT",
  "eventId":"65140513cf07b1c43188db51",
  "icalUrl":"https://calendars.illinois.edu/ical/6991/33467052.ics",
  "id":"651405bc16fa9f00084c95d5",
  "isEventFree":true,
  "isInPerson":true,
  "isVirtual":false,
  "location":{
    "description":"Charles Miller Auditorium, B102 Chemical & Life Sciences Laboratory",
    "latitude":40.1105875,
    "longitude":-88.2072697
  },
  "originatingCalendarId":"937",
  "outlookUrl":"https://calendars.illinois.edu/outlook2010/6991/33467052.ics",
  "recurrenceId":0,
  "recurringFlag":false,
  "sourceId":"0",
  "sponsor":"Department of Microbiology",
  "startDate":"Tue, 20 Feb 2024 22:00:00 GMT",
  "title":"Microbiology Student Seminar:  Tori Boyle/Hatoum-Aslan Lab and Mireille Farjo/Brooke Lab"
}
```

**Comment by vburgett** [comment]
@mihail-varbanov this wasn't an issue until recently. I am making  an assumption that something has changed our end with our recent event updates (in the app and with the event and calendar bbs). 

The app didn't used to display the end time for Webtools events in these cases. Is there logic to apply on our end to again not display these instances of end times in the app?

If you still believe the issue is on the dev side with UIUC Web Services, I will contact them. Thank you for troubleshooting with me.

**Comment by mihail-varbanov** [comment]
@vburgett, I think the answers of all your questions are given in my previous post.

_I am making an assumption that something has changed our end with our recent event updates..._
"something has changed our end" is not an option because the input that we get from the external web service provides these end times. This is not a result of some logic performed on our side.

_Is there logic to apply on our end to again not display these instances of end times in the app?_
No, there is no logic to apply. If we are told that the event ends on "Wed, 21 Feb 2024 05:59:00 GMT" what kind of logic could we perform? Round the date time to the nearest hour or half? This is ridiculous. 

_If you still believe the issue is on the dev side with UIUC Web Services._
Yes, I do.

CC @pmarkhennessy

**Comment by vburgett** [comment]
@mihail-varbanov Perhaps the event bb logic with Webtools events was don't display an end time in the app.
I will contact UIUC Web Services.

**Comment by vburgett** [comment]
This is what was shared by UIUC Web Services team. Please advise. @mihail-varbanov @pmarkhennessy 


> Below is a snapshot of the data from one event from the XML. The timezones in our system are either set to CST or CDT. The calendar system I built assumes that all events are local to Champaign, Chicago, and Springfield.
>  
> FYI: How do we set the timezone? I set the timezone in my database and on my Linux servers to Chicago.

```
<publicEventWS>
<calendarId>7</calendarId>
<calendarName>General Events</calendarName>
<eventId>33483236</eventId>
<recurrence>false</recurrence>
<recurrenceId>0</recurrenceId>
<originatingCalendarId>2889</originatingCalendarId>
<originatingCalendarName>Campus General Request Event</originatingCalendarName>
<title>Military Connections Collective</title>
<titleURL/>
<eventType>Social/Informal Event</eventType>
<sponsor>Chez Veterans Center</sponsor>
<dateDisplay>true</dateDisplay>
<startDate>2/12/2024</startDate>
<endDate>2/29/2024</endDate>
<timeType>START_AND_END_TIME</timeType>
<startTime>3:00 pm</startTime>
<endTime>5:00 pm</endTime>
<endTimeLabel/>
<inPersonEvent>true</inPersonEvent>
<location>Chez Veterans Center | 908 W. Nevada St. Urbana, IL 61801</location>
<description><p id="isPasted" style="text-align: center;"><strong>Attention all military-connected students, including Veterans, Active-Duty, National Guard, Reservists, and military dependents!</strong></p><p>Join us for our Military Connections Collective, an epic study haven for military-connected students:</p><ul type="disc"><ul type="disc"><li>Use the Center for a great study space</li><li>Enjoy some snacks</li><li>Connect with other students with similar experiences</li><li>Access the resources the Chez Veterans Center has available to you</li></ul></ul><p>Chez Veterans Center is open from 0800-2000 Monday thru Friday. &nbsp;This group will meet regularly throughout February Monday thru Thursday from 1500-1700. &nbsp;See you there!</p><p>&nbsp;</p><p style="text-align: center;"><a href="https://chezveteranscenter.ahs.illinois.edu/" rel="noopener noreferrer" target="_blank">Learn more about the Chez Veterans Center by clicking here.</a></p><p style="text-align: center;"><br></p><p style="text-align: center;"><br></p></description>
<speaker/>
<registrationLabel/>
<registrationURL/>
<contactName>Ingrid Wheeler</contactName>
<contactEmail>[ithorso2@illinois.edu</contactEmail](mailto:ithorso2@illinois.edu%3c/contactEmail)>
<contactPhone/>
<costFree>true</costFree>
<cost>Free</cost>
<createdBy>[ithorso2@illinois.edu</createdBy](mailto:ithorso2@illinois.edu%3c/createdBy)>
<createdDate>2/9/2024</createdDate>
<editedBy/>
<editedDate>2/9/2024</editedDate>
<summary/>
<audienceFacultyStaff>false</audienceFacultyStaff>
<audienceStudents>false</audienceStudents>
<audiencePublic>false</audiencePublic>
<audienceAlumni>false</audienceAlumni>
<audienceParents>false</audienceParents>
<shareWithUrbanaEventsInChicagoArea>false</shareWithUrbanaEventsInChicagoArea>
<shareWithResearch>false</shareWithResearch>
<shareWithSpeakers>false</shareWithSpeakers>
<shareWithIllinoisMobileApp>true</shareWithIllinoisMobileApp>
<thumbImageUploaded>false</thumbImageUploaded>
<largeImageUploaded>false</largeImageUploaded>
<largeImageSize>0</largeImageSize>
<virtualEvent>false</virtualEvent>
<virtualEventURL/>
</publicEventWS>
```

> These are the instructions to query our event data. This is how your IT team gets our information:
> [https://blogs.illinois.edu/view/6291/437291](https://blogs.illinois.edu/view/6291/437291)
>  
> Please talk with your software developers. I cannot help you debug your software. Your software developers know where the calendar XML data is coming from and how they are getting it. 
>  
> Event URL to get the XML listed below:
> [https://xml.calendars.illinois.edu/eventXML16/6991.xml?pageNumber=1](https://xml.calendars.illinois.edu/eventXML16/6991.xml?pageNumber=1)

 
```
<publicEventWS>
<calendarId>6991</calendarId>
<calendarName>Illinois Mobile App Master Calendar</calendarName>
<eventId>33467052</eventId>
<recurrence>false</recurrence>
<recurrenceId>0</recurrenceId>
<originatingCalendarId>937</originatingCalendarId>
<originatingCalendarName>Microbiology Department</originatingCalendarName>
<title>Microbiology Student Seminar: Tori Boyle/Hatoum-Aslan Lab and Mireille Farjo/Brooke Lab</title>
<titleURL/>
<eventType>Seminar/Symposium</eventType>
<sponsor>Department of Microbiology</sponsor>
<dateDisplay>true</dateDisplay>
<startDate>2/20/2024</startDate>
<endDate>2/20/2024</endDate>
<timeType>START_TIME_ONLY</timeType>
<startTime>4:00 pm</startTime>
<endTime/>
<endTimeLabel>5:00 p.m.</endTimeLabel>
<inPersonEvent>true</inPersonEvent>
<location>Charles Miller Auditorium, B102 Chemical & Life Sciences Laboratory</location>
<description/>
<speaker/>
<registrationLabel/>
<registrationURL/>
<contactName>Diane Tsevelekos</contactName>
<contactEmail>[dtsevele@illinois.edu](mailto:dtsevele@illinois.edu)</contactEmail>
<contactPhone>217-333-1736</contactPhone>
<costFree>true</costFree>
<cost/>
<createdBy>[dtsevele@illinois.edu](mailto:dtsevele@illinois.edu)</createdBy>
<createdDate>8/25/2023</createdDate>
<editedBy/>
<editedDate>8/28/2023</editedDate>
<summary/>
<audienceFacultyStaff>false</audienceFacultyStaff>
<audienceStudents>false</audienceStudents>
<audiencePublic>false</audiencePublic>
<audienceAlumni>false</audienceAlumni>
<audienceParents>false</audienceParents>
<shareWithUrbanaEventsInChicagoArea>false</shareWithUrbanaEventsInChicagoArea>
<shareWithResearch>false</shareWithResearch>
<shareWithSpeakers>false</shareWithSpeakers>
<shareWithIllinoisMobileApp>true</shareWithIllinoisMobileApp>
<thumbImageUploaded>false</thumbImageUploaded>
<largeImageUploaded>false</largeImageUploaded>
<largeImageSize>0</largeImageSize>
<virtualEvent>false</virtualEvent>
<virtualEventURL/>
</publicEventWS>
```

**Comment by mihail-varbanov** [comment]
@petyos ^

**Comment by mihail-varbanov** [comment]
Let me please just point out that Events BB was developed and supported by Sandeep's team, and we have never worked on it. As long as I remember we had to retire it after the new Calendar BB appeared.

**Comment by petyos** [comment]
Hi @vburgett 

We are working on addressing the 11:59 pm issue. The reason is that some events come from WebTools with date but missing time. We must have both date and time in order to import this in the system. This is why for these events explicitely is set 11:59 pm.

Do you prefer to set a different predefined time or preffer not to set end date and time for these events at all?

cc @mihail-varbanov @pmarkhennessy

**Comment by mihail-varbanov** [comment]
I would set the time to 12:00:00 (noon) or 00:00:00 (midnight) when we have only a date. If the end date time does not exist I would leave it null in the calendar event, that is a valid value. But let's hear @vburgett too.

**Comment by vburgett** [comment]
When we only have a date and no start (or end) time, I would exclude the event and not display it in the app. 

If the end date time does not exist, leaving it null works for me assuming null results in no end time displaying in the app. 

Thank you, @mihail-varbanov and @petyos.

**Comment by vburgett** [comment]
This doesn't seem to be an issue any more in 6.0.27. I am marking it as completed. Thank you!
