### ISSUE TITLE
[BUG] One to-do list reminder: MANY notifications sent

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3985]
1. Create a to-do list item
2. Add a reminder
3. Receive 50 or so push and in-app notifications from the one to-do list reminder all at one time

To-do list item created via
Version 5.1.29 prod
Android 14, Pixel 6

Notifications received on both prod versions 5.1.29 (Android) and 5.0.78 (iPhone)
 

https://github.com/rokwire/illinois-app/assets/1044905/0f1976a3-82d5-43f7-af31-10ff1aba0b46

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
We were not able to reproduce this behavior. Could you please give us more details about the To-Do item?
For example, what are the settings - reminder, reminder date, category etc.

Other than that, can you reproduce this behavor again? It may be a single malfunction of the backend service.

Either way, I've created a backend issue: https://github.com/rokwire/wellness-building-block/issues/36

**Comment by vburgett** [comment]
1. Go to Browse > Academics > To-Do List
2. Tap "Add Item" button
3. Add text for item name
4. Choose today's date as your due date
5. Choose Reminder > Specific time > specify a time in the next few minutes
6. Save
7. Wait for the reminder notifications
8. Thankfully this time I received only two notifications so far—one that says it was sent "9 hours ago" and one that says "sent now"  
I would expect to get one notification.
@dobromirdobrev 
Version 5.1.29 prod
Android 14, Pixel 6

![Screenshot_20240219-095807](https://github.com/rokwire/illinois-app/assets/1044905/28058a4c-6a6b-457b-9c47-105f47bec685)

**Comment by mdryankov** [comment]
Hi @vburgett, 

There is a new deployed version of Wellness BB with improved logic which handles potentially incosistent notifications. Also please note the current logic sends two independant notifications (depends on presens of due time & reminder time). This means the number of notifications may vary between 0 and 2 (depends on the settings). More than 2 for a single non repeatble todo is an indicator for an unresolved problem. 

Please test and give feedback.

Thanks, 
Mladen
