### ISSUE TITLE
[BUG] "My Bus Stop" widget "View All" goes to the wrong panel

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3987]
1. Under Favorites, tap on the "View All" link for the "My Bus Stops" widget.
2. See how it leads to the "All Bus Stops" panel
3. I expect the "My Bus Stops" "View All" link to lead to the "My Bus Stops" panel.

Version 5.1.29 prod
Android 14, Pixel 6

**Comment by mihail-varbanov** [comment]
Fixed in version 5.1.32, as well as "View All" navigation from "My Destinations" widget.

**Comment by vburgett** [comment]
Fixed in 5.1.34 on prod.
