### ISSUE TITLE
[USABILITY] Display how-to content when there are no Favorites widgets

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#3999]
In 5.1.29, the Favorites screen is empty when a user has unstarred all widgets. 

Please add the below text and suggested design updates when there are no starred widgets.

**Text:**
Tap the [star]s under Browse to add shortcuts to Favorites. Note that some features require specific privacy settings and signing in with your NetID, phone number, or email address. 

**Requested update:**
![Screenshot 2024-02-22 at 11 38 25 AM](https://github.com/rokwire/illinois-app/assets/1044905/870a3f67-07fd-4c79-a269-58fa27f8381d)

**Comment by mihail-varbanov** [comment]
This was implemented in version 5.2.2.

**Comment by vburgett** [comment]
Confirmed as working in 5.1.34—thank you!!
