### ISSUE TITLE
Edit My Privacy Button in Settings Should Take User to Privacy Center

### ISSUE THREAD

**Issue by alex-pixo** [rokwire/illinois-app#40]
### Screen Location:
Settings > Edit My Privacy

### Problem:
The "Edit My Privacy" button currently takes user to the onboarding privacy slider screen.

### Recommended Action
The "Edit My Privacy" button should take user to new Privacy Center.

<img width="655" alt="Screen Shot 2020-09-02 at 9 04 40 AM" src="https://user-images.githubusercontent.com/60981190/91998376-c048c980-ed00-11ea-9442-e47e490d45a7.png">

### Test Device

Device: iPhone XS
OS: iOS 13.6.1
Illinois App v2.2.13

**Comment by dobromirdobrev** [comment]
Cannot be reproduced. The design is changed - there is no "Edit My Privacy" button in Settings panel.

**Comment by alex-pixo** [comment]
Confirmed that the design has changed and this is no longer relevant.
