### ISSUE TITLE
[USABILITY] Add event cover image file details

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#4010]
**Describe the usability issue**
Please add this text to one of the two spots on the Illinois admin website shown in the below mockups:
The event image displays a 16:9 or 1000px x 615px jpg, png, or gif (not animated). Larger images are automatically positioned within the frame and can be tapped to view in their entirety within the Illinois app.

**Additional context**
This issue is related to https://github.com/rokwire/illinois_admin/issues/561

cc @vburgett

**Comment by dobromirdobrev** [comment]
Done in version 5.1.34.

**Comment by vburgett** [comment]
Confirming this is complete is 5.1.34.
