### ISSUE TITLE
[BUG] Event registration label does not work

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#4012]
**Describe the bug**
The label for external registration is not handled by the Illinois app.

**Additional context**
This issue is consequence of https://github.com/rokwire/illinois_admin/issues/552

**Comment by dobromirdobrev** [comment]
This is fixed in version 5.1.34 of the Illinois app.

**Comment by vburgett** [comment]
Confirming that the "Add Registration Label" does indeed update the button text in the app. Thank you!
