### ISSUE TITLE
[BUG] Name pronunciation recording won't save

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4033]
Under My Profile, the name pronunciation recording won't save. 

Go to Profile > My Profile 
Record a name pronunciation recording. 
Tap Save. 
Get the below error.
See how no name recording is saved. 

iPhone 13 Pro
App 5.1.34

![image](https://github.com/rokwire/illinois-app/assets/1044905/a188387a-e37b-4d52-9215-92af138a909b)

**Comment by TodorBachvarov** [comment]
I'm not able to reproduce this issue for both ios and android. @vburgett could you test it again with the latest build. If you still reproduce it does it happen every time or in some specific scenario? Also which environment dev or prod?

**Comment by TodorBachvarov** [comment]
Thank you @vburgett, this seems to happen only on Prod. I've created backend issue in the content BB: https://github.com/rokwire/content-building-block/issues/102
