### ISSUE TITLE
[USABILITY] Out-of-date link under Wellness Tip 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4037]
Under Wellness > Today's Wellness Tip, please update the button "Learn more about the 8 dimensions" to lead to https://www.mckinley.illinois.edu/wellness. Please also have the link open outside of the app in a browser to avoid the "web content blocked" issue.

v5.1.34

**Comment by mihail-varbanov** [comment]
The URL is fixed in our config service for Illinois app versions 5.1 and 5.2. The launch in external browser feature is implemented in version 5.2.8.

**Comment by vburgett** [comment]
Complete in 5.2.10.
