### ISSUE TITLE
[USABILITY] UI Clean Up: Share Panels from Events and Groups

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4039]
When you go to a specific event or a specific group and tap on "Share this event/group," please delete the share icon on the Share Link buttons. 

For the Group share panel, please update the text "Promote this group" to "Share this group"

See below screenshots.

v5.1.34

![IMG_4994](https://github.com/rokwire/illinois-app/assets/1044905/61622513-85e4-42f9-9583-593776191d00)
![IMG_4995](https://github.com/rokwire/illinois-app/assets/1044905/404028d3-e058-4da1-88d1-9e99ea96e6c6)

**Comment by mihail-varbanov** [comment]
Resolved in version 5.2.10.

**Comment by vburgett** [comment]
Complete in 5.2.10.
