### ISSUE TITLE
[USABILITY] Alphabetize Event Departments Names 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4040]
Please make sure the text under Event Filters > College, School & Unit and Event Filters > Department are in alphabetical order (not using "The").

Here are two examples. Under College, School & Unit > Student Affairs and Departments:
1. "University Housing" should be listed under "Testing Center"
2. "The Career Center" should be listed under "Campus Mail."

v 5.1.34
cc: @kpecknold 
 
![IMG_4989](https://github.com/rokwire/illinois-app/assets/1044905/d9336204-e559-49fe-af8f-69052828efe7)
![IMG_4990](https://github.com/rokwire/illinois-app/assets/1044905/4f1eff49-b845-4d54-88ad-875817995ef2)

**Comment by mihail-varbanov** [comment]
This is done, as far as I understood this complex sorting rule, and as far as I was capable to observe the hundreds of departments in our attributes definitions. These definitions reside on our Content service so the update does not involve Illinois app's source code. This update is performed on dev/test/production environments and it is now available to all apps that use our content service, including the live app version 5.1.

**Comment by vburgett** [comment]
Thank you!
