### ISSUE TITLE
[FEATURE] Add Share and Clear "Filtered View" on Event Feed Panel

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4041]
Please add the ability to share and clear a filtered event view in the event feed panel. Please see the PDF:  

[ShareEventFilteredView.pdf](https://github.com/rokwire/illinois-app/files/15191738/ShareEventFilteredView.pdf)

**Comment by mihail-varbanov** [comment]
@vburgett, don't you think that lining up the share and clear buttons next to each other on the right side would give a more consistent user experience? I consider that this could increase the chance to mistake the button that the user attempts to tap some, but in other hand it is a common practice to group action buttons on the right (like profile / notification / settings in the header bar above) and keep the left side button for some more general actions like back, drawer menu, etc. This is just a suggestion.

<img width="388" alt="ShareEventFilteredView" src="https://github.com/rokwire/illinois-app/assets/5631487/39f607d2-d254-42ef-b3bf-5d35e2edbc68">

**Comment by mihail-varbanov** [comment]
Implemented in version 5.2.9. There are slight differences to [ShareEventFilteredView.pdf](https://github.com/rokwire/illinois-app/files/15191738/ShareEventFilteredView.pdf) design that I hope are for better.

**Comment by vburgett** [comment]
Thanks, Misho. Did you end up implementing what you shared via your screenshot or another solution?

**Comment by mihail-varbanov** [comment]
Hi @vburgett. Yes, I did. It is available in 5.2.9 build. Please ask @pmarkhennessy, to provide you with a link to this build.

**Comment by vburgett** [comment]
It works great. Thank you, @mihail-varbanov. 

As part of the styles.json icon clean up, the app uses the solid share icon (see screenshots). Please change this event feed share icon to the same one. 

To avoid big thumbs from tapping the clear button instead of the share icon, please align the share icon with the "plus icon" (see screenshot).

![Screenshot_20240520-121523](https://github.com/rokwire/illinois-app/assets/1044905/885246eb-2382-4bb6-9a39-46077287b723)
![Screenshot_20240520-121542](https://github.com/rokwire/illinois-app/assets/1044905/75d5740a-ce24-4211-8ef0-1280e78c21d9)
![Screenshot_20240520-121643](https://github.com/rokwire/illinois-app/assets/1044905/e7eaad9f-69c8-45e1-b268-05e8bc102774)

**Comment by mihail-varbanov** [comment]
@vburgett, I think the last request is fulfilled. This is available in version 6.0.1.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov. The icons are now aligned but the share icon is still incorrect in 6.0.4 on dev.

**Comment by mihail-varbanov** [comment]
@vburgett, I think I misunderstood you before. I think share icon is a you want it in 6.0.7.

**Comment by vburgett** [comment]
The icon you used in 6.0.7 is correct. Thank you, @mihail-varbanov!

**Comment by vburgett** [comment]
@Priyaravi8 you need to have a filtered view before you can clear it. Please add a filter then you will see an X to clear that filter.

**Comment by Priyaravi8** [comment]
@vburgett  - Thank you. All good.
