### ISSUE TITLE
[USABILITY] Event Registration: Update Pop-Up Messages

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#4042]
Please update the pop-up messages after tapping the “Register” or “Unregister” buttons for in-app event registration. See attached images for both the current and proposed.

**Current**
Part 1:
1. Go to an event with in-app registration set up where you are not the admin (ex. on dev, see event “Github Admin Registration” on June 29, 2024)
2. Tap the “Register” button 
3. View pop-up (”Do you want to star this event?”)
4. Select “Yes”

Part 2:
4. On the same event detail screen, tap “Unregister”
5. View pop-up

**Proposed**
Part 1 (REGISTER Pop-up):
1. ”Do you want to star this event” should be updated to “You’re registered! Would you like to add this event to [orange star icon] My Events? 
2. The buttons below the new text should be “No” (blue outline) and “Yes” (orange outline)
3. Selecting “Yes” should star/favorite the event

Part 2 (UNREGISTER Pop-up):
4. The pop-up text should read “You are no longer registered for this event.”
5. The button below the text should say “OK”
6. Selecting “OK” should NOT unstar/unfavorite the event

CC: @vburgett 

Screenshots for current and proposed attached.
![Current-Register-Unregister](https://github.com/rokwire/illinois-app/assets/129777610/a4fd121b-e892-4e68-844f-bba9e2b90dfd)
![Proposed-Register-Unregister](https://github.com/rokwire/illinois-app/assets/129777610/5ffe6278-0d06-4fb3-8ad7-38002a9b6176)

Device: [Pixel 7]
OS: [14]

**Comment by mihail-varbanov** [comment]
This is implemented in version 5.2.11. There are small style differences with the proposed UI because I wanted to reuse the prompt/message styles that we already use in Calendar Events.
