### ISSUE TITLE
[BUG] Can't delete event cover image

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4044]
After an event admin has added a cover image and saved it in the app, there is no way to clear the image and reset the event cover image to the default Alma Mater image. See screen recording.

Please add a "clear" button to mimic the event cover image options on the admin website.

v5.1.34

https://github.com/rokwire/illinois-app/assets/1044905/701f9a8f-5a96-403d-bc20-58bafb4fece4

**Comment by TodorBachvarov** [comment]
Added in version 5.2.8. Same change was made and for Group cover image.

**Comment by vburgett** [comment]
Complete in 5.2.10.
