### ISSUE TITLE
[USABILITY] Delete Item in Campus Guide

### ISSUE THREAD

**Issue by bstandard** [rokwire/illinois-app#4045]
The Campus Guide has an errant section with an item that cannot be located through the web admin panel.

The May section appears In Campus Guide > Complete Campus Guide:

![bad-category](https://github.com/rokwire/illinois-app/assets/141068526/9aad8cab-ae95-435c-a8e7-09911d1b883e)

Clicking on the section takes the user to an item that should be under Campus Reminders:

![may-item](https://github.com/rokwire/illinois-app/assets/141068526/000c5a97-9902-4743-b28d-35c08fac3e10)

This item does not exist in the web admin panel:

![admin-may](https://github.com/rokwire/illinois-app/assets/141068526/3475264a-47ec-4538-9eb7-9d1a3e1c130d)

Please delete the item (which should delete the section) or provide instructions on how to locate the item and delete it. Thanks.

**Comment by mihail-varbanov** [comment]
The item with content id "may-17.id" was wrongly formatted. I think the intention for it was to be a campus reminder, but its category and section fields had wrong values that led to the above view in Complete Campus Guide. I fixed the item and it appears not in the proper location: in "Campus Reminders" section inside the "May" group.

**Comment by bstandard** [comment]
Thanks for trying to fix this. Now Campus Reminders has two sections for May:
![double-may](https://github.com/rokwire/illinois-app/assets/141068526/848eed73-6b66-42bd-a81a-b141311fdf7e)

The bottom one leads to this item that was formatted incorrectly. This incorrect item still is not visible in the admin interface so I can't fix this problem either.

Does this incorrect item perhaps have different info listed in the section field? Here's an example of an item in the original May section of Campus Reminders:

![admin-campus-reminders](https://github.com/rokwire/illinois-app/assets/141068526/2ad769f3-bdc2-4984-9b6b-f4f167100012)

If you can't fix this incorrect item so it shows up with the other May items in Campus Reminders, please delete it. Thanks.

**Comment by mihail-varbanov** [comment]
My fix yesterday was incomplete. I forgot to set {"content_type" : "campus-reminder"} filed to this article. After this was applied, this article gets merged to the other content from May.

I do not use the Admin app for editing guide content, I do this straightly in its source JSON. This is how the "problematic" article currently looks like:

```
{
	"_id":"28ee78fc-f9fe-4521-bde5-bda0a9378931",
	"content_id":"may-17.id",
	"guide":"For students",
	"category":"Campus Reminders",
	"section":"May",
	"date":"2024-05-17",
	"content_type":"campus-reminder",
	"list_title":"Deadline for UG and GRAD to Add a POT S1 Course via Student Self-Service and All Students to Drop POT S1 Course for Tuition Refund",
	"list_description":"May 17, 2024",
	"detail_title":"Deadline for UG and GRAD to Add a POT S1 Course via Student Self-Service and All Students to Drop POT S1 Course for Tuition Refund",
	"detail_description":"<ul><li>Deadline for UG to add a POT S1 course via Student Self-Service</li><li>Deadline for GRAD to add a POT S1 course via Student Self-Service</li><li>Deadline for all students to drop a POT S1 course for a tuition refund if registered for any other summer POT course</li></ul><p><b>Note.</b> <br>POT: Part of term (POT) values indicate the time frame for the course.<br>S1 = First 4 weeks of the semester (5/13/2024–6/07/2024 plus finals)"
}
```

If you still find some problems please thy to fix them yourself - this is only in guide JSON content, not in the application source code. Or, if you cannot fix it let me know and I will try to do it.

**Comment by mihail-varbanov** [comment]
@bstandard, you have it, I believe.

**Comment by bstandard** [comment]
I have access only to Content/Guide. There is no Json Structure option and I was never told this was an option. Do you know whether this requires special permission?

**Comment by mihail-varbanov** [comment]
I checked in Admin app's source code and I see that this command availability is controlled by "content.guide_json" permission, or "app admin" privilege. That's why you do not see it in the Content commands list.

**Comment by bstandard** [comment]
I'm the admin of Campus Guide. If you and your team don't want to be bothered with these kinds of changes it would make sense to give admin access to someone else. Is this a question for Mark?

**Comment by mihail-varbanov** [comment]
I am not sure who controls these rights. Probably @pmarkhennessy would know this better.

**Comment by bstandard** [comment]
@pmarkhennessy Is it possible to give me access to the Campus Guide/Content/JSON Structure option in the admin app? I am now the Campus Guide admin. Sometimes when there's a formatting mistake a Campus Guide item disappears from the admin app and can be fixed only by someone with access to the JSON file. Ordinary editing would still be done in the admin app but having this emergency access would save time and effort for the developers. Previously I worked on the strings.json files so I have experience with making these kinds of changes.
