### ISSUE TITLE
[USABILITY] Event Sub-Category Typo

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4046]
Under Event Filters > Event Category > Recreation, Health and Fitness, please change "Adventure Req" to "Adventure Recreation"

v5.1.34

**Comment by mihail-varbanov** [comment]
@vburgett, @pmarkhennessy, I am afraid that yesterday I misled @dobromirdobrev that fulfilling this requirement would affect existing events/groups attributes. When I dived into attributes support in the Illinois client app I found out that a long time ago I designed a way to solve a problem like this one exactly. So I updated the attribute definitions on dev/prod/test, both for events and groups, and now the attribute value reads "Adventure Recreation", as requested. Please note that this also affects the existing 5.1 release. Let me know please if you see some issue with this update.

**Comment by vburgett** [comment]
Confirming as fixed on dev. Thank you!
