### ISSUE TITLE
[USABILITY] Eliminate Infinite Nesting of Group Replies

### ISSUE THREAD

**Issue by jake-fava** [rokwire/illinois-app#4049]
When a user replies to a reply on a post, their “sub-reply” creates a new thread underneath the reply. This can be repeated a seemingly infinite number of times, creating “sub-sub-replies”, “sub-sub-sub-replies”, and so on, creating an “infinitely-nested” web of replies. **(See image 1)**

To reproduce:
1. Create a post in any Group
2. Create a reply to that post
3. Reply to the reply on that post (creating a “sub-reply”) 
4. See how multiple panels are created in the app for numerous replies to a single post **(image 1)**

Please make ALL replies (eliminating sub-replies, sub-sub replies, etc.) to a post appear in a single panel in chronological order with the oldest reply at the top and the most recent at the bottom. **(See image 2)**

Related to ticket #2938 - whenever a user taps on a notification for a reply, the app should display this single panel **(image 2)** with the original post at the top. 

v 5.1.34

@vburgett

Image 1:
![Image 1 (1)](https://github.com/rokwire/illinois-app/assets/109174739/c94d61bf-e338-4b50-aa6e-b8e2d96d8a45)

Image 2:
![Image 2 (1)](https://github.com/rokwire/illinois-app/assets/109174739/05e6b6e4-86ed-4c8b-a7e0-7c9ce1a4f858)

**Comment by vburgett** [comment]
Adding on: 

All replies are still possible. They just show up in the same panel under the original post like Jake’s screenshot.

**Comment by TodorBachvarov** [comment]
In order to prevent user from creating sub-reply, I've removed the "Reply" from the ReplyCard options and disabled the reply card taping. In this way the user won't be able to create new sub-replies and all newly created replies will appear below the original post. The old sub-replies will remain as they were before. Changed in version 5.2.10.

**Comment by jake-fava** [comment]
Thanks for your work on this, @TodorBachvarov! A couple changes still need to be made:

1. Replies should be listed in "chronological order with the oldest reply at the top and the most recent at the bottom" - currently it is the opposite
2. "whenever a user taps on a notification for a reply, the app should display this single panel with the original post at the top" - currently, tapping on a reply notification takes me to a new panel for that reply where I am able to create a sub-reply (**image 3**); you can see this reply has a sub-reply because it has "1 reply" (**image 4**)

cc: @vburgett 


![Image 4](https://github.com/rokwire/illinois-app/assets/109174739/3fcd0f58-a503-49da-9e06-a195236ee696)
 
![Image 3](https://github.com/rokwire/illinois-app/assets/109174739/c1c298b8-8cf1-499b-bada-0331181aa4fb)

**Comment by TodorBachvarov** [comment]
This will require a groups BB change. I've created this issue: https://github.com/rokwire/illinois-app/issues/4081. 
When it's done I'll implement the following change: 
Whenever a user taps on a notification for a reply, the app will display a single panel with the original post at the top and all post replies below (the latest reply will be at the bottom). @jake-fava @vburgett Could you confirm that this is the desired behaviour?

**Comment by vburgett** [comment]
That is accurate. Thank you, @TodorBachvarov.

**Comment by TodorBachvarov** [comment]
Done in version 6.0.10

**Comment by vburgett** [comment]
Confirming as fixed in 6.0.12. @jake-fava if you agree, please close this ticket.

**Comment by jake-fava** [comment]
Confirmed working in 6.0.14 as well - thanks, y'all!
