### ISSUE TITLE
[USABILITY] Simplify Browse: hide Notifications

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4051]
Our user data shows us that Notifications are accessed from the bell notifications icon. To simplify the content and user experience in the Illinois app, please hide the following:

Browse > Notifications section
Customize > Unread Notifications 
Customize > All Notifications

**Comment by mihail-varbanov** [comment]
Resolved in version 5.2.8

**Comment by vburgett** [comment]
Complete in 5.2.10.
