### ISSUE TITLE
[BUG] Ability to remove yourself as the last admin of a group- leaving it with no admin(s)

### ISSUE THREAD

**Issue by nataliehelregel** [rokwire/illinois-app#4052]
A sole admin of a group can remove their own admin status and leave the group with no admin to run a group. Leaving it locked and without an admin to continue to run the group. 

**To Reproduce**
1. Create your own Group so you are the admin.
2. Navigate to "Manage Members"
3. Tap on your name (not your picture)
4. Toggle off "Admin" removing yourself as the only admin OR remove yourself from the group entirely. 

**Expected behavior**
When a user (who is the only admin assigned to a group) attempts to remove themselves as the admin- a pop up will appear that says the following:

"Would you like to remove yourself as the only group admin and delete this group?"
Then provide two options within the pop up that say "No" and "Yes"

cc: @vburgett  @kpecknold

**Comment by TodorBachvarov** [comment]
Hi @vburgett, just to verify- pressing "Yes" will delete the entire group?

**Comment by vburgett** [comment]
pressing "Yes" will delete the entire group?
**That is correct.**

Currently if the user is the last group admin, we do not show "Leave group" button in GroupDetailPanel(so in this case we wont be able to show the new Dialog). 
**Correct when there is only one group admin, they should continue to **not** see the "Leave Group" option.**

**Comment by TodorBachvarov** [comment]
@vburgett this should be fixed in version 4.6.23

**Comment by nataliehelregel** [comment]
@TodorBachvarov Thank you!  This has been fixed as requested.
