### ISSUE TITLE
[FEATURE] Add Three New Radio Stations to Browse and Favorites

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4059]
- Create a new section under Browse called “Radio Stations” (It should be listed under "Polls" to keep the alpha order.)
- Move "WPGU 107.1 FM" from "Feeds" to this new section.

Add three new stations to this list:
WILL News & Talk (NPR) https://icecast.will.illinois.edu/WILL-mp3-48
WILL Classical & More https://icecast.will.illinois.edu/WILLFM-48
Illinois Soul 101.1 FM https://icecast.will.illinois.edu/WILL-HD2-48

Favorites
- Match how WPGU 107.1 FM works with corresponding widgets for each new station
- Add each new station name to the Customize list on Favorites.

The final Browse update will read as:

**Radio Stations**
Listen to Illinois Public Media and student-run WPGU.

Illinois Soul 101.1 FM
WILL Classical & More
WILL News & Talk (NPR)
WPGU 107.1 FM

**Comment by mihail-varbanov** [comment]
Implemented in versin 5.2.9.
