### ISSUE TITLE
[FEATURE] “Feeds” to “Illini News” change  

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4060]
- Under Browse, rename “Feeds” to “Illini News”
- Change the text under “Feeds” to read “Catch the latest from Illinois social media and The Daily Illini.”
- Move WPGU 107.1 FM out of the Illini News section to the new Radio Stations section (see #4059) 

- Move the "Illini News" section under "Groups" in the Browse menu to keep the alpha order.
 
- For X/Twitter, add the account @NewsAtIllinois to the dropdown feed options (https://twitter.com/NewsAtIllinois)
- New Illinois app users should see @UofIllinois as the default X/Twitter feed.
 
The final Browse update will read as:

**Illini News**
Catch the latest from Illinois social media and The Daily Illini.

The Daily Illini
X/Twitter

**Comment by mihail-varbanov** [comment]
Resolved in version 5.2.10.

**Comment by vburgett** [comment]
Complete in 5.2.10.
