### ISSUE TITLE
[USABILITY] Stakeholder edits to Student Affairs department listing

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4070]
Under events and groups, please make the following changes to the **Student Affairs departments** filter listing:

- Replace “Inclusion & Intercultural Rels” with “New Student & Family Experiences”
- Move it below "Minority Student Affairs" to keep the alpha order

- Change “Student Success and Engagement” to “Student Success, Inclusion & Belonging”

**Comment by mihail-varbanov** [comment]
The update has been made on Content BB on prod and dev. This does not involve Illinois app code changes. It also affects the currently released Illinois 5.1 app.

**Comment by vburgett** [comment]
Confirmed as updated. Thank you!
