### ISSUE TITLE
[USABILITY] Correct NetID and privacy 4 or 5 pop-up text

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4079]
With the recent reorganization of Profile and Settings, a use now signs in under Profile (and not Settings). 

Please change the wording of the below pop-up to 
"To access [Notifications], you need to sign in with your NetID and set your privacy level to 4 or 5 under Profile." wherever this message is used throughout the app. 

![Screenshot_20240524-135154](https://github.com/rokwire/illinois-app/assets/1044905/71272f88-0f35-4d1a-91a4-2faa93273aee)

**Comment by mihail-varbanov** [comment]
This has been implemented in version 6.0.3.

**Comment by vburgett** [comment]
Apologies, @mihail-varbanov. I introduced a new error. Please update this text to read:

"To access [Notifications], you need to sign in with your NetID under Profile and set your privacy level to 4 or 5 under Settings."

**Comment by mihail-varbanov** [comment]
https://github.com/rokwire/illinois-app/issues/4080

**Comment by vburgett** [comment]
Confirmed as resolved in version 6.0.7. Thank you!
