### ISSUE TITLE
[USABILITY] Order of group post replies

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4081]
Please list the replies within a Group post from oldest to newest. The newest reply should be at the bottom.

![Screenshot_20240528-094939](https://github.com/rokwire/illinois-app/assets/1044905/40fec332-ba23-4fc6-ae7e-aa83e39269d3)

**Comment by vburgett** [comment]
I appreciate this comment, @mihail-varbanov. The logic derives from user experience patterns established in social media.

For example on Facebook, the user's home feed displays posts from newest to oldest. 
The replies to a single post are then listed from oldest to newest. 

The same difference would apply here. Let's proceed with this update. Thank you!

**Comment by TodorBachvarov** [comment]
Implemented in version 6.0.7

**Comment by vburgett** [comment]
It worked in 6.0.7. Thank you, @TodorBachvarov!
