### ISSUE TITLE
[BUG] Can't delete a name pronunciation recording

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4083]
Under Profile > My Profile, a user cannot delete their voice recording. The trash icon is only partially on the screen and not responsive to a user tapping on it.

Please make the "edit" icon smaller and move the trash can icon into the frame of the phone. If needed, the text "Your name pronunciation recording" could be smaller. 

v5.1.34 iphone

**Comment by mihail-varbanov** [comment]
There were a lot of problems and tweaks in the pronunciation control that I hope I have fixed. I also added prompt before deletion of a pronunciation recording. This is available in version 6.0.3.

**Comment by vburgett** [comment]
Works great. Thank you! To simplify the prompt, can you delete the word "Delete" and the X icon?

![Screenshot_20240611-120609~2.png](https://github.com/rokwire/illinois-app/assets/1044905/8763ab67-1539-4d33-bae1-310f37b405a4)

**Comment by TodorBachvarov** [comment]
Changes are applied in version 6.0.7

**Comment by vburgett** [comment]
Thank you, @TodorBachvarov. Confirming the changes are in place in 6.0.7.
