### ISSUE TITLE
[USABILITY] Text edit to department event/group filter 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4085]
As we meet with stakeholders, requests are being made to correct unit and department names.

Under the event and group Department filter, please change the department name "Institute for Genomic Biology" to "Carl R. Woese Institute for Genomic Biology" (This department is part of the "Research and Innovation" "College, School & Unit.") 

The name should now be listed under "Cancer Center at Illinois" to keep the list in alphabetical order.

![File (2)](https://github.com/rokwire/illinois-app/assets/1044905/91d1e8c2-5154-4daf-93fe-dfdb37792bdc)

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
This was done in the Content BB on dev and prod. It does not involve code changes and also affects the currently released Illinois 5.1 app.
