### ISSUE TITLE
[USABILITY] In-app registration: do not display "required" text 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4086]
Our stakeholders would like to use in-app registration, and their events may or may not _require_ registration. Please update the registration text in the app to match what we did in ticket #4043. 

The wording that displays on the event panel when in-app registration is set should read as either "Registration is available for this event." or "This event has registration..."

**Comment by mihail-varbanov** [comment]
@vburgett, I can't find the difference with #4043. Could you please define explicitly if you want something different than what we already have in Illinois app from #4043.

**Comment by vburgett** [comment]
The only difference is whether the event uses _an external link_ for registration OR _in-app_ registration. 

Ticket #4043 is about registration with an external link.
This ticket is about registration using the in-app registration feature.

The text that should display in the app to the user is the same in both cases.

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.6. Thank you!
