### ISSUE TITLE
[USABILITY] Stay on post panel after posting to a Group

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4087]
When a user replies to a post in a Group, the user should stay on the post panel to see their post appear after sending it. Right now the user hits send to post a reply and the Group panel then displays. 

Please see this screen recording: https://github.com/rokwire/illinois-app/assets/1044905/db345a0c-1762-413f-890a-0aee03dc3023

Dev 6.0.0
Android Pixel 6

**Comment by TodorBachvarov** [comment]
This will require Groups BB update: https://github.com/rokwire/illinois-app/issues/4081.

**Comment by TodorBachvarov** [comment]
Fixed in version 6.0.9
