### ISSUE TITLE
[FEATURE] New Assistant UI

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#4089]
**Fwd: Illinois App • Vanessa added new screens** / 2024/06/03

Could you take a look at this please and make the changes to the Assistant UI please

Ref: [UI mockup](https://app.zeplin.io/project/61df16e6e59b1b28c417589b/screen/665a05271e003058e03e2cf5)

[IllinoisAssistantUI-2024-05-31.pdf](https://github.com/user-attachments/files/15532652/IllinoisAssistantUI-2024-05-31.pdf)

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

We started to work on the new Assistant UI. So, a couple of questions arose in this regard.

1. What should "Clear All" link button do?
2. We need more precise `.png` files for the Assistant tab icon (please see the attached screenshots). The background color should be transparent (not white) and not to be cut off at the side. Current icons have white background and are cut off at top, right and bottom sides. Could you please provide them?

<img width="320" alt="Screenshot 2024-06-03 at 14 28 52" src="https://github.com/rokwire/illinois-app/assets/5978121/c174644e-4345-4d4c-b272-e56a1538f9d9">

<img width="140" alt="Screenshot 2024-06-03 at 16 38 11" src="https://github.com/rokwire/illinois-app/assets/5978121/442a5aea-6956-46da-af1a-f7fe140a0501">

Other questions comments may appear during the development process. Thanks cc @pmarkhennessy

**Comment by vburgett** [comment]
@dobromirdobrev attached are new pngs files for the icon.

“Clear All” removes everything in the thread but the initial prompt from the Assistant. 
![Screenshot 2024-06-03 at 8 56 48 AM](https://github.com/rokwire/illinois-app/assets/1044905/432cf761-2e44-47cc-af27-12c6176caea0)

[Icon-IllinoisAssistant.zip](https://github.com/user-attachments/files/15534846/Icon-IllinoisAssistant.zip)

**Comment by dobromirdobrev** [comment]
@vburgett ,

Thank you! Somehow I missed the "Clear All" behaviour description in the .pdf file.

Regarding the icons, the new ones still have white background. Please see the attached screenshot:

![Screenshot_20240604-174050.png](https://github.com/rokwire/illinois-app/assets/5978121/d32a193d-0366-48d4-b367-b54b118223b5)

The other tab icons have transparent background while the Assistant icon has white one. Maybe this is not so important but I just wanted to let you know what it would look like.

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
This is implemented in version 6.0.5 of the Illinois app. You can verify it when you have a chance.

**Comment by vburgett** [comment]
Thank you, @dobromirdobrev. Two items:

When a user posts a response, the UI scrolls up to the top of the thread instead of keeping the focus on the most recent response. Can this be updated?

During a session, the Illinois Assistant thread should not be cleared when going to another panel like the Illinois Assistant FAQs or Browse for example. The thread should be visible to the user during that session unless they "clear all."

**Comment by dobromirdobrev** [comment]
@vburgett ,
Your latest requirement is done in version 6.0.6 of the illinois app. Please verify when you have a chance

**Comment by vburgett** [comment]
Confirming that the below is working in 6.0.5. Thank you. @dobromirdobrev. 
_During a session, the Illinois Assistant thread should not be cleared when going to another panel like the Illinois Assistant FAQs or Browse for example. The thread should be visible to the user during that session unless they "clear all."_
