### ISSUE TITLE
[BUG] Unregistering from an Event: Failed Pop-Up Message

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#4104]
**Describe the bug**
There is a "Failed" error message when Unregistering for an event. 

**To Reproduce**
- Go to an event with in-app registration set up where you are not the admin (ex. on dev, see event “Github Admin Registration” on June 29, 2024)
- Tap the “Register” button
- View pop-up (”Do you want to star this event?”)
- Select “Yes”
- On the same event detail screen, tap “Unregister”
- View pop-up message: "Failed; Error getting finding: error performing transaction"

**Expected behavior**
(UNREGISTER Pop-up):
- The pop-up text should read “You are no longer registered for this event.”
- The button below the text should say “OK”
- Selecting “OK” should NOT unstar/unfavorite the event

Device: [Pixel 7]
OS: [14]

![Screenshot_20240611-121028](https://github.com/rokwire/illinois-app/assets/129777610/33d88d6d-0cdd-430b-ba61-1c59cb5922cb)

**Comment by TodorBachvarov** [comment]
There seems to be a backend issue with this event. The described behaviour was implemented with this issue https://github.com/rokwire/illinois-app/issues/4042 and the dialog will appear if the backend successfully register/unregister the event. @cdukeUX Do you observe this behaviour with some other events registration/unregistration this? I'll create a backend issue and will link it to this one.

**Comment by cdukeUX** [comment]
@TodorBachvarov yes, this issue happens when attempting to unregister for events. The UI/behavior is updated (#4042) but I'm still getting an error when unregistering which might be a problem on the backend. 

I've just created another event that may help locate the problem: "Admin Test Registration - August" (event date is August 31, 2024).

**Comment by TodorBachvarov** [comment]
I've created issue in the Calendar BB: https://github.com/rokwire/calendar-building-block/issues/464

**Comment by cdukeUX** [comment]
@TodorBachvarov I see that the BB ticket is closed, but I'm still seeing the "Failed" error message when unregistering:
![Register-Screenshot_20240624-165240](https://github.com/rokwire/illinois-app/assets/129777610/36bccf4c-dd67-4d91-8c5d-7e922834bd4b)
![Unregister-Failed-Screenshot_20240624-165245](https://github.com/rokwire/illinois-app/assets/129777610/5ec8f21d-84ee-465d-a593-ab51907acfe2)
