### ISSUE TITLE
[USABILITY] Daily Wellness Tip Text Update

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4105]
Our contact at McKinley requested adding the text "McKinley Health" to the below wellness tip. It should read as "McKinley Health Center and the Counseling . . . ” instead of "Center and the Counseling . . ."

![image001](https://github.com/rokwire/illinois-app/assets/1044905/ba2b8783-451c-455a-beb6-007daef31cba)

**Comment by TodorBachvarov** [comment]
@vburgett I've updated the text on Dev only. No need of new build, just reinstall the previous build(to clear the app cache).
Please let me know if it's okay and I'll update test and prod as well.

**Comment by vburgett** [comment]
Where does this list of Wellness Tips live? Can I check there instead of in the app? I am not sure when I will see that daily tip in order to close this ticket. @TodorBachvarov

**Comment by mihail-varbanov** [comment]
@vburgett, in the Admin app, choose an environment, login and select Illinois app. Go to Content / Custom Content Item. Enter "wellness_tips" as a category and choose the "Load" button. In "JSON Content" Text Field you will get the wellness tips JSON. You will see this daily tip text in the "strings / en / mental.10" JSON entry.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov. This worked when I went to Content / Wellness Tips (but not Content / Custom Content). 

Confirming that this wellness tip is now updated.
