### ISSUE TITLE
[USABILITY] Hide "Due Date Catalog" from Academics Dropdown Menu

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4106]
Please hide "Due Date Catalog" from the Academics dropdown menu.

(Across the spring, summer, and fall 2023 semesters, only 573 distinct users tapped on the button to access the Due Date Catalog.)

**Comment by TodorBachvarov** [comment]
Hi @vburgett, I'm finding two instances of "Due DateCatalog": 
1. HomeTab -> SectionTab -> Academics(section drop down) -> "Due DateCatalog".
2. AcademicsPanel (the old academics tab) -> DropDown button -> "Due DateCatalog".

Do we want to remove them both?

**Comment by vburgett** [comment]
Yes, please. The Due Date link should not appear in either location you referenced. Thank you, @TodorBachvarov.

**Comment by TodorBachvarov** [comment]
@vburgett, removed in version 6.0.9.

**Comment by vburgett** [comment]
Confirmed as complete in 6.0.9. Thank you!
