### ISSUE TITLE
[FEATURE] Merge Favorites and Browse panels

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#4108]
**Re: University Monday 2024/06/09** / 2024-06-12

[IllinoisAssistantUI-2024-05-31.pdf](https://github.com/user-attachments/files/15799672/IllinoisAssistantUI-2024-05-31.pdf)

**Comment by vburgett** [comment]
@mihail-varbanov here are a few edits based on the 6.06 dev build. 

![Screenshot 2024-06-13 at 4 34 04 PM](https://github.com/rokwire/illinois-app/assets/1044905/4ded0a0e-7b99-4e3e-b2ae-fbf49377297a)

**Comment by mihail-varbanov** [comment]
@vburgett, the above requests are fulfilled in version 6.0.10.

**Comment by vburgett** [comment]
Thank you, Misho. Can you also add the shadow?

**Comment by mihail-varbanov** [comment]
@vburgett, I think it has been added:

![Screenshot 2024-06-21 at 3 19 43 PM](https://github.com/rokwire/illinois-app/assets/5631487/1c1f2532-abb3-4b48-a78c-7b6a11844d6c)

**Comment by mihail-varbanov** [comment]
@vburgett, I just noticed that the shadow would look better if it is gradient filled, implemented in 6.0.11.

![Screenshot 2024-06-21 at 3 32 52 PM](https://github.com/rokwire/illinois-app/assets/5631487/cbff6c70-40c9-4c4e-bf29-50970aebaea6)

**Comment by vburgett** [comment]
Thank you. Can the shadow display even after the user scrolls. 

![Screenshot_20240621-124844.png](https://github.com/rokwire/illinois-app/assets/1044905/495b13fa-e6bf-47ed-9985-8364ac296c17)

**Comment by mihail-varbanov** [comment]
@vburgett, this is implemented in version 6.0.12. If you do not stop requesting small updates like this we will never finish.

**Comment by vburgett** [comment]
Thanks for making this update, @mihail-varbanov. I am confirming that it has been implemented in 6.0.12.
