### ISSUE TITLE
[USABILITY] Update 6.0 Welcome Message 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4121]
Please see below image. 

On the home panel, please:
1. Replace the “Welcome to Illinois 6.0” header with “Tailor Your App Experience”  
2. Replace the video with the same text used after a user has unstarred all of their favorite widgets. 
3. Please update the wording in _both_ locations: replace “under Browse” with “in Sections or Customize” (the words Sections and Customize should both link to the related panels)

![Screenshot 2024-06-13 at 4 24 12 PM](https://github.com/rokwire/illinois-app/assets/1044905/577e23fd-4649-471f-97a0-a15c8667ba1a)

**Comment by mihail-varbanov** [comment]
Hi @vburgett,

there is a problem in this design. If the user has not closed the Welcome widget ("Tailor Your App Experience") and unstars all favorite widgets, he or she will get two consequent widgets with (almost) the same content:

![Screenshot 2024-06-25 at 3 43 46 PM](https://github.com/rokwire/illinois-app/assets/5631487/0247d0bb-c9a3-4638-918a-c2adf61d346b)



The resolution that I chose was to show the "Tailor Your App Experience" widget also in case all favorite widgets are unstarred, and never to show the old message card under Favorites section (the second one in the above example). If the "Tailor Your App Experience" welcome widget had already been closed, and all favorite widgets are unstarred, the "Tailor Your App Experience" widget is presented without a close button. In this case, as soon as the user stars some favorite, this widget automatically disappears. This is a little complex and confusing but this is what we get when trying to reuse the same content in different contexts - a welcome widget and empty favorites widget.

Another note is that as long as this widget is presented only in the Home / Favorites tab, choosing the Favorites link from the message never does anything.

Anyway, with the above in mind, the new welcome message is available in version 6.0.13.

**Comment by vburgett** [comment]
@mihail-varbanov thank you for the solution you put in place. I can confirm that it is working in 6.0.13 as you described. 

Before or after the 6.0 release, please remove the Favorites link from both instances of the message. (If you prefer, I can open a new ticket. Let me know.)

**Comment by mihail-varbanov** [comment]
@vburgett, the link is removed in version 6.0.14:

![Screenshot 2024-06-26 at 10 12 59 AM](https://github.com/rokwire/illinois-app/assets/5631487/64e7aecb-daba-4f74-82b1-f2f99f25e2fa)

**Comment by vburgett** [comment]
@mihail-varbanov I now see the original issue. The request was:

"Please update the wording in both locations: replace “under Browse” with “in Sections **or Customize**” (the words Sections and Customize should both link to the related panels)"

**Comment by mihail-varbanov** [comment]
@vburgett, sorry about that. I have no idea how I messed up the wording. This is fixed in version 6.0.15

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov! Confirmed as updated in 6.0.15.
