### ISSUE TITLE
[USABILITY] Make Customize link smaller and add an edit icon

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4122]
Please update the Customize link on Favorites to be smaller (Proxima Nova Semibold 14pt)
Please also add a tappable edit icon.

![Screenshot 2024-06-13 at 4 39 44 PM](https://github.com/rokwire/illinois-app/assets/1044905/3cca40b0-4326-480c-b0c1-84af262dbf7e)

**Comment by mihail-varbanov** [comment]
This is implemented in version 6.0.13

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.14.
