### ISSUE TITLE
[BUG] Research favorite widget cut off

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4125]
Please fix research project cards on favorite widgets to not get cut off. See below screenshot from dev 6.0.6.

![Screenshot_20240614-072041.png](https://github.com/rokwire/illinois-app/assets/1044905/2f7ef8de-e15b-4501-9179-beece64b957b)

**Comment by mihail-varbanov** [comment]
This should be fixed in version 6.0.16.
