### ISSUE TITLE
[BUG] Illinois Assistant Sources and Links Focus 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4128]
When a user scrolls up to view and expand or collapse the Sources and Links section from an older answer, the assistant should keep the focus on those Sources and Links. Right now it jumps back to the bottom of the panel.

Please see the below screen recording. 

Dev 6.0.6 Android Pixel 6

https://github.com/rokwire/illinois-app/assets/1044905/d66c7d9d-e928-4904-911c-419855296f63

**Comment by dobromirdobrev** [comment]
@vburgett ,

This is fixed in version 6.0.13 of the Illinois app.

**Comment by vburgett** [comment]
Confirmed as completed in 6.0.13. Thank you!
