### ISSUE TITLE
[USABILITY] Text for removing/adding Favorites under Browse/Sections

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4131]
When a user stars or unstars a top section (ex: Dining) under Browse/Sections, please update the pop-up text. 

Current:
Are you sure you want to ADD ALL items to your favorites?

Are you sure you want to REMOVE ALL items from your favorites?

New:
Are you sure you want to ADD these items to your favorites?

Are you sure you want to REMOVE these items from your favorites?

(Users are confused that remove all and add all refers to _every_ favorite option available.)

![image](https://github.com/rokwire/illinois-app/assets/1044905/02d873e9-7d35-434e-80ab-220e179909da)

![image](https://github.com/rokwire/illinois-app/assets/1044905/88dfdc01-0407-4715-aba6-8fbfb57369a1)

**Comment by mihail-varbanov** [comment]
Resolved in version 6.0.14

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.14.
