### ISSUE TITLE
[FEATURE] Implement conditional content attributes

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#4134]
**University Tuesday 2024/06/17** / 2024-06-18

1 Misho, could you add or get Petyo to add a Core BB permission like we have for University Managed Groups called "RSO Managed Group" and within Groups only show the UI for setting a Registered Student Organization if the user has this permission please

**Comment by kpecknold** [comment]
We should hide the RSO attribute and filter completely. At some point in the future, we may use the attribute to support an import/integration, but that will be some time from now if it happens.
