### ISSUE TITLE
[BUG] Wellness and Academics Links missing from Sections

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4143]
Below are edits to the Academic and Wellness lists under Home > Sections. (In 5.1, these items are _only_ listed under the Academic and Wellness panel dropdown menus which are not part of 6.0 with the merging of Browse and Favorites.) 

Please add to Sections > Academics:
- myIllini (no star, under My Courses)—can the chevron right icon be replaced with the external window icon?

Please add to Sections > Wellness:
- Change "Rings" to "Daily Rings" and move to the top of the Wellness list above "Daily Tip"
- Add link to the article "Healthy Illini Podcast" above "Illinois Health Screener" (no star)
- Add link to the article "I'm Struggling" below "Illinois Health Screener" (no star)

**Comment by mihail-varbanov** [comment]
@vburgett, I believe these all had been implemented in version 6.0.11.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov. Sections > Academics > myIllini needs to open in a browser outside of the app to avoid sign in issues on this external website.

**Comment by mihail-varbanov** [comment]
@vburgett, I am sorry for this, I did not test it well last Friday. This is fixed in version 6.0.12.

**Comment by vburgett** [comment]
Confirming as fixed in 6.0.12. Thank you, @mihail-varbanov.

**Comment by Priyaravi8** [comment]
@mihail-varbanov  - Please check this - As per Vanessa's note - Add link to the article "I'm Struggling" below "Illinois Health Screener" (no star). But in Version 6.0.17, "I'm Struggling" is displayed above "Illinois Health Screener"

![image](https://github.com/rokwire/illinois-app/assets/26231179/52aca8e4-7fff-4b4f-8b94-fc21afbbcb99)

**Comment by vburgett** [comment]
Thanks, @Priyaravi8. I believe it is correctly alphabetized in your screenshot. @bstandard please confirm.

**Comment by bstandard** [comment]
@Priyaravi8 is correct. Alphabetization is letter-by-letter and apostrophes are ignored. Order is:
Healthy Illini Podcast
Illinois Health Screener
I'm Struggling

**Comment by mihail-varbanov** [comment]
We used а standard lexicographic sort in Sections and that's why "I'm Struggling" appeared before "Illinois Health Screener". Now some custom and non-standard sort rules are requested that I tried to implement. Let's just note that we are ignoring not only apostrophes but generally all symbols that are not alphanumeric or space (r"[^\w\s]+"), e.g. dash, dot, comma, quotation marks, brackets and so on. Also, the string comparison is case insensitive as it was before. This has been implemented in version 6.0.18.

**Comment by vburgett** [comment]
@mihail-varbanov In 6.0.19 I am still seeing the incorrect order under Sections > Wellness.
This is the correct placement of "I'm Struggling":

Healthy Illini Podcast
Illinois Health Screener
I'm Struggling

**Comment by mihail-varbanov** [comment]
@vburgett, sorry about that. I remember that I verified the updated sort order after my fix but now I saw it was not what needs to be again. I have no idea how this happened.

Anyway, I fixed it again and now it should be OK, available in version 6.0.20.

**Comment by vburgett** [comment]
Confirming as updated. Thank you!
