### ISSUE TITLE
[USABILITY] Hide App Help under Sections

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4144]
Please hide "App Help" under Home > Sections. Under Customize, please hide App Help and Video Tutorials.

Reasons: 
- The App Help section is redundant with Settings > Contact Us
- The videos are out of date and have very low engagement numbers
- To avoid having "App Help" as our second listed app section

**Comment by mihail-varbanov** [comment]
@vburgett, this is implemented in version 6.0.11.

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.11. Thank you!
