### ISSUE TITLE
[BUG]  "Failed" error message when registering for an event.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#4152]
**Describe the bug**
There is a "Failed" error message when registering for an event.

**To Reproduce**

Go to an event with in-app registration set up where you are not the admin (ex. on dev, see event “Github Admin Registration” on June 29, 2024)
Tap the “Register” button

**Actual Result**
View pop-up message: "Failed; Error getting finding: error performing transaction"

Expected behavior
User should be able to register the event without Error

![err](https://github.com/rokwire/illinois-app/assets/26231179/787246d9-183f-4136-a980-0d82aaf5a63f)

Device: [Pixel 7]
APK Version [e.g. 6.0.6]

**Comment by mihail-varbanov** [comment]
This is a backend's issue. I am unable to test the register case because I am currently registered for this event and when I try to unregister it fails with the same error as above. I created an issue in Calendar BB's repo for this: https://github.com/rokwire/calendar-building-block/issues/471

**Comment by mihail-varbanov** [comment]
@Priyaravi8, the backend issue has been resolved (Events Calendar BB version 1.69.3). Now I can register and unregister successfully for “Github Admin Registration” event. Please check this on your side and close the issue if it works for you either.

**Comment by Priyaravi8** [comment]
This is fixed.
