### ISSUE TITLE
[BUG] UI Clean-Up, Styles.json typography

### ISSUE THREAD

**Issue by TodorBachvarov** [rokwire/illinois-app#4158]
Here is a new Miro board link that should work for you and others:
https://miro.com/app/board/uXjVK5AZle4=/?share_link_id=587712420253

**Comment by TodorBachvarov** [comment]
Hi @vburgett, I've made the changes for Events card and detail panel. I see that there is a comment "These updates should eventually also change the detail panels across the app. My Courses, Groups, Buildings, etc." As I understand it the scope of the task is the Event card and panel, and we will update the others in the future. Is that correct? If we want to update the Ui of the Groups, Courses etc. it will be very helpful if you provide me more details what should be updated (similar to the Link with the Events updates, because there might be some slight changes for the Card or Detail panel). As we are closer to the release date I prefer to be sure that I understand the update request.

**Comment by nataliehelregel** [comment]
Thank you @TodorBachvarov for working on this ticket before the next release! We've noticed two items to adjust after reviewing the 6.0.14 build. 

1. There is still a large amount of paragraph spacing within both the Event's page and event's card. The spacing has been highlighted yellow in screenshot's provided from the 6.0.14 build with this comment. Please make updates for this spacing to match the example spacing provided in our original Miro file. 

2. Change the text treatment for the code line that reads "Research Park" to size 14 and fillColorPrimary. I've circled the line in green for reference within one on the screenshots attached.

![Screenshot_01](https://github.com/rokwire/illinois-app/assets/96087558/b2c4c969-a777-4d77-bbef-a5533659aee6)
![Screenshot_02](https://github.com/rokwire/illinois-app/assets/96087558/57d110b0-5eb5-4cb9-aa62-6d8deb7127db)

Scope for updating detail panels across the app (My Courses, Groups, Buildings, etc) can wait until after this release. 

Thank you.


cc @vburgett

**Comment by TodorBachvarov** [comment]
Hi @nataliehelregel, Unfortunately I don't have access to the original Miro file so I'll reduce the spacing(marked in yellow). Please let me know how exactly to reduce it if it's still too large. I've updated the text to use title.secondary: {"font_family": "regular", "size": 14.0, "color": "fillColorPrimary"}. Changes are implemented in version 6.0.15

**Comment by vburgett** [comment]
Looks great, @TodorBachvarov. Thank you.

We'll close this ticket and continue the work for the other details panels.  

CC: @nataliehelregel
