### ISSUE TITLE
[BUG] Missing questions in create/modify group

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#417]
**Re: University Monday 2021/06/28** / 2021/07/02

1.5 In create/modify group we are missing the questions?

**Comment by dobromirdobrev** [comment]
Done in 2.5.4

**Comment by Priyaravi8** [comment]
Added questions are not saved in the membership questions

**Comment by dobromirdobrev** [comment]
Following up the comment from @Priyaravi8 :

> Added questions are not saved in the membership questions

This issue is a result of two problems:
1. Illinois app does not parse membership questions to json properly.
2. Groups BB does not acknowledge the field `membership_questions` when creating group.

The first problem is fixed in version 2.6.18 and 3.0.0 for Illinois app. 
For the second problem we created an issue https://github.com/rokwire/groups-building-block/issues/36 . 

@Priyaravi8 , please verify this again when the issue in Groups BB gets resolved with the proper Illinois app version (e.g. 2.6.18 or above). cc @pmarkhennessy

**Comment by knguyenjahiel** [comment]
Closed: no longer relevant to current functionality and design
