### ISSUE TITLE
[BUG] If group setting is off, members should not be able to send a direct message

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4170]
In 6.0.14, a group member can see the plus sign for creating a direct message when the admin has the setting "Send posts to specific members" turned off. 

Members should _not_ see the plus sign for direct messages when this toggle is turned off.

**Comment by TodorBachvarov** [comment]
HI @vburgett this is fixed in version 6.0.15.

**Comment by vburgett** [comment]
Confirming that Jake Fava, a member of a group with this setting turned off, no longer sees the plus sign by direct messages in 6.0.17. Thank you!
![Screenshot_20240702-110710](https://github.com/rokwire/illinois-app/assets/1044905/d474e93e-32a1-41b6-a5da-0967b950a8fe)
