### ISSUE TITLE
[USABILITY] More meaningful group notifications: polls and direct messages

### ISSUE THREAD

**Issue by jake-fava** [rokwire/illinois-app#4171]
Currently, notifications for polls have "Illinois" as the title **(see image 1)** - instead, the title should say "Group - [GROUP NAME]" (for example, "Group - Enneagram Enthusiasts") 

Currently, notifications for direct messages say "[NAME] posted [MESSAGE]" **(see images 2 and 3)** instead, "posted" should be replaced with "messaged you" - "[NAME] messaged you [MESSAGE]" (for example, "Vanessa Burgett messaged you "Hi Jake") 

![Screenshot_20240626-122631](https://github.com/rokwire/illinois-app/assets/109174739/ab9aef3f-fa4a-4fba-aaa0-876cf7353482)
![Screenshot_20240626-130036](https://github.com/rokwire/illinois-app/assets/109174739/97041014-9e15-45c7-849c-c252c8248bdb)
![Screenshot_20240626-130050](https://github.com/rokwire/illinois-app/assets/109174739/2686ae95-ecf9-43b0-9d82-3b029e3d6236)

cc: @vburgett
v6.0.14

**Comment by mihail-varbanov** [comment]
@jake-fava, the backend issues had been reported as resolved so you could check if they match the expected behavior.

**Comment by jake-fava** [comment]
Working in 6.0.22 - thank you!
