### ISSUE TITLE
[USABILITY] Update home panel photos

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4172]
Please update the morning, afternoon, and evening photos featured on the Favorites/Sections home panel with these files: https://drive.google.com/drive/folders/11v8c8dZ5Ud8_uCPKp6n-zDfZcZq--btC?usp=sharing

**Comment by mihail-varbanov** [comment]
@vburgett, can I get these files in WEBP image format please?

**Comment by vburgett** [comment]
https://drive.google.com/drive/folders/1FIIo9s6WwO0DIfR73mxhoQXzHcHCGDHE?usp=sharing @mihail-varbanov

**Comment by mihail-varbanov** [comment]
Hi @vburgett,

This is done with the following notes:

1\. The evening WEBP folder contains just 9 images, while the JPG folder contains 34. I created WEBPs from JPGs for all missing images.

2\. The Illinois app differentiates 4 periods of the day - morning, afternoon, evening and night. I created the night images set to be the same as evening images, so when the welcome text is "Good night" we will pick some image from the evening set. This was the same with the previous favorites tout images.

This update is applied on dev, prod and test and does not involve code changes, i.e. everything happens on the clouds.

**Comment by mihail-varbanov** [comment]
For reference, here is the complete image set that is currently in use for the home tout:

Morning
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-02-150604-060.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-02-161108-142.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-02-200614-281.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-02-210802-032.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-04-161116-008.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-190905-023.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-191203-034.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-191216-086.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-200115-004.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-200911-025.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-201120-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-210405-003.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-210728-003.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-210823-012-Boneyard.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-210823-013.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-08-211108-076.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-220714-MH-107.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-221101-MH-167.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-230109-FZ-013.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-230615-FZ-043.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-230829-FZ-006.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-230831-FZ-011.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-231017-FZ-101.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-FZ-220421-006.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/morning/UI-KCPA-amphi.webp

Afternoon
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/Architecture.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/ArtDesignStudent.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/FAA-20220819_134539.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/FAAstudent.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-02-140805-380.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-02-140813-815.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-03-151103-042.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-04-191020-932.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-08-210730-052.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-220608-MH-018.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-220629-FZ-002.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-220802-FZ-002-flipped.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-220817-FZ-026.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-220822-MH-031.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-220927-FZ-008.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-221216-MH-262.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230117-MH-043.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230124-FZ-031.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230125-MH-342.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230301-FZ-193.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230304-FZ-008.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230331-MH-072.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230331-MH-193.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230405-FZ-012.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230505-MH-005.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230820-MH-104.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230902-FZ-044.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-230927-MH-043.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-231004-FZ-037.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-231010-FZ-060.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-231010-FZ-065.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-231020-FZ-012.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-231021-FZ-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-231103-MH-057.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-231129-MH-028.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI-231205-MH-015.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/afternoon/UI2-230109-026.webp

Evening
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/240410%20Gangster%20Play%20CAP1303.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/Airness_034.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/I_Wish_b_856.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/KAM.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/kcpa-52.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/KrannertCenter2020-02-StepAfrika_CredALongworth_0473-02.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/LyricTheatre.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/RebeccaNettlFiol-IntheStringRoom2017-100.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/Rent.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-02-151130-013.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-190109-010.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200607-009-sunsetting.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200607-023.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200612-011.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200612-020.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200911-025.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200918-007_(1).webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-201109-010.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-201120-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-210917-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-220623-FZ-085.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-220928-MH-039.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-220929-MH-433.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-221014-FZ-52.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-221014-MH-104.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-221021-FZ-050.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230109-FZ-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230202-FZ-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230401-FZ-002.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230830-FZ-100.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230830-FZ-101.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-231006-FZ-21.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-231006-FZ-34.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-231129-MH-043.webp

Night
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/240410%20Gangster%20Play%20CAP1303.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/Airness_034.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/I_Wish_b_856.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/KAM.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/kcpa-52.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/KrannertCenter2020-02-StepAfrika_CredALongworth_0473-02.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/LyricTheatre.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/RebeccaNettlFiol-IntheStringRoom2017-100.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/Rent.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-02-151130-013.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-190109-010.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200607-009-sunsetting.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200607-023.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200612-011.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200612-020.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200911-025.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-200918-007_(1).webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-201109-010.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-201120-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-08-210917-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-220623-FZ-085.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-220928-MH-039.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-220929-MH-433.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-221014-FZ-52.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-221014-MH-104.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-221021-FZ-050.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230109-FZ-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230202-FZ-001.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230401-FZ-002.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230830-FZ-100.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-230830-FZ-101.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-231006-FZ-21.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-231006-FZ-34.webp
https://rokwire-images.s3.us-east-2.amazonaws.com/favorites2/tout/evening/UI-231129-MH-043.webp

**Comment by vburgett** [comment]
1. Not sure how that happened. Thank you for saving the files.
2. Thanks for this information.
@mihail-varbanov
