### ISSUE TITLE
[USABILITY] Wellness Resources Stakeholder Edits

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4186]
Please see attached for edits to the Sections > Wellness > Resources panel as requested by our stakeholders. 
 
[2024-06-28-WellnessResourcesUpdates.pdf](https://github.com/user-attachments/files/16035204/2024-06-28-WellnessResourcesUpdates.pdf)

**Comment by mihail-varbanov** [comment]
@vburgett, the requested changes have been applied on dev, prod and test. They do not involve Illinois app code update as these resource resides in the clouds.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov. The Student Assistance Center link is not working. The url should be https://odos.illinois.edu/community-of-care/student-assistance-center

**Comment by mihail-varbanov** [comment]
@vburgett, sorry for the typo in the URL. It must be fixed now.

**Comment by vburgett** [comment]
Thank you! Confirming that this update is complete.
