### ISSUE TITLE
[BUG] Overlapping pins in map are inaccessible when zoomed in

### ISSUE THREAD

**Issue by jake-fava** [rokwire/illinois-app#4192]
When there are two or more pins at the same location on the map (for example - PAR Dining Hall and Urbana South Market in the "Residence Hall Dining" view), a user can only tap on one of them when zoomed in. (see picture 3)

Instead of changing to the pin when the user zooms in, it would be great if the map would display the circled "2" (see picture 1) no matter how far zoomed in the user is.

(Hypothesis - does this have to do with two or more pins having the same exact coordinates? Perhaps one pin is blocking the other(s)?)

cc: @vburgett @kpecknold

V6.0.17 (Dev AND Prod)

![Screenshot_20240702-111303](https://github.com/rokwire/illinois-app/assets/109174739/b5bba8d2-199f-43ac-899f-b8f5ff5bfa3b)
![Screenshot_20240702-111308](https://github.com/rokwire/illinois-app/assets/109174739/7beebec0-2c22-4642-877e-964c4ae91ff7)
![Screenshot_20240702-111321](https://github.com/rokwire/illinois-app/assets/109174739/9db8b49d-0d11-4f46-a5bc-41f88130a3c9)

**Comment by mihail-varbanov** [comment]
This was implemented in version 6.0.19.

**Comment by jake-fava** [comment]
Seems to be working in 6.0.19 prod ✅
