### ISSUE TITLE
[ACCESSIBILITY] Assistant - Improper sequence after question entry (TalkBack)

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#4195]
**Describe the issue**
After entering a question, the focus order should go to the status message (BUG #4194 ) and then to the response. 

[WCAG 2.4.3 Focus Order](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html)

1. Using TalkBack
2. Go to 'Assistant'
3. Gesture until you hear 'Edit box, double tap to edit text'
4. Double tap, enter any question (for this I used 'Where is the nearest dining hall?' via voice entry button)

**Expected behavior**
After entering any question, screen reader user needs to be given a cue that the Assistant is processing or working on it. Then, when response is available, it should receive visual focus and screen reader focus to announce response.

**Actual behavior**
After entering any question, screen reader user hears "Cleared text, keyboard hidden, button, double tap to activate." Then they have to Gesture through:

1. "context"
2. "skrim Double tap to close bottom sheet..."
3. "Illinois Assistant # questions remaining today ..."
4. Clear all
5. close button
6. "Ask Illinois Assistant Button"
7. unlabeled thumbs up, 
8. unlabeled thumbs down
9. Sources and links (from previous responses) 
10. then my question
11. then FINALLY the response. :( too many swipes later

**Screenshots**

https://github.com/rokwire/illinois-app/assets/82892873/dbb8d3f2-1583-4a16-bd9d-8e12edbd6cc4

**Testing Environment & Devices (please complete the following information):**
• OS: Android Version 13
• Device: Google Pixel 4a

**Additional context**

**Comment by TodorBachvarov** [comment]
Fixed in version 6.0.20

**Comment by acovher2** [comment]
MUCH BETTER:) Verified as fixed in 6.0.36 android Prod
