### ISSUE TITLE
Privacy Level Change Modal Displaying Incorrectly

### ISSUE THREAD

**Issue by alex-pixo** [rokwire/illinois-app#42]
### Screen Location:
Browse > Privacy Center > Manage and Understand Your Privacy > Change Privacy Slider > "Set My Privacy" > Modal

### Problem:
Modal is displaying full height of device

![IMG_2012](https://user-images.githubusercontent.com/60981190/91999247-cb502980-ed01-11ea-979e-be549eab032d.PNG)

### Recommended Change
Modal should only be the height of text within.

<img width="255" alt="Screen Shot 2020-09-02 at 9 09 16 AM" src="https://user-images.githubusercontent.com/60981190/91999265-d2773780-ed01-11ea-892e-f05d4c9b2bd8.png">

Zeplin reference file: https://zpl.io/beRj3PB

### Test Device
Device: iPhone XS
OS: iOS 13.6.1
Illinois App v2.2.13

**Comment by TodorBachvarov** [comment]
This issue is caused  by the updated support for Accessibility- Large text + the Flutter limitations. If the dialog is not stretched, if the user uses large text, the content of the dialog wont be able to define size so it won't be able to scroll (and will show warning that pixels are overlapping)

**Comment by acovher2** [comment]
This bug is a result of another bug fix as Todor mentioned. THis needs closed or reassigned as Pixo is no longer on the project. 

THanks,
Amanda
