### ISSUE TITLE
[BUG] Only one event (created via admin site) of two Group-member only events is showing in "My Events" when starred

### ISSUE THREAD

**Issue by acovher2** [rokwire/illinois-app#4200]
**Describe the bug**
When a group member, stars two group-member only events in the group screen, they are not seeing both events in "My Events." 

**To Reproduce**

--Two Group-member only events were created:
- One was created via app. (Vanessa's Birthday...)
- Second was created via Admin site. (Cookout..)--

1. Go to '.My Groups.'
2.  Scroll down to 'Events'
3. Star both events
4. Toggle to "Home"
5. Scroll to "Events"
6. Click "My Events"

**Expected behavior**
User expects to see both starred events under "My Events" 

**Actual behavior**
User can only see "Cookout" event in "My Events" (This is the event created from Admin site) 

**Screenshots**

https://github.com/rokwire/illinois-app/assets/82892873/90436d1f-ec8f-4fe4-8246-020aea64174b
![20240703_133747](https://github.com/rokwire/illinois-app/assets/82892873/b917d8ca-41ef-4c91-a3ae-4318c3a4580e)

![20240703_134437](https://github.com/rokwire/illinois-app/assets/82892873/bf4f7cc8-5a2c-4b0f-88ca-e35bfd44e893)

**Smartphone (please complete the following information):**
• OS: Android Version 13
• Device: Google Pixel 4a

**Additional context**

**Comment by vburgett** [comment]
I am closing this ticket and correcting a few details in the new ticket #4202
