### ISSUE TITLE
[BUG] Only one event (created via app) of two Group-member only events is showing in "My Events" when starred

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4202]
When a group member stars two group-member only events in the group details panel, they are not seeing both events in "My Events."

**To reproduce:**
In the Group "Kathryn" two Group-member only events were created:

One was created via the admin website. (Vanessa's Birthday...)
Second was created via the app. (Cookout..)--

**Steps to reproduce the behavior:**
Go to '.My Groups.' > Kathryn
Scroll down to 'Events'
Star both events
Toggle to "Home"
Scroll to "Events"
Click "My Events"

**Expected behavior**
Group members should see both starred group-member only events under "My Events" and neither event under All Events (no filters turned on).

**Actual behavior**
User can only see "Cookout" event in "My Events" (This is the event created from the app). "Cookout" can also be seen under All Events.

Please note the Group Kathryn was public during testing. It is now private since we are testing on prod.

6.0.19 on prod

Smartphone:
• OS: Android Version 13
• Device: Google Pixel 4a
CC: @acovher2 

![GroupEventsx2](https://github.com/rokwire/illinois-app/assets/1044905/ad762f98-4439-44e2-be35-55257a90b3a2)
![GroupEvent-Cookout](https://github.com/rokwire/illinois-app/assets/1044905/799f0969-3fa6-4ce7-a273-e0e28780e4c7)

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

Can you tell us who made these screenshots? (and the ones in #4203) It is important for our investigation.
My assumption is that they are made from Kathryn Courtney. Is this correct? We see that she is the admin of "Cookout!" event.

For example, if you do the same scenario, what will you see? My feeling is that you will see the other event "Vanessa's Birthday Celebration!" because you are the admin of that event.

Thanks.

**Comment by vburgett** [comment]
@dobromirdobrev the screenshots and issues were experienced by @acovher2 who is a member of this group and not the admin of either event.

**Comment by dobromirdobrev** [comment]
@vburgett ,

This is strange. Is it possible that she was admin during the taking of the screenshots?

Could you please reproduce the same scenario on dev environment? And let us know which is the group, the relevant events and the users? All details will be very helpful.

We don't have access to the production database and we cannot properly investigate the problem.

**Comment by vburgett** [comment]
@dobromirdobrev she was never a group admin. 

We will try to reproduce the issue on dev and report back. 

Cc: @knguyenjahiel @acovher2

**Comment by dobromirdobrev** [comment]
@vburgett ,

> @dobromirdobrev she was never a group admin.

I meant event admin, e.g admin of the event "Cookout!".

> We will try to reproduce the issue on dev and report back.

Thank you!

**Comment by vburgett** [comment]
@dobromirdobrev she was also never an event admin for either event.

**Comment by vburgett** [comment]
@dobromirdobrev We tested this on dev and Group-member only events that are starred by Group members do not show up under My Events regardless of where they were created.

The above event names and details are the same. The Group on dev is "Groups Hangout."

**Comment by dobromirdobrev** [comment]
@vburgett ,
This is fixed on dev. Please verify when you have a chance. 

Resolved on the backend via https://github.com/rokwire/calendar-building-block/issues/472

**Comment by vburgett** [comment]
Confirming that this is fixed on dev 6.0.25. We tested group members starring "group-member only" events made via the app, via the admin website, and within a private and public group.  

(Kathryn, this ticket is the same as your ticket #4231.)
