### ISSUE TITLE
[BUG] Group-member only events are showing in "All Events" for group members

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4203]
**Describe the bug**
Group-member only events are displaying under "All Events" for group members

--Two Group-member only events were created:

One was created via the admin website. (Vanessa's Birthday...)
Second was created via the app. (Cookout..)--

**To Reproduce**
Go to '.My Groups.' > Kathryn
Scroll down to 'Events'
Star both events
Toggle to "Home" > Sections
Scroll to "Events"
Click "All Events"
Scroll to look for two created events.

User can only see "Cookout" event in "All Events" (This is the event created from the app)

**Expected behavior**
Group members should NOT be able to see their Group-member only events listed in "All Events"

6.0.19 on prod

Smartphone:
• OS: Android Version 13
• Device: Google Pixel 4a

Resubmitting @acovher2's ticket #4201 to help correct a few details.

![GroupEvent-MemberAllEvents](https://github.com/rokwire/illinois-app/assets/1044905/6a89f71a-273a-41b7-a4a9-7cdf219425f3)

**Comment by acovher2** [comment]
![20240711_145515](https://github.com/rokwire/illinois-app/assets/82892873/92ebe885-226b-4c3a-8c3c-a4b7a5f37aaa)
Retest Passed on Dev 6.0.25

**Comment by vburgett** [comment]
The group-member only events are also not seen on prod under All Events, as expected. v6.0.25
