### ISSUE TITLE
[BUG] No Custom Notification Tap Thru to Event Details Panel  

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4214]
When receiving a custom notification for an upcoming event, the user is unable to tap on the notification and go to the related event details panel, as expected.

- The event "Pet a St. Bernard Puppy" was created via the admin website by me.
- The event was for group members only for the private group "Puppy Testing Group"
- The custom notification was set for this morning 7/8 and the event is 7/12 at 12pm.  
- The custom notification was set for users in the group and anyone who had starred the event.
- There was no tap thru for me as the event admin and the group members.

v6.0.19 prod
Android Pixel 6

![Screenshot_20240708-121447](https://github.com/rokwire/illinois-app/assets/1044905/5ce61d30-1395-42d6-9947-4dc466f866b5)

**Comment by dobromirdobrev** [comment]
Fixed in version 6.0.23 of the Illinois app.

**Comment by vburgett** [comment]
Confirming as updated and working in 6.0.23. Thank you, @dobromirdobrev!
