### ISSUE TITLE
[BUG] Poll and direct message notifications show up under muted when not muted

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4216]
When creating a new poll or a direct message in a group, the appropriate group members receive the notification but only when they "show muted" notifications. The three users testing had local and global group notifications turned on for all group options (posts, events, polls).

I expect to receive a notification for a new poll as unmuted when the notifications for Group Polls is toggled on globally (or locally).

I expect to receive a notification for a new direct message to myself as unmuted as part of the post option being toggled on. Better yet, I expect a "Direct Messages" toggle to display in the Group notification settings locally and globally.

**Comment by dobromirdobrev** [comment]
This is a backend issue - Groups BB [477](https://github.com/rokwire/groups-building-block/issues/477)

**Comment by dobromirdobrev** [comment]
@vburgett , could you please re-test this scenario? The backend issue is resolved and the issue should be fixed. Thanks.

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
These were fixed on the backend. You can verify when you get a chance using dev environment. Thanks.

**Comment by vburgett** [comment]
The notification worked for a direct message in 6.0.27. I can not test notifications with polls due to issue #4232.

**Comment by vburgett** [comment]
As expected, group members with group notifications turned ON _did_ receive a notification for a group poll under the bell icon when notifications were set to "hide muted." Thank you! @dobromirdobrev 
Version 6.0.32 prod
