### ISSUE TITLE
[USABILITY] Remove wallet widget as default widget for new users

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4219]
Now that we have the wallet in the footer navigation, please remove the wallet widget as a default favorite widget for new app users and replace it with "My Groups."

**Comment by mihail-varbanov** [comment]
@vburgett, this is implemented in version 6.0.24. Please note that to test this feature you need to delete your account first because the default favorites content gets initialized only on first app launch on fresh new account.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov! I installed the 6.0.24 prod build on Android and can confirm the update is in place by not signing into the app.
