### ISSUE TITLE
[USABILITY] Add text to Illini ID

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4223]
Per Bill, please add the text "This ID must be presented to university officials upon request." to the Illini ID. See screenshot. 
The text is navy in Proxima Nova Italic 14pt centered.

![Screenshot 2024-07-10 at 4 40 03 PM](https://github.com/rokwire/illinois-app/assets/1044905/86755b70-1414-44f0-9464-80def18b06f8)

**Comment by mihail-varbanov** [comment]
Added in version 6.0.25.

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.25. Thank you, @mihail-varbanov!!
