### ISSUE TITLE
[USABILITY] Match Wallet items in Favorites/Sections to the Wallet in footer

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4224]
Under Sections and the Favorite wallet widget, please update the below Wallet panels to match the new panels in the Wallet accessible from the footer nav.  

**Favorites/Sections > Wallet > panels**
Add Illini Cash
Bus Pass
Illini Cash
Meal Plan

**To reproduce:**
1) Go to Sections > Meal Plan or Favorites > Wallet > Meal Plan
2) See how the Meal Plan panel is different from Wallet (footer)> Meal Plan

![Screenshot 2024-07-10 at 4 40 59 PM](https://github.com/rokwire/illinois-app/assets/1044905/898c8242-7463-481b-a79b-20c2c149a4b1)

**Comment by mihail-varbanov** [comment]
This was implemented in version 6.0.25. The same was done when opening wallet panels from Wallet favorite widget.

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.25. Thank you, @mihail-varbanov!!
