### ISSUE TITLE
[USABILITY] Add Illini Cash to Wallet section from footer

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4225]
From the Wallet in the footer, the dropdown menu has "Add Illini Cash" but it is missing the menu option and panel for "Illini Cash." Please add it the wallet's dropdown menu.

**Comment by mihail-varbanov** [comment]
Added in version 6.0.25

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.25. Thank you, @mihail-varbanov!!
