### ISSUE TITLE
[USABILITY] Update onboarding video and srt files 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4226]
Please replace the onboarding video and srt file for the 6.0 release with the files in [this folder](https://drive.google.com/drive/folders/1y6rdR1_8qniUWXjfyb932KuBc8rAcqCr?usp=sharing). 

This video should continue to display right after "The Smart Campus in Your Pocket" screen and before "Who are you?" during onboarding.

Please note this video needs to continue to go horizontal in landscape mode. Is it possible to move the skip button to not cover the captions in landscape mode?

![Screenshot_20240710-200300](https://github.com/rokwire/illinois-app/assets/1044905/052826b7-39ee-44b3-ae1d-e77bf329febf)

**Comment by dobromirdobrev** [comment]
@vburgett ,
We can easily move the position of the "Skip" button. But the question is where to place it?
One solution that I can think of is to make it smaller and similar to the "CC" button and to place it above it. 

Do you have any suggestions? cc @pmarkhennessy

**Comment by vburgett** [comment]
@dobromirdobrev instead of a button could it just be underlined text that says "Skip"? Perhaps that way it can stay centered and overlap less in landscape mode?

**Comment by vburgett** [comment]
@dobromirdobrev please note the video file is now a new file. 
2024_illinois_app_intro_video_v2 (1080p).mp4

**Comment by dobromirdobrev** [comment]
@vburgett ,
The video (v2) and the cc file are replaced.

I've also changed the "Skip" button to be underlined link button and placed it on the left side when in landscape. I decided to do that because even as link button it was still overlapping in landscape mode. I think now it looks good. 

Please verify it with version 6.0.26 when you have a chance.

**Comment by vburgett** [comment]
Thank you, @dobromirdobrev. The closed caption button now disappears as an option after a few seconds of the video playing. Can the CC option remain visable throughout the video like the "Skip" text?

**Comment by dobromirdobrev** [comment]
@vburgett ,
CC button is always visible now. This is done in version 6.0.28 of the Illinois app.

**Comment by vburgett** [comment]
Confirming that the CC button visibility update is made in 6.0.29. Thank you!
