### ISSUE TITLE
[BUG] "Find A Therapist" is not working under Map

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4236]
1. Tap on Map in the footer
2. Choose "Find a Therapist" from the dropdown menu
3. See no locations pop up

v6.0.25 prod Android pixel 6

![Screenshot_20240712-094053](https://github.com/user-attachments/assets/59379a37-f0fc-41b3-a822-93ae4091744f)

**Comment by acovher2** [comment]
Reproduced this issue in Dev 6.0.25 Android apk on a Google Pixel 4a
Screenshots:
![20240712_100227](https://github.com/user-attachments/assets/8fc66083-c1e9-498e-85e3-3057f252c83c)

![20240712_100233](https://github.com/user-attachments/assets/079fb35e-ab43-4a35-99ee-7b6052831a7f)

**Comment by mihail-varbanov** [comment]
The problem is resolved in Student Guide content in Rokwire cloud service, no source code changes had been applied.

**Comment by mihail-varbanov** [comment]
I created a task in gateway building blocks repo how to avoid situations like this:
https://github.com/rokwire/gateway-building-block/issues/105

**Comment by vburgett** [comment]
Find a Therapist under Map is now working. Thank you!
