### ISSUE TITLE
[BUG] Name pronunciation recording fails when app requests microphone access on Android

### ISSUE THREAD

**Issue by jake-fava** [rokwire/illinois-app#4247]
The first time a user attempts to record their name pronunciation in My Profile, the request for microphone access (image 1) occurs when the user taps on the record button.

After permission is granted, the app says "Recording - Release to stop" (image 2) even though the button isn't being held. 

Is it possible to request microphone permission when the user taps on "Add name pronunciation..."? 

Tested on multiple Android devices
6.0.27 prod

![Screenshot_20240717-110911](https://github.com/user-attachments/assets/e07727ce-6905-464e-90a5-4564ba2ea0e9)
![Screenshot_20240717-110921](https://github.com/user-attachments/assets/11853119-817b-4a94-96b1-e259cfc8ba4d)

cc: @vburgett

**Comment by TodorBachvarov** [comment]
@jake-fava, this was fixed in version 6.0.29.

**Comment by jake-fava** [comment]
Tested on two different Android devices in 6.0.29 - the new ask for permission works perfectly; thank you!
