### ISSUE TITLE
[USABILITY] Settings > Contact Us: Text and Link Update 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4248]
Under Settings > Contact Us, please update "Share Feedback & Ideas" with "Share an Idea"

Update the link for "Share an Idea" and "Partner with Us" to https://go.illinois.edu/AppIdeas 

![Screenshot 2024-07-23 at 4 33 27 PM](https://github.com/user-attachments/assets/b8fc7a19-f1ef-43d0-adca-1bd849b69aad)

**Comment by dobromirdobrev** [comment]
Done in version 6.0.29

**Comment by vburgett** [comment]
Confirming that this update is made in 6.0.29. Thank you!
