### ISSUE TITLE
[BUG] Search can't find events "too far" into the future 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4251]
Searching for an event does not find an event in the app.

1. In 6.0.27 on an iPhone, go to Home > Sections > Events > All Events
2. Search for JCPenny Suit-Up
3. See that there are no matching events
4. Go back to the all event feed with no filters applied
5. Scroll until September 8 at 4pm 
6. See the JCPenny Suit-Up Event 2024

Why does this event not show up via a search? Is there a threshold to searching for an event "too far" into the future? 

This event is a Webtools event. 

![Screenshot 2024-07-23 at 4 50 44 PM](https://github.com/user-attachments/assets/167eaed9-62fc-413f-8d0d-e8e9b90e8ebf)

**Comment by dobromirdobrev** [comment]
@vburgett ,
This is not an issue but a typo. Please note that the name of the event is `JCPenney Suit-Up Event 2024` but you search for `JCPenny Suit-Up` (missed one `e` at the end of `JCPenney`). Since the word is mistaken, the search does not find it :) E.g. all works as expected.

**Comment by vburgett** [comment]
You are correct, @dobromirdobrev. Thank you!
