### ISSUE TITLE
[USABILITY] Spaces and Places: Add New Icon to Styles.json

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4254]
@aidanhenry is working on updating the building detail panels to include "Floor Plans & Amenities" using a new icon.
Please help update the styles.json file to include the below. I am not sure about the correct size. Please see the below screenshot for reference. 

"floorplan": {"src": "0xf279", "type": "fa.icon", "weight": "regular", "color": "fillColorSecondary", "size": 18},

![Screenshot 2024-07-25 at 9 39 51 AM](https://github.com/user-attachments/assets/dc5b3361-7408-443e-a53f-bec40ed27135)

cc: @clint156 @cdukeUX

**Comment by mihail-varbanov** [comment]
Added "Floor Plans & Amenities" detail entry to Building detail panel, available in version 6.0.29.

**Comment by vburgett** [comment]
Thank you, @mihail-varbanov. The functionality won't be ready for this next release. Can "Floor Plans & Amenities" be hidden for now and not display on the building detail panels? 

cc: @clint156 @aidanhenry

**Comment by mihail-varbanov** [comment]
Done in version 6.0.31.

**Comment by vburgett** [comment]
Thank you!
