### ISSUE TITLE
[USABILITY] Add "Approve All" and clean up group member panels 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4268]
Please add an "Approve All" link to the pending members group panel and implement the below related clean-up items. 
  
![Screenshot 2024-08-05 at 3 47 14 PM](https://github.com/user-attachments/assets/a23c72fa-cfdd-4c65-af7c-34e595963c20)

![Screenshot 2024-08-05 at 3 47 23 PM](https://github.com/user-attachments/assets/65146d72-c455-4356-b5b2-475b070602c9)

**Comment by TodorBachvarov** [comment]
Approve All was hooked in version 6.0.32

**Comment by vburgett** [comment]
Thank you, @TodorBachvarov. Can "Approve All" only display under Manage Members > Pending?

**Comment by TodorBachvarov** [comment]
@vburgett, this is done in version 6.0.35

**Comment by vburgett** [comment]
@TodorBachvarov Approve All is not yet working in 6.0.36. 

https://github.com/user-attachments/assets/b2e605f2-9f9e-4679-9644-4406112c2bde

**Comment by TodorBachvarov** [comment]
This should be fixed on BB. https://github.com/rokwire/groups-building-block/issues/507

**Comment by mihail-varbanov** [comment]
@vburgett, this should get fixed in 6.0.42

**Comment by vburgett** [comment]
Confirming that this is fixed in 6.0.43 on dev (Android). Thank you!
