### ISSUE TITLE
[USABILITY] Stakeholder edits: text updates to event filter department names 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4272]
When creating or filtering events in the app, please make the following text updates to the departments under the College/Unit "Applied Health Sciences":

- Change "Ctr Health, Aging, Disability" to "Center on Health, Aging & Disability"
- Change "Ctr Wounded Veterans Higher Ed" to "Chez Veterans Center"
- Change "Disability Res & Educ Svcs" to "Disability Resources & Educ Svcs"
- Move "Disability Resources & Educ Svcs" below "Disability Research Institute"
- Delete "Motorcycle Rider Program"
- Change "Health and Wellness Initiative" to "Health & Wellness Initiative"
- Change "Kinesiology & Community Health" to "Health & Kinesiology"
- Move "Health & Kinesiology" above "Health & Wellness Initiative"

![File (5)](https://github.com/user-attachments/assets/c02bfe1a-c585-4878-8696-0e47c05694a9)

**Comment by mihail-varbanov** [comment]
These had been updated in our Content cloud service so these updates are available right now, nevertheless The Illinois app version.

**Comment by vburgett** [comment]
Confirming this update has been made. Thank you!
