### ISSUE TITLE
[BUG] My Canvas Courses not loading

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4273]
I am receiving the error "Failed to load course. Please try again later" for all Canvas courses.

1. Go to Sections > Academics > My Canvas Courses
2. Tap on any course
3. Get the error message

v6.0.27 
iPhone 13 Pro
17.5.1

![IMG_8870](https://github.com/user-attachments/assets/d5eceb91-c808-421f-8f41-39ead2e5da27)
![IMG_8871](https://github.com/user-attachments/assets/b410cff2-7a00-437c-a9c8-fa32d5c06aa6)

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,

This is fixed. Please, verify when you have a chance. Thanks

**Comment by vburgett** [comment]
This is fixed in 6.0.27 (and 6.0.32). Thank you!
