### ISSUE TITLE
[USABILITY] Confirmation Modal needed after Illinois Assistant "Clear All"

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#4281]
Thanks for the work on #4129! Can we add a confirmation modal after the user taps on "Clear All"? cc: @vburgett 

Please add a pop-up modal after the user taps on "Clear All" in the Illinois Assistant.

**Expected Behavior:**
1. User taps on "Clear All"
2. Confirmation modal pops up with this text: "Are you sure you want to clear your Illinois Assistant history? This action cannot be undone." The options should be "YES" or "Cancel." The UI can be similar to the confirmation modal under Settings > My Browsing History when you toggle off "Display recently viewed app content" (see photo)
3. When the user taps "YES," the current message appears ("Successfully removed all messages" - OK)
4. When the user taps "Cancel," they are returned to the Illinois Assistant panel

![Screenshot_20240808-103440](https://github.com/user-attachments/assets/dc657199-070a-4ea3-a838-e1a54eff9ee5)

Device: [Pixel 7]
OS: [14]

**Comment by mihail-varbanov** [comment]
The prompt was added in version 6.0.33.
