### ISSUE TITLE
[BUG] Sub-events not displaying within super event within a Group

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4283]
Within the university-managed group "New Student Experiences," our stakeholders created and published a super event "Welcome Week 2024" within the group _only_ (not under All Events). Some sub-events are set to publish only in the super-event.  

The admin who published the events, Jim, _can_ see the sub-events under the super event in the app. See below screenshot. Myself and another admin do not. See the second screenshot. One group member also confirmed that they do not see the sub-events as part of the super event.

Everyone in the Group should see sub-events as part of the super event.

This group has 11,632 members so I am marking this issue as "high."

![WW_JimView](https://github.com/user-attachments/assets/d4abfcce-2aea-455e-89d2-ca88b6245716)
![WW_GretchenView](https://github.com/user-attachments/assets/f973a2b0-0caf-4faf-9467-73fc5a5a52f0)

**Comment by pmarkhennessy** [comment]
@vburgett This is a backend issue that is in progress

**Comment by mdryankov** [comment]
@vburgett, @pmarkhennessy, This is а disadvantage of the current platform. In other words the group events are more limited than the All/My events functionality - e.g there is no current support of super, sub events and related filtering capabilities there. The average time to address it is about 2 weeks, the amount of changes will be significant and will be located on Client side, and backend side (both Groups BB & Calendar BB). So, it will be more than just a hot fix. 

The decision to postpone the release and implement the changes or live temporary with the current state and make an additional release is up to you. 

We will wait for confirmation what and how do you want to proceed. 

CC @mihail-varbanov, @petyos @stefanvit

**Comment by mihail-varbanov** [comment]
**Re: University Monday 2024/08/12** / 2024-08-15

For now please hide "There are no events available." for super events. See the attached screenshot, WW_GretchenView.jpg, an example from New Student Programs Welcome Week super event starting August 19 in their 11,000+ member group.

We will fix this properly after this release.

![WW_GretchenView](https://github.com/user-attachments/assets/e86d6716-ab3a-48d0-b773-a540b916878a)

**Comment by mihail-varbanov** [comment]
The hide text status request was implemented in version 6.0.36.

**Comment by vburgett** [comment]
Using the admin website on dev, I created a super event called "Test Super Event" with one sub-event called "Test Sub Event." I published both events to "group members only" to the dev Group "Testing Testing."
The group is set up to allow members to auto-join. Can you join and confirm that you can see the sub-event as part of the super event?

The "Test Sub Event" is set to _only_ display with the super event on the admin website. The "Test Sub Event" is displaying on its own in the group when it should not. 
![Screenshot 2024-09-13 at 4 37 13 PM](https://github.com/user-attachments/assets/0ca4a2ee-913d-47d8-94d8-1d29a5ee7fdc)
![Screenshot_20240913-163738](https://github.com/user-attachments/assets/64b984be-94e0-49e8-9c94-dfe070ecbe2d)

**Comment by vburgett** [comment]
OK I will test on the dev build once the dev admin website is available. (I can't sign in right now.) 

A super event I made previously is displaying the super event and sub-event as expected to group members.

**Comment by dobromirdobrev** [comment]
@vburgett ,
The sign in problem in the Admin web on dev is fixed now. You can test when you get a chance.

**Comment by vburgett** [comment]
Confirming that this issue is fixed on 6.0.48 on prod.
