### ISSUE TITLE
[BUG] Assistant Clear All messages failed on initial attempts, then suddenly worked and Question Quota for the day displays "0" [Android ver. 6.0.32 prod]

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#4284]
**Describe the bug**
In the Assistant, when "Clear All" is selected error message "Failed to clear all messages" displays during several attempts [Fig. 1.]. Eventually, messages are cleared and confirmation message "Successfully removed all messages" displays. However, the Number of Questions Remaining for the day goes to "0". Please note that I hadn't asked any questions.

**To Reproduce**
1. Select "Assistant" from bottom menu
2. Submit a few questions
3. Select "Clear All"
4. See error message similar to Fig. 1 below
5. Attempt a few more attempts to "Clear All"
6. See message similar to Fig 2 below (which confirms "successful clearing of all messages" AND Number of Questions Remaining goes to 0.

**Expected behavior**
1. I expect to see a confirmation pop-up that all my questions will be cleared, and then a verification that all messages have been successfully cleared
2. I expect the number of questions remaining to be accurate, based on the number of questions I've posed. During the test, I had not posed any questions.

**Screenshots**
_Fig. 1. Assistant Failed to Clear All Messages_ 
![Assistant_FailedtoClearAllMessages](https://github.com/user-attachments/assets/abe21699-95e1-4b7c-a557-10483a813fb6)

_Fig. 2. Assistant Successfully Removed All Messages, with Zero Remaining Question Quota_ 
![Assistant_ClearedAllMessages_ZeroQuestions](https://github.com/user-attachments/assets/47c6d7c9-d277-4d07-9d5d-1bb639d3ba2c)

**Smartphone (please complete the following information):**
 - Device: Android
 - Version: 6.0.32 prod

**Comment by TodorBachvarov** [comment]
I was not able to reproduce this issue. @knguyenjahiel could you retest with version 6.0.35

**Comment by knguyenjahiel** [comment]
Confirming both issues have been fixed. Thank you!
