### ISSUE TITLE
Notification Toggles in Settings Are Not Responding

### ISSUE THREAD

**Issue by alex-pixo** [rokwire/illinois-app#43]
### Describe the bug
Notification Toggles are not responding in settings page

### To Reproduce

Go to 'Settings'
Click on 'Event Reminders' or 'Athletics updates' or 'Dining Specials'

### Expected behavior
Toggles should turn on or off by tapping toggle icon

### Screenshots

<img width="328" alt="Screen Shot 2020-09-02 at 9 19 04 AM" src="https://user-images.githubusercontent.com/60981190/91999539-208c3b00-ed02-11ea-990d-05e7a356be6d.png">

### Smartphone
Device: iPhone XS
OS: iOS 13.6.1
Illinois App v2.2.13

**Comment by dobromirdobrev** [comment]
Cannot be reproduced. 
In latest version of the app (2.2.17 as per now) the design is changed. These notification toggles are accessed from:
`Settings -> Privacy Center -> Notification Preferences.`
When tapped, each of them changes its state.

@alex-pixo , could you please re-test this issue with the latest version and check if it's reproducible? 
Thanks

**Comment by alex-pixo** [comment]
I retested toggles found here:
Settings -> Privacy Center -> Notification Preferences in version 2.3.4 and they are still unresponsive when toggled. 

I notice that when you tap them there is no animation to toggle so it looks like nothing is happening. However, if you go back a page and return, the toggle is changed.

**Comment by knguyenjahiel** [comment]
Closing: This issue was from 9/2/2020 and pertained to v2.2.13. It is no longer relevant to v4.3
