### ISSUE TITLE
[BUG] Users cannot zoom in on any of the map views in 6.0.36 on an iPhone

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#4306]
**Describe the bug**
Users cannot Zoom in /Zoom out the Map view screen on an **iPhone**

**To Reproduce**
1. Install the app version 6.0.36
2. Navigate to any of the Map screens and Zoom 

Actions
Users cannot Zoom in /Zoom out the Map view screen. 

**Expected behavior**
Users should be able to Zoom the Map screen successfully

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone]
 - Version [e.g. 6.0.36]

**Comment by mihail-varbanov** [comment]
Good catch, @Priyaravi8! This problem persisted since Feb 20, 2024 and we made a couple of releases since then: 5.1 and 6.0. This should be fixed now. The fix is available in 6.0.37 and 6.1.7.

**Comment by Priyaravi8** [comment]
Retested this issue, and it's fixed in version 6.0.37.
