### ISSUE TITLE
[BUG] Bus Stop is failed to display

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#4307]
**Describe the bug**
App failed to display the Bus stop

**To Reproduce**
1. Install the app
2. Navigate to the MTD Buses section
3. Tap on All Bus stop

**Actual Results**
App results: "Failed to load bus stop."

**Expected behavior**
App should load the Bus stop without a failure message

**Screenshots**
![Bus stop](https://github.com/user-attachments/assets/0f0ba82a-7898-4521-a25c-1c18e1c1d3d0)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone and Android]
 - Version [e.g. 6.0.36]

**Comment by mihail-varbanov** [comment]
Currently I am unable to recreate this issue neither on production, nor on dev. The application displays this message when the HTTP request to the Gateway BB API fails for some reason. I would suppose that this was some temporary malfunction of Gateway BB. Please try again, and if you continue to get this error message please provide a recreation scenario, that includes details for your device, platform, environment, precise steps.

![Screenshot 2024-08-22 at 8 55 03 AM](https://github.com/user-attachments/assets/0b84fbd3-92ea-4822-9e7a-587b6ba62af5)

**Comment by Priyaravi8** [comment]
This issue is not reproduced.

**Comment by Priyaravi8** [comment]
I reproduce this issue in version 6.0.37

**Comment by nelshopp** [comment]
I also am having this issue with version 6.0.37 on the map as well as the MTD Bus Stops section.

**Comment by Priyaravi8** [comment]
![Bus stop](https://github.com/user-attachments/assets/a4355411-a7ca-484a-8baf-b321e2f92dc5)

**Comment by vburgett** [comment]
On 5.037 on an **Android**, I have an issue with seeing :
- Map > Bus Stops (there are no bus stop markers until I zoom in and out)

I have no issues with:
- Sections > MTD Buses > All Bus Stops
- Sections > MTD Buses > My Bus Stops
- Sections > MTD Buses > My Destinations

On 5.037 on an **iPhone**, I have no issues with seeing any of the below screens:
- Map > Bus Stops
- Sections > MTD Buses > All Bus Stops
- Sections > MTD Buses > My Bus Stops
- Sections > MTD Buses > My Destinations

**Comment by Priyaravi8** [comment]
This issue is fixed in version 6.0.38.
