### ISSUE TITLE
[BUG] Laundry appliances not showing correct status

### ISSUE THREAD

**Issue by clint156** [rokwire/illinois-app#4311]
**Describe the bug**
Washers and dyers should show as either available, in use, out of service or unknown. Up until now the gateway building block has only returned the first 3 statuses. The building block will be changed to return unknown as a status as well.

**To Reproduce**
Go to the laundry feature and pick a laundry room. Right now, either of the bousfield rooms shows the issue. According to CSC Laundryview, most of the appliances should be unknown but we are showing out of service.  This is subject to change as machine statuses change. 

**Expected behavior**
If the appliance status is returned to the app as "unknown", the app should display "Unknown" as the status.  An issue for the gateway building block has also been opened so that the building block will start returning the unknown status.

Relevant Code lines: 345-359 in Laundryroomdetailpanel.dart

**Comment by mihail-varbanov** [comment]
The new status is acknowledged in Illinois client app versions 6.0.37 & 6.1.8.

**Comment by clint156** [comment]
I just pushed a version of the gateway building block to dev that fixes the building block part of this issue as well. The building block now sends back the "unknown" status when appropriate

**Comment by mihail-varbanov** [comment]
The new "unknown" status is acknowledged properly by the client app.
