### ISSUE TITLE
[USABILITY] Update "TODO Reminder" to "To-Do List Reminder"

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4319]
Update the to-do list reminder text from "TODO Reminder" to "To-Do List Reminder"

![IMG_9170](https://github.com/user-attachments/assets/72709110-7b3e-4d73-a2c0-c191b6e6be7d)

**Comment by mihail-varbanov** [comment]
This issue is a duplicate of #3173, that depends on rokwire/wellness-building-block#35.

**Comment by mihail-varbanov** [comment]
@vburgett, rokwire/wellness-building-block#35 was resolved in Wellness BB 1.5.1. It will be deployed on dev today so you can test it.

**Comment by vburgett** [comment]
Confirmed as updated. Thank you!
