### ISSUE TITLE
[BUG] Phone notifications are being sent even when they should be muted

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#4323]
Sometime in the past few days, I suddenly started getting phone notifications (Android) for posts in a group that I have turned off.  Over the weekend, I turned them on and back off again to see if I could get it to reset. I got another notification today.

The Group is "Illini Squirrel Enthusiasts"
An image of my phone notification today.
![image](https://github.com/user-attachments/assets/c01f5d42-9472-4cab-94cd-414ca795a1cd)

In the app, the same notification was in "muted notifications"

An image showing that I have custom notifications turned on for this group:
![image](https://github.com/user-attachments/assets/b8313e55-9a39-42ee-8a38-8456279eab93)

@vburgett

**Comment by vburgett** [comment]
I can confirm that I also have this issue (iPhone):

1. My global settings for groups were all on.
2. I received a notification, as expected, from the squirrel group about a new post "I am itchy."
3. I turned my notifications for the squirrel group off at the group level. 
4.0 There were then two new posts to the squirrel Group. 
4.1 As expected under the bell icon in the app, I see "I am itchy" as my last Unread Notification and then later under "All Notifications." I have "Hide Muted" selected.
4.2 On my device's Lock Screen, push notifications for the most recent two squirrel group posts display and tap thru to the related post. I don't expect to see these two recent posts on my Lock Screen.  

![image](https://github.com/user-attachments/assets/be846d13-1aa9-4df5-9ade-2e9e3e539557)![image](https://github.com/user-attachments/assets/a06766d8-c94a-43f0-9242-01660a6b00ab)

**Comment by TodorBachvarov** [comment]
This should be checked on the backend. I've created this issue https://github.com/rokwire/groups-building-block/issues/508

**Comment by vburgett** [comment]
Just confirming that this is still an issue as of 10:30am CT on Friday, September 6.

**Comment by vburgett** [comment]
Confirming that this is fixed. I did not get notified via my phone for the latest post in a muted group, as expected. 
 ![image](https://github.com/user-attachments/assets/3e29ba15-7325-4f6c-bcf1-94cf5aa267c5)
![image](https://github.com/user-attachments/assets/8fe65bd6-032a-4100-a40e-4d113077d18a)
