### ISSUE TITLE
[BUG] Radio Stations Always Streaming

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4326]
Our colleagues at Illinois Public Media have let us know that their three radio stations (see screenshot) are showing up in their logs as streaming the entire time a user is in the app, even with no interactions with the radio stations. These three connections streaming outside of listening time is causing issues on their end (maintenance and skewed logs). Can the radio stations only connect when the user plays the radio station?

![image](https://github.com/user-attachments/assets/a686154c-9aa3-4e0e-8d60-058f22405477)

**Comment by mihail-varbanov** [comment]
This should be resolved in version 6.0.39.

**Comment by vburgett** [comment]
Confirming that this issue is resolved on prod with the release of 6.0.48. Thank you!
