### ISSUE TITLE
[USABILITY] Text and UI updates to the Skills Self-Evaluation 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4331]
Please make the below updates to the Skills Self-Evaluation under Home/Sections > Academics > Skills Self-Evaluation

1) Update "Skills Self-Evaluation" to "Skills Self-Evaluation & Career Explorer"
- under Home/Sections > Academics 
- in the Academics dropdown menu
- in the header on the Skills Self-Evaluation panel
- under Settings > My Assessments
- can the name by the back arrow truncate and use the ellipsis?  (" < Skills Self-Evaluation & . . . ")

2) Update "5 minutes" to "10 minutes" on the Skills Self-Evaluation panel

3) change the background color for each "result block" to white under 
- Results (Self-Eval ellipsis menu > View past results) and 
- Career Explorer (Self-Eval ellipsis menu > View past results > Career Explorer)  
(see screenshots and starred "result blocks")

![IMG_9313](https://github.com/user-attachments/assets/d80fddc7-794e-47f1-b4d8-dbc9c9d836f0)
![IMG_9314](https://github.com/user-attachments/assets/a57cc422-1937-41f6-ae2f-e074fc8e162e)

**Comment by TodorBachvarov** [comment]
This was updated in version 6.0.40

**Comment by vburgett** [comment]
Confirming these updates as complete in 6.0.40. Thank you, @TodorBachvarov. Apologies on missing this one last color edit. Please change the background color for the Career Explorer panel to match the background of the Results panel. I believe the color is F5F5F5.

**Comment by dobromirdobrev** [comment]
Hi @vburgett ,
The latest request for changing color is done in version 6.0.41.

**Comment by vburgett** [comment]
Confirming as complete. Thank you, @dobromirdobrev!
