### ISSUE TITLE
[USABILITY] Add "Share this feature" option for Skills Self-Evaluation

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4332]
Please add a share option to the Skill Self-Evaluation panel. 

![Screenshot 2024-09-03 at 12 51 50 PM](https://github.com/user-attachments/assets/9b8c6753-f181-4952-8a2d-ac1c3d220960)

**Comment by dobromirdobrev** [comment]
This is done in version 6.0.41

**Comment by vburgett** [comment]
Complete in 6.0.43. Thank you!
