### ISSUE TITLE
[FEATURE] Radio Stations Analytics

### ISSUE THREAD

**Issue by cschwin2** [rokwire/illinois-app#4335]
Hello,

We would like to request some additional information for user actions associated with the Radio Stations. The screenshot below shows an example log of when a user tapped either Play or Pause.

![Screenshot 2024-09-04 at 2 16 47 PM](https://github.com/user-attachments/assets/d83ddef8-112d-45dd-9123-e6656b70f7cd)

Two requests we have:

1. Can we please see which radio station the log is associated with?
2. Is there a way to distinguish between whether the user pressed "Play" vs. "Pause"? Right now, either action results in a general "Play/Pause" value.

Thank you!

Cameron
@vburgett

**Comment by mihail-varbanov** [comment]
This was implemented in 6.0.46. I added "radio_station" attribute with radio station name. Play/Pause is separated as well. Here is a sample log of showing ration stations popular, play, pause and close:
```
{"name":"select","target":"Radio Station: WILL Classical & More","source":null,"page":"HomePanel","feature":"Home"}
{"name":"page","page_name":"RadioPopupWidget","page_feature":"Radio Stations","previous_page_name":"HomePanel","previous_page_feature":"Home","radio_station":"WILL Classical & More","page":"RadioPopupWidget","feature":"Radio Stations"}
{"name":"select","target":"Play","source":"RadioPopupWidget","radio_station":"WILL Classical & More","page":"RadioPopupWidget","feature":"Radio Stations"}
{"name":"select","target":"Pause","source":"RadioPopupWidget","radio_station":"WILL Classical & More","page":"RadioPopupWidget","feature":"Radio Stations"}
{"name":"select","target":"Close","source":"RadioPopupWidget","radio_station":"WILL Classical & More","page":"RadioPopupWidget","feature":"Radio Stations"}
{"name":"page","page_name":"HomePanel","page_feature":"Home","previous_page_name":"RadioPopupWidget","previous_page_feature":"Radio Stations","page":"HomePanel","feature":"Home"}
```
