### ISSUE TITLE
[USABILITY] Hide completion number under My Canvas Courses

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4346]
Please hide the completion number (or N/A) under Academics > My Canvas Courses. (Students have worried that this number is their grade for the course.)
Please update the font and add the chevron right icon.

![Screenshot 2024-09-11 at 5 08 52 PM](https://github.com/user-attachments/assets/4bddd276-69b9-444c-afda-76283d6b6091)

**Comment by dobromirdobrev** [comment]
Done in version 6.0.43

**Comment by vburgett** [comment]
@dobromirdobrev can the cards in the My Canvas Courses favorites widget be half the height they are now?
![Screenshot_20240912-182418.png](https://github.com/user-attachments/assets/445244e6-f58c-4d69-a57f-8ce9186cb9e4)

**Comment by dobromirdobrev** [comment]
> @dobromirdobrev can the cards in the My Canvas Courses favorites widget be half the height they are now? 

This is done in version 6.0.44

**Comment by vburgett** [comment]
Looks and works great in 6.0.44 on dev. Thank you!
