### ISSUE TITLE
[USABILITY] Hide Healthy Illini Podcast 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4347]
Please hide "Healthy Illini Podcast" under:
1. Home > Sections > Wellness
2. Wellness dropdown menu

(The Healthy Illini Podcast is already listed under Wellness Resources.)

**Comment by dobromirdobrev** [comment]
Done in version 6.0.43

**Comment by vburgett** [comment]
Complete in 6.0.43. Thank you!
