### ISSUE TITLE
[ACCESSIBILITY] Inaccessible text style within Big 10 Athletics > Teams > Coaching Staff

### ISSUE THREAD

**Issue by nataliehelregel** [rokwire/illinois-app#4358]
**Describe the issue**
Text style for the header text "Coaching Staff" is a bold white over a light grey- making the text difficult to read. 

**Steps to reproduce the behavior:**
1. Open the app and navigate to "Sections"
2. Tap on Big 10 Athletics
3. Tap "Teams" under Big 10 Athletics
4. Select any of the sports/teams listed - for example "Women's Basketball"
5. Scroll all the way down to the button of the screen to view "Coaching Staff" header text that is white on a grey background.

**Expected behavior**
"Coaching Staff" text style should match the "Team Roster" text style. The "Team Roster" text style is the section above Coaching Staff shown in the screenshot provided.

**Screenshots**
![IMG_9130](https://github.com/user-attachments/assets/c1a85d98-0c91-4b9d-bfb1-4f0e15c3542c)

@vburgett

**Comment by TodorBachvarov** [comment]
This was fixed in version 6.0.45
