### ISSUE TITLE
[USABILITY] Incorrect Navy Blue Diagonal Header Blocks

### ISSUE THREAD

**Issue by nataliehelregel** [rokwire/illinois-app#4359]
Describe the usability issue
Incorrect blue header blocks create a disorganized screen. 

To Reproduce
1. Open the app and navigate to "Sections"
2. Tap on Big 10 Athletics
3. Tap "Teams" under Big 10 Athletics
4. Select any of the sports/teams listed - for example "Women's Basketball"
5. Scroll to "Schedule" - the first card should be higher/overlapping with the blue diagonal block. 
Current design shown in Screenshot_1
Expected design mocked up in Screenshot_2
6. Scroll to "News" - the News banner and the diagonal are not lined up. 
Current design shown in Screenshot_3
Expected design mocked up in Screenshot_4

Screenshots
![Screenshot_1](https://github.com/user-attachments/assets/f3f68d64-560e-4411-bfb2-f1ec03d60409)
![Screenshot_2](https://github.com/user-attachments/assets/2b648553-8f5b-4809-b84e-fcf704ddeb1c)
![Screenshot_3](https://github.com/user-attachments/assets/3ce2982f-3ce0-41e3-8477-59fb1d5cb099)
![Screenshot_4](https://github.com/user-attachments/assets/b56b7832-5fe4-459d-bc99-88dc01fc59bf)

@vburgett

**Comment by TodorBachvarov** [comment]
This should be fixed in version 6.0.45
