### ISSUE TITLE
[USABILITY] Text Edit: "My Destinations" to "My Locations"

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#4361]
In every place that "My Destinations" is referenced, please update to the text to "My Locations." 

NOTE: This relates to any/all map or bus stop screens currently using the word "destinations," such as:
Map > My Destinations (dropdown menu)
MTD Buses > My Destinations (sections menu)
MTD Buses > My Destinations (header on top bar after tapping on it)

Also, on the pop-up for Map > My Destinations, the text should be updated to: "Select a location on the map and tap the star to save it as a favorite." Please keep the "Don't show me this again." with radio button. [The current text is "Please tap a location on the map that will be your destination. Tap the star to save the destination as a favorite."]

cc: @vburgett 

Device: Pixel 7
OS: Android 14
Illinois app 6.0.43

**Comment by mihail-varbanov** [comment]
Resolved in 6.0.45
