### ISSUE TITLE
[USABILITY] Updated Text for Sharing Screens

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#4362]
Please update the text for all screens featuring a QR code and share link. 

CURRENT: "Invite others to view this [feature/event/group/set of filtered events] by sharing a link or the QR code after saving it to your photo library."

PROPOSED:
The new text should read, "Want to invite other Illinois app users to view this [feature/event/group/set of filtered events]? Use one of the sharing options below." See attached screenshot for mockup.

NOTE: This "feature" should be the default option for all screens unless otherwise specified. In some cases, the text can be customized so that "this feature" is replaced by other text such as "this event," "this group," or "this set of filtered events." Please see below for these specific cases.

**Use Default Text:** "Want to invite other Illinois app users to view this feature? Use one of the sharing options below."
- Skills Self-Evaluation & Career Explorer
- SafeWalks (coming soon)

**Specific Cases - Use customized text:**
- [From a group detail screen]: **Share this group** > [NEW TEXT]: "Want to invite other Illinois app users to view this group? Use one of the sharing options below."
- [From an event detail screen]: **Share this event** > [NEW TEXT]: "Want to invite other Illinois app users to view this event? Use one of the sharing options below."
- [From an event feed]: **Share this event set** > [NEW TEXT]: "Want to invite other Illinois app users to view this set of filtered events? Use one of the sharing options below."

cc: @vburgett 

![Frame 2](https://github.com/user-attachments/assets/709bdc4f-1ed0-4c13-9b16-a38ac8608b6b)

**Comment by mihail-varbanov** [comment]
Resolved in version 6.0.46.
