### ISSUE TITLE
[USABILITY] Text edit to Wellness Resources

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4375]
- Under **Wellness > Resources**, please update the text "Student Assistance Center" to "Connie Frank CARE Center." 
- The link should be to https://odos.illinois.edu/community-of-care/CAREcenter 
- To keep the list in alphabetical order, please move "Connie Frank CARE Center" to be listed after "After Hours Support."

![Screenshot_20240917-205814](https://github.com/user-attachments/assets/c34558d7-1c94-4fd8-b846-bb2874359e03)

**Comment by mihail-varbanov** [comment]
@vburgett, this was done in our content service on dev/test/prod. This does not affect the client app, i.e. it is available right now for all client app versions.

**Comment by vburgett** [comment]
Confirmed as updated. Thank you!
