### ISSUE TITLE
[USABILITY] Line stars and icon up with text under Wellness Resources

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4376]
Go to **Wellness > Resources**.
See how the star and chevron icon no longer line up with text when they should.

(If it helps to address this issue, please make the alphabetical list starting with "24-Hour Crisis Resources" match the font weight and size of the resource cards under "Mental Health Resources." One example of the font weight and size to match is "Anxiety Fact Sheet.")  

![Screenshot_20240917-205814 (1)](https://github.com/user-attachments/assets/a1e03a33-a0b4-4962-870f-9365164e6022)

**Comment by TodorBachvarov** [comment]
This should be fixed in version 6.0.47

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.48 on dev. Thank you!
