### ISSUE TITLE
[USABILITY] Campus building image overlay

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4378]
Under Map > Campus Buildings, tap on any _single_ location marker. See how the image does not have the orange slash overlay like images do in similar panels like events and groups. 

Please add the orange overlay to images on the map building detail panels. 

![image](https://github.com/user-attachments/assets/c44ec100-0035-4026-a117-a33429e4d763)

![image](https://github.com/user-attachments/assets/3a3aed78-6cb4-4742-8050-03efb88ab05e)

**Comment by mihail-varbanov** [comment]
Resolved in 6.0.47.

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.48 on dev. Thank you!
