### ISSUE TITLE
[USABILITY] Text edit to MyMcKinley Appointments

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4380]
1. Go to Sections > Wellness > MyMcKinley Appointments
2. Update the text "Visit MyMcKinley.illinois.edu . . . " to "View a full history of past appointments at MyMcKinley.illinois.edu."
3. Match the text size and color to the text "Don't Display My Appointments"  (see screenshot) 

![Screenshot 2024-09-18 at 8 51 10 PM](https://github.com/user-attachments/assets/116fef08-edfc-4d1b-bf7d-ba30bce6db9f)

**Comment by mihail-varbanov** [comment]
Resolved in 6.0.47.

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.48 on dev. Thank you!
