### ISSUE TITLE
[USABILITY] Update search "clear" icon

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4384]
Throughout the app where there is a search option, please replace the "close window" icon (circle around the x) with the "clear" icon (just the x). The correct "clear" icon is currently used in the app under Section > Events > All Events to clear filters.

**Current**
![Screenshot 2024-09-19 at 12 00 37 PM](https://github.com/user-attachments/assets/af048743-8228-43a5-90af-fd2b870d4345)

**Requested**
![Screenshot 2024-09-19 at 12 00 28 PM](https://github.com/user-attachments/assets/07583822-a95b-4115-99cd-97041946ee41)

**Events Example**
![Screenshot 2024-09-19 at 12 00 56 PM](https://github.com/user-attachments/assets/e6002e75-43bc-4cff-b5dd-2532f8508842)

**Comment by mihail-varbanov** [comment]
Resolved in version 6.0.48.

**Comment by vburgett** [comment]
Confirmed as updated in 6.0.48 on dev. Thank you!
