### ISSUE TITLE
[USABILITY] update purple backgrounds to white

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4385]
1) Go to Sections > Wellness > Illinois Health Screener
2) Tap "Take the Screener" button 
3) See the purple backgrounds for  the answers to each question  

Please change all instances of purple to white in the health screener and any other known locations in the app. 

![image](https://github.com/user-attachments/assets/9b757890-cd27-4fa2-b132-ce4eeb6aa4a9)

**Comment by TodorBachvarov** [comment]
@vburgett the issue from the screenshot should be fixed in version 6.0.49. I've also fixed few more places with this issue. Please let me know if you observe it somewhere else because there is no general solution and we have to find and fix each widget/card one by one.

**Comment by vburgett** [comment]
Confirming as complete in 6.1.13. Thank you!
