### ISSUE TITLE
[USABILITY] Skills Self-Evaluation Pop-Up Text Update

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4391]
1. Go to Sections > Academics > Skills Self-Evaluation and Career Explorer
2. At the bottom of the panel, see the text "Your results will be saved for you to compare with future results."
3. Underline this text to match the underlining style used for "Don't Save My Results" below it
4. Tap on the text
5. See the pop-up window
6. Update the pop-up window text to add the words "personally identifiable" so it reads:
"Your results will be saved for you to compare with future results.
No personally identifiable data from this assessment . . . "

![IMG_9810](https://github.com/user-attachments/assets/d24bfb09-92ea-4f36-866a-668ee6b4520f)
![IMG_9811](https://github.com/user-attachments/assets/a1f45aee-1e16-4556-886a-c68cffd06ceb)

**Comment by mihail-varbanov** [comment]
This was done in support branch (version 6.0.49) and main development branch (version 6.1.9).

**Comment by vburgett** [comment]
Confirming as complete in 6.1.13. Thank you!
