### ISSUE TITLE
[BUG] Fix Navy Diagonal Backgrounds for It's Game Day 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4394]
The same issue as #4359 exists under Sections > Big 10 Athletics > It's Game Day! Please fix the diagonal navy backgrounds for all sports that are part of the "It's Game Day" section and favorite widget.  

6.0.48 prod

![IMG_0003](https://github.com/user-attachments/assets/52b8dedb-98fe-4cb1-ab6b-2d3e07456583)

**Comment by dobromirdobrev** [comment]
@vburgett ,

I don't quite understand what the actual result should be.

Could you please explain how this view should look like?

For example, should we stretch the figure that is inside the red rectangle?
<img width="419" alt="Screenshot 2024-10-01 at 15 49 45" src="https://github.com/user-attachments/assets/d1a45b6d-50e8-494e-87b1-dd4fd93cded8">

**Comment by vburgett** [comment]
@dobromirdobrev the diagonal line should cover the width of the app. I am not sure how that is done—stretching the image or another way. It should match the treatment of the below screenshot. 
![IMG_0005](https://github.com/user-attachments/assets/be0febf3-dd4f-48e0-8cb6-577cab23b70a)

**Comment by TodorBachvarov** [comment]
Hi @vburgett, This should be fixed in version 6.1.17

**Comment by vburgett** [comment]
Confirmed as fixed in 6.1.17. Thank you!
