### ISSUE TITLE
[BUG] Events displaying registration text without any registration

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4395]
- Go to Sections > Events > All Events
- Go to various events and see how the text "Registration is available for this event." displays on the event-specific panel when no registration is available. 
- Example events include:
- UIPD therapy dogs visit Beckman
- MRSEC/MRL Spanish Conversation Group

I don't expect to see this text unless there is in-app or external registration set.

6.0.48 prod

**Comment by dobromirdobrev** [comment]
@vburgett ,
This is fixed in both dev and prod. You can verify when you have a chance

**Comment by vburgett** [comment]
Confirming as complete. Thank you!
