### ISSUE TITLE
[FEATURE] Add "Share This Location" to campus buildings 

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4396]
Please add the option to "Share This Location" on building-specific panels accessed via Map > Campus Buildings.

![Screenshot 2024-10-01 at 11 32 35 AM](https://github.com/user-attachments/assets/13e32156-3cbd-45af-8b50-bfc84d9b66c9)

**Comment by mihail-varbanov** [comment]
This was implemented in 6.0.49.

**Comment by vburgett** [comment]
Confirming as complete in 6.1.13. Thank you!
