### ISSUE TITLE
[USABILITY] Text update to event panels

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4397]
For consistency's sake, please update "Share this event" to "Share This Event" on all event-specific panels under Events or within a Group. 

![File (10)](https://github.com/user-attachments/assets/d94b230a-1601-4876-8acf-5da8568e040a)

**Comment by TodorBachvarov** [comment]
Button title was updated in version 6.0.49

**Comment by vburgett** [comment]
Confirming as complete in 6.1.13. Thank you!
