### ISSUE TITLE
Change Dining Tile Color

### ISSUE THREAD

**Issue by alex-pixo** [rokwire/illinois-app#44]
**Describe the bug**
Dining tile on Browse page is the wrong color

**To Reproduce**
1. Go to 'Browse'
2. See error

**Expected behavior**
'Dining' tile should be yellow

Please refer to zeplin file: https://zpl.io/V03mKEK

**Screenshots**

![IMG_2015](https://user-images.githubusercontent.com/60981190/92003311-7ebb1d00-ed06-11ea-9c70-cbfc0e69e327.PNG)

**Smartphone (please complete the following information):**
Device: iPhone XS
OS: iOS 13.6.1
Illinois App v2.2.13

**Comment by TodorBachvarov** [comment]
Fixed.

**Comment by knguyenjahiel** [comment]
Closing: This issue is from 9/2/2020 for v2.2.13. It is no longer relevant to v4.3
