### ISSUE TITLE
[FEATURE] InfoSwap (My Info & Illinois Connections)

### ISSUE THREAD

**Issue by nataliehelregel** [rokwire/illinois-app#4402]
Please see the attached PDF for the InfoSwap feature request. 
[InfoSwap_Feature.pdf](https://github.com/user-attachments/files/17263930/InfoSwap_Feature.pdf)
cc: @vburgett 

Google Drive Links for additional exported materials
[Navy Block I](https://drive.google.com/drive/folders/1kPMwBIE_o7E65MhiAqWxxz01kZNo21Nk?usp=drive_link)
[Orange Horizontal Footer](https://drive.google.com/drive/folders/12aZM4fezG8O1aY_AGoBXZjYQW1J9lx6G?usp=drive_link)
[Combined Block I and Orange Footer](https://drive.google.com/drive/folders/1cEwE7wLYRc_019vFK2YeTRK3a8QKgGjK?usp=drive_link)

**Comment by mihail-varbanov** [comment]
The most recent spec: [InfoSwapForDev-2024-10-25.pdf](https://github.com/user-attachments/files/17600540/InfoSwapForDev-2024-10-25.pdf)

**Comment by mihail-varbanov** [comment]
**University Monday 2024/12/09** / 2024-12-09

2 Misho, ... At some point you could add a Section for Directory.

**Comment by mihail-varbanov** [comment]
**Re: University Monday 2024/12/09 / 2024-12-12**

2.1 In the Direcotry designs from Vanessa I think the copy for the Directory section is there so no need for Lorum...

2.2 I noticed when making a change and cancelling the change. the word "loose" came up. It should be "lose". Loose me not tight, as in a knot.

2.3 I think Filters was implemented by Ryan, not sure if you hooked this up yet

**Comment by mihail-varbanov** [comment]
The issue is generally completed. The further change and polish requests will go as separate GIT issues.
