### ISSUE TITLE
[USABILITY] Section text updates

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4431]
Under Home > Sections, please update the descriptions to match the below text. 

Academics
Tools for managing your academic life. 

Appointments 
View, schedule, or cancel various appointments. 

Big 10 Athletics
Stay up-to-date with your favorite Illinois teams.
 
Events 
Find in-person and online Illinois events to attend. 

Groups
Discover a new group or start your own. 

Polls
Enter a poll number to vote, or create and share your own poll.

Research at Illinois 
Discover and participate in research projects.

Wallet
Your ID, bus pass, Illini Cash balance, and residence hall meal plan all in one place. 

Wellness 
Resources and tools for maintaining and improving your health and well-being.

**Comment by mihail-varbanov** [comment]
@vburgett, this is resolved in version 6.1.14.

**Comment by vburgett** [comment]
Confirmed as complete in 6.1.14. Thank you!
