### ISSUE TITLE
[FEATURE] Add SafeWalks to the Splunk Logs

### ISSUE THREAD

**Issue by cdukeUX** [rokwire/illinois-app#4447]
Request: Create meaningful logs for Splunk with @cschwin2 to track how many:

1. users tap “Request a SafeWalk” under Home > Sections > Safety
2. users tap on the “Start with a Text” button on the Favorites widget and/or the “Request a SafeWalk” panel

Associated ticket: https://github.com/rokwire/illinois-app/issues/4363
cc: @vburgett @cschwin2

**Comment by mihail-varbanov** [comment]
Hi @cschwin2,

You can identify the events above using the following analytics log entries, available in 6.1.17 after a minor fix: 

1. Users tap “Request a SafeWalk” under Home > Sections > Safety
`{"name":"select","target":"Request a SafeWalk","source":null,"page":"BrowseContentWidget","feature":"Sections"}`

2. Users tap on the “Start with a Text” button on the Favorites widget
`{"name":"select","target":"Start with a Text","source":null,"page":"HomeFavoritesContentWidget","feature":"Safety"}`

3. Users tap on the “Start with a Text” button on the“Request a SafeWalk” panel
`{"name":"select","target":"Start with a Text","source":null,"page":"SafetyHomePanel","feature":"Safety"}`

Let me know please if you need anything else.

**Comment by cschwin2** [comment]
Thank you very much, @mihail-varbanov!

**Comment by mihail-varbanov** [comment]
OK, then I am closing this issue, and if something additional is needed we can reopen it, or create a new issue.
