### ISSUE TITLE
[USABILITY] Stakeholder Text Edit under Events

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4449]
When creating an event in the app or the admin website for the unit Student Affairs, please make the below edits to Event Attributes > Department: 

-change Minority Student Affairs to The Jeffries Center

-move The Jeffries Center to be above McKinley Health Center 

-Change Division of Campus Recreation to Campus Recreation

-replace Campus Mail with Campus Recreation

-delete Aux Health/WB Marketing 

![image](https://github.com/user-attachments/assets/116e8d3b-bcd1-442d-968a-758f33b84898)

**Comment by mihail-varbanov** [comment]
@vburgett, these changes were applied in our Content service on dev/prod/test. The update is available right now and it does not depend on app version number.

**Comment by vburgett** [comment]
The updates look great in the Illinois app. The stakeholders are creating events via https://api.rokwire.illinois.edu/admin-web. Can we make this edit there too? @mihail-varbanov

**Comment by vburgett** [comment]
Nevermind, I see Dobromir's admin Git ticket now. Thank you!
