### ISSUE TITLE
[BUG] User unable to post event to group despite being admin

### ISSUE THREAD

**Issue by nelshopp** [rokwire/illinois-app#4453]
**Describe the bug**
User atwumwaa is admin of a private group named Jesus Saves [raises hands emoji] but is unable to post an event to that group.  

Instead of the event posting, they receive this error "Error validating request: error validating permission"

They are able to post a normal post to the group.  

She is at privacy level 5 using the latest version of the app.  
![image](https://github.com/user-attachments/assets/0541ee49-8bd2-4cb1-84ca-631e765b8a01)

Let me know if you need more information.

Tom

**Comment by dobromirdobrev** [comment]
Hi @nelshopp ,
`atwumwaa` (Twumwaa Ansah) didn't have permissions to create an event. Today we granted the needed permissions. 
Now the user has to sign out and sign in again to be able to create an event.

**Comment by nelshopp** [comment]
Thanks, @dobromirdobrev.  It is working for the customer now!
