### ISSUE TITLE
'Delete My Data' Button Wrong Styling

### ISSUE THREAD

**Issue by alex-pixo** [rokwire/illinois-app#45]
**Describe the bug**
When clicking 'Delete my personal data' button in the privacy center, a modal appears to confirm changes. The button options are 'cancel' and 'delete my data'. The 'delete my data' button has the wrong styling.

**To Reproduce**
1. Go to 'browse'
2. Click on 'Privacy Center'
3. Click on 'Personal Information'
4. Click on ''Delete my personal data'
5. Modal confirmation should appear with incorrect button styling

**Expected behavior**
'Delete my data' button should be dark orange with white text.

**Screenshots**
**Current**:
![IMG_2016](https://user-images.githubusercontent.com/60981190/92004917-6fd56a00-ed08-11ea-9ae5-454a72ccef4b.PNG)

**Should appear like this:**
![Screen Shot 2020-09-02 at 10 38 50 AM](https://user-images.githubusercontent.com/60981190/92004966-82e83a00-ed08-11ea-9de4-ec995ce6c032.png)

**Smartphone (please complete the following information):**
Device: iPhone XS
OS: iOS 13.6.1
Illinois App v2.2.13

**Comment by dobromirdobrev** [comment]
@alex-pixo , the button becomes dark orange with white text when it gets available, e.g. when at least one option is selected.

**Comment by knguyenjahiel** [comment]
Closing: item associated with ver. v2.2.13 and no longer relevant. Individual no longer working with initiative
