### ISSUE TITLE
[FEATURE]  Make Illini Cash features possible to hide/show without an app release

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#4509]
The Illini Cash Program is likely going to be completely retired. I'd like to make the features possible to hide without an app release so that we can respond to the timing of the retirement.  These features should be possible to hide separately from each other, without an app release:
1)  the option to add Illini Cash
2) the display of the Illini Cash card in the wallet

@clint156 @vburgett

**Comment by kpecknold** [comment]
They may remove the ability to add Illini Cash sometime in May and retire the wallet display in summer/fall of 2025.

**Comment by mihail-varbanov** [comment]
We can do this for the existing (already released) versions but I added explicit flags in app config to control this behavior since version 6.1.26, that will make it much easier when the time comes.
