### ISSUE TITLE
[BUG] Cafe Credits to Dining Dollars - missed one spot

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#453]
Still displaying Cafe Credits

**To Reproduce**
Go to Wallet
Next to "Meal Plan", tap "View"
See 3rd blue title bar still says " Cafe Credit History"
Should say "Dining Dollars History"

![Cafe Credits to Dining Dollars](https://user-images.githubusercontent.com/69397705/124627334-13ba0580-de45-11eb-9c36-5d890c6958d3.png)

**Comment by mdryankov** [comment]
Fixed

**Comment by kpecknold** [comment]
Yes, fixed, thank you!
