### ISSUE TITLE
The check box of "Personal information and Who you are" missing in Delete your personal data

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#46]
**Describe the bug**
In the pop up  "Delete your personal data"  screen "Personal information and Who you are" are missing

**To Reproduce**
1. Install Illinois app
2. Complete onboarding steps and verify the user role as University student
3. Navigate to browse menu and tap on Privacy center
4. Tap on Personal Information on the Privacy center screen.
5. Tap on Delete my Personal data button

**Actual result** 
On Delete your personal data pop up screen "Personal information and Who you are" are missing. The app displays only the "Interest and Food filter" option.

**Expected behavior**
The checkbox of "Personal information and Who you are" missing in Delete your personal data pop up

**Screenshots**
![delete pop](https://user-images.githubusercontent.com/26231179/92037835-ff464180-ed37-11ea-8f83-eb04f3b9afda.png)

**Smartphone (please complete the following information):**
 - Device: [e.g.Android]
 - Version [e.g. 2.2.16]

**Additional context**

**Comment by dobromirdobrev** [comment]
@pmarkhennessy on 2020/07/27 in "Safer and UIUC Monday 2020/07/27" you requested these two items to be removed:

> 3.3 Privacy center client. Do not do any of the COVID settings in 2.2 UIUC as we have taken COVID away. Also on the Remove Info panel (image attached) we do not want the 2 items for Who are you and Personal Info.

Could you please take a decision should they exist or not?

cc @Priyaravi8 

![miro_overides_01](https://user-images.githubusercontent.com/5978121/92227468-004daf00-eeaf-11ea-8cf9-3769123cb7e5.jpg)

**Comment by pmarkhennessy** [comment]
As designed - there are 2 deletes - 1 for non destructive and 1 for destructive

![Screenshot_20200915-113125](https://user-images.githubusercontent.com/5613085/93250745-1cbbd800-f748-11ea-9207-06941a9dd325.png)

![Screenshot_20200915-113113](https://user-images.githubusercontent.com/5613085/93250748-1d546e80-f748-11ea-846a-c5a643d5fc7a.png)

**Comment by Priyaravi8** [comment]
closing this issue as it is as designed.
