### ISSUE TITLE
[FEATURE] Better phone number validation is needed

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#47]
**Is your feature request related to a problem? Please describe.**
Currently, due to less strict phone number validation in the phone verification UI, we can see a lot of errors during the phone number verification process. For example, a user can enter less than or more than 10 digits. 

**Describe the solution you'd like**
Since these are meant to be mobile phone numbers, we can restrict them to 10 digits. 

**Describe alternatives you've considered**
If there are better phone number validation rules, that needs to be considered.

**Additional context**

**Comment by mdryankov** [comment]
@sandeep-ps,  I have made some research and I think we could summarize the US phone number validation as below:

- 10 digit number which start with first character different than 0 or 1  (is a valid US phone number)
- 11 digit number (with country code) which start with first character as 1 and the second character is not 0 or 1  (is a valid US phone number)
- 12 characters - 11 digit number (with + character and a country code) which starts with +1 and has 10 digits after that (is a valid US phone number)

Everything else is not a valid US phone number. 

The above logic is implemented for release builds. Debug time builds will skip this check for testing purpose.

**Comment by sandeep-ps** [comment]
Checked in 2.3.18. The current validations looks better. Closing this. Thanks.
