### ISSUE TITLE
[BUG] Not able to star the Events in the group

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#476]
**Describe the bug**
Users are not able to star the favorite upcoming Events in the Group

**To Reproduce**

1. Complete the onboarding and user verify his identity with Netid/PWD
2. Proceed to the Browse screen and tap on Groups
3. Create a group
4. Add Events in the group
5. Tap on the star on any of the Upcoming events 

**Actual Result**
User not able to star their favorite group event

**Expected behavior**
user should be able to star their favorite event

**Smartphone (please complete the following information):**
Device: [e.g. Android]
Version [e.g. 2.5.8]

**Additional context**

**Comment by mihail-varbanov** [comment]
Fixed in version 2.5.9

**Comment by Priyaravi8** [comment]
This issue is fixed.
