### ISSUE TITLE
[BUG] The circle with dot icon in group event is not working

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#477]
**Describe the bug**
The circle with dot icon on the top right side of the Group event screen is not working

**To Reproduce**

1. Complete the onboarding and user verify his identity with Netid/PWD
2. Proceed to the Browse screen and tap on Groups
3. Create a group and an event in the group
4. Navigate to the created Event

**Actual Result**
The circle with dot icon on the top right side of the Group event screen is not working

**Expected behavior**
It should provide information to the user about specific events.

**Screenshots**
![menu icon](https://user-images.githubusercontent.com/26231179/124989053-5b3ac000-e004-11eb-97b0-262925b7a6d1.png)

**Smartphone (please complete the following information):**
Device: [e.g. Android]
Version [e.g. 2.5.8]

**Comment by TodorBachvarov** [comment]
@Priyaravi8, Thos button works only if the event is marked as Public - the from this button we can add this event to a group. If the event is marked as Private then we cannot add it to a group, so the button do nothing. What we can do in this case is to hide the button if there is no available action.
cc @pmarkhennessy

**Comment by TodorBachvarov** [comment]
Options button is hidden for private group events.

**Comment by Priyaravi8** [comment]
The button is hidden for a Private events. This is fixed.
