### ISSUE TITLE
[BUG] Typo Add Event pop up sentence

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#479]
**Describe the bug**
Users navigate to the public event in the group. Change the word **"form" to "for"** in the sentence **Choose a group you're an admin form.**

**To Reproduce**

1. Complete the onboarding and user verify his identity with Netid/PWD
2. Proceed to the Browse screen and tap on Groups
3. Create a group
4. Tap on the circle with dot menu on the top right of the Group screen
5. Tap on Add Public Event
6. Select an Event from the list and add the Event to the Group
7. Navigate to the Added Public event in the group
8. Tap on the circle with a dot menu on the top right of the public event of the group

Actual Result
Typo in the sentence -- **Choose a group you're an **admin** form.**

**Expected behavior**
Change the word **"form" to "for"** in the sentence **Choose a group you're an admin form.**

**Screenshots**
![typo](https://user-images.githubusercontent.com/26231179/124991752-af936f00-e007-11eb-9050-aa159988181a.png)

**Smartphone (please complete the following information):**
Device: [e.g. Android]
Version [e.g. 2.5.8]

**Additional context**

**Comment by mihail-varbanov** [comment]
Fixed in version 2.5.9

**Comment by Priyaravi8** [comment]
This issue is fixed
