### ISSUE TITLE
[FEATURE] Sub-events appear in the order in which it is stored in the JSON object

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#48]
**Is your feature request related to a problem? Please describe.**
Currently, sub-events appear in the order in which it is stored in the JSON object. This is the same order in which the events are entered in the Events Manager.

**Describe the solution you'd like**
If `/events?superEventId=<super event ID>` endpoint is used to get all sub-events of a super event, the resulting sub-events are sorted in the increasing order of start date.

**Describe alternatives you've considered**
Another alternative is to fix this order in the Events Manager. Since the above endpoint is already available, thought of sharing it.

**Additional context**

**Comment by dobromirdobrev** [comment]
Done for version 2.2.19, 2.3.1 and above

**Comment by sandeep-ps** [comment]
Checked in 2.3.18. This looks good. Thanks.
