### ISSUE TITLE
[BUG] Group membership requests shows incorrect number of pending requests

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#481]
When there is only 1 pending group membership request, the app displays "2 Pending Member" to the admin.
If there is only 1 pending, it should say "1 Pending Member"
If there is more than 1 pending, Member should be plural - "Members"

**To Reproduce**
1. Be an admin of a group
2. Have 1 person request to join
3. See the screen shots below
![2 Pending Member](https://user-images.githubusercontent.com/69397705/124997220-db1a5780-e00f-11eb-8149-0673ddd78b7f.png)
![1 Pending Request](https://user-images.githubusercontent.com/69397705/124997231-deadde80-e00f-11eb-8ffa-51ee4ff89369.png)

**Comment by mihail-varbanov** [comment]
Fixed in version 2.5.9
