### ISSUE TITLE
[BUG] event search no results

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#547]
**Describe the bug**
I can't get results from the events search.

**To Reproduce**
1. Go to Events and find a word in the title for an event listed
2. Click on the search icon
3. type in a word from an event in the list
4. the app returns no results

https://user-images.githubusercontent.com/11352701/126396109-49d4c303-f43b-4256-b992-f237f29e28b8.mp4

**Expected behavior**
The app would return results from the browse events list.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone and Android
 - OS: latest
 - Version 2.5.9 and 2.6.6

**Additional context**

**Comment by pmarkhennessy** [comment]
@isaac-galvan We believe this is an Event BB issue @sandeep-ps

**Comment by sandeep-ps** [comment]
This has been fixed through https://github.com/rokwire/rokwire-building-blocks-api/issues/732 and deployed in the DEV instance. Please check. Thanks.

**Comment by sandeep-ps** [comment]
@isaac-galvan, This is now fixed through backend updates. Please close this issue if it's resolved. Thanks.
