### ISSUE TITLE
[FEATURE] Calculate event end date if the event is marked as "all day"

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/illinois-app#616]
**Re: University Monday 2021/07/26** / 2021/07/27

4.1 Why do we need to set an end date for an all day event?

**Comment by dobromirdobrev** [comment]
Done in version 2.6.11

**Comment by sandeep-ps** [comment]
Hi @dobromirdobrev, Just going by the descriptions/commit messages in this task, regular all-day events can have an end date. E.g., a multi-day conference/hackathon, holidays, etc. (https://calendars.illinois.edu/detail/7?eventId=33410550). If an all-day event is only for one day, its start date and end date will be on the same date. I'm not sure if that's what was meant here or if group events need different behavior. Thanks.

CC: @pmarkhennessy

**Comment by dobromirdobrev** [comment]
Hi @sandeep-ps ,
Thank you for your explanations. It cleared things. Now we brought back end date requirement when user creates all day events. This was handled in #627 
cc @pmarkhennessy
