### ISSUE TITLE
[BUG] Deny reason is not provided to the user

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#619]
**Describe the bug**
When the user is denied from the group, he has not been notified of the reason.

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and user verify his identity with Netid/PWD
3. Proceed to the Browse screen and tap on Groups
4. Send a request Join a Public group. 
5. Admin of the group denied the request with reason.

**Actual Result**
The user didn't notify the reason for denying the request.

**Expected behavior**
The admin should notify the user of the reason why he is not accepted into the group.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.6.10]

**Comment by knguyenjahiel** [comment]
This isn't a [BUG] or [USABILITY] issue with the app. Though User **should be** provided a reason for denial to membership to group, it should be the responsibility of the GROUP ADMIN to provide the reason for denial
