### ISSUE TITLE
[BUG] Members of the public group should be visible to all group members

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#620]
**Describe the bug**
If a user is a member of a Public group, he should be able to see all the group members.

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and user verify his identity with Netid/PWD
3. Proceed to the Browse screen and tap on Groups
4. Send a request Join a Public group. Once the request is accepted, and the user became a member of the group.

**Actual Result**
Once the user is a member of a Public group, he cannot see other members of the group.

**Expected behavior**
If a user is a member of a Public group, he should be able to see all the group members.

**Smartphone (please complete the following information):**
Device: [e.g. Android]
Version [e.g. 2.6.10]

**Comment by pmarkhennessy** [comment]
This is the current desired behaviour

**Comment by Priyaravi8** [comment]
Closing as per the desired behavoiur.
