### ISSUE TITLE
[BUG] Private event in a public group is visible to non members who are denied

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#621]
**Describe the bug**
Members who are denied in the Public group can see the private event listed in the group.

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and user verify his identity with Netid/PWD
3. Proceed to the Browse screen and tap on Groups
4. Send a request Join a Public group.
5. Admin of the group denied the request with reason.

**Actual Reson**
Though the user is denied in the group, a private event displayed in a specific group is visible to non members who are denied.

**Expected behavior**
Private events in a public group should not be visible to nonmembers who are denied

**Smartphone (please complete the following information):**
 Device: [e.g. Android]
Version [e.g. 2.6.10]

**Comment by dobromirdobrev** [comment]
Fixed in version 2.6.12 and above. Please verify.

I reopen this issue because github closed it automatically.

**Comment by Priyaravi8** [comment]
Retested and its fixed.
