### ISSUE TITLE
[BUG] The group Event level screen should mention whether it’s a private or public event.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#622]
**Describe the bug**
The group Event level screen should mention whether it’s a private or public event.

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and user verify his identity with Netid/PWD
3. Proceed to the Browse screen and tap on Groups
4. Create a Public group and create an Event in the group (Either Public or Private)
5. Navigate to the created event. The event-specific screen is displayed. 

**Actual Result**
The group, Event level screen, shouldn't mention whether it’s a private or public event in the event-specific screen.

**Expected behavior**
Group Event  level screen should mention whether it’s a private or public event in the event-specific screen

**Smartphone (please complete the following information):**
Device: [e.g. Android]
Version [e.g. 2.6.10]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 JP and I reviewed this. We will place this on the detail panel.

**Comment by dobromirdobrev** [comment]
Fixed in version 2.6.13. 

P.S. Reopen this issue because github closes it automatically.

**Comment by Priyaravi8** [comment]
Retested this issue. This is fixed with version 2.6.17
