### ISSUE TITLE
[BUG] Replying to the post didn't navigate back to Group screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#623]
**Describe the bug**
When a user replies to the post, the user does not navigate back to the Group screen. Also, another input filed is opened up in the Post screen once the post is sent.

**To Reproduce**

1. Install the Illinois app
2. Complete the onboarding and user verify his identity with Netid/PWD
3. Proceed to the Browse screen and tap on Groups
4. Create a group and create a post in the group.
5. Tap on the post, reply to the post and tap the "Send" button.

**Actual Result**
Replying to the post didn't navigate back to the Group screen. Also, another input filed is opened up in the Post screen once the post is sent.

**Expected behavior**
The user should navigate back to the specific group. Remove the extra input field that is opened up after sending the post.

**Smartphone (please complete the following information):**
Device: [e.g. Android]
Version [e.g. 2.6.10]

**Comment by pmarkhennessy** [comment]
@dobromirdobrev When creating/modifying a Post or Reply please go back to the previous panel after a "Save"

**Comment by dobromirdobrev** [comment]
Done in version 2.6.13.

P.S. I reopen this issue because github closes it automatically.

**Comment by Priyaravi8** [comment]
Retested this issue. It is fixed with version - 2.6.17
