### ISSUE TITLE
[BUG] Events without end date don't display

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#625]
**Describe the bug**
An event created in Events Manager with a start date but no end date does not show up in the app.
This has been tested in dev environment with version 2.6.10

**To Reproduce**
1. Create and Save an event in Events Manager with the required fields: Title, Category, Time Zone, and Start Date
2. Publish that event
3. Open the Illinois app and the event does not show
4. Go back to the Events Manager and edit the event to add an end date. Save the event.
5. Open the Illinois app and the event is now shown

Events created in events manager with an end date on create show up immediately. 

**Expected behavior**
Events show up in the Illinois app even if they only have a start date, or make Events Manager require an end date if the app requires it.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Version 2.6.10 in dev environment

**Additional context**

**Comment by dobromirdobrev** [comment]
This is not a client issue. That behaviour is a consequence of another issue #83 . 
The Illinois app always pass end date as a http query parameter to the events service (for reference, please see #83 description). So, when an event does not have end date, the events service does not return it in the http response.
IMO, this needs to be handled in Events Manager and end date field to become required.

@sandeep-ps , could you please share your thoughts ?

**Comment by sandeep-ps** [comment]
I agree. I remember that there were some previous discussions on this topic. It's not directly possible to search for an event based on the end date if there is no end date in the database. If we can make the end date a required field in Events BB, Events Manager, and Illinois app, I think we can solve this fairly quickly. This will mean that we need to add a default end date to those events coming from WebTools, which may not be the best thing to do. In short, I think I'm stuck there.

@kpecknold or @isaac-galvan, Could you please share your thoughts too?

If the end date needs to remain optional, we will need to check if there are any other options.

**Comment by sandeep-ps** [comment]
Hi, @kpecknold, I would like to follow up on this slightly older issue as we ran into this again while testing the upcoming Events Manager release. Could you please go through this when you get a chance? I think the basic problem is we cannot search events based on end dates that do not have an end date. 

@bingzhang and I think that we can make the end date a required field at least on the Events Manager User Events space, to address this particular bug report. We might still run into this issue for those events from WebTools that do not have an end date. Please let us know what you think. Thanks.

**Comment by knguyenjahiel** [comment]
Closed: issue submitted 7/27/2021 and is not relevant to the present functionality and design. Submitter is no longer working with the Ill App
