### ISSUE TITLE
[BUG] Group public event in Athletics category doesn't show start time

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#636]
**Describe the bug**
I created a Public event from a Group using the Athletics category.
When I view the event in the events list and details or from the group detail, it does not show a start time, only a date.
If you go to edit the event, it shows a start time.
if you change the category to something other than Athletics, the time shows in the event's details.

**To Reproduce**
1. Go to a group you admin and tap on ..., then "create group event"
2. Choose the Athletics category, title, start and end date and time, make it public, then create the event.
3. The event details view shows only a date, no time. Tap Edit and see there is a time for the event.
4. Change the category to something other than Athletics and the time now shows in the events detail. WEIRD!

**Expected behavior**
The start time would be displayed for Athletic events, or users cannot create Athletic events (is this reserved for DIA events? @pmarkhennessy @johnmpaul)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11
 - Version 2.6.10

**Additional context**

**Comment by dobromirdobrev** [comment]
Fixed in version 2.6.17.

P.S. I reopen this issue because github closed it automatically.

**Comment by knguyenjahiel** [comment]
Closed: issue is not relevant to the present functionality and design. Submitter is no longer working with the Ill App
