### ISSUE TITLE
[BUG] Can't edit events from the See all events button in a group

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#637]
**Describe the bug**
If you've added more than three events to a group, you can only edit the three events shown on the group detail view. If you tap on See all events to see more than three events, you are not allowed to edit those events.

**To Reproduce**
1. Go to more than three group events to a group
2. tap on one of the three events shown on the group page. You can edit the event.
3. tap on See all events, then tap an event from that list. You cannot edit the event.

**Expected behavior**
The events in the See all events -> Upcoming events list can be edited.

**Smartphone (please complete the following information):**

- Device: Pixel 3a
- OS: Android 11
- Version 2.6.10

**Comment by dobromirdobrev** [comment]
Fixed in version 2.6.17. 

P.S. I reopen this issue because github closed it automatically.

**Comment by knguyenjahiel** [comment]
Closed: issue not relevant to the present functionality and design. Submitter is no longer working with the Ill App
