### ISSUE TITLE
Verbiage needs to be updated on Upgrade Required screen

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#64]
**Describe the bug**
On the "Upgrade required" screen, the verbiage should be more clear

**To Reproduce**
1. Install Illinois app 2.2.18 version and open
2. Update required screen is displayed

**Actual Result**
The verbiage on the screen needs to be more clear. It says it requires an upgrade to the version 2.4.3 or later but it didn't specify the app name "Safer Illinois" that needs to be upgraded

**Expected behavior**
The verbiage should be more clear like - "Illinois app requires an upgrade to the version **2.4.3 or later of Safer Illinois**". It should specify the app name "Safer Illinois" in the verbiage

**Screenshots**
![Upgrade verbiage](https://user-images.githubusercontent.com/26231179/92278777-87088900-eebb-11ea-8fa0-9b469a8bc5ad.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.2.18]

**Comment by pmarkhennessy** [comment]
This was a bad build and is fixed in the rebuild of 2.2.18

**Comment by Priyaravi8** [comment]
Retested this issue with version 2.3.1. This issue is resolved.
