### ISSUE TITLE
[BUG] Editing events with long title and description

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/illinois-app#657]
**Describe the bug**
There is a bug and usability issue when editing events with a long title and description from the Groups talent.

**To Reproduce**
1. Add an existing event with a long title or description to a group.
2. Click on the edit event button.
3. Try to edit the event title.
4. A few things can be observed:
a. Event title appears in a single line and is difficult to reach beyond the screen space for editing. (Screenshot 1.)
b. Character count initially appears to be greater than the limit (64). Soon, it crops the characters beyond the limit (Screenshots 1. and 3.). 
c. The long description also appears in a single line making it difficult to read and edit. (Screenshot 2.)

**Expected behavior**
1. If it's possible to wrap the title and description within the text box, and provide an internal scroll in the vertical text box, it may provide a better user experience when editing the event title and description. I'm not a UI expert, so please see if there are other better options for this situation.
 2. Editing events with long titles need to be allowed.

**Screenshots**
### Screenshot 1.
![image](https://user-images.githubusercontent.com/4306604/127713007-7a36faba-e6b9-439e-9b92-4278db0cdf3e.png)

### Screenshot 2.
![image](https://user-images.githubusercontent.com/4306604/127713079-ce0fe789-7e6b-479f-a60c-5cf06d43ca9f.png)

### Screenshot 3.
![image](https://user-images.githubusercontent.com/4306604/127713131-97fec641-3d2b-4bca-99d5-6560041484da.png)

**Smartphone (please complete the following information):**
 - Device: Android
 - Version 2.6.14

**Additional context**

**Comment by TodorBachvarov** [comment]
fixed in version version 4.1.14

**Comment by sandeep-ps** [comment]
Thanks, Todor. I tested this with version 4.1.36, and it's working as described in the expected behavior. I will close this issue.
