### ISSUE TITLE
[FEATURE] update icon for Dining Dollars

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#669]
Cafe Credits name was changed to Dining Dollars in the app, but the icon image still has a C.
https://github.com/rokwire/illinois-app/blob/develop/images/icon-payment-type-dining-dollars.png

Please update the icon to represent Dining Dollars.

**Comment by mihail-varbanov** [comment]
Fixed in version 2.6.17 & 3.0.0

**Comment by isaac-galvan** [comment]
That's excellent thanks!
