### ISSUE TITLE
[BUG] permission toggle and continue bounce during setup on small screen

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#679]
**Describe the bug**
The toggle and continue buttons bounce during setup on first-gen iPhone SE.
See the video below

**To Reproduce**
1. Install app
2. Choose Continue from the first screen, then employee
3. tap Begin on the "control data privacy" screen
4. The toggle and the continue button bounce on the next three screens

**Expected behavior**
The toggle and continue button would have static position to make them easy to tap

**Screenshots**

https://user-images.githubusercontent.com/11352701/129088276-b1eda13c-cdc1-4d3b-b11e-781b10308a6f.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone SE (1st generation)
 - OS: iOS 14.7
 - Version Illinois app v. 2.6.14 (current store version) and 2.6.17

**Additional context**

**Comment by mihail-varbanov** [comment]
Fixed in 2.6.18

**Comment by isaac-galvan** [comment]
Looks great, thanks!
