### ISSUE TITLE
[FEATURE] Delay creating MapView in ExplorePanel

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#701]
**Firebase**: https://console.firebase.google.com/u/0/project/rokwire-mvp01-dev/crashlytics/app/ios:edu.illinois.rokwire.ios/issues/4ec1eeb0cf2640cc10b2aaca25ef301c?time=last-seven-days&sessionEventKey=d64f59101de34531b49e49be761741af_1576941629403710501

**Re: University Monday 2021/08/16** / 2021-08-20

2.3 The iOS crash with google maps initialization. I could not recreate the crash. I did find 2 things about Flutter and Google Maps:

2.3.1 Delay the initialization.

2.3.2 There seems to be quite a lot about camera and google maps. Here are a couple:

https://stackoverflow.com/questions/21964211/cant-get-google-maps-to-initialize-ios

https://stackoverflow.com/questions/56416528/flutter-google-maps-not-determining-current-location-of-device

**Comment by ToddNelson** [comment]
Looks good, thanks!
