### ISSUE TITLE
[FEATURE] show Contacts from event manager in details

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/illinois-app#713]
**Is your feature request related to a problem? Please describe.**
We allow users to add a contact and their details in the Events Manager. Those contact details are not shown in the Illinois app event details view.

**Describe the solution you'd like**
If a user adds contact information, it would be displayed in the app.

**Additional context**
I've created an event with ID 61241eb9ce6fc70008888c4a in the dev environment.
This event has a Contact defined with a first name, last name, email address, phone number, and organization name.
None of those fields show in the Illinois app description.

<img width="948" alt="Screen Shot 2021-08-23 at 5 25 27 PM" src="https://user-images.githubusercontent.com/11352701/130527255-290d8cbe-f2d4-4a7a-a61b-78908443e68f.png">

![Screenshot (Aug 23, 2021 5_24_58 PM)](https://user-images.githubusercontent.com/11352701/130527317-23dc09db-45d6-4538-8b58-d5a574a9465a.png)

**Comment by isaac-galvan** [comment]
The events manager does allow for adding multiple contacts. My test event has been updated with two contacts for testing.

<img width="956" alt="Screen Shot 2021-08-23 at 5 28 56 PM" src="https://user-images.githubusercontent.com/11352701/130527569-a1754dfb-f9fb-4e79-afeb-15f41658778a.png">

**Comment by dobromirdobrev** [comment]
Done in version 2.6.24 and 3.0.5.

**Comment by knguyenjahiel** [comment]
Closed: issue submitted8/23/2021 and is not relevant to the present functionality and design. Submitter is no longer working with the Ill App
