### ISSUE TITLE
Android - Map screen - Failed to detect current location message is displayed

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#75]
**Describe the bug**
Location of the Events and Dining is not detected

**To Reproduce**
1. Install Illinois app
2. Complete onboarding steps and verify the role of University student
3. Tap on any of the locations on the Events and Dining.

**Actual Result**
Failed to detect current location message is displayed

**Expected behavior**
App should display the Events/Dining directions of the location 

**Screenshots**
![map](https://user-images.githubusercontent.com/26231179/93110153-8e2d5500-f67a-11ea-8795-eda1c5fbde14.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.2.18]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 I cannot reproduce this. More info is needed as in OS version and device. I also noticed from your other map issue that the device message said location services denied for the app. Maybe this is why.

**Comment by Priyaravi8** [comment]
Retested this issue with version 2.3.1. This issue is resolved.
