### ISSUE TITLE
[BUG] Privacy notification replaces Feedback Screen with no way back

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#76]
**Reproduce Problem**
1. Go to Browse > Provide Feedback
2. Tap "Provide Feedback". The feedback panel appears.
3. At the bottom of the feedback panel, tap "Privacy".

**Problem**
The privacy statement appears, replacing the Feedback panel. Tapping the back arrow (<) does not take you back to the Feedback panel. Instead it takes you to the "Browse" panel. 

**Recommended Action**
Make it so the back button takes you back to the Feedback panel, if possible.

Seen in build 2.2.18

**Comment by pmarkhennessy** [comment]
@joegrohens this is the behaviour of Back - the OS back does the same thing. It's quite some work to hack around this and then the 2 backs would work differently.
