### ISSUE TITLE
Android - App is not proceeding to further screens from "Share my Location" screen during on-boarding.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#77]
**Describe the bug**
During onboarding steps, the user not able to proceed to further screen from "Share my Location"

**To Reproduce**
1. Install Illinois app
2. Continue the steps in the onboarding process
3. Tap on the "Share my Location" button on the "Know what's nearby" screen

**Actual Result**
The app is not proceeding to further screen. "You have already denied access to this app" message is displayed.

**Expected behavior**
Once the user taps on "Share my Location", the app should gain the location access and proceed further. 

**Screenshots**
![location denied](https://user-images.githubusercontent.com/26231179/93138841-4e2f9780-f6a5-11ea-9361-09c719220284.png)

**Smartphone (please complete the following information):**
 - Device: [e.g.Andoid]
 - Version [e.g. 2.2.18]

**Comment by pmarkhennessy** [comment]
@Priyaravi8 - I cannot reproduce this. More detail needed on Android device and version etc please

**Comment by Priyaravi8** [comment]
Retested this issue with version 2.3.1. This issue is resolved.
