### ISSUE TITLE
Home screen - Button without label is displayed in Campus Remainder section

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#82]
**Describe the bug**
A button without a label is displayed on the Home screen under the Campus Remainder section

**To Reproduce**
1. Install Illinois app
2. Complete onboarding screen and verify as University Student
3. Home screen is displayed

**Actual Result**
No label on the button is displayed on the Home screen under the Campus Remainder section

**Expected behavior**
The button should have a label on it without empty.

**Screenshots**
![Empty submit](https://user-images.githubusercontent.com/26231179/93491970-e90bba00-f8cf-11ea-972d-f6f0e71fbbcf.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.3.1]

**Comment by TodorBachvarov** [comment]
Fixed

**Comment by Priyaravi8** [comment]
Retested this issue and it is fixed in version 2.2.18.
