### ISSUE TITLE
[BUG] DINING/RECENTLY VIEWED doesn't show dining schedule accurately

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#835]
When accessing a dining location from the home page under "Recently Viewed", the dining locations appear to be closed for the next 2 weeks and have no menus.

**To Reproduce**
1. Go to Dining
2. Choose a location, view the hours and menus
3. Go back to the home page
4. Scroll to "recently viewed"
5. Tap on the location
6. See that there is no schedule/menu displayed

**Expected behavior**
The correct schedule and menu should appear, just as it does when accessing via "Dining"

**Comment by mdryankov** [comment]
@kpecknold Please verify the fix with a fresh build (eg. 3.0.40+).

**Comment by kpecknold** [comment]
Resolved
