### ISSUE TITLE
[USABILITY] Font Size too large in Athletics > News

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#855]
**The problem:**

The font size displayed in Athletics News Articles is too big (approx 36 pt), and the font weight is extra heavy as well.

This results in maximum 12 characters per line, interfering with readability. Each line prints only two or three words. A 700-word article takes up nearly 30 screens.

**To Reproduce**
Go to **Illinois app > Home > Athletics > News**.
Tap on any sports story.

**Screenshots**

![IMG_0987](https://user-images.githubusercontent.com/66988329/138500847-4601c397-309c-4fa7-89a5-66e6d6ebf43b.jpeg)

**Equipment:**
iphone 11 ios 14.8
Illinois app version:  2.7.2

**Other Notes:**
The articles feed comes from FightingIllini.com/news.

**Comment by dobromirdobrev** [comment]
Fixed in 2.7.5 and 3.0.41.

cc @joegrohens
