### ISSUE TITLE
[FEATURE] Add an element locator for  "X" and "✓" with accessibility ID / XPath.

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#881]
Building Access part in Illini ID. The image of "X" (Denied) and "✓" (Granted) is not an element locator in Illinois ID (Use ID) Illinois apps. 
Please add an element locator for  "X" and "✓" with accessibility ID / XPath.

Screenshot

![Element locator for X](https://user-images.githubusercontent.com/26231179/139328140-f89c5c86-3f69-4ff2-84a8-3f94a13f04ed.png)

**Comment by Priyaravi8** [comment]
@TodorBachvarov - Accessibility id is "building access" for both Granted and Denied. Unique specific accessibility id for Granted and Denied will help in scripting.

**Comment by TodorBachvarov** [comment]
Added in v3.2.15
