### ISSUE TITLE
[BUG] Events and Posts buttons don't do anything inside a group

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#904]
**Describe the bug**
In a group, the two buttons right above "Upcoming Events", don't seem to do anything. What are they supposed to do?

**To Reproduce**
1. Go into a group
2. Tap on the two buttons
3. Observe no visible change to the display

**Expected behavior**
Not sure what is supposed to happen

**Screenshots**
![image](https://user-images.githubusercontent.com/69397705/140078347-d054d9bd-4e8c-46b3-b316-9f494fe45cae.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2 XL
 - OS: Android 11
  - Illinois App Version 3.0.39

**Comment by pmarkhennessy** [comment]
@kpecknold These 2 buttons are meant to move Posts or Events on a Group main panel into focus. If you have many events you would not see any posts etc

**Comment by kpecknold** [comment]
Ok, thanks.
