### ISSUE TITLE
[BUG] GROUPS - Group website link doesn't work on group card

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#905]
**Describe the bug**
On the main group card, the group website link doesn't work.

**To Reproduce**
1. Go into a group (I am an admin for the group)
2. Add a website Link
3. Confirm URL
4. Update Settings
4. Notice a "Website" row now appears below "Promote this group"
5. Tapping on that "website" row doesn't do anything

**Expected behavior**
Tapping should open a website

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 11
 - Illinois app Version 3.0.39

**Comment by mihail-varbanov** [comment]
This is related to #900 and should be fixed since 3.0.40.
