### ISSUE TITLE
[BUG] GROUPS - When group name is too long, the edit display goes blank 

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#906]
**Describe the bug**
When creating a group and the group name is too long, the edit display goes blank 

**To Reproduce**
1. Create a group (or edit an existing group settings)
2. Enter this for the Group Name: Women in Math, Science, & Engineering LLC (WIMSE)
4. Observe the edit display go blank
5. Update Settings
6. Observe the group name does actually display on the group card
7. Go into Group Settings, observe the group name appears to be blank (but you can edit if you delete characters you can't see)

**Expected behavior**
We could increase the limit slightly and also handle the limit gracefully?

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 11
 - Illinois app Version 3.0.39

**Additional context**
I am going to encourage stakeholder to keep the group names short

**Comment by mihail-varbanov** [comment]
Fixed in version 3.0.41.
