### ISSUE TITLE
[BUG]  QUICK POLLS - Can't create poll

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#929]
I can't create a quick poll. SAVE and START POLL  both give an error "Failed to create poll. Please fill all fields and try again.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 11
  - App Version 3.0.41
  - Pointed at Dev

**Additional context**

**Comment by mihail-varbanov** [comment]
I was unable to recreate the problem. Polls service was recently updated to work with the new Core BB tokens. My assumption is that when the problem was observed that polls service had not been updated yet. Please check whether the problem persists on the latest version of polls service.
