### ISSUE TITLE
[BUG] QUICK POLLS - height of option text boxes

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#930]
**Describe the bug**
When creating a quick poll, the height of  the "option" boxes doesn't fit the text, some is cutoff vertically.

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 11
 - Version 3.0.41

**Comment by TodorBachvarov** [comment]
Not Able to reproduce. Probably this has been fixed.
