### ISSUE TITLE
[FEATURE] Building access widget

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#932]
**Re: University Monday 2021/11/08** / 2021-11-10

1.1 UIUC 2.7 has become the highest priority for JP as he is trying to do away with Safer Illinois. We will also need this is UIUC 3.x:

So, we need a new Widget at the top, after the emergency widget and before anything else. This widget will have 4 items, each one with the ">" right aligned and will show a new or existing panel.

Building access
Test locations
My McKinley
Wellness Answer Center

The title of this widget will be "Building access"

1.1.1 Building access will show the same thing that we see for a user's wallet/card. It can open the wallet/card if needed or be the same content in a new panel.

1.1.2 Test locations are probably the hardest and this should look like the same panel in Safer Illinois and have the same functionality. Calling Health BB may be an issue. You can store the data somewhere else if needed but we must be able to add/edit/delete locations.

1.1.3 My McKinley will open this web link: https://mymckinley.illinois.edu/

1.1.4 Wellness answer center will be the same content we show in Safer Illinois for the COVID-19 Wellness Answer Center.

It is important not to use the word COVID-19 anywhere. So for example in the Wellness answer center we would just remove COVID from the text (contact the Wellness center and Email the Wellness center etc). Use the email for now and I will see about a new one.

In test locations we will not need the 2 drop downs as they will all be what is at UIUC (Champaign and all providers)

**Comment by joegrohens** [comment]
I have a couple of minor corrections to wording.

**In lib/ui/home/HomeSaferWidget.dart** 

- My McKinley should styled as "MyMcKinley" (one word) in button titles and descriptions. (also in line 132 - analytics)
- Analytics().logSelect(target: 'Test Locaations'); change to "Locations"

**In assets/strings.en.json and localizations**
- Use "MyMcKinley"
- "If you having issues with the app" change to "If you are having issues with the app" (1763)
