### ISSUE TITLE
[BUG]   GROUPS - in 2.7.7, when app is left open for a little while, all groups disappear

### ISSUE THREAD

**Issue by kpecknold** [rokwire/illinois-app#948]
Open the app, display groups, leave for 30 minutes
Notice there are no groups displayed
It's necessary to exit the app and go back in to see the groups again.

**Comment by mihail-varbanov** [comment]
@kpecknold, I am unable to recreate this problem. Can you recreate it again? If yes, could you please provide the exact steps that you did to get this. E.g. what device did you use (Android/iOS), what was the groups selection (My/All Groups), did the phone get locked during the 30 minutes inactivity, and any other meaningful information that could be helpful.
