### ISSUE TITLE
[BUG] Group - Denial reason is not notified to the user

### ISSUE THREAD

**Issue by Priyaravi8** [rokwire/illinois-app#959]
**Describe the bug**
Group admin denies a user with the reason which is not notified to the user

**To Reproduce**

1. Install the new version of the Illinois app
2. Go to groups feature
3. Send a "Request to Join" to a Private group (Eg Group A)
4. Admin of the Private group (Group A) rejects the request along with a noted reason.

**Actual Result**
Group admin denies a user with the reason which is not notified to the user

**Expected behavior**
The denial reason should be notified to the user.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Version [e.g. 2.7.7]

**Comment by mdryankov** [comment]
@Priyaravi8 @pmarkhennessy this functionality is available in 3.0. This will make big overhead if you wish to enable it for 2.8, because Notifications BB is working with 3.0 Core

**Comment by mdryankov** [comment]
Also core is not deployed yet on production yet

**Comment by kpecknold** [comment]
@mdryankov @Priyaravi8 @pmarkhennessy 
3.0 is fine, thanks!

**Comment by mdryankov** [comment]
Thank you @kpecknold !
