### ISSUE TITLE
[FEATURE] Create initial infrastructure for Canvas

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/illinois-app#998]
**Re: University Monday 2021/11/15** / 2021-11-19

2 Misho, here is a Canvas video for you to watch. We would like to start implementing home panel widgets that show courses and groups. I will let you know more after I talk to JP on Sunday

**Comment by dobromirdobrev** [comment]
Reopening this issue. **University Monday 2022/01/24** / 2022/01/24

3.2.1 Provide me with the redirect URL for Canvas login so I can get what we will need to "masquerade" our API calls for users of Canvas.

3.2.2  Start on the "rough" UI/flow that we discussed on Friday.
